import searchUrl from '@/data/collegeGrid/collegeGridSearch.json?url';
import judgeUrl from '@/data/collegeGrid/collegeGridJudge.json?url';
import { collegeSearchSource, loadCollegeSearch } from '@/lib/collegeGrid';
import type { PlayerSourceConfig } from '@/lib/playerSearch';

/**
 * The browser's only door to College Grid's two key files (Round 1105).
 *
 * WHY THIS IS ITS OWN MODULE AND MUST STAY ONE. The two imports above end in
 * ?url, which vite turns into the hashed address of each file in the build
 * (so a long cache can never serve a stale key). Node harnesses bundle
 * src/lib/collegeGrid.ts and src/lib/gridEngine.ts with plain esbuild
 * (scripts/genCollegeGridData.mjs, scripts/genCollegeGridBoards.mjs,
 * scripts/simCollegeGridKey.mjs), and esbuild would read a ?url import as the
 * parsed JSON itself, a megabyte of it, not as an address. So no ?url import
 * may ever sit in those two libs. They take the addresses as arguments, and
 * this file is the one place that knows them. Do not fold it back in.
 *
 * Both files are generated by `node scripts/genCollegeGridData.mjs --compact`
 * from scripts/data/collegeGridPlayers.json and are never edited by hand.
 */
export const COLLEGE_KEY_URLS = { search: searchUrl, judge: judgeUrl } as const;

/** The search box source: the key's display names, held in memory, longest NFL careers first. */
export const COLLEGE_GRID_PLAYER_SOURCE: PlayerSourceConfig = collegeSearchSource(searchUrl);

/**
 * Loads and folds the search list ahead of the first keystroke. The search box
 * calls it when it opens, so the one time cost of folding 35,000 names lands
 * while the player is reaching for the keyboard, not on his third letter.
 */
export function warmCollegeSearch(): void {
  void loadCollegeSearch(searchUrl);
}
