project_id = "ldnmovwrdpdgdrwrgbto"

[functions.evaluate-lineup]
verify_jwt = false

[functions.validate-player]
verify_jwt = false

[functions.suggest-players]
verify_jwt = false

[functions.nba-suggest-players]
verify_jwt = false

[functions.nba-validate-player]
verify_jwt = false

[functions.nba-evaluate-lineup]
verify_jwt = false

[functions.nba-connect4-validate]
verify_jwt = false

[functions.nba-chain-validate]
verify_jwt = false

[functions.nascar-daily]
verify_jwt = false

[functions.nascar-chain-validate]
verify_jwt = false
