import { useState, useCallback, useEffect, useMemo } from 'react';
import { NascarDriverPuzzle, NascarDriverState, MAX_CLUES, POINTS_BY_CLUE } from '@/types/nascarDriver';
import { supabase } from '@/integrations/supabase/client';
import { getTodayET } from '@/lib/dateUtils';
import { ensureAnswerInList } from '@/lib/ensureAnswerInOptions';
import { useGameCompletion } from '@/hooks/useGameCompletion';

/* ROUND 374: THE CLUES COME FROM A COMMITTED FILE NOW, AND BEFORE THIS ROUND
   THEY CAME FROM NOWHERE.
   This hook used to build each puzzle out of six columns on `nascar_drivers`:
   vibe_word, era_hint, car_number_hint, wins_hint, championship_hint and
   famous_moment_hint, plus common_names. NONE OF THOSE COLUMNS EXIST on that
   table and none ever did, so every clue was undefined and a player was shown
   six blank cards with no way to reason at all. The rest of the table is nearly
   empty too: of 83 rows only rank, driver_name and country are populated.
   src/data/nascarDrivers.json is generated by scripts/genNascarDrivers.mjs from
   nascar_race_results and nascar_champions, which do hold real data, and every
   clue is a fact one of those tables states outright. Read the generator's
   header before changing a clue: the results table is NOT a complete win log
   and it mixes in exhibition races, so nothing may total it or call a row a
   "Cup Series win", and that constraint is the reason the clues are shaped the
   way they are.
   Rendering from the file also means the page ships its game to a crawler
   instead of a spinner, and stops querying Supabase on every visit. */
import nascarDriverPool from '@/data/nascarDrivers.json';

const POOL: NascarDriverPuzzle[] = nascarDriverPool.drivers as NascarDriverPuzzle[];

export function useNascarDriver() {
  const [gameState, setGameState] = useState<NascarDriverState | null>(null);
  const [allDrivers] = useState<NascarDriverPuzzle[]>(POOL);
  const [loading, setLoading] = useState(false);
  const [status] = useState<'loading' | 'ready' | 'error'>('ready');

  const startGame = useCallback(async (mode: 'daily' | 'unlimited') => {
    setLoading(true);
    try {
      if (mode === 'daily') {
        /* ROUND 366: ET, not UTC. An evening ET player could be served the next day's driver while their completion filed under the current ET date, because completions.ts resolves through getEtDateString(). */
        const today = getTodayET();
        /* ROUND 374: the `nascar_daily` lookup that used to sit here is gone.
           It selected a driver_id and then fetched it with .eq('id', ...) from
           a table that HAS no id column, so it could only ever have thrown, and
           it never ran: nascar_daily has zero rows and always has. The daily
           driver has therefore always come from the seeded index below, which
           is the real mechanism and is kept.
           The pool's ORDER is what makes that index mean anything, and it is
           now fixed in the committed file rather than asked for at query time.
           Round 362 ordered this query by driver_name for exactly that reason,
           noting the table has no primary key at all; the generator sorts by
           the same key, so the guarantee survives the move. */
        if (allDrivers.length > 0) {
          const seed = parseInt(today.replace(/-/g, ''), 10);
          const puzzle = allDrivers[seed % allDrivers.length];
          setGameState({ puzzle, revealedClues: 1, guesses: [], gameStatus: 'playing', score: 0, mode });
        }
      } else {
        if (allDrivers.length > 0) {
          const puzzle = allDrivers[Math.floor(Math.random() * allDrivers.length)];
          setGameState({ puzzle, revealedClues: 1, guesses: [], gameStatus: 'playing', score: 0, mode });
        }
      }
    } finally {
      setLoading(false);
    }
  }, [allDrivers]);

  const makeGuess = useCallback((input: string) => {
    if (!gameState || gameState.gameStatus !== 'playing') return;

    const norm = input.trim().toLowerCase();
    const isCorrect = gameState.puzzle.common_names.some(n => n.toLowerCase() === norm) ||
      gameState.puzzle.driver_name.toLowerCase() === norm;
    const newGuesses = [...gameState.guesses, input];

    if (isCorrect) {
      const score = POINTS_BY_CLUE[gameState.revealedClues - 1] ?? 0;
      setGameState(prev => prev ? { ...prev, guesses: newGuesses, gameStatus: 'won', score } : null);
      const today = getTodayET();
      supabase.from('nascar_scores').insert({
        puzzle_date: today,
        clues_used: gameState.revealedClues,
        score: POINTS_BY_CLUE[gameState.revealedClues - 1] ?? 0,
        guessed: true,
        mode: gameState.mode,
      }).then(() => {});
    } else {
      const newRevealed = gameState.revealedClues + 1;
      const isLost = newRevealed > MAX_CLUES;
      if (isLost) {
        const today = getTodayET();
        supabase.from('nascar_scores').insert({
          puzzle_date: today,
          clues_used: MAX_CLUES,
          score: 0,
          guessed: false,
          mode: gameState.mode,
        }).then(() => {});
      }
      setGameState(prev =>
        prev ? {
          ...prev,
          guesses: newGuesses,
          revealedClues: Math.min(newRevealed, MAX_CLUES),
          gameStatus: isLost ? 'lost' : 'playing',
          score: 0,
        } : null
      );
    }
  }, [gameState]);

  const revealHint = useCallback(() => {
    if (!gameState || gameState.gameStatus !== 'playing' || gameState.revealedClues >= MAX_CLUES) return;
    setGameState(prev => prev ? { ...prev, revealedClues: prev.revealedClues + 1 } : null);
  }, [gameState]);

  const giveUp = useCallback(() => {
    if (!gameState || gameState.gameStatus !== 'playing') return;
    setGameState(prev => prev ? { ...prev, gameStatus: 'lost', score: 0 } : null);
  }, [gameState]);

  const resetGame = useCallback(() => setGameState(null), []);

  const pointsForCurrentClue =
    gameState ? (POINTS_BY_CLUE[gameState.revealedClues - 1] ?? 0) : POINTS_BY_CLUE[0];

  // Ensure current puzzle answer is always in the selectable options
  const validatedDrivers = useMemo(() => {
    if (!gameState?.puzzle) return allDrivers;
    return ensureAnswerInList(allDrivers, gameState.puzzle.driver_name, d => d.driver_name, gameState.puzzle);
  }, [allDrivers, gameState?.puzzle]);

  useGameCompletion('guess-nascar-driver', gameState?.gameStatus === 'won' || gameState?.gameStatus === 'lost', gameState?.score ?? 0);

  /* `status` stays in the shape and stays 'ready': the pool is bundled, so
     there is no fetch to be loading or to fail. `reloadDrivers` is gone with
     the fetch it retried. */
  return { gameState, startGame, makeGuess, giveUp, revealHint, resetGame, maxClues: MAX_CLUES, pointsForCurrentClue, allDrivers: validatedDrivers, loading, status };
}
