import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import PageSeo from '@/components/seo/PageSeo';

const WhatsNew = () => {
  return (
    <div className="min-h-screen bg-background text-foreground px-4 py-12 max-w-3xl mx-auto">
      <PageSeo
        title="What's New | DoUKnowBall Updates"
        description="The running log of everything new on DoUKnowBall: fresh games, features, fixes, and content drops, newest first."
        path="/whats-new"
      />
      <Link
        to="/"
        className="mb-6 inline-flex items-center gap-2 rounded-full px-3 py-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        <ArrowLeft className="w-4 h-4" />
        Back to the games
      </Link>
      <h1 className="text-3xl font-bold mb-2">What's New</h1>
      <p className="text-sm text-muted-foreground mb-8">
        The running log of what changed around here, newest first. We ship a lot. If something looks off after an update, hit the Report a bug button in the footer and we will get on it.
      </p>

      <section className="space-y-8 text-sm leading-relaxed text-muted-foreground">
        <div>
          <h2 className="text-lg font-semibold text-foreground mb-2">August 2026</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong className="text-foreground">The Record Books are open.</strong> All week we have been checking our champion tables season by season against the official record, and that work deserved more than a quiz answer key, so it is now a page you can read. The Record Books (linked in the footer) lists every champion year by year across ten competitions: every Super Bowl with its score and MVP, NBA champions back to 1947 with every Finals MVP, the World Series since 1903, the Stanley Cup since 1915, the WNBA with every beaten finalist, college football with its split titles carried per selector, college hoops, the English title, and both Australian codes. Where history is odd we keep it odd: seasons that were never played are missing on purpose, and stripped titles stay vacant with a note saying why. Each table links straight into the games that play on the same history.</li>
            <li><strong className="text-foreground">Champ or Not grows a Hard mode.</strong> The regular fakes pull any winner from a competition's whole history, which a sharp fan can smell from the era alone. Hard mode, on the Unlimited tab, is crueler: the fake winner really did lift that trophy, within about three seasons of the year on the card. "The Penrith Panthers won the 2020 premiership" is exactly the kind of lie it deals now (they won the four either side; 2020 was Melbourne). Still never invented. A measured year of hard sets puts 99 percent of fakes within three seasons, with the rare exception being stretches like the Dragons' eleven straight, where there is literally no other nearby winner to borrow.</li>
            <li><strong className="text-foreground">The NRL joins the records shelf.</strong> Every top grade rugby league premier since 1908 is now on the site, and it went straight into two games at once: Name Them All gets its 28th list (every club to win the premiership, under the name it wore at the time, so Eastern Suburbs and the Sydney Roosters are separate answers), and Champ or Not now deals league claims as its tenth competition. The history is handled the way the record books handle it: 1997 counts both premiers because the game genuinely split that year (Newcastle in the ARL, Brisbane in Super League), and 2007 and 2009 are deliberately absent because Melbourne's titles from those seasons were stripped and stay vacant, so no quiz here will ever teach them. All 117 seasons checked against two independent records, with the famous numbers landing exactly: Souths on 21, St George on 15 with the eleven straight, Manly and the Bulldogs on 8.</li>
            <li><strong className="text-foreground">New game: Champ or Not.</strong> Ten claims about champions, one at a time, and every one of them sounds right. The Bulls in 1994? The Islanders in 1982? Leicester in 2016? Two of those happened, and your job is calling which. The fakes are the cruelest kind we could build honestly: every team named is a real champion of that competition, the lie is only ever the year, and the reveal always names who really won. Nine competitions in the mix, from the Super Bowl and the NBA to the English title and the VFL/AFL flag, all reading from the same record books we spent this week auditing season by season. Ten claims a day, same set for everyone, unlimited mode when ten is not enough. Lives in World and Olympic Games.</li>
            <li><strong className="text-foreground">Name every VFL/AFL premier, and the whole records shelf got an audit.</strong> The List Quiz's 27th list is for the footy crowd: every club to win a flag since 1897, under the name it wore at the time, so South Melbourne and Sydney are separate answers the same way the Minneapolis Lakers are. All 129 seasons were checked against two independent records before shipping, and the famous counts hold: Essendon, Carlton and Collingwood on 16 apiece. While building the checker that guards it, we audited every list the quiz serves against the record and repaired the tables behind the finals lists (Stanley Cup, World Series, NBA, WNBA), whose unused columns carried scrambled scrape data waiting to bite a future feature. The answers you see were always right; now the shelves behind them are too, and the 2026 Stanley Cup is on the books.</li>
            <li><strong className="text-foreground">The college football champions are the real champions now.</strong> While building a permanent check that no College Grid square can ever be impossible (every square on all 75 boards is now verified against 28,000 real draft picks, the Heisman list and the title history), we found our national champions table was badly corrupted: it claimed USC won the 2005 title that Texas famously took in the Rose Bowl, listed Ohio State as the 2006 champion when Florida beat them in the title game, credited Iowa with 1985, and was missing about half the real winners entirely, including Texas, Penn State, BYU and Clemson's 1981. Rebuilt season by season from 1981 through Indiana's first ever title this January, every row checked. The List Quiz's "name every national champion" now has the right answers, six more schools among them.</li>
            <li><strong className="text-foreground">G'day: the site's first footy game.</strong> Australia is our second biggest country and until today the menu had nothing for you, so here is AFL Higher or Lower. Two goal kicking greats side by side, from Gordon Coventry booting 1,299 for Collingwood before World War Two to Buddy Franklin's 1,066, and you pick who kicked more career goals. Ten rounds, streak bonuses, a shared daily plus an unlimited mode with a hard setting that serves up the close calls. The pool is sixty legends and every total was checked against the all time records before shipping, with only retired players included so no number ever moves under you. Sits in its own new Aussie Rules section. More footy games to come if this one gets played.</li>
            <li><strong className="text-foreground">The dugout is a real job now.</strong> Retire in Soccer Career, take a manager's job, and until now every season came back as a coin flip and an adjective: maybe "mid-table", maybe a trophy out of nowhere, maybe sacked at random. Now the season is simulated like the rest of your career: your club and the real clubs at your level play out a full league to a points table you can read, with your W-D-L line, and everything follows from where you actually finished. Champions means you topped the table, promotion means you finished top two down the pyramid and go up WITH your club instead of teleporting to a random one, relegation can go two ways (a board that keeps faith or a sack on the spot), and the sack only ever follows a finish a real board would act on. There is a proper cup run every season too, giant-killings included, and titles and cups won from the dugout now sit in your trophy cabinet next to the ones you won in boots. Your record matters: a manager with silverware measurably finishes higher, so building a reputation over seasons is the whole game.</li>
            <li><strong className="text-foreground">Grade the Transfer is back from the dead, with a cleaner deck.</strong> The game builds its transfer list from a big historical query, and that query had quietly grown past the database's time limit, so the page was timing out and loading empty. While rebuilding it as a fast stored table we found two data problems worth fixing properly: exact duplicate transfers, and a nastier one where different real players sharing a name (Brazilian one-name players especially) got merged into one impossible career, which invented transfers that never happened. Every fabricated or ambiguous case is gone: 759 real graded transfers remain, each one a move that actually took place, and the crowd vote for a transfer can no longer mix in votes for a different player with the same name. The years are right now too: cards used to date a move by the buyer's first recorded season, which ran a year or two late (Neymar's move to Barcelona showed as 2015), and every card now carries the year the player actually left, checked against the famous moves and locked in by a test. On top of that, the same daily-shuffle bug we fixed last round turned out to live in four more games: Grade the Transfer could only ever show 81 of its cases, Ball IQ kept drawing its questions from the same dozen clues per difficulty, Emoji Guess served the same 3 easy puzzles all year, and Mystery Box circled half of each rarity pool. All four now use the proper shuffle, measured over a simulated year, and a permanent check makes sure this class of bug can never ship again anywhere on the site.</li>
            <li><strong className="text-foreground">Overrated and Tier List actually rotate now.</strong> A while back one of you told us the same names kept turning up, and you were more right than we knew. We measured a full simulated year of both games and found the daily picker was quietly broken: the maths it used to spread players across days was losing precision, so Overrated or Underrated could only ever reach a quarter of its 600 player pool and Tier List an eighth, and 17 days a year the tier list dealt exactly yesterday's board again. Both games now draw from the same properly mixed shuffle the rest of our dailies use: measured over the same year, they reach essentially the whole pool, never repeat a day, and turn over almost the entire board every single day. The two games still never share a player on the same day, and that rule is now enforced in one place instead of two files trying to stay in sync. Budget Builder got a check of its own while we were in there: every daily board demand is now proven winnable inside the budget in all three eras, which caught one that was not (the 90+ star demand was mathematically impossible in the 2015 and 2007 markets, where money was smaller and no player rates that high, so it now only appears in the Today market).</li>
            <li><strong className="text-foreground">A broken save can never take a game down again.</strong> Saves live on your device, and a bad update or an interrupted write can leave one mangled. So we built a test that loads every game on the site with its saved data deliberately wrecked six different ways, and one game failed it: the World Cup bracket could crash to a blank page if its saved picks were damaged, taking your whole bracket screen with it. Fixed: it now clears anything unreadable and starts you fresh instead of dying. Every other game on the site already survived all six kinds of wreckage, and the test now runs with the rest of our checks so no future game can ship without passing it.</li>
            <li><strong className="text-foreground">Soccer Career: loans, and an honest word about your minutes.</strong> The transfer window now tells you straight how much football your club is planning to give you next season, about X to Y league games, and that projection comes from the exact same maths the season is simulated with, so it cannot sugarcoat. If you are young, under contract and the answer is "not much" at a big club, the loan window opens: clubs further down offer you a season of real football, your contract and wage stay put, and the record books mark the year honestly as a loan. Under the hood two long-standing quirks got fixed too: the big club training boost used to apply in full even if you never played (it now has to be earned with minutes), and your development used to react to last season instead of the one you just played. Play well now, grow now.</li>
            <li><strong className="text-foreground">New game: Wonderkid Factory.</strong> Our second idle game, and this one grows people instead of grandstands. You run a youth academy: scouts bring kids through the door, coaches grow them toward a ceiling only better scouts can read, and the whole game is deciding when to sell. Fees pay extra for a kid with room left to grow, that promise fades through his early twenties, and at 24 he walks out free. Sell your stars on deadline day for half as much again, move the academy up through six regions, and every reputation star you earn is yours forever. Every kid is generated, so no real footballer ever turns up in your dorms. It sits in the Soccer section, saves on your device, and keeps working at half speed for up to eight hours while you are away.</li>
            <li><strong className="text-foreground">You can actually read the site now, everywhere, and use it without a mouse.</strong> We measured every word on every page against the contrast bar accessibility guidelines set, and a lot of quiet grey text plus a few loud buttons came up short: the main green button printed white on green at under half the required contrast, and one World Cup group was drawing its own headings in a colour you could barely see at all. All of it is fixed, by raising only the brightness of the words so every page still looks like itself. Keyboard players get a real deal too: every page now draws a visible ring around whatever is focused, and a hidden skip link jumps straight past the menu to the game. Screen readers now hear every square on the Connect 4 board and every score box in the World Cup predictor announced properly instead of silence.</li>
            <li><strong className="text-foreground">An iPhone pass, and a daily puzzle bug it caught.</strong> A lot of people play this site on a phone, and most of those phones are iPhones, so we went looking for the things that work in one browser and quietly break in Safari. One was real: Minefield worked out which day it was by formatting the date into text and reading it back, which is a shape Safari can refuse outright. That would have left the daily board unable to build at all on an iPhone. It now reads the date properly, and produces exactly the same puzzle it always did. Alongside that, every busy page was checked at phone size for anything hanging off the side of the screen (nothing does), the daily board was checked to actually deal, and every control inside a page now has to be big enough for a thumb, which caught a link we shipped last week at half the size it should have been.</li>
            <li><strong className="text-foreground">You can manage your country in Club Manager.</strong> Win enough at a big enough club and your national federation calls, and you can hold both jobs the way a real manager occasionally does. Club football carries on exactly as it is; the country only plays between seasons. The tournaments are the real ones, with real qualifying groups and the actual slot counts each confederation gets, run on the same international engine our Soccer Career has used for months. What you bring is a small edge rather than a magic wand: a top manager makes his country meaningfully more likely to win a tournament, but the players still decide most of it. Win one and it goes in the same cabinet as a league title. Fail to qualify for a tournament your country should have reached and the federation moves on without you.</li>
            <li><strong className="text-foreground">Getting sacked is a chapter now, not the last page.</strong> In Club Manager, losing your job used to end the save: one screen, a share button, start again from scratch. That is the one moment a manager game should never end on. Now the sack puts you out of work with your record intact, and clubs start calling. The offers are real clubs from the real pyramid with real briefs, and what you get is what you earned: trophies and title finishes open doors, relegations shut them, and the size of the club that just let you go still counts for something. Waiting is a genuine decision, because every week without a job cools the market and the job you hold out for may be gone when you finally say yes. And it can never dead end: sit out long enough with nothing on the table and somebody down the pyramid will take a chance on you. Take a job and you start next season there, with your cabinet, your record, and a board that has its own ideas about what counts as success.</li>
            <li><strong className="text-foreground">Club Manager clubs have shirt sponsors now.</strong> Whenever your club has no deal, the Finances desk puts three offers on the table, and they are three genuinely different bets rather than three numbers: the biggest guaranteed cheque with nothing riding on it, a smaller one with a serious bonus for winning the league, or the smallest locked in for four seasons with a little extra for a top half finish. The money goes into the same kitty as everything else, one payment a season, and the bonus arrives at the end of the season that earns it. Offers scale with the club you are actually running: a giant is worth several times a promoted side, Europe is worth a third again, and a trophy cabinet counts. Leave for another job and the deal stays behind, because it belonged to the club and not to you. Every sponsor is invented, checked against the real companies that sponsor real clubs, same rule as the players.</li>
            <li><strong className="text-foreground">No invented player anywhere on the site wears a real person's name.</strong> Last week's fix covered the two generators behind soccer careers. This one covers all ten, every engine that invents a player, checked by multiplying out every name each can possibly produce and comparing the lot against every real player the site ships. Four more real people turned up: the youth academy could hand you a kid named after two real footballers, the hockey front office could list a real goaltender as a free agent, and the new international pools could produce a real South African international. All fixed. The era world filler was the interesting one, because it already refused any name matching a Club Manager player and was simply blind to everyone else: five names it could still produce belong to real people on other parts of the site, and those are now blocked by name. From here a new generator cannot ship without being checked.</li>
            <li><strong className="text-foreground">A full search-visibility pass over every page on the site.</strong> We went through all 124 pages and made sure each one either earns a place in Google and can be reached from inside the site, or says plainly that it does not want one. Four things came out of it. The games retired over the last few months kept working links but were in no menu and no sitemap, so the only way to land on one was a search result with no way onward; they now tell search engines to skip them while still working for anyone with an old bookmark. Profile and password reset pages were quietly indexable and are not any more, and the admin screens are closed off properly. The College Games Hub, a real page listing every college game, was linked from nowhere at all: it is in the sitemap now and reachable from the College Sports heading on the home page. And the biggest one: the write-up block at the bottom of every game page used a second page-title heading, so around forty pages were telling Google they had two titles. That one taught us something on the way. The obvious fix, demoting it everywhere, would have been worse, because 82 of those pages have no headline of their own and would have ended up with none at all. So the block now reads the page it is on: it steps down where a game already has a title, and provides the title where a game does not. A sweep of all 115 submitted pages in a real browser confirmed exactly one heading each, and nothing looks any different.</li>
            <li><strong className="text-foreground">Your national team screen shows the actual starting eleven.</strong> The Squad screen in Soccer Career used to answer the question with a rank, a number of places and a score, which told you where you stood without ever showing you the team. It is a team sheet now: eleven men in a 4-3-3, front line to keeper, each with his shirt, his name and his rating, and your own card lit up in gold when you are in it. Miss out and you still see the eleven that went without you, with the man keeping you out named underneath. One more thing came out of building it, and it is worth saying plainly: the ten teammates are invented, and while writing the generator we audited the one that already existed and found it could produce seventy six real footballers' exact names, plus four more in the career rivalry system. A generated player has never been allowed to wear a real person's name here, so both generators now draw from pools whose entire combination space is checked, name by name, against every real player on the site. Nearly five thousand invented names across thirty four naming traditions, zero of them belonging to anybody real, and the check runs on every build from now on.</li>
            <li><strong className="text-foreground">Stadium Tycoon got a boardroom, and selling up finally has a decision in it.</strong> Every sale now pays legacy points: one for the sale itself, plus one for every division that ground climbed. Cash out the second the bar fills and you bank one. Push the ladder to The Summit first and you bank ten. Spend them in the new Legacy drawer on eight permanent perks that survive every future club: Boardroom Sway (+10% income a level, up to half again forever), Rolling Investment so the next ground opens with money already in the till, Deep Roots for a faster fanbase, Veteran Payroll so every staff member earns more, a Steady Dressing Room that keeps half your win streak through a defeat instead of losing it all, an Away Day Deal that lifts idle earnings to 80% for 12 hours, Stadium Voltage that charges Matchday Hype two minutes quicker, and Gold Polish that stretches the golden whistles. The whole board costs exactly 100 points, so it is a long game with an actual end. Anyone who already has reputation stars gets a point for each one, automatically, on the next visit.</li>
            <li><strong className="text-foreground">Playing now counts the moment you play.</strong> The header's games-played number has always moved when you finished something with a score, which quietly meant nine of the biggest sims never counted at all: the four Front Office games, the four My Career games and Stadium Tycoon. Fixed sitewide. A played GM week counts, a played career season counts, and the idle game counts once per sitting on your first real action, a tap, a purchase or a hire, however long you stay. The lines we held: loading a page is never playing it, creating a career is not playing one either, and none of these marks carries a score, so leaderboards and best-score tables are exactly as before. Club Manager and Soccer Career already worked this way; now the whole site does. Verified by counting the actual requests a real browser sends: one per played week, one per played season, one per idle sitting, zero for just looking around.</li>
            <li><strong className="text-foreground">Every player wears his real flag, and the market filters by nation.</strong> Club Manager's transfer market grew its last missing filter: nationality, with 132 real nations drawn from your own world's market and a live player count next to each. Every real player on the market and in your squad now carries his real nationality's flag. The detail we sweated: nationality is resolved inside each era separately, because a name is not a person. The 2010 world's Aaron Ramsey is the Welshman at Arsenal; today's is the English midfielder; each wears his own flag in his own world. Made-up academy players honestly get no flag at all. All 6,262 real players across the four worlds are covered, checked name by name against the same market data everything else runs on.</li>
            <li><strong className="text-foreground">Release clauses, and the contracts desk finds the wall.</strong> Club Manager renewals are a real negotiation now: re-sign an expiring player at his full ask, or 12 percent cheaper with a release clause written in at 1.5 times his value that day. The clause is a live exit door, not flavor text: any club can pay it, the trigger chance follows how much of a bargain it has become as he grows, a met clause cannot be rejected or blocked, an ignored one executes itself on deadline day, and the only way to delete one is a later full-price renewal. The desk lives on the Squad tab with every door you have granted in plain sight, bargain warnings included. And an honest confession: the contracts screen was built months ago and never wired into the page, so re-signing was impossible this whole time while deals quietly ran out. Fixed, tested in a real browser, sorry about your free-transfer departures.</li>
            <li><strong className="text-foreground">The GM faces the press room.</strong> All four Front Office games (NFL, NBA, NHL, MLB) now put you at the podium: an introduction presser the day you take the job, the champion's podium if you win it all, the accountability scrum when you miss the owner's ask, and the trade question after a headline deal in a steady year. Every answer comes in three registers, measured, candid or bold, and moves your trust upstairs for real, with the bold answers genuinely gambling. The big ones go further: promise a repeat at the podium and next season's mandate ratchets a tier harder, ask the room for patience after a collapse and the bar softens, at a small cost, because ownership hates hearing smallness. Quiet mandate-met summers stay quiet, no filler pressers.</li>
            <li><strong className="text-foreground">The 2015-16 era gets Serie A.</strong> Club Manager's Leicester season now runs three leagues: Italy joins England and Spain with all 20 real clubs of the 2015-16 Serie A, from Juventus chasing a fifth straight Scudetto (Dybala newly arrived from Palermo, Pogba still in Turin, Vidal honestly gone to Bavaria) to Higuaín's record-chasing Napoli, Totti's Roma with Džeko and Salah newly in, and little Carpi in their one top flight season. That's 60 real clubs and nearly 1,100 real players in that era, every one at their real 2015 age and value, with the famous summer moves applied across all three leagues and the thin squads honestly marked.</li>
            <li><strong className="text-foreground">GM trades became real phone calls.</strong> In all four Front Office games (NFL, NBA, NHL, MLB), proposing a trade no longer gets a flat yes or no. The other GM answers like a person: a fair swap gets the handshake, a close one gets "add a pick and we are done", a stretch gets "he is off the table, but we would move THIS man instead" naming a real player, and an insult gets the dial tone. You can stand firm exactly once per call, and it genuinely gambles: hold leverage (a young piece, a partner thin at that position) and they blink, push a weak hand and the price goes up, sometimes killing the deal. The trade finder still exists for lazy afternoons.</li>
            <li><strong className="text-foreground">Croatia joins Club Manager.</strong> The SuperSport HNL is the twentieth real league: Dinamo Zagreb fresh off their 26th title with Livaković back home in goal, Hajduk Split on the other side of the Eternal Derby, Rijeka rebuilding after the sales that followed their own title, and Rudeš up as the promoted side. That makes 20 leagues, 330 clubs and over 3,600 real players, with the thin small-club squads honestly marked as partial like always.</li>
            <li><strong className="text-foreground">The home page wakes up as you scroll.</strong> Game tiles now rise into place section by section as they enter your screen, each grid in a quick stagger, once, and never again on the same visit. Search results stay instant on purpose, nothing moves for people who ask their device for reduced motion, and no tile can ever be lost behind the effect: the curtain only decorates the entrance.</li>
            <li><strong className="text-foreground">The GM verdict got its moment too.</strong> All four Front Office games (NFL, NBA, NHL, MLB) now stage the season's end instead of printing it: the champion line slams in, ownership's verdict lands a beat later, the playoff results walk in one by one, and if YOUR roster won it all the card pulses gold under falling confetti. The rule is strict on purpose: confetti belongs to the GM whose build won the title and to nobody else, a good grade is not a parade, and a firing gets one honest shake and a grey card, never a celebration.</li>
            <li><strong className="text-foreground">Every career season gets its curtain.</strong> In all four career games (NFL, NBA, NHL, MLB My Career), playing a season now opens a staged reveal instead of dumping text in a feed: the year slams in, the team result lands with the weight it deserves, winning it all pours confetti, and the season's story (the camp battle, the awards, the pressers, the body holding up or not) walks in line by line in the order it happened. Losses stay quiet on purpose, a suspended year gets a deliberately muted card, and the stat line is your true final from the first frame, never a number counting through values you did not put up.</li>
            <li><strong className="text-foreground">Denmark and Switzerland join Club Manager.</strong> Two more real leagues: the Danish Superliga (FC Copenhagen's Champions League regulars, Brøndby's derby, AGF the reigning champions) and the Swiss Super League (Basel's trophy room, Young Boys' plastic-pitch fortress, Thun the surprise champions, and Vaduz playing over the border from Liechtenstein). That makes 19 leagues and 320 clubs, every squad built from real market data, with the thin small-club squads honestly marked as partial.</li>
            <li><strong className="text-foreground">The press room opened in every career game.</strong> All four career sims (NFL, NBA, NHL, MLB) now have a press that actually watched your season. Win it all and you take the championship podium. Collapse and you face the accountability scrum. Change teams and the new city wants its introduction, ride the bench and a beat reporter asks the role question, win MVP and the trophy interview follows, play into a contract year and the future question never stops. Every presser is three answers: the safe one, the honest one, and the fiery one, and the fiery one genuinely gambles, sometimes the clip runs all week and the city is yours, sometimes it runs all week for the wrong reasons. That completes the whole Club Manager playbook, roles, press, talks, market and boards, across every sport on the site.</li>
            <li><strong className="text-foreground">The depth chart reached the ice and the diamond.</strong> NHL and MLB My Career got their version of the chart, with the sport truths kept: no rookie goalie walks into a number one job on draft capital alone (backup goalies get their honest twenty-odd starts), fourth-liners play every night on half the ice time, bench bats get pinch hits and spot starts, long-relief arms wait for the phone, and relievers are exempt because the bullpen ladder already lives in whether you are the closer. Same camp battles, same stakes, same rule that a ring-chase signing can cost a mid player his spot.</li>
            <li><strong className="text-foreground">Nobody hands you the job any more.</strong> NFL and NBA My Career grew a real depth chart. Top picks open as starters, everyone else opens behind an incumbent whose level matches the roster, and every offseason is a camp battle: close the gap and you take the job, decline hard and a starter can lose his. Backup seasons are honest spot duty (quarterbacks hold clipboards, second units get bench minutes), they wear on your morale and your fame, and the free agency choice just got sharper: signing with a stacked contender can cost a mid player the starting spot, so the money, the ring odds and the role are now a real three-way call. NBA Sixth Man of the Year finally goes to actual bench seasons. Old saves are untouched, you were the starter all along.</li>
            <li><strong className="text-foreground">Every game page now points you somewhere good next.</strong> The little "more games" links at the bottom of each page became a proper block of six tiles, and the picks are smarter: games from the same sport, one from the next section over, and a couple of surprises from across the site, chosen the same way every time so you can find your way back. Under the hood this means every single game on the site is now reachable from every other one by following those tiles, which is as good for people who wander as it is for search engines that do the same.</li>
            <li><strong className="text-foreground">The GM games got owners, and owners get impatient.</strong> All four Front Office sims (NFL, NBA, NHL, MLB) now hand you an ownership mandate the day you take the job: a loaded roster is told to win it all, a mid one to make the postseason, a bare one to hit an honest win number, and the ask resets every offseason from where your roster really stands. The hub shows your trust upstairs (0 to 100) and a live read on whether you are on pace, season end brings a graded verdict, and a championship buys years of peace. Miss badly for long enough and you are fired, the save ends, and you take another front office. A defending champion is never asked for less than a deep run. The GM chair finally has stakes.</li>
            <li><strong className="text-foreground">Free agency got real in every career sim.</strong> All four US career games (NFL, NBA, NHL, MLB My Career) replaced the old two-button contract call with an actual market. When your deal expires you now get a window of competing offers from real named teams, each with its own salary, contract length and roster quality, and the roster number is the exact strength your next seasons simulate on. Contenders lowball you because they can, rebuilds overpay because they must, and you can push any offer for more, once. Push a weak case and the offer can vanish, but your own team never walks away, so a career can never be stranded without a deal. Works in the throwback eras too, sealed to era teams and era money.</li>
            <li><strong className="text-foreground">Austria and Greece join Club Manager.</strong> Two more real leagues: the Austrian Bundesliga (take Salzburg's machine, Rapid's crowd or Sturm's champions) and the Super League Greece (Olympiacos, Panathinaikos, AEK and PAOK, one of Europe's angriest title races). That makes 17 leagues and 296 clubs, every squad from real market data, with the small-club squads honestly marked where the records run thin.</li>
            <li><strong className="text-foreground">Manage 2005-06.</strong> The era picker reaches all the way back to Ronaldinho's Ballon d'Or season: Mourinho's back to back Chelsea, Henry's Arsenal, Gerrard fresh off Istanbul, a 17 year old Messi on Barcelona's bench, and Michael Owen arriving at Newcastle. All 40 clubs of that Premier League and La Liga, over 740 real players at their real 2005 ages and values, that summer's moves applied both ways, and the boards even call the second European prize by its right name, the UEFA Cup. This is as far back as the records honestly reach, so there is no invented 2000 era and never will be.</li>
            <li><strong className="text-foreground">Manage the Leicester season.</strong> Club Manager's era picker now offers 2015-16: the real Premier League and La Liga of the year Leicester won it at 5000 to 1. All 40 clubs, over 760 real players at their real 2015 ages and values, with that famous summer's moves applied: Sterling and De Bruyne newly at City, Pedro at Chelsea, Vardy, Mahrez and Kante at their honest pre-title level, MSN at Barcelona. The era's giants rate like the legends they were, prime Messi and Ronaldo above anyone in today's game, and it is a sealed world: nothing from 2026 can leak in, and there is no Conference League because it did not exist yet.</li>
            <li><strong className="text-foreground">Every career sim has a throwback era now.</strong> All four US career games grew an era picker on the create screen. NFL My Career can start in 2005, with the Raiders in Oakland, the Chargers in San Diego and the Rams in St. Louis. NBA My Career can start in 2003-04, the 29 team league with the SuperSonics still in Seattle and no Charlotte yet. NHL My Career can start in 2006-07, with the Thrashers in Atlanta and the Coyotes in Phoenix. MLB My Career can start in 2004, the Expos' last Montreal summer. Every era is a sealed world checked against the real season records: old franchises, old money, and your whole career stays inside it.</li>
            <li><strong className="text-foreground">Found your own club in Club Manager.</strong> The picker grew a fourth option: create your own club, in any league, either era. Name it, build your crest from scratch (six shield shapes, six patterns, your colors, your initials), name your ground, and pick your backing: 15, 40 or 90 million. Your club takes the league place of the division's weakest side, starts with a squad of 24 generated players (all honestly marked), and then you buy real stars off the real market to climb. The boards stay honest about it too: 90 million in the Eredivisie gets told to win it, the same money in the Premier League gets told to survive first, and the create screen quotes your board's demand live while you build.</li>
            <li><strong className="text-foreground">You can manage in 2010 now.</strong> Club Manager's era picker has a real past season: the 2010-11 Premier League and La Liga, all 40 clubs, over 800 real players with their real 2010 ages and values. Take prime Messi's Barcelona with Xavi and Iniesta, Cristiano's young Madrid with Kaka and a just-signed Ozil, Rooney's United, or try keeping Blackpool up. It is a sealed world too: no 2026 wonderkid can leak into your 2010 market, and there is no Conference League because it did not exist yet. Club Manager also covers 13 leagues and 270 clubs today, with Portugal, Scotland, Turkey, Belgium and the German second division all playable.</li>
            <li><strong className="text-foreground">New game: Stadium Tycoon.</strong> Our idle game. You run a tiny club's matchday empire: fans pay you every second, a live toy match pays crowd-sized bonuses for every goal, win streaks light a flame that multiplies everything, and nine upgrade tracks take you from a fence with two benches to a ground that hums. Charge up Matchday Hype and press it to double everything for a minute. It even earns at half speed while you are away, and when the club outgrows its ground you can sell up for a permanent Reputation star and do it all again, faster.</li>
            <li><strong className="text-foreground">Boards talk like boards, and the site celebrates like a stadium.</strong> Club Manager boards now demand the actual prize: win the league, reach the Champions League, avoid the drop, never "finish top 6". The second and third biggest clubs in a league want the title too, exactly like real life. Full time got proper drama: the verdict slams in, scorers roll through in minute order, wins pulse, trophies pour confetti. And every game on the whole site now throws confetti when you win, each with its own fall.</li>
            <li>Profile cleanup: the favourite game picker now lists every game on the site instead of an old partial list, and the Fav Sport stat uses real sport categories (and simply hides instead of saying "General"). We also verified the stats pipeline end to end against the live database: points, leaderboard rank, recently played and best scores are all recording correctly.</li>
            <li><strong className="text-foreground">Club Manager got a proper home screen.</strong> No more one long page. Your club home is now a dashboard of boxes (Board, Inbox, Calendar, League, Cups, Manager, Treatment, Rival watch, Market, Cabinet) and tapping one opens its own screen. The rival viewer is in: tap ANY club in any table and see their full squad, values, ratings, form and standing. And switching mentality on the tactics screen finally looks like something: your outfield line visibly pushes up for attacking or drops deep for defensive, with a little surge animation on every switch.</li>
            <li><strong className="text-foreground">Your players now text you.</strong> Club Manager grew a dressing room with opinions: benched stars demand starts (promise them and then bench them, see what happens), unhappy players threaten moves, and the group chat energy is real, from a Lamborghini in the training ground fountain to a teammate whose podcast episode one is titled "Why My Manager Does Not Understand Football". Every player now carries a full stat line too: appearances, goals, assists, cards, clean sheets and an average match rating, plus a season calendar showing your recent results and what's coming, byes included.</li>
            <li><strong className="text-foreground">Club Manager went worldwide and up to date.</strong> Nine leagues are now playable: the big five with their real 2026-27 lineups (Coventry, Ipswich and Hull are up, West Ham went down, Schalke are back), plus the EFL Championship, the Saudi Pro League, both MLS conferences and the Eredivisie. 186 clubs, over 2,900 real players. And the squads now reflect the summer window we all just watched: Lewandowski at Chicago Fire, ter Stegen on loan at Ajax, Griezmann at Orlando, Morgan Rogers at Chelsea, Tonali at Spurs. We verified the window move by move and stamped every squad screen with the date it reflects.</li>
            <li><strong className="text-foreground">Club Manager transfers are a real game now.</strong> Clicking a player opens an actual negotiation: the selling club sets an ask, you lowball, haggle or meet it, and their patience runs out if you insult them. Rival clubs jump into your deals and start bidding wars, and they will close YOUR deal if you dither. About a third of players carry release clauses you can just pay for an instant signing. You can take two players on loan per season. AI clubs slide bids for your own stars into your inbox, and rejecting them can sour the player. Plus a Latest Transfers feed sortable by biggest fees, and a manager career card with your record, biggest win, worst defeat, priciest buy and best sale.</li>
            <li><strong className="text-foreground">Club Manager just got its biggest upgrade ever.</strong> Every single club in the Premier League, La Liga, Serie A, Bundesliga and Ligue 1 is now playable, 96 clubs total, each with its real 2026 squad, ages and market values (yes, Lewandowski is at Barca). Pick your nation, then your league, then your team, and confirm without ever scrolling. The board hands you a proper objective list like a real manager game: league finish, a cup run, Europe, finishing above your rival, a goals quota, all graded live and at season end. The transfer market now carries nearly 2,000 real players at their actual market values instead of inflated made-up fees, opposition goals come from real scorers, and the cup finally tells you which cup it is.</li>
            <li>Every multi step game now follows one rule: after you tap something, the next step appears in view on its own. Fourteen games got the treatment, from Soccer Career's ceremonies to the Banker's offer in Squad Deal to the week results in the Dynasty sims. No more tapping a button and staring at nothing while the result renders below the fold.</li>
            <li>Player Stock Market got a second way to play: <strong className="text-foreground">Names only</strong>. The classic game hides the names and gives you the numbers. The new unlimited style does the exact opposite, you see exactly who everyone is and none of the values, so you are buying purely on reputation. Find out whether you actually know ball or just know prices.</li>
            <li><strong className="text-foreground">College Grid went from 15 puzzles to 75.</strong> It used to repeat every fifteen days, so if you play daily you had seen every board four times over. Now it runs eleven weeks without repeating, with 26 new programs, the Pac-12, five new awards (Thorpe, Doak Walker, Outland, Butkus, Conference Player of the Year) and new angles like Pro Bowler, Super Bowl winner, Played Two Sports and Transferred Schools.</li>
            <li><strong className="text-foreground">One College Grid board was impossible to win.</strong> An old puzzle paired Oregon with National Champion, and Oregon has never won a national title, so that square could never be filled. Once every fifteen days the daily was unwinnable through no fault of yours. Fixed, and every one of the 75 boards is now checked so all nine squares have real answers.</li>
            <li><strong className="text-foreground">All five career games are now done.</strong> NHL My Career got the last mega round, about 200 additions: five positions (C, LW, RW, D, G) with 17 archetypes, 90 new offseason crossroads, 49 things to buy, and your face on the create screen. Wingers split into left and right, the blue line got a puck mover, and goalies got a workhorse who starts 65 games.</li>
            <li>NHL My Career has a dirty side too: an envelope on the bench with a bounty in it, a twelve year contract whose tail years everyone knows you will never play, a doctor in Europe with a suitcase, a man who pays to know the starting goalie an hour early, and a junior agent holding paper you signed at sixteen. Six new awards as well, so a shutdown defenseman finally has something to chase: Rocket Richard, Art Ross, Selke, Jennings, Masterton and Comeback Player.</li>
            <li>MLB My Career got the mega treatment, about 200 additions. <strong className="text-foreground">Eleven real positions</strong> (SP, RP, C, 1B, 2B, 3B, SS, LF, CF, RF, DH) with 33 archetypes, and relievers finally have their own line with saves and holds instead of pretending to be starters. Catchers, shortstops and designated hitters all hit differently now, and each position falls off at the age it actually falls off.</li>
            <li>MLB My Career has a dirty side built from the sport's own history: a camera in center field and a trash can behind the dugout, something on the glove worth 300 rpm, a clinic in Florida that beats the testing panel, tipping pitches to a man who likes first innings, and an academy that takes a third of a teenager's signing bonus. The commissioner's office tracks all of it.</li>
            <li>Eight new MLB awards too. The game only had Rookie of the Year, All-Star, MVP and Cy Young, so a glove first shortstop or a lights out closer could play fifteen years and win nothing. Added Gold Glove, Silver Slugger, batting title, home run crown, ERA title, saves leader and Comeback Player.</li>
            <li>NBA My Career got the mega treatment too, about 200 additions. <strong className="text-foreground">Five real positions</strong> instead of three buckets (PG, SG, SF, PF, C) with 15 archetypes, so a Point God and a Paint Beast live completely different careers. Build your face before the draft, 90 new offseason crossroads, and 43 new things to buy across seven aisles.</li>
            <li>NBA My Career has a dirty side as well: take the under on your own rebound totals, fake a load management injury for a bettor, coast through March for lottery odds, or take the agent advance nobody is supposed to mention. The league tracks it all, and an indefinite suspension costs you a full season.</li>
            <li>Scoring got a realism fix in NBA My Career. A 78 rated guard was averaging 27 points a night and an 88 was averaging 37, which is a top ten season in league history. Now a solid starter lands around 17, an All Star around 25, and only an all time scorer having a career year gets near 38.</li>
            <li>NFL My Career got the same treatment Soccer Career just got, about 250 additions. <strong className="text-foreground">Five new positions</strong> (tight end, linebacker, corner, edge rusher and kicker) each with their own real stat lines, their own awards and their own aging curve, so a shutdown corner and a franchise quarterback are completely different careers. You build your player's face before the draft, there are 90 new offseason crossroads, and 43 new things to buy across seven aisles.</li>
            <li>NFL My Career has a dirty side too. Sell the real injury report to an offshore book, put money in the bounty envelope, take the program the league cannot test for yet, or let your agent skim your signing bonus. League security tracks all of it on a hidden meter, and at the top of it is an indefinite suspension: you lose the season, the money gets seized, and one rebuilding team calls with the minimum.</li>
            <li>Also in NFL My Career: progression is much slower now (1 to 2 rating points a year instead of 2 to 4), and interception numbers got fixed. A 95 rated quarterback used to throw 12 picks a year, which no elite passer does. Elite seasons now land around 8, average starters 13, bad starters 17.</li>
            <li>Soccer Career got the biggest update in the site's history: over 400 additions in one go. You now <strong className="text-foreground">build your player's actual face</strong> before kickoff (skin tone, hairstyle and colour, beard, boots, accessory, and a signature celebration that gets described every time you score), and that face follows you onto the Ballon d'Or stage and into your retirement. The club that raised you now always offers you a first team deal, so you can finally spend a whole career at your boyhood club, and they can call you home again later.</li>
            <li>Soccer Career also got a dirty side. Betting syndicates, bent officials, transfer kickbacks, offshore accounts, a nightclub that launders money, even buying Ballon d'Or votes. Every dirty choice heats up a hidden investigation meter, and if you stay hot too long: dawn raid, trial, prison, and a comeback from three divisions down. There is always a way out if you want one.</li>
            <li>More of everything in Soccer Career: 95 new clubs across 5 continents, 66 new flags, 47 new things to buy in three new shop aisles (Flex, Family, and a Shady aisle that only appears once you have something to hide), 109 new life events, 20 new newspaper stories, and 6 new animations including confetti on trophy nights. Progression is much slower now too, so hitting world class is a decade of work instead of three good seasons.</li>
            <li><strong className="text-foreground">Two Soccer Career bugs killed.</strong> Winning the World Cup used to break the game completely: the celebration buttons crashed and there was no way to continue, so your best moment was a dead end. It now has a proper winner's speech with four real choices. And the Ballon d'Or can no longer snub you: goals were capped so low in the voting formula that a 45 goal season could not even get nominated. Post the best season in the world and the trophy is yours.</li>
            <li>The whole site got dramatically faster. Everything used to arrive as one giant script before the first game could load; now each game ships as its own small piece, so first loads are about 85 percent lighter and pages you have visited open instantly. Lost visitors also get a proper 404 page now, one that points you at the good games instead of a dead end.</li>
            <li>A big correctness sweep on the dailies. Eight games that quietly flipped their puzzle at the wrong midnight (UTC or your local clock) now all roll over at midnight Eastern like the rest of the site, and NFL Career Path's daily finally locks when you finish it instead of handing you a fresh run on refresh.</li>
            <li>Honest scoreboards everywhere: the NBA, MLB and NHL grids no longer refund your wrong guesses when you reload mid-daily, Baseball Career's final clue pays the 100 points it always advertised, the last hint in Missing Five and Missing Nine actually unlocks on your final guess, The Medal Games' seventh clue now reveals the athlete's initials instead of charging you for nothing, Baseball Connections stopped claiming 4/4 groups on a loss, Mystery Box shows a real error screen when packs fail to load, and Sports Millionaire's Ballon d'Or questions now work for everyone.</li>
            <li>Rebuild Challenge got a full rebuild of its own. Budgets now scale with the club (65M at modest clubs up to 200M at giants), you flip one of ten fortune cards after hiring your coach, you commit your sales BEFORE the market opens, and the board deals a third demand tied to the club's identity. Superclubs want a galactico. Small clubs want the books balanced. Miss one and they sell your best player.</li>
            <li>Conquest's Daily Challenge is now the real deal, in all four sports. Every player gets the same date-seeded season (same map, same fixtures, same results), so scores are finally comparable. One scored run per day, streaks if you keep showing up, and a share line built for the group chat. Free Play stays unlimited.</li>
            <li>Soccer Career got a life. Pick a personality (Showman, Ice Cold, Hothead, Professor, or Enigma), sign an agent (or let your cousin handle it, good luck), and live through 40+ new off-pitch storylines: cursed boots, lookalike scams, pet pigeons, podcast feuds and more, all with real consequences for your career. Smoother animations on the big moments too.</li>
            <li>Real guides on every game page. Every single game now has a proper writeup at the bottom of its page: how to play, the rules that matter, an example run, strategy tips, and an FAQ. No more guessing what a game is about before you click in.</li>
            <li>New <Link to="/about" className="underline hover:text-foreground transition-colors">About</Link>, <Link to="/contact" className="underline hover:text-foreground transition-colors">Contact</Link>, and What's New pages (you are reading one right now).</li>
            <li>A Report a bug button in the footer of every page. Reports land straight in our inbox with the page attached, so fixes happen fast.</li>
            <li>Sign in got a full overhaul: instant signup with no email confirmation wait, Google sign in, and a working Forgot Password flow. Your profile now shows Games Today and Days in a Row.</li>
            <li>The biggest content drop yet: My Career modes for NFL, NBA, MLB, and NHL where you live a whole player career, Front Office GM sims for all four leagues with real rosters and cap rules, Conquest imperialism maps for NHL and MLB, CFB Dynasty and CBB Dynasty college sims, a deeper Soccer Career with new story arcs, Club Manager with real leagues, and Budget Builder v2.</li>
            <li>Quality of life: poll results show your vote instantly, the home page remembers your scroll spot when you come back from a game, and hundreds of small copy cleanups across the whole site.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground mb-2">July 2026</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>A big honesty pass on answer checking. The grid and board game validators got much stricter, so nonsense answers stopped sneaking through as correct.</li>
            <li>Retired a batch of games that were not fun enough and fixed old favorites instead. Rarity Round came back with its scoring bug squashed and the board reveal it always deserved.</li>
            <li>Verified lineup data across the Missing XI family and loaded big new puzzle batches into the grids and Connections games.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground mb-2">Spring 2026</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>DoUKnowBall launched with the first wave of daily soccer games. It has grown to eleven sports and over 100 games since, and it is still growing.</li>
          </ul>
        </div>

        <div>
          <p>
            Want something added or changed? <Link to="/contact" className="underline hover:text-foreground transition-colors">Tell us</Link>. A lot of what you see above started as a player suggestion.
          </p>
        </div>
      </section>

      <div className="mt-16 pt-8 border-t border-border text-center text-xs text-muted-foreground space-y-2">
        <p>All team names, logos and trademarks are property of their respective owners. DoUKnowBall is not affiliated with the NFL, NBA, UFC, NHL, MLB, FIFA, IOC, NCAA, F1, PGA Tour, NASCAR, ATP or WTA. © 2026 DoUKnowBall</p>
        <div className="flex items-center justify-center gap-3">
          <Link to="/privacy" className="underline hover:text-foreground transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link to="/terms" className="underline hover:text-foreground transition-colors">Terms of Service</Link>
        </div>
      </div>
    </div>
  );
};

export default WhatsNew;
