import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
export const ROOT=process.cwd(),BASE='09df145abfb241679022b41903d2f19bc254ebf9',NOW=1791658800000;
export const OUT=path.resolve('career-transfer-brief-artifacts');
export const sha=v=>createHash('sha256').update(v).digest('hex');
export const copy=v=>JSON.parse(JSON.stringify(v));
export const git=(...args)=>execFileSync('git',args,{encoding:'utf8',maxBuffer:30*1024*1024}).trim();
export function seeded(seed,fn){const random=Math.random,now=Date.now;let n=seed>>>0;const draws=[];Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>NOW;try{return{value:fn(),draws};}finally{Math.random=random;Date.now=now;}}
const common="export * as engine from './src/lib/soccerCareerEngine';export * as eras from './src/lib/careerEras';export * as world from './src/lib/soccerCareerLeagueWorld';";
const extras="export * as brief from './src/lib/soccerCareerTransferBrief';export * as moments from './src/components/soccer-career/careerMoments';export * as review from './src/lib/soccerOfferReview';";
export async function bundleTransferBrief({original=false,patches=[],browser=false}={}){const loaded=[],faults=[],temp=fs.mkdtempSync(path.join(os.tmpdir(),'transfer-brief-')),file=path.join(temp,'engine.cjs');
 try{const result=await build({stdin:{contents:common+(original?'':extras),resolveDir:ROOT,loader:'ts'},bundle:true,format:browser?'iife':'cjs',globalName:browser?'TransferBriefOracle':undefined,platform:browser?'browser':'node',outfile:browser?undefined:file,write:!browser,alias:{'@':path.join(ROOT,'src')},define:{'import.meta.env':'{"PROD":true,"DEV":false}'},jsx:'automatic',loader:{'.css':'empty','.svg':'empty','.png':'empty','.jpg':'empty','.webp':'empty'},logLevel:'error',plugins:[{name:'held-source',setup(b){b.onLoad({filter:/\.(ts|tsx|json)$/},args=>{const rel=path.relative(ROOT,args.path).replaceAll('\\','/');if(!rel.startsWith('src/'))return;const raw=original?execFileSync('git',['show',BASE+':'+rel],{maxBuffer:30*1024*1024}):fs.readFileSync(args.path);let contents=raw.toString('utf8').replaceAll('\r\n','\n');for(const patch of patches.filter(p=>p.file===rel)){assert.equal(contents.split(patch.from).length,2,'Unique copied source anchor: '+patch.id);const before=sha(contents);contents=contents.replace(patch.from,patch.to);assert.notEqual(sha(contents),before,'Effective copied source fault');faults.push({id:patch.id,file:rel,before,after:sha(contents)});}let instrumentation=null;if(rel==='src/lib/soccerCareerEngine.ts'){const addition='\nexport {getInterestedTiers as __transferInterestedTiers};\n';instrumentation={scope:'Private existing function export appended in memory only',sha256:sha(addition)};contents+=addition;}loaded.push({file:rel,rawSha256:sha(raw),compiledSha256:sha(contents),original,instrumentation});return{contents,loader:rel.endsWith('.json')?'json':rel.endsWith('.tsx')?'tsx':'ts'};});}}]});assert.equal(faults.length,patches.length,'Every requested fault reached actual compiled source');return{value:browser?result.outputFiles[0].text:createRequire(path.join(ROOT,'package.json'))(file),loaded,faults};}
 finally{fs.rmSync(temp,{recursive:true,force:true});}}
export function sourceReceipt(files){const result=[];for(const file of files){const bytes=fs.readFileSync(file);result.push({file,sha256:sha(bytes)});}return result;}
export function writeEvidence(name,value){fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2));return name;}
export function recordedPlayers(){return JSON.parse(fs.readFileSync('scripts/data/careerLeagueWorldSaves1100.json','utf8')).saves.filter(v=>v.kind==='player');}
export function transferFixture(B,id='ere'){const recorded=recordedPlayers().find(v=>v.id===id);assert(recorded,'Actual captured player fixture');const c=B.engine.repairCareer(copy(recorded.state));c.phase='transfer_window';c.transferSituation={type:'no_interest'};c.pendingOffers=[];c.pendingLoanOffers=null;c.pendingSummary=null;c.pendingBallonDor=null;c.seasonMoments=null;c.contractYearsLeft=3;c.loan=null;c.retired=false;delete c.transferBrief;return c;}
export function independentEligible(B,c){const year=c.seasons[c.seasons.length-1].year+1,tiers=B.engine.__transferInterestedTiers(c.overall,c.age);return B.world.projectLeagueWorldClubs(c,B.eras.adjustClubsForYear(B.engine.FALLBACK_CLUBS,year),year).filter(club=>B.world.clubKeyOf(club.name)!==B.world.clubKeyOf(c.currentClub)&&tiers.includes(club.tier));}
export function independentMatching(B,c,priority){const clubs=independentEligible(B,c);if(priority==='home')return clubs.filter(club=>club.country===c.nationality);if(priority==='level'){const tier=Math.min(...clubs.map(club=>club.tier));return clubs.filter(club=>club.tier===tier);}const ranked=clubs.map(club=>({club,band:B.engine.projectLeagueApps(c.overall,club.tier,club.name,0)})),min=Math.max(...ranked.map(v=>v.band.min)),max=Math.max(...ranked.filter(v=>v.band.min===min).map(v=>v.band.max));return ranked.filter(v=>v.band.min===min&&v.band.max===max).map(v=>v.club);}
export function legacyRequest(B,input){const result=B.engine.requestTransfer(input,B.engine.FALLBACK_CLUBS),next={...input,transferSituation:result};if(result.type==='request_result'&&!result.offer){next.phase='playing';next.transferSituation=null;}return next;}
export function findRequest(B,input,priority,status){const chosen=B.brief.setTransferBrief(copy(input),priority);for(let seed=1;seed<=160;seed++){const result=seeded(seed,()=>B.engine.requestTransferDecision(copy(chosen),B.engine.FALLBACK_CLUBS));if(B.brief.transferBriefResult(result.value,B.engine.projectLeagueApps)?.status===status)return{seed,chosen,expected:result};}throw Error('No actual request seed for '+priority+'/'+status);}