import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
export const ROOT=process.cwd(),BASE='faf0a5f3',NOW=1791658800000;
export const OUT=path.resolve('career-press-market-artifacts');
export const sha=v=>createHash('sha256').update(v).digest('hex');
export const copy=v=>JSON.parse(JSON.stringify(v));
export const git=(...args)=>execFileSync('git',args,{encoding:'utf8',maxBuffer:30*1024*1024}).trim();
export function seeded(seed,fn){const random=Math.random,now=Date.now;let n=seed>>>0;const draws=[];Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>NOW;try{return{value:fn(),draws};}finally{Math.random=random;Date.now=now;}}
const sports="export {NFL_CAREER_SPORT} from './src/lib/nflCareerSport';export {NBA_CAREER_SPORT} from './src/lib/nbaCareerSport';export {MLB_CAREER_SPORT} from './src/lib/mlbCareerSport';export {NHL_CAREER_SPORT} from './src/lib/nhlCareerSport';export {defaultAppearance} from './src/lib/soccerCareerAppearance';";
const common="export * as engine from './src/lib/soccerCareerEngine';"+sports;
const extras="export * as press from './src/lib/soccerCareerPress';export * as market from './src/lib/usCareerMarket';export * as extension from './src/lib/usCareerExtension';export * as fa from './src/lib/usCareerFreeAgency';export * as moments from './src/components/soccer-career/careerMoments';export * as summer from './src/lib/usCareerSummer';export * as retirement from './src/lib/usCareerRetirementFlow';export * as social from './src/lib/careerSocial';";
export async function bundlePressMarket({original=false,patches=[],browser=false}={}){const loaded=[],faults=[],temp=fs.mkdtempSync(path.join(os.tmpdir(),'press-market-')),file=path.join(temp,'engine.cjs');
  try{const result=await build({stdin:{contents:common+(original?'':extras),resolveDir:ROOT,loader:'ts'},bundle:true,format:browser?'iife':'cjs',globalName:browser?'PressMarketOracle':undefined,platform:browser?'browser':'node',outfile:browser?undefined:file,write:!browser,alias:{'@':path.join(ROOT,'src')},define:{'import.meta.env':'{"PROD":true,"DEV":false}'},jsx:'automatic',loader:{'.css':'empty','.svg':'empty','.png':'empty','.jpg':'empty','.webp':'empty'},logLevel:'error',plugins:[{name:'held-source',setup(b){b.onLoad({filter:/\.(ts|tsx|json)$/},args=>{const rel=path.relative(ROOT,args.path).replaceAll('\\','/');if(!rel.startsWith('src/'))return;const raw=original?execFileSync('git',['show',BASE+':'+rel],{maxBuffer:30*1024*1024}):fs.readFileSync(args.path);let contents=raw.toString('utf8').replaceAll('\r\n','\n');for(const patch of patches.filter(p=>p.file===rel)){assert.equal(contents.split(patch.from).length,2,'Unique copied source anchor: '+patch.id);const before=sha(contents);contents=contents.replace(patch.from,patch.to);assert.notEqual(sha(contents),before,'Effective copied source fault');faults.push({id:patch.id,file:rel,before,after:sha(contents)});}loaded.push({file:rel,rawSha256:sha(raw),compiledSha256:sha(contents),original});return{contents,loader:rel.endsWith('.json')?'json':rel.endsWith('.tsx')?'tsx':'ts'};});}}]});assert.equal(faults.length,patches.length,'Every requested fault reached actual compiled source');return{value:browser?result.outputFiles[0].text:createRequire(path.join(ROOT,'package.json'))(file),loaded,faults};}
  finally{fs.rmSync(temp,{recursive:true,force:true});}}
export const sportList=B=>[B.NFL_CAREER_SPORT,B.NBA_CAREER_SPORT,B.MLB_CAREER_SPORT,B.NHL_CAREER_SPORT];
export function soccerFixture(B){const recorded=JSON.parse(fs.readFileSync('scripts/data/careerLeagueWorldSaves1100.json','utf8')).saves.find(v=>v.id==='ere'&&v.kind==='player');assert(recorded);const c=B.engine.repairCareer(copy(recorded.state));c.phase='playing';c.pendingSummary=null;c.pendingBallonDor=null;c.seasonMoments=null;c.position='ST';c.overall=94;c.shooting=94;c.pace=90;c.dribbling=90;c.physical=88;c.popularity=50;c.morale=70;c.contractYearsLeft=4;c.matchFixBanned=0;c.prisonSeasons=0;c.loan=null;delete c.pressRoom;const row=c.seasons.filter(s=>s.type==='playing').at(-1);Object.assign(row,{apps:28,goals:14,assists:6,rating:7,injury:null,injurySevere:false});return c;}
export function usFixture(B,sport,years){const c=seeded(810,()=>sport.startCareer('Market Player',sport.create.defaultPos,sport.create.archetypes[sport.create.defaultPos][0],Math.random,B.defaultAppearance(),sport.create.eras[0].id)).value;c.contractYears=years;c.ovr=94;c.pot=Math.max(94,c.pot);c.age=24;c.salary=Math.max(1,c.salary);c.netWorth=2;c.role='starter';c.health=100;delete c.summer;delete c.retirement;return{c,phase:'season',teamQuality:75,coach:null};}
export function usPlayedSave(B,sport,input){const c=copy(input.c),tq=input.teamQuality;const camp=sport.campBattle(c,tq,Math.random),played=sport.simSeason(c,tq,Math.random);sport.progress(c,Math.random);c.headlines=B.social.pushHeadlines(c.headlines,sport.headlinesFor(c,played.line));assert(!sport.shouldRetire(c),'Young actual fixture does not retire');const event=B.summer.startSummer(c,sport,Math.random,B.retirement.talkDeckFilter(c,sport.hall));const quality=event?tq:sport.rollTeamQuality(tq,Math.random);return{save:{c,phase:event?'event':'season',teamQuality:quality,coach:null},camp,line:played.line,eventId:event?.id??null};}
export function sourceReceipt(files){const result=[];for(const file of files){const bytes=fs.readFileSync(file);result.push({file,sha256:sha(bytes)});}return result;}
export function writeEvidence(name,value){fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2));return name;}