import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { OUT, BASE, sha } from './soccerAgentReviewKit.mjs';
const read=file=>JSON.parse(fs.readFileSync(path.join(OUT,file),'utf8'));
const mode=process.argv[2];
let result;
if(mode==='units'){
 const v=read('units.json'),assertions=v.testResults.flatMap(t=>t.assertionResults);
 assert.equal(v.success,true);assert.equal(v.numFailedTests,0);assert.equal(v.numPendingTests,0);assert.equal(assertions.length,129);assert(assertions.every(t=>t.status==='passed'));
 const files=['soccerAgentReview.test.ts','soccerAgentReviewUi.test.tsx','soccerAgentReviewPage.test.tsx','soccerCareerSaveRetry.test.tsx'],counts=[83,28,10,8];
 result={mode,total:assertions.length,files:files.map((file,index)=>{const rows=v.testResults.filter(t=>t.name.replaceAll('\\','/').endsWith('/'+file));assert.equal(rows.length,1);assert.equal(rows[0].assertionResults.length,counts[index]);assert(rows[0].assertionResults.every(t=>t.status==='passed'));return{file,passed:rows[0].assertionResults.length};})};
}else if(mode==='outcomes'){
 const v=read('outcomes.json');assert.equal(v.base,BASE);assert.deepEqual(v.sourceAfter,v.sourceBefore);assert.equal(v.groups.length,8);assert(v.groups.every(t=>t.ok));assert.equal(v.controls.length,7);assert.equal(v.neutral.length,120);
 for(const row of v.neutral){const pair=read(row.file);assert.deepEqual(pair.current,pair.original);assert.deepEqual(pair.read.draws,[]);assert(Array.isArray(pair.original.draws));}
 assert.deepEqual([...new Set(v.neutral.map(t=>t.kind))].sort(),['absent','future','malformed','missing-agent']);assert(v.neutral.some(t=>t.age===31));
 for(const control of v.controls){assert.equal(control.faults.length,1);assert.equal(control.faults[0].targetCount,1);assert.notEqual(control.faults[0].before,control.faults[0].after);assert(control.loaded.length>0);assert.deepEqual(control.groups.filter(t=>!t.ok).map(t=>t.name),control.expectedFailures);assert(control.groups.filter(t=>!t.ok).every(t=>t.assertion));assert.equal(control.groups.filter(t=>t.ok).length,8-control.expectedFailures.length);}
 const later=read('healthy-later-recorded-year.json');assert(later.completed.trace.length>0);assert.equal(later.completed.value.phase,'playing');assert(later.completed.trace.some(t=>t.phase==='season_summary'));assert(later.completed.trace.every(t=>t.value.seasons.length===later.input.seasons.length));assert.equal(v.fixtures.length,4);result={mode,groups:8,originalWholePairs:120,readVectors:120,sourceControls:7,branches:4,sourceHeld:true};
}else if(mode==='page-control'){
 const v=read('page-control-receipt.json');assert.deepEqual(v.sourceAfter,v.sourceBefore);assert.equal(v.controls.length,2);
 for(const c of v.controls){const total=c.id==='page-double-callback'?10:28;assert.equal(c.baseline,total);assert.equal(c.baselineExit,0);assert.equal(c.exit,1);assert.notEqual(c.faultHash,c.sourceHash);assert.equal(c.failed.length,c.id==='page-double-callback'?3:1);assert.equal(c.unrelatedPassed,total-c.failed.length);assert.equal(c.edits.length,c.id==='page-double-callback'?2:1);assert(c.edits.every(t=>t.targetCount===1&&t.before!==t.after));assert(c.failed.every(t=>t.messages.length>0));}
 result={mode,pageBaseline:10,componentBaseline:28,sourceControls:2,intendedFailures:v.controls.map(c=>({id:c.id,failed:c.failed.map(t=>t.title),unrelatedPassed:c.unrelatedPassed}))};}else if(mode==='native'){
 const v=read('native/report.json');assert.equal(v.failed,0);assert.equal(v.forwarded,0);assert.equal(v.cases.length,12);assert.equal(v.controls.length,3);assert.deepEqual(v.sourceAfter,v.sourceBefore);assert.deepEqual(v.bootstrapSourceAfter,v.bootstrapSources.map(({file,sha256})=>({file,sha256})));
 let pairs=0,reloads=0,vectors=0,bootstraps=0,layouts=0,restorations=0,shots=0,legacyControls=0;
 const seen=new Set();
 for(const c of v.cases){assert(c.ok&&c.checks>0);assert(!c.errors.length&&!c.assetErrors.length);assert(c.fontsUsed.length>0);assert([320,390,1280].includes(c.width));assert(['cousin','shark','super','self'].includes(c.fixture));assert(!seen.has(c.id));seen.add(c.id);
  assert.equal(c.id,c.width+'-'+c.fixture);assert(c.pairs.length>=7);assert.equal(c.reloads.length,5);assert.equal(c.bootstrap.length,c.reloads.length);assert.equal(c.restorations.length,4);for(const op of ['choose','next','sign'])assert.equal(c.actions.filter(a=>a.op===op).length,1);
  const catalogue=read('native/'+c.id+'-catalogue-terms.json');assert.equal(catalogue.length,4);assert.deepEqual(catalogue.map(a=>a.id),['cousin','shark','super','self']);assert(catalogue.every(a=>JSON.stringify(a.actual)===JSON.stringify(a.wanted)));
  const annual=read('native/'+c.id+'-annual-commission.json'),signed=read('native/'+c.id+'-actual-signed-terms.json'),rounded=value=>Math.round(value*100)/100;
  assert.equal(annual.input.agentId,c.fixture);assert.equal(annual.played.seasons.length,annual.input.seasons.length+1);assert.equal(annual.played.age,annual.input.age+1);assert.equal(annual.played.weeklyWage,annual.input.weeklyWage);assert.equal(annual.gross,annual.input.weeklyWage*52/1000000+annual.played.sponsorshipIncome);assert.equal(annual.commission,rounded(annual.gross*annual.rate));assert.equal(annual.played.agentFeesPaid,rounded(annual.input.agentFeesPaid+annual.commission));
  assert.equal(signed.agent.id,c.fixture);assert.equal(signed.windowState.transferSituation.type,'contract_expiry');assert(signed.windowState.transferSituation.offers.some(a=>JSON.stringify(a)===JSON.stringify(signed.offer)));assert.equal(signed.signedWage,Math.round(signed.offer.wage*signed.agent.wageMult));assert.equal(signed.fee,rounded(signed.offer.transferFee*signed.agent.transferCut));assert.equal(signed.final.weeklyWage,signed.signedWage);assert.equal(signed.final.agentFeesPaid,rounded(signed.windowState.agentFeesPaid+signed.fee));assert.equal(signed.final.currentClub,signed.offer.club.name);assert.equal(signed.final.phase,'playing');assert.equal(signed.final.agentReview.sourceCount,annual.input.agentReview.sourceCount);assert.equal(annual.rate,signed.agent.incomeCut);
  for(const p of c.pairs){const d=read('native/'+p.file);assert.equal(d.actualBytes,d.expectedBytes);assert.equal(d.actualSha256,sha(d.actualBytes));assert.equal(d.expectedSha256,sha(d.expectedBytes));assert.deepEqual(d.actual,d.expected);assert.deepEqual(d.diff,[]);pairs++;}
  for(const p of c.reloads){const d=read('native/'+p.file);assert.equal(d.before,d.after);assert.equal(d.beforeSha256,sha(d.before));assert.equal(d.afterSha256,sha(d.after));reloads++;}
  for(const p of c.rng){const d=read('native/'+p.file);assert.deepEqual(d.actual,d.expected);assert.equal(p.actualSha256,sha(JSON.stringify(d.actual)));assert.equal(p.expectedSha256,sha(JSON.stringify(d.expected)));vectors++;}
  for(const p of c.bootstrap){const d=read('native/'+p.file);assert.equal(d.callerFilter,false);assert.equal(d.engineOracleComparison,false);assert.equal(d.startedBeforeModules,true);assert.equal(d.scope,'unfiltered-site-reload-to-ready');assert.deepEqual(d.draws,d.calls.map(t=>t.value));assert.equal(p.drawCount,d.calls.length);assert.equal(p.callsSha256,sha(JSON.stringify(d.calls)));assert.equal(p.drawsSha256,sha(JSON.stringify(d.draws)));assert(d.calls.every(t=>Number.isFinite(t.value)&&t.value>=0&&t.value<1&&typeof t.stack==='string'&&t.stack.length>0));const raw=read('native/'+d.rawReload);assert.equal(d.beforeSha256,raw.beforeSha256);assert.equal(d.afterSha256,raw.afterSha256);for(const asset of d.assets){const held=v.bootstrapSources.find(t=>t.file===asset.file);assert(held);assert.equal(held.sha256,asset.sha256);}bootstraps++;}
  for(const p of c.restorations){assert.equal(p.focus,true);assert.deepEqual(p.before,p.after);assert(Array.isArray(p.before.declarations));restorations++;}
  for(const d of c.layouts){assert.equal(d.viewport.requested.width,c.width);assert(Math.abs(d.viewport.inner.width-c.width)<=1);assert(d.viewport.client.width<=c.width+1);assert(!d.viewport.visual||Math.abs(d.viewport.visual.scale-1)<=0.01);assert.equal(d.overflow,false);assert(d.stableFrames>=4&&d.finiteAnimations===0&&d.fonts==='loaded');assert(d.required.length>0);for(const target of d.required){assert(target.inside&&target.painted);assert.equal(target.points.length,5);assert(target.points.every(t=>t.insideTarget&&Number.isFinite(t.x)&&Number.isFinite(t.y)));if(target.touchFloor>0)assert(target.width>=target.touchFloor-0.5&&target.height>=target.touchFloor-0.5);}layouts++;}
  for(const p of c.shots){assert.equal(sha(fs.readFileSync(path.join(OUT,'native',p.file))),p.sha256);shots++;}
  legacyControls+=c.legacyControls.length;
 }
 assert.equal(shots,39);assert(v.controls.every(c=>c.effective&&c.restored));for(const c of v.controls){for(const probe of c.probes??[c]){assert.notDeepEqual(probe.faulty,probe.observed);assert.deepEqual(probe.restoredObservation,probe.observed);assert(probe.failed.length>0);}}
 for(const item of v.fontManifest)assert.equal(sha(fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,item.file))),item.sha256);
 for(const item of v.bootstrapSources)assert.equal(sha(fs.readFileSync(path.join(OUT,'native',item.retained))),item.sha256);
 result={mode,checks:v.checks,journeys:12,wholePairs:pairs,postStartupExactVectors:vectors,rawReloads:reloads,unfilteredStartupObservations:bootstraps,layouts,restorations,shots,observationControls:3,legacyControls,scope:'Agent review, cookie and existing contract-review controls assert their44px floor. Other legacy gameplay controls retain measured dimensions. Startup is unfiltered and retained separately from exact action vectors.'};
}else throw Error('Unknown agent review receipt mode '+mode);
fs.writeFileSync(path.join(OUT,'checked-'+mode+'.json'),JSON.stringify(result,null,2));console.log('PASS agent review '+mode+': '+JSON.stringify(result));
