// Remote-only complete engine fixtures and source receipts for the modern league phase.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
export const ROOT=process.cwd(),BASE='09df145abfb241679022b41903d2f19bc254ebf9',OUT=path.resolve('manager-ucl-league-artifacts'),KEY='dukb-club-manager-save',NOW=1791720000000;
export const copy=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value)),sha=value=>createHash('sha256').update(value).digest('hex');
export const git=(...args)=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8',maxBuffer:64*1024*1024});
export function held(files){const result=[];for(const file of files){const raw=fs.readFileSync(path.join(ROOT,file));result.push({file,sha256:sha(raw)});}return result;}
export function store(){const values=new Map();globalThis.localStorage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),clear:()=>values.clear()};return values;}
export function seeded(seed,fn){const previous=Math.random,previousNow=Date.now,draws=[];let state=seed>>>0;Math.random=()=>{state+=0x6d2b79f5;let n=state;n=Math.imul(n^n>>>15,n|1);n^=n+Math.imul(n^n>>>7,n|61);const value=((n^n>>>14)>>>0)/4294967296;draws.push(value);return value;};Date.now=()=>NOW;try{return{value:fn(),draws};}finally{Math.random=previous;Date.now=previousNow;}}
export async function bundleUcl({original=false,patch=null,browser=false}={}){
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'manager-ucl-proof-')),loaded=[],faults=[],file=path.join(temp,'bundle.cjs');
 try{const result=await build({stdin:{contents:"export * as E from './src/lib/clubManager';export * as C from './src/lib/clubManagerCalendar';export * as eras from './src/lib/clubManagerEras';export * as M from './src/lib/uclFormatHistoryEngine';"+(original?'':"export * as L from './src/lib/clubManagerUclLeague';")+(!browser?"export {CalendarCard} from './src/components/club-manager/CalendarCard';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';export const renderCalendar=(career)=>renderToStaticMarkup(React.createElement(CalendarCard,{career}));":''),resolveDir:ROOT},bundle:true,platform:browser?'browser':'node',format:browser?'iife':'cjs',globalName:browser?'UclOracle':undefined,outfile:browser?undefined:file,write:!browser,jsx:'automatic',alias:{'@':path.join(ROOT,'src')},define:{'import.meta.env':'{"PROD":true,"DEV":false}'},loader:{'.css':'empty','.svg':'empty','.png':'empty'},logLevel:'error',plugins:[{name:'actual-held-source',setup(b){b.onLoad({filter:/\.(tsx?|json)$/},args=>{
 const relative=path.relative(ROOT,args.path).replaceAll('\\','/');if(!relative.startsWith('src/'))return;
 const raw=original?execFileSync('git',['show',BASE+':'+relative],{cwd:ROOT,maxBuffer:64*1024*1024}):fs.readFileSync(args.path);let contents=raw.toString('utf8').replaceAll('\r\n','\n');
 if(patch&&relative===patch.file){const count=contents.split(patch.from).length-1;assert.equal(count,1,'Copied source fault anchor exactly once: '+patch.name);const before=sha(contents);contents=contents.replace(patch.from,patch.to);assert.notEqual(sha(contents),before);faults.push({name:patch.name,file:relative,count,beforeSha256:before,afterSha256:sha(contents),from:patch.from,to:patch.to});fs.mkdirSync(path.join(OUT,'fault-source'),{recursive:true});fs.writeFileSync(path.join(OUT,'fault-source',patch.name+'.ts'),contents);}
 loaded.push({file:relative,source:original?BASE:'current',rawSha256:sha(raw),compiledSha256:sha(contents)});return{contents,loader:relative.endsWith('.json')?'json':relative.endsWith('.tsx')?'tsx':'ts'};
 });}}]});if(patch)assert.equal(faults.length,1);return{value:browser?result.outputFiles[0].text:createRequire(path.join(ROOT,'package.json'))(file),loaded,faults};}finally{fs.rmSync(temp,{recursive:true,force:true});}
}
export function leagueTotals(stage){return stage.table.map(({club})=>{const row={club,w:0,d:0,l:0,gf:0,ga:0,pts:0};for(const result of stage.results){if(result.home!==club&&result.away!==club)continue;const own=result.home===club?result.hg:result.ag,other=result.home===club?result.ag:result.hg;row.gf+=own;row.ga+=other;if(own>other){row.w++;row.pts+=3;}else if(own<other)row.l++;else{row.d++;row.pts++;}}return row;});}
export function scheduleProof(stage,field,myClub){
 assert(stage&&stage.format==='league36','Actual modern league format');assert.equal(stage.table.length,36);assert.deepEqual(stage.table.map(r=>r.club).sort(),[...field].sort());assert.equal(stage.fixtures.length,8);const pairs=new Set();
 for(const day of stage.fixtures){assert.equal(day.length,18);assert.deepEqual(day.flat().sort(),[...field].sort());for(const pair of day){assert.notEqual(pair[0],pair[1]);const key=JSON.stringify([...pair].sort());assert(!pairs.has(key),'Eight distinct opponent fixtures');pairs.add(key);}}
 assert.equal(pairs.size,144);for(const club of field){const games=stage.fixtures.flat().filter(pair=>pair.includes(club));assert.equal(games.length,8);assert.equal(games.filter(p=>p[0]===club).length,4,'Four actual home fixtures');assert.equal(games.filter(p=>p[1]===club).length,4);assert.equal(new Set(games.map(p=>p[0]===club?p[1]:p[0])).size,8);}
 assert.deepEqual(stage.opponents,stage.fixtures.map(day=>{const pair=day.find(p=>p.includes(myClub));return pair[0]===myClub?pair[1]:pair[0];}));
 assert.equal(stage.results.length,stage.matchday*18);assert.deepEqual(stage.table,leagueTotals(stage),'All36 saved rows equal independent actual result totals');
}
export function advance(B,input,seed){return seeded(seed,()=>B.E.playNextEntry(copy(input),{skipHalftime:true,noCoach:true}));}
export function runSeason(B,input,seed,{stopAtLeague=false}={}){
 let state=copy(input);const trace=[],reports=[],checkpoints=[];let guard=0;
 while(state.week<state.calendar.length&&guard++<250){const before=copy(state),result=advance(B,before,seed+guard),next=result.value.state;assert(next,'Actual match callback returns state');assert(next.week>before.week||result.value.kind==='window','Actual calendar callback progresses');trace.push({week:before.week,entry:before.calendar[before.week],input:before,result:result.value,draws:result.draws});if(result.value.report)reports.push(result.value.report);state=next;
 if(before.uclGroup?.matchday!==state.uclGroup?.matchday||before.uclKoRound!==state.uclKoRound)checkpoints.push({week:state.week,stage:copy(state.uclGroup),round:state.uclKoRound,bracket:copy(state.uclBracket)});
 if(stopAtLeague&&state.uclGroup?.matchday===8)break;
 }
 assert(guard<250,'Bounded complete actual season');return{state,reports,trace,checkpoints};
}
export function saveProof(B,input,seed=910){const values=store(),before=JSON.stringify(input),first=seeded(seed,()=>{assert(B.E.saveCareer(copy(input)));return B.E.loadCareer();});assert(first.value);const afterFirst=values.get(KEY),second=seeded(seed+1,()=>{assert(B.E.saveCareer(first.value));return B.E.loadCareer();});const afterSecond=values.get(KEY);assert.equal(afterSecond,JSON.stringify(second.value));assert.deepEqual(second.value,first.value,'Second whole load remains canonical');assert.equal(JSON.stringify(input),before);return{input,first,second,before,afterFirst,afterSecond};}
export async function dependencies(mode){fs.mkdirSync(OUT,{recursive:true});const file=path.join(OUT,'dependencies-before.json'),packagesFiles=held(['package.json','package-lock.json']);if(mode==='before'){const lock=JSON.parse(fs.readFileSync('package-lock.json','utf8')),packages=[];for(const[d,m]of Object.entries(lock.packages)){const f=path.join(ROOT,d,'package.json');if(!d.startsWith('node_modules/')||!fs.existsSync(f)||!m.version)continue;const actual=JSON.parse(fs.readFileSync(f,'utf8'));assert.equal(actual.version,m.version);packages.push({directory:d,name:actual.name,version:actual.version});}assert(packages.length);fs.writeFileSync(file,JSON.stringify({packagesFiles,packages},null,2));}else{const before=JSON.parse(fs.readFileSync(file,'utf8'));assert.deepEqual(packagesFiles,before.packagesFiles);for(const p of before.packages){const actual=JSON.parse(fs.readFileSync(path.join(ROOT,p.directory,'package.json'),'utf8'));assert.equal(actual.name,p.name);assert.equal(actual.version,p.version);}fs.writeFileSync(path.join(OUT,'dependencies-after.json'),JSON.stringify(before,null,2));}console.log('PASS actual locked dependency versions and package bytes '+mode);}
if(process.argv[2]==='dependencies')await dependencies(process.argv[3]);
if(process.argv[2]==='units'){const result=JSON.parse(fs.readFileSync(path.join(OUT,'units.json'),'utf8'));assert.equal(result.success,true);assert.equal(result.numFailedTests,0);assert.equal(result.numPendingTests,0);assert.equal(result.numTodoTests??0,0);for(const[name,count]of[['clubManagerUclLeague.test.ts',50],['managerUclCalendarUi.test.tsx',1]]){const unit=result.testResults.find(r=>r.name.endsWith('/'+name));assert(unit&&unit.assertionResults.length===count);assert(unit.assertionResults.every(r=>r.status==='passed'));}console.log('PASS actual50 league model assertions plus one expanded saved-calendar UI assertion, zero skipped/pending/todo');}
