// Built Soccer Career season history journeys. Remote CI only.
import '../lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createServer } from 'node:net';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import pw from '../lib/playwrightLoader.mjs';
assert(process.env.CI, 'Native season history proof runs only in remote CI');
process.env.SEASON_HISTORY_IMPORT_ONLY = '1';
const { rawHistory, rawComparison } = await import('./seasonHistory1193.mjs');
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..'), OUT = path.resolve(ROOT, process.env.SHOTS || '.tmp-fx/season-history/native');
const INPUT = path.resolve(ROOT, process.env.SEASON_HISTORY_ARTIFACTS || '.tmp-fx/season-history/outcomes'), CACHE = path.resolve(ROOT, process.env.FREE_KICK_FONT_CACHE || '.tmp-fx/season-history/font-cache');
const KEY='soccerCareerSave',NOW=1791586800000,copy=value=>JSON.parse(JSON.stringify(value)),sha=value=>createHash('sha256').update(value).digest('hex');
const files=['src/components/soccer-career/SeasonRatings.tsx','src/components/soccer-career/SoccerSeasonHistory.tsx','src/lib/soccerCareerSeasonHistory.ts','src/lib/soccerCareerEngine.ts','src/pages/SoccerCareer.tsx','scripts/qa/playSeasonHistory1193.mjs'];
function sourceHashes(){const out={};for(const file of files){const bytes=fs.readFileSync(path.join(ROOT,file));out[file]=sha(bytes);}return out;}
fs.mkdirSync(OUT,{recursive:true});
const write=(name,value)=>fs.writeFileSync(path.join(OUT,name+'.json'),JSON.stringify(value,null,2));
const git=(...args)=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8'}).trim();
const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),cases:[],controls:[],checks:0,failed:0,forwardedExternalRequests:0,sourceBefore:sourceHashes()};
const fonts=new Map(JSON.parse(fs.readFileSync(path.join(CACHE,'manifest.json'),'utf8')).map(entry=>{assert(['https://fonts.googleapis.com','https://fonts.gstatic.com'].includes(new URL(entry.url).origin));const body=fs.readFileSync(path.join(CACHE,entry.file));assert.equal(sha(body),entry.sha256);return[entry.url,{body,contentType:entry.contentType}];}));
const fixtures=JSON.parse(fs.readFileSync(path.join(INPUT,'native-fixtures.json'),'utf8'));assert.equal(fixtures.cases.length,3);
const oracleBuild=await build({stdin:{contents:"export * as soccer from './src/lib/soccerCareerEngine'; export * as moments from './src/components/soccer-career/careerMoments';",resolveDir:ROOT,loader:'ts'},bundle:true,platform:'browser',format:'iife',globalName:'__seasonHistoryOracle',write:false,jsx:'automatic',alias:{'@':path.join(ROOT,'src')},define:{'import.meta.env':'{"DEV":false,"PROD":true,"MODE":"production"}'},loader:{'.css':'empty','.svg':'empty','.png':'empty','.jpg':'empty','.webp':'empty'},logLevel:'error'});
const layoutFailures=o=>[o.stable<4&&'stable-frames',!o.inside&&'viewport',!o.painted&&'painted-center',Number(o.opacity)!==1&&'opacity',o.finite!==0&&'animations',o.overflow&&'horizontal-overflow',o.controls.some(c=>c.points.some(p=>!p.painted))&&'painted-controls',o.controls.some(c=>c.clipped)&&'clipped-controls',o.required.some(r=>!r.inside||!r.painted)&&'required-targets',(!o.controls.length||o.controls.some(c=>c.width<44||c.height<44))&&'touch-target'].filter(Boolean);
const restoreFailures=o=>[!o.actual.focus&&'focus',o.actual.top!==o.expected.top&&'mode-position',o.actual.inline!==o.expected.inline&&'inline-overflow',o.actual.computed!==o.expected.computed&&'computed-overflow',o.actual.y!==o.expected.y&&'page-position'].filter(Boolean);
const savedFailures=o=>[JSON.stringify(o.expected)!==JSON.stringify(o.actual)&&'saved-values'].filter(Boolean);
function detector(name,baseline,mutate,predicate,expected){assert.deepEqual(predicate(baseline),[]);const faulty=copy(baseline),undo=mutate(faulty);assert.equal(typeof undo,'function');assert.notDeepEqual(faulty,baseline);const failed=predicate(faulty);assert.deepEqual(failed,expected);write('control-'+name+'-baseline',baseline);write('control-'+name+'-mutated',faulty);undo();assert.deepEqual(faulty,baseline);assert.deepEqual(predicate(faulty),[]);report.controls.push({name,changed:true,failed,restored:true,scope:'Copied actual browser observation, not a served product mutation'});console.log('CONTROL FIRED(native '+name+'): '+failed.join(', '));}
const port=await new Promise((resolve,reject)=>{const probe=createServer();probe.once('error',reject);probe.listen(0,'127.0.0.1',()=>{const value=probe.address().port;probe.close(error=>error?reject(error):resolve(value));});});
const BASE='http://127.0.0.1:'+port,server=spawn(process.execPath,['scripts/lib/hostLikeServer.mjs','dist',String(port)],{cwd:ROOT,stdio:['ignore','pipe','pipe'],windowsHide:true});
let serverLog='',browser;
const ready=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Owned server did not start')),15000);server.once('error',error=>{clearTimeout(timer);reject(error);});server.once('exit',code=>{clearTimeout(timer);reject(new Error('Owned server exited '+code+': '+serverLog));});server.stdout.on('data',data=>{serverLog+=data;if(serverLog.includes('host-like server:')){clearTimeout(timer);resolve();}});server.stderr.on('data',data=>{serverLog+=data;});});
const format=(value,digits=0,signed=false)=>value===null?'Not recorded':(signed&&value>0?'+':'')+value.toFixed(digits);
const year=value=>value===null?'Year not recorded':value+'/'+String((value+1)%100).padStart(2,'0');
const identity=value=>[year(value.year),value.club??'Club not recorded',value.age===null?'Age not recorded':'Age '+value.age,...(value.onLoanFrom?['On loan from '+value.onLoanFrom]:[])];
const injury=value=>!value.injuryRecorded?'Not recorded':value.injury??'No injury recorded';
const suspended=value=>value===null?'Not recorded':value+' club '+(value===1?'match':'matches')+' missed';
const expectedFields=value=>({apps:format(value.apps),injury:injury(value),weeks:value.injuryWeeks===null?'Not recorded':value.injuryWeeks+' '+(value.injuryWeeks===1?'week':'weeks'),severity:value.injurySevere===null?'Not recorded':value.injurySevere?'Serious injury recorded':'No serious injury recorded',suspension:suspended(value.suspensionMatches),reason:value.zeroAppsReason??(value.apps===null?'Appearances not recorded':'Appearances recorded')});
try{
  await ready;browser=await pw.chromium.launch({headless:true});
  for(const profile of[{width:320,height:568,touch:true},{width:390,height:844,touch:true},{width:1280,height:900,touch:false}])for(const input of fixtures.cases){
    const id=profile.width+'-'+input.id,row={id,...profile,case:input.id,checks:[],errors:[],assetErrors:[],intercepted:[],writes:[],layouts:[],reloads:[],readings:[],restorations:[],selections:[]};report.cases.push(row);
    const check=(ok,label)=>{report.checks++;if(!ok)report.failed++;row.checks.push({ok:!!ok,label});console.log((ok?'ok  ':'FAIL')+' '+id+': '+label);assert(ok,id+': '+label);};
    const fixture=copy(input.career);write(id+'-fixture',{simulation:input.simulation,fixture});
    const context=await browser.newContext({viewport:{width:profile.width,height:profile.height},hasTouch:profile.touch,isMobile:profile.touch,colorScheme:'dark',reducedMotion:'reduce',serviceWorkers:'block',storageState:{cookies:[],origins:[{origin:BASE,localStorage:[{name:KEY,value:JSON.stringify(fixture)},{name:'cookie-consent',value:'essential'},{name:'dukb-theme',value:'dark'},{name:'dukb-guest-handle',value:'SteadyVolley-18'}]}]}});
    const oracleContext=await browser.newContext(),oracle=await oracleContext.newPage();
    const clock=now=>{const OldDate=Date;window.Date=class extends OldDate{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};};
    await context.addInitScript(clock,NOW);await oracle.addInitScript(clock,NOW);
    await context.addInitScript(()=>{const old=Math.random;window.__seasonHistoryReadDraws=[];Math.random=()=>{const value=old();window.__seasonHistoryReadDraws.push(value);return value;};});
    await context.route('**/*',route=>{const request=route.request(),url=new URL(request.url());if(url.origin===BASE){assert(['GET','HEAD'].includes(request.method()));return route.continue();}row.intercepted.push({method:request.method(),origin:url.origin,path:url.pathname,blocked:true});if(!['GET','HEAD','OPTIONS'].includes(request.method()))row.writes.push({method:request.method(),path:url.pathname,blocked:true});if(request.method()==='GET'&&fonts.has(url.href))return route.fulfill({status:200,...fonts.get(url.href)});if(['fonts.googleapis.com','fonts.gstatic.com'].includes(url.hostname)){row.assetErrors.push('Uncached font '+url.href);return route.abort();}if(request.resourceType()==='image')return route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="12"/>'});return route.fulfill({status:200,contentType:request.resourceType()==='stylesheet'?'text/css':'application/json',body:request.resourceType()==='stylesheet'?'':'[]'});});await context.routeWebSocket('**/*',socket=>socket.close());
    const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>row.errors.push(String(error)));page.on('requestfailed',request=>{if(request.url().startsWith(BASE))row.assetErrors.push(request.url()+': '+request.failure()?.errorText);});page.on('response',response=>{if(response.url().startsWith(BASE)&&response.status()>=400)row.assetErrors.push(response.url()+': '+response.status());});
    const bytes=()=>page.evaluate(key=>localStorage.getItem(key),KEY),body=()=>page.evaluate(()=>({inline:document.body.style.overflow,computed:getComputedStyle(document.body).overflow,y:scrollY}));
    const activate=async button=>{await button.scrollIntoViewIfNeeded();await button.focus();if(profile.touch)await button.tap();else await button.press('Enter');};
    let canonicalBytes,canonical,readDraws,observedValues,observedLayout,observedRestore;
    const unchanged=async name=>{const actual=await bytes(),draws=await page.evaluate(()=>window.__seasonHistoryReadDraws);write(id+'-'+name+'-saved',{expected:JSON.parse(canonicalBytes),actual:JSON.parse(actual),expectedBytes:canonicalBytes,actualBytes:actual,drawsBefore:readDraws,drawsAfter:draws});row.readings.push({name,expectedSha256:sha(canonicalBytes),actualSha256:sha(actual),bytes:Buffer.byteLength(actual),drawCount:draws.length-readDraws.length});check(actual===canonicalBytes,name+': every complete saved byte held');check(JSON.stringify(draws)===JSON.stringify(readDraws),name+': no global random draws');};
    const capture=async(target,name)=>{
      const required=['[data-season-history-help]','[data-season-history-close]','h2',...(name==='comparison-top'?['[data-season-history-heading]','[data-season-history-select="first"]','[data-season-history-select="second"]','[data-season-history-swap]']:name==='availability-top'?['[data-season-history-heading]','[data-season-history-select="availability"]']:[])];
      await page.bringToFront();await page.waitForFunction(()=>!document.querySelector('[data-sonner-toast]'),undefined,{timeout:10000});
      const layout=await target.evaluate(async(element,requiredSelectors)=>{let previous='',stable=0,last;const started=performance.now();while(performance.now()-started<2500){await new Promise(resolve=>requestAnimationFrame(resolve));const r=element.getBoundingClientRect(),style=getComputedStyle(element),center=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);const controls=[...element.querySelectorAll('button,select')].flatMap(control=>{const b=control.getBoundingClientRect(),css=getComputedStyle(control),clip=control.closest('[data-season-history-scroll]')?.getBoundingClientRect();if(!control.getClientRects().length||css.visibility==='hidden'||b.bottom<=0||b.y>=innerHeight||(clip&&(b.bottom<=clip.y||b.y>=clip.bottom)))return[];return[{clipped:b.y<0||b.bottom>innerHeight+1||!!clip&&(b.y<clip.y||b.bottom>clip.bottom),label:control.getAttribute('aria-label')||control.innerText,width:b.width,height:b.height,points:[[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]].map(([x,y])=>{const hit=document.elementFromPoint(b.x+b.width*x,b.y+b.height*y);return{painted:!!hit&&control.contains(hit)};})}];});last={x:r.x,y:r.y,width:r.width,height:r.height,viewport:[innerWidth,innerHeight],opacity:style.opacity,inside:r.width>0&&r.height>0&&r.x>=0&&r.right<=innerWidth+1&&r.y>=0&&r.bottom<=innerHeight+1,painted:!!center&&element.contains(center),finite:document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.getTiming().iterations!==Infinity).length,overflow:document.documentElement.scrollWidth>innerWidth+1,controls,required:requiredSelectors.map(selector=>{const node=element.querySelector(selector),target=node?.tagName==='SELECT'?node.closest('label'):node;if(!target)return{selector,inside:false,painted:false};const box=target.getBoundingClientRect(),clip=target.closest('[data-season-history-scroll]')?.getBoundingClientRect(),hit=document.elementFromPoint(box.x+box.width/2,box.y+box.height/2);return{selector,x:box.x,y:box.y,width:box.width,height:box.height,inside:box.width>0&&box.height>0&&box.x>=0&&box.right<=innerWidth+1&&box.y>=0&&box.bottom<=innerHeight+1&&(!clip||box.y>=clip.y&&box.bottom<=clip.bottom),painted:!!hit&&target.contains(hit)};})};const signature=JSON.stringify(last);stable=signature===previous?stable+1:1;previous=signature;if(stable>=4&&last.inside&&last.painted&&Number(last.opacity)===1&&last.finite===0&&!last.overflow&&controls.every(c=>c.points.every(p=>p.painted)))break;}return{...last,stable};},required);
      row.layouts.push({name,...layout});write(id+'-'+name+'-layout',layout);check(layoutFailures(layout).length===0,name+': four stable readable painted frames without overflow');check(layout.controls.length>0&&layout.controls.every(c=>c.width>=44&&c.height>=44),name+': every visible history control has a 44 pixel target');await page.screenshot({path:path.join(OUT,id+'-'+name+'.png')});return layout;
    };
    const loaded=async()=>{await page.getByRole('button',{name:'How to play',exact:true}).waitFor({timeout:45000});await page.locator('[data-open-season-ratings]').waitFor();await page.evaluate(()=>document.fonts.ready);};
    const reload=async name=>{const before=await bytes();await page.reload({waitUntil:'domcontentloaded'});await loaded();const after=await bytes();write(id+'-'+name+'-reload-bytes',{before,after});row.reloads.push({name,equal:before===after,beforeSha256:sha(before),afterSha256:sha(after),bytes:Buffer.byteLength(before)});check(before===after,name+': strict complete serialized reload equality');readDraws=await page.evaluate(()=>window.__seasonHistoryReadDraws);};
    try{
      await oracle.goto('about:blank');await oracle.addScriptTag({content:oracleBuild.outputFiles[0].text});const expectedLoad=await oracle.evaluate(input=>{const E=window.__seasonHistoryOracle,state=E.soccer.repairCareer(structuredClone(input));E.moments.settleLoadedMoments(state);return JSON.parse(JSON.stringify(state));},fixture);
      await page.goto(BASE+'/soccer-career',{waitUntil:'domcontentloaded'});await loaded();canonicalBytes=await bytes();canonical=JSON.parse(canonicalBytes);write(id+'-canonical-loader',{input:fixture,expected:expectedLoad,actual:canonical});check(JSON.stringify(canonical)===JSON.stringify(expectedLoad),'Independent unchanged Chromium loader matches every first-load field');readDraws=await page.evaluate(()=>window.__seasonHistoryReadDraws);await reload('canonical-second-load');
      const open=page.locator('[data-open-season-ratings]'),selector='[data-open-season-ratings]';await open.scrollIntoViewIfNeeded();await open.focus();const before=await body();const openerRect=await open.evaluate(element=>{const r=element.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return{width:r.width,height:r.height,inside:r.x>=0&&r.right<=innerWidth&&r.y>=0&&r.bottom<=innerHeight,painted:!!hit&&element.contains(hit)};});write(id+'-opener-rectangle',openerRect);check(openerRect.width>=44&&openerRect.height>=44&&openerRect.inside&&openerRect.painted,'Actual Ratings page opener is a fully painted 44 pixel target');await activate(open);
      const dialog=page.locator('[data-season-ratings="dialog"]'),scroll=dialog.locator('[data-season-history-scroll]');await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[data-season-ratings="dialog"]')?.contains(document.activeElement),undefined,{timeout:2000});check((await body()).computed==='hidden','Shared dialog locks body scroll');check(await dialog.locator('[data-season-ratings-row]').count()===rawHistory(canonical).length,'Existing Ratings still lists every saved senior row only');
      const mode=name=>dialog.locator('[data-season-history-mode="'+name+'"]'),help=dialog.locator('[data-season-history-help]');
      const helpRound=async expectedMode=>{const snapshot={top:await scroll.evaluate(element=>element.scrollTop),...await body()},first=await dialog.locator('[data-season-history-select="first"]').count()?await dialog.locator('[data-season-history-select="first"]').inputValue():null,second=await dialog.locator('[data-season-history-select="second"]').count()?await dialog.locator('[data-season-history-select="second"]').inputValue():null,available=await dialog.locator('[data-season-history-select="availability"]').count()?await dialog.locator('[data-season-history-select="availability"]').inputValue():null;await activate(help);await mode('help').waitFor();const text=await dialog.locator('[data-season-history-help-body]').innerText();check(/second season minus the first/.test(text)&&/not recorded/.test(text)&&/weeks/.test(text)&&/Example:/.test(text),'Reopenable help explains saved values and worked comparison/availability examples');await capture(dialog,expectedMode+'-rules');await activate(dialog.locator('[data-season-history-back="help"]'));await mode(expectedMode).waitFor();const restored={expected:snapshot,actual:{top:await scroll.evaluate(element=>element.scrollTop),...await body(),focus:await help.evaluate(element=>document.activeElement===element)}};row.restorations.push({name:expectedMode+'-help',...restored});check(restoreFailures(restored).length===0,expectedMode+': Help Back restores exact focus, scroll, body and page');if(first!==null)check(await dialog.locator('[data-season-history-select="first"]').inputValue()===first&&await dialog.locator('[data-season-history-select="second"]').inputValue()===second,'Help preserves both indexed comparison choices');if(available!==null)check(await dialog.locator('[data-season-history-select="availability"]').inputValue()===available,'Help preserves indexed availability choice');await unchanged(expectedMode+'-help');};
      await helpRound('ratings');
      const launcher=dialog.locator('[data-season-history-open="compare"]');await launcher.scrollIntoViewIfNeeded();check(await scroll.evaluate(element=>element.scrollHeight>element.clientHeight),'Saved long history naturally overflows Ratings at this viewport');const scrollBox=await scroll.boundingBox();await page.mouse.move(scrollBox.x+scrollBox.width/2,scrollBox.y+Math.min(48,scrollBox.height-1));await page.mouse.wheel(0,8);await page.waitForFunction(()=>document.querySelector('[data-season-history-scroll]')?.scrollTop>0,undefined,{timeout:2000});await launcher.scrollIntoViewIfNeeded();await launcher.focus();const ratingsTop=await scroll.evaluate(element=>element.scrollTop);const launcherVisible=await launcher.evaluate(element=>{const r=element.getBoundingClientRect(),clip=element.closest('[data-season-history-scroll]').getBoundingClientRect();return r.y>=clip.y&&r.bottom<=clip.bottom;});check(ratingsTop>0&&launcherVisible,'Real wheel input establishes a nonzero Ratings offset while Compare stays fully visible');await activate(launcher);await mode('compare').waitFor();
      check(await dialog.locator('[data-season-history-select="first"]').inputValue()==='28'&&await dialog.locator('[data-season-history-select="second"]').inputValue()==='29','Comparison opens with the actual latest two original indices');
      await dialog.locator('[data-season-history-select="first"]').selectOption(String(input.first));await dialog.locator('[data-season-history-select="second"]').selectOption(String(input.second));
      const expected=rawComparison(canonical,input.first,input.second),actual=await dialog.locator('[data-season-history-comparison]').evaluate(element=>({identities:['first','second'].map(side=>[...element.querySelector('[data-season-history-side="'+side+'"]').querySelectorAll('p')].map(p=>p.textContent)),metrics:[...element.querySelectorAll('[data-season-history-stat]')].map(row=>({key:row.getAttribute('data-season-history-stat'),label:row.querySelector('dt').textContent,...Object.fromEntries(['first','second','delta'].map(key=>[key,row.querySelector('[data-season-history-value="'+key+'"]').textContent]))}))}));
      observedValues={expected:{identities:[identity(expected.first),identity(expected.second)],metrics:expected.metrics.map(metric=>({key:metric.key,label:metric.label,first:format(metric.first,metric.digits),second:format(metric.second,metric.digits),delta:format(metric.delta,metric.digits,true)}))},actual};write(id+'-comparison-observation',observedValues);check(savedFailures(observedValues).length===0,'Same-year loan records and every position metric equal independent original-index raw-save values');
      const swap=dialog.locator('[data-season-history-swap]');await activate(swap);check(await dialog.locator('[data-season-history-select="first"]').inputValue()===String(input.second)&&await dialog.locator('[data-season-history-select="second"]').inputValue()===String(input.first),'Swap atomically reverses the two original saved indices');const swappedExpected=rawComparison(canonical,input.second,input.first),swappedActual=await dialog.locator('[data-season-history-stat]').evaluateAll(elements=>elements.map(element=>({key:element.getAttribute('data-season-history-stat'),first:element.querySelector('[data-season-history-value="first"]').textContent,second:element.querySelector('[data-season-history-value="second"]').textContent,delta:element.querySelector('[data-season-history-value="delta"]').textContent})));check(JSON.stringify(swappedActual)===JSON.stringify(swappedExpected.metrics.map(metric=>({key:metric.key,first:format(metric.first,metric.digits),second:format(metric.second,metric.digits),delta:format(metric.delta,metric.digits,true)}))),'Swap renders every reversed saved value and signed delta');await activate(swap);
      check(await dialog.locator('[data-season-history-select="first"] option[value="'+input.second+'"]').count()===0&&await dialog.locator('[data-season-history-select="second"] option[value="'+input.first+'"]').count()===0,'Selectors reject choosing the same original row twice');check(actual.metrics[0].first==='Not recorded'&&actual.metrics[0].delta==='Not recorded'&&actual.metrics[0].second!=='97','Older missing OVR never borrows current overall or becomes zero');row.selections.push({mode:'compare',first:input.first,second:input.second});observedLayout=await capture(dialog,'comparison-top');
      await dialog.locator('[data-season-history-stat]').last().scrollIntoViewIfNeeded();await helpRound('compare');await activate(dialog.locator('[data-season-history-back="ratings"]'));await mode('ratings').waitFor();check(await scroll.evaluate(element=>element.scrollTop)===ratingsTop&&await launcher.evaluate(element=>document.activeElement===element),'Compare Back restores the Ratings offset and exact launcher focus');
      const availabilityLauncher=dialog.locator('[data-season-history-open="availability"]');await availabilityLauncher.scrollIntoViewIfNeeded();await availabilityLauncher.focus();const availabilityRatingsTop=await scroll.evaluate(element=>element.scrollTop);check(availabilityRatingsTop===ratingsTop&&availabilityRatingsTop>0,'Availability launcher also starts at the reachable nonzero saved Ratings offset');await activate(availabilityLauncher);await mode('availability').waitFor();await dialog.locator('[data-season-history-select="availability"]').selectOption(String(input.availability));
      const expectedAvailability=expectedFields(rawHistory(canonical).find(value=>value.index===input.availability).availability),actualAvailability=await dialog.locator('[data-season-availability]').evaluate(element=>Object.fromEntries([...element.querySelectorAll('[data-season-availability-field]')].map(field=>[field.getAttribute('data-season-availability-field'),field.textContent])));write(id+'-availability-observation',{expected:expectedAvailability,actual:actualAvailability});check(JSON.stringify(actualAvailability)===JSON.stringify(expectedAvailability),'Zero-app injury weeks, severity and actual suspension matches remain separate saved facts');await capture(dialog,'availability-top');
      const summary=await dialog.locator('[data-season-availability-summary]').evaluateAll(elements=>elements.map(element=>({index:Number(element.getAttribute('data-season-availability-summary')),...Object.fromEntries([...element.querySelectorAll('[data-availability-summary-field]')].map(field=>[field.getAttribute('data-availability-summary-field'),field.textContent]))}))),summaryExpected=[...rawHistory(canonical)].reverse().map(value=>({index:value.index,year:year(value.year),club:value.club??'Club not recorded',injury:injury(value.availability),suspension:suspended(value.availability.suspensionMatches)}));write(id+'-availability-summary',{expected:summaryExpected,actual:summary});check(JSON.stringify(summary)===JSON.stringify(summaryExpected),'Whole-career Availability includes every indexed senior row latest first without guessing missing fields');await dialog.locator('[data-season-availability-summary]').last().scrollIntoViewIfNeeded();await capture(dialog,'availability-oldest');await helpRound('availability');
      await dialog.locator('[data-season-history-select="availability"]').selectOption(String(input.unknown));const unknown=await dialog.locator('[data-season-availability-field="suspension"]').innerText();check(unknown==='Not recorded','Older missing suspension count stays unknown');await dialog.locator('[data-season-history-select="availability"]').selectOption(String(input.suspended));check(await dialog.locator('[data-season-availability-field="reason"]').innerText()==='Banned','Recorded zero-app ban remains a saved status, not an injury inference');row.selections.push({mode:'availability',index:input.suspended});
      await activate(dialog.locator('[data-season-history-back="ratings"]'));await mode('ratings').waitFor();check(await scroll.evaluate(element=>element.scrollTop)===availabilityRatingsTop&&await availabilityLauncher.evaluate(element=>document.activeElement===element),'Availability Back restores the exact nonzero Ratings offset and its own launcher');
      check(!/Ballon d.or|award rank|winner/i.test(await dialog.innerText()),'Comparison and Availability reveal no pending award result');if(input.id==='pending-keeper')check(JSON.parse(await bytes()).pendingBallonDor.revealed===false,'Natural newspaper-phase pending ballot stays unrevealed while history is read');await unchanged('both-history-modes');
      for(const key of['Tab','Tab','Shift+Tab','Shift+Tab']){await page.keyboard.press(key);check(await dialog.evaluate(element=>element.contains(document.activeElement)),key+': shared dialog focus remains trapped');}
      const closeAndCheck=async(name,close)=>{await close();await dialog.waitFor({state:'hidden'});await page.waitForFunction(({selector,before})=>document.activeElement?.matches(selector)&&document.body.style.overflow===before.inline&&getComputedStyle(document.body).overflow===before.computed&&scrollY===before.y,{selector,before},{timeout:2000}).catch(()=>{});const observation={expected:{...before,top:0},actual:{...await body(),top:0,focus:await open.evaluate(element=>document.activeElement===element)}};row.restorations.push({name,...observation});write(id+'-'+name+'-restoration',observation);check(restoreFailures(observation).length===0,name+': exact opener, body and page restoration');await unchanged(name);return observation;};
      observedRestore=await closeAndCheck('close',()=>activate(dialog.locator('[data-season-history-close]')));
      await activate(open);await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[data-season-ratings="dialog"]')?.contains(document.activeElement),undefined,{timeout:2000});await closeAndCheck('escape',()=>page.keyboard.press('Escape'));await reload('completed-read-only');
      await activate(open);await dialog.waitFor();await activate(dialog.locator('[data-season-history-open="compare"]'));await dialog.locator('[data-season-history-select="first"]').selectOption(String(input.first));await dialog.locator('[data-season-history-select="second"]').selectOption(String(input.second));const reloadedIdentity={expected:identity(expected.second),actual:await dialog.locator('[data-season-history-side="second"] p').evaluateAll(elements=>elements.map(element=>element.textContent)),innerText:await dialog.locator('[data-season-history-side="second"]').innerText()};write(id+'-reloaded-identity-observation',reloadedIdentity);check(JSON.stringify(reloadedIdentity.actual)===JSON.stringify(reloadedIdentity.expected),'Reload keeps the same original saved loan record available');await closeAndCheck('reloaded-escape',()=>page.keyboard.press('Escape'));
      if(!report.controls.length){const beforeControls=await bytes();detector('wrong-value',observedValues,o=>{const old=o.actual.metrics[0].first;o.actual.metrics[0].first='97';return()=>{o.actual.metrics[0].first=old;};},savedFailures,['saved-values']);detector('paint',observedLayout,o=>{const old=o.opacity;o.opacity='0';return()=>{o.opacity=old;};},layoutFailures,['opacity']);detector('geometry',observedLayout,o=>{const old={inside:o.required[0].inside,clipped:o.controls[0].clipped,width:o.controls[0].width};o.required[0].inside=false;o.controls[0].clipped=true;o.controls[0].width=43;return()=>{o.required[0].inside=old.inside;o.controls[0].clipped=old.clipped;o.controls[0].width=old.width;};},layoutFailures,['clipped-controls','required-targets','touch-target']);detector('return',observedRestore,o=>{const old={...o.actual};o.actual.focus=false;o.actual.top++;o.actual.inline='incorrect';o.actual.computed='incorrect';o.actual.y++;return()=>{o.actual=old;};},restoreFailures,['focus','mode-position','inline-overflow','computed-overflow','page-position']);check(await bytes()===beforeControls,'Copied observation detectors do not alter the actual saved career');}
      check(row.errors.length===0&&row.assetErrors.length===0,'No page or owned asset errors');check(row.writes.every(write=>write.blocked)&&report.forwardedExternalRequests===0,'All external write attempts blocked with zero forwarding');row.ok=true;
    }catch(error){report.failed++;row.ok=false;row.error=String(error.stack||error);console.log('FAIL '+id+': '+row.error);await page.screenshot({path:path.join(OUT,id+'-failure.png')}).catch(()=>{});}
    finally{await context.close();await oracleContext.close();write(id+'-report',row);}
  }
  report.sourceAfter=sourceHashes();assert.deepEqual(report.sourceAfter,report.sourceBefore);report.fontManifestEntries=fonts.size;
}finally{await browser?.close();server.kill();write('report',report);}
console.log('Season history native: '+report.checks+' checks,'+report.failed+' failed,'+report.cases.filter(row=>row.ok).length+'/'+report.cases.length+' journeys,'+report.controls.length+' copied observation controls; artifacts '+OUT);
assert.equal(report.cases.length,9);assert.equal(report.controls.length,4);assert.equal(report.failed,0);assert(report.cases.every(row=>row.ok));
