/* Round 678: public.game_rules, generated from src/data/pointsFamilies.ts.

   docs/design/POINTS-ECONOMY-V2.md sections 5 (E3) and 9 (E3b). The table is
   (game, family, scale, pays, claim, round), one row per completion key, and
   it is never typed by hand: the family table in src is the one place a
   game's rule is written, the door (record_play) reads the table, and a
   second copy written beside the first would drift from it the way the caps
   table drifted from the scoring code for months.

   Round 691 applies the seed as step E3b the day before the release, and E3b
   refuses unless the seed's md5 equals what `node scripts/genGameRules.mjs
   --check` prints on the frozen release tree. scripts/simKnowledgeLine.mjs
   section 1 holds the committed file to a fresh generation on every run, and
   both hold every row of it to the family table itself through
   scripts/lib/gameRulesRows.mjs, which reads the SQL back without this file,
   so a bug here cannot check out against its own output.

   loadFamilies  bundles pointsFamilies.ts with esbuild and imports it; a
                 control hands in a plugin that serves a planted copy
   seedSql       the seed text, rows sorted by game; refuses a key in two
                 families and a rule the door would read wrong
   md5           the digest E3b compares, of the text with line endings
                 folded to LF */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';

export const FAMILIES_FILE = 'src/data/pointsFamilies.ts';
export const SEED_FILE = 'scripts/data/gameRulesSeed.sql';

const CLAIMS = new Set(['first-action', 'deal', 'week-one', 'finish']);
const SCALES = new Set(['dp', 'g']);

let loads = 0;

/** POINTS_FAMILIES as the source has it (or as a control's plugin plants it). */
export async function loadFamilies(root, tmpDir, plugins = []) {
  const { build } = createRequire(path.join(root, 'package.json'))('esbuild');
  const built = await build({
    stdin: { contents: `export { POINTS_FAMILIES } from '@/data/pointsFamilies';`, resolveDir: root, loader: 'ts' },
    bundle: true, write: false, format: 'esm', platform: 'node', logLevel: 'silent',
    alias: { '@': path.join(root, 'src') }, plugins,
  });
  loads += 1;
  const out = path.join(tmpDir, `pointsFamilies.${process.pid}.${loads}.mjs`);
  fs.writeFileSync(out, built.outputFiles[0].text);
  const { POINTS_FAMILIES } = await import(pathToFileURL(out).href);
  return POINTS_FAMILIES;
}

/** Every [key, family, rule] in the table, in file order, duplicates kept. */
export function familyRows(groups) {
  return groups.flatMap(g => Object.entries(g.games).map(([key, rule]) => [key, g.family, rule]));
}

const q = s => `'${String(s).replace(/'/g, "''")}'`;

/** The seed, or a thrown refusal naming every problem. */
export function seedSql(groups) {
  const rows = familyRows(groups);
  const problems = [];
  const seen = new Map();
  for (const [key, family, rule] of rows) {
    if (seen.has(key)) problems.push(`${key} is filed under both ${seen.get(key)} and ${family}`);
    else seen.set(key, family);
    if (!/^[a-z0-9-]{1,64}$/.test(key)) problems.push(`${key} is not a completion key the door accepts`);
    if (!CLAIMS.has(rule.claim)) problems.push(`${key}: claim ${rule.claim}`);
    if (!/^(\d+|none)$/.test(String(rule.round))) problems.push(`${key}: round ${rule.round}`);
    if (rule.pays === true && !SCALES.has(rule.scale)) problems.push(`${key} pays on no scale (${rule.scale})`);
    if (rule.pays === true && rule.round === 'none') problems.push(`${key} pays with no round behind it`);
    if (rule.pays === false && rule.scale !== null) problems.push(`${key} does not pay but carries scale ${rule.scale}`);
    if (rule.pays === false && !(typeof rule.forFun === 'string' && rule.forFun.trim())) problems.push(`${key} does not pay and gives no reason`);
    if (rule.pays !== true && rule.pays !== false) problems.push(`${key}: pays is ${rule.pays}`);
  }
  if (problems.length) throw new Error(`the family table cannot seed game_rules:\n  ${problems.join('\n  ')}`);
  const sorted = [...rows].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  const paying = sorted.filter(r => r[2].pays).length;
  const lines = sorted.map(([key, family, rule], i) =>
    `  (${q(key)}, ${q(family)}, ${rule.scale === null ? 'null' : q(rule.scale)}, ${rule.pays}, ${q(rule.claim)}, ${q(rule.round)})${i === sorted.length - 1 ? ';' : ','}`);
  return [
    '-- public.game_rules, generated by scripts/genGameRules.mjs from src/data/pointsFamilies.ts.',
    '-- Never edit by hand: change the family table and run the generator again.',
    `-- ${sorted.length} games, ${paying} paying, ${sorted.length - paying} not paying.`,
    'insert into public.game_rules (game, family, scale, pays, claim, round) values',
    ...lines,
    '',
  ].join('\n');
}

export const md5 = text => crypto.createHash('md5').update(text.replace(/\r\n/g, '\n')).digest('hex');
