/**
 * Round 1052: a league whose squads are gathered from committed receipts
 * (two hosts a player) rather than baked from the value table. This is
 * everything scripts/genClubManagerALeague.mjs (Round 1035) did between
 * reading its inputs and writing its file, lifted so a second and third
 * league are generated by the SAME rules and not a copy of them. Pure: no
 * file reads, no network, nothing evaluated at import.
 *
 *   buildGatheredLeague({ clubs, supersedes, bakedText, nowBlockText, options })
 *     -> { rosters, partial, noValue, positionThin, nationalities, stats, errors }
 *   renderGatheredFile({ prefix, header, docs, meta, rosters, partial,
 *                        noValue, positionThin?, supersedes, nationalities })
 *     -> the text of src/data/clubManager<League>.ts
 *
 * `clubs` is the caller's normalised input, one entry a club:
 *   { engine, sources?, rows: [{ name, group, tmPosition, valueEur, age,
 *     ageHosts, nationality, nationalityHosts, hosts?, foldedNamesake? }] }
 * A row with no group is skipped (and still counts toward the partial mark,
 * the Release AH rule). Every other problem FAILS CLOSED: it is returned in
 * `errors` and the caller writes nothing.
 *
 * `options` are the rules the leagues after the A-League add. The A-League
 * caller leaves them off, which is what keeps its file byte identical:
 *   receipts            the words an error uses for this league's receipts
 *   minMen              a club that ships fewer men is partial (the baked
 *                       world's own rule: fewer than 8 real players)
 *   freeAgentText       a shipped name in the free agent file fails closed
 *   otherGeneratedTexts a shipped name in another generated league's file
 *                       fails closed
 *   twoSquadSources     each club carries at least two squad lists on
 *                       different hosts, none of them a wiki, and every
 *                       row names at least two of its club's hosts
 *   foldedCheck         the name checks above are repeated under the
 *                       engine's own fold (accents and special letters
 *                       off, lower case): a folded hit that is not an exact
 *                       hit fails closed unless the row carries a
 *                       foldedNamesake verdict of 'namesake' naming it
 *   statedPosition      (Release AO) a man whose detailed position sits
 *                       outside the group two hosts agree on ships THAT
 *                       position, the one a host prints for him, and never
 *                       the group's default, which no host states; a man with
 *                       no detailed position the game knows still ships the
 *                       default. Both are returned in `positionThin` and
 *                       written as the POSITION_THIN export, as "name|club"
 */
import { POS_MAP, ratingOf, gbpM, usdOfEur, FLOOR_USD } from './cmValueCurve.mjs';

/** The ledger's group of each engine position, and each group's default. */
export const GROUP_OF = { GK: 'GK', CB: 'DEF', LB: 'DEF', RB: 'DEF', CDM: 'MID', CM: 'MID', CAM: 'MID', LM: 'MID', RM: 'MID', LW: 'FWD', RW: 'FWD', ST: 'FWD', CF: 'FWD' };
export const GROUP_DEFAULT = { GK: 'GK', DEF: 'CB', MID: 'CM', FWD: 'ST' };

/** Other hosts' nationality spellings -> Transfermarkt's, the house
 *  convention (the same table _people.json records). Round 1052 added
 *  ESPN's 'Cape Verde Islands'. */
export const NATIONALITY_ALIAS = {
  'Bosnia and Herzegovina': 'Bosnia-Herzegovina', 'Congo DR': 'DR Congo', 'Republic of Ireland': 'Ireland',
  'South Korea': 'Korea, South', 'Korea Republic': 'Korea, South', 'South Sudan': 'Southern Sudan', USA: 'United States',
  'Cape Verde Islands': 'Cape Verde',
};

/** The engine's own name fold (foldClubName in src/lib/clubManager.ts over
 *  src/lib/nameFold.ts), written out because a pure script cannot import
 *  the app. scripts/simClubManagerGathered.mjs holds the two equal. */
const SPECIALS = { 'ø': 'o', 'Ø': 'o', 'đ': 'd', 'Đ': 'd', 'ð': 'd', 'Ð': 'd', 'ł': 'l', 'Ł': 'l', 'æ': 'ae', 'Æ': 'ae', 'œ': 'oe', 'Œ': 'oe', 'ß': 'ss', 'þ': 'th', 'Þ': 'th', 'ħ': 'h', 'Ħ': 'h', 'ı': 'i', 'İ': 'i', 'ŋ': 'n', 'Ŋ': 'n' };
export function foldName(s) {
  return [...(s || '')].map(ch => SPECIALS[ch] ?? ch).join('')
    .normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

const unq = s => s.replace(/\\'/g, "'");
const WIKI = /(^|\.)(wikipedia|wikimedia|wikidata|fandom|wikia)\./i;

/** Every squad of a baked or generated roster file: name -> the clubs it is at. */
export function squadNamesOf(text) {
  const out = new Map();
  for (const b of text.matchAll(/^  '((?:[^'\\]|\\.)+)': \[\n([\s\S]*?)^  \],\n/gm)) {
    for (const m of b[2].matchAll(/\bn: '((?:[^'\\]|\\.)*)'/g)) {
      const n = unq(m[1]);
      if (!out.has(n)) out.set(n, []);
      out.get(n).push(unq(b[1]));
    }
  }
  return out;
}

/** The names of src/data/clubManagerFreeAgents2026.ts. */
export function freeAgentNamesOf(text) {
  return new Set([...text.matchAll(/\{ name: '((?:[^'\\]|\\.)*)', position:/g)].map(m => unq(m[1])));
}

/** The modern block of src/data/playerNationalities.ts as name -> nationality. */
export function nowBlockOf(natText) {
  /* Round 1042: the past worlds left this file for src/data/nationalities/, so the modern block
     ends on its own closing line, the first one after it starts, not where the next world began. */
  const nowStart = natText.indexOf('\nnow: {');
  const nowEnd = natText.indexOf('\n},', nowStart);
  if (nowStart < 0 || nowEnd < 0) return null;
  return natText.slice(nowStart, nowEnd);
}

export function buildGatheredLeague({ clubs, supersedes = {}, bakedText, nowBlockText, options = {} }) {
  const receipts = options.receipts ?? 'the A-League receipts';
  const errors = [];
  const rosters = {};
  const partial = [];
  const noValue = [];
  const positionThin = [];
  const nationalities = {};
  let groupWon = 0;
  let skipped = 0;
  for (const club of clubs) {
    const engine = club.engine;
    const list = [];
    if (options.twoSquadSources) {
      const hosts = [...new Set((club.sources ?? []).map(s => s.host))];
      if (hosts.length < 2) errors.push(`${engine}: fewer than two squad lists on different hosts`);
      for (const s of club.sources ?? []) if (WIKI.test(s.host) || WIKI.test(new URL(s.url).host)) errors.push(`${engine}: a squad list is on a wiki host (${s.host})`);
      for (const row of club.rows) {
        const named = [...new Set(row.hosts ?? [])].filter(h => hosts.includes(h));
        if (named.length < 2) errors.push(`${row.name} (${engine}): on ${named.length} of his club's squad lists, two are needed`);
      }
    }
    for (const row of club.rows) {
      if (!row.group) { skipped += 1; continue; }
      if (!GROUP_DEFAULT[row.group]) { errors.push(`${row.name}: unknown group ${row.group}`); continue; }
      if (!Number.isInteger(row.age) || row.age < 14 || row.age > 45) { errors.push(`${row.name}: age ${row.age} is not two sourced or not plausible`); continue; }
      if ((row.ageHosts ?? []).length < 2) { errors.push(`${row.name}: age on ${(row.ageHosts ?? []).length} host(s)`); continue; }
      let p = POS_MAP[row.tmPosition];
      if (!p || GROUP_OF[p] !== row.group) {
        /* Release AO: the Russian file shipped two wide men as CB and eight
           wingers as CM this way, a detailed position none of their three
           hosts states. With statedPosition on, the position a host prints
           ships and the row is marked; the default is left for the man no
           host gives a detailed position, and he is marked too. */
        if (options.statedPosition) positionThin.push(`${row.name}|${engine}`);
        if (!p || !options.statedPosition) { p = GROUP_DEFAULT[row.group]; groupWon += 1; }
      }
      let usd;
      if (Number.isFinite(row.valueEur) && row.valueEur > 0) usd = usdOfEur(row.valueEur);
      else { usd = FLOOR_USD; noValue.push(`${row.name}|${engine}`); }
      list.push({ n: row.name, p, a: row.age, v: gbpM(usd, 2), r: ratingOf(usd) });
      if (row.nationality) {
        if ((row.nationalityHosts ?? []).length < 2) errors.push(`${row.name}: nationality on one host`);
        else if (nationalities[row.name] && nationalities[row.name] !== row.nationality) errors.push(`${row.name}: two nationalities for one name`);
        else nationalities[row.name] = row.nationality;
      }
    }
    list.sort((a, b) => b.v - a.v || a.n.localeCompare(b.n));
    rosters[engine] = list;
    /* Release AH (Round 1035 review F10): the partial mark counts the club's
       LEDGER rows, the group-less rows held back included, so a club whose
       page has no value for most of its squad is marked even when the rows
       that ship fall just under half. */
    const ledgerNoValue = club.rows.filter(row => !(row.valueEur > 0)).length;
    if (ledgerNoValue * 2 > club.rows.length || (options.minMen && list.length < options.minMen)) partial.push(engine);
  }

  /* One name, one man: a name in two squads of the league would merge two
     players wherever the engine keys on the name. */
  const seen = new Map();
  for (const [club, list] of Object.entries(rosters)) {
    for (const p of list) {
      if (seen.has(p.n)) errors.push(`${p.n} is in two squads (${seen.get(p.n)}, ${club})`);
      seen.set(p.n, club);
    }
  }

  /* The baked world must not carry these men too. A name already in
     src/data/clubManagerRosters.ts is either the same man on a stale row
     there (the value table's snapshot is older than these ledgers) or a
     namesake, and only a person can tell which. So every such name must be
     listed in the caller's supersedes table with the proof, or the run
     fails. A listed man is dropped from that baked club where the files are
     joined (src/data/clubManagerWorldRosters.ts). */
  const bakedClubOf = squadNamesOf(bakedText);
  for (const n of seen.keys()) {
    const at = bakedClubOf.get(n);
    if (!at) continue;
    if (supersedes[n] === undefined) errors.push(`${n} is also in the baked ${at.join(', ')} squad: list him in SUPERSEDES with the proof he is the same man, or prove a namesake`);
    else if (at.length !== 1 || at[0] !== supersedes[n]) errors.push(`${n}: SUPERSEDES names ${supersedes[n]} but the baked file has him at ${at.join(', ')}`);
  }
  for (const n of Object.keys(supersedes)) if (!seen.has(n) || !bakedClubOf.has(n)) errors.push(`SUPERSEDES lists ${n}, who is no longer in both files: remove the line`);

  /* nationalityOf reads the modern map first, so a man whose name is
     already there must carry the same nationality, or the flag would be the
     other entry's. */
  for (const m of nowBlockText.matchAll(/^  '((?:[^'\\]|\\.)*)': '((?:[^'\\]|\\.)*)',$/gm)) {
    const n = unq(m[1]);
    const nat = unq(m[2]);
    if (seen.has(n) && nationalities[n] !== nat) errors.push(`${n}: the modern nationality map says ${nat}, ${receipts} say ${nationalities[n] ?? 'unknown'}`);
  }

  /* Round 1052: the rules the later leagues add. */
  const elsewhere = [];
  if (options.freeAgentText) for (const n of freeAgentNamesOf(options.freeAgentText)) elsewhere.push({ n, where: 'the free agent pool' });
  for (const other of options.otherGeneratedTexts ?? []) for (const [n, at] of squadNamesOf(other.text)) elsewhere.push({ n, where: `${other.label} (${at.join(', ')})` });
  for (const e of elsewhere) if (seen.has(e.n)) errors.push(`${e.n} (${seen.get(e.n)}) is also in ${e.where}`);
  if (options.foldedCheck) {
    const folded = new Map();
    const add = (n, where) => { const f = foldName(n); if (!folded.has(f)) folded.set(f, []); folded.get(f).push({ n, where }); };
    for (const [n, at] of bakedClubOf) add(n, `the baked ${at.join(', ')} squad`);
    for (const e of elsewhere) add(e.n, e.where);
    const verdictOf = new Map();
    for (const club of clubs) for (const row of club.rows) if (row.foldedNamesake?.verdict === 'namesake') verdictOf.set(row.name, row.foldedNamesake.of);
    const own = new Map();
    for (const [n, club] of seen) {
      const f = foldName(n);
      for (const hit of folded.get(f) ?? []) {
        if (hit.n === n) continue;
        if (verdictOf.get(n) !== hit.n) errors.push(`${n} (${club}) folds to the same name as "${hit.n}" in ${hit.where}: the research row must say same man (then he is left out) or namesake`);
      }
      if (own.has(f) && own.get(f).n !== n) errors.push(`${n} (${club}) folds to the same name as "${own.get(f).n}" (${own.get(f).club}) inside the league`);
      own.set(f, { n, club });
    }
  }

  const total = Object.values(rosters).reduce((s, l) => s + l.length, 0);
  return { rosters, partial, noValue, positionThin, nationalities, stats: { total, groupWon, skipped }, errors };
}

const esc = s => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

/** The file text. `header` is the leading comment and `docs` the four doc
 *  comments, word for word from the caller; `meta` is written key by key in
 *  the caller's order (a string quoted, a number bare). */
export function renderGatheredFile({ prefix, header, docs, meta, rosters, partial, noValue, positionThin, supersedes, nationalities }) {
  const clubs = Object.keys(rosters).sort();
  const metaLines = Object.entries(meta).map(([k, v]) => `  ${k}: ${typeof v === 'number' ? v : `'${esc(String(v))}'`},`).join('\n');
  /* Written only for a caller that passes the list, so the A-League file, whose caller does not, stays byte identical. */
  const thinBlock = positionThin === undefined ? '' : `${docs.positionThin}
export const CM_${prefix}_POSITION_THIN: string[] = [
${positionThin.map(s => `  '${esc(s)}',`).join('\n')}
];

`;
  let out = `${header}
import type { BakedPlayer } from '@/data/clubManagerRosters';

export const CM_${prefix}_META = {
${metaLines}
};

${docs.partial}
export const CM_${prefix}_PARTIAL: string[] = ${JSON.stringify([...partial].sort())};

${docs.noValue}
export const CM_${prefix}_NO_VALUE: string[] = [
${noValue.map(s => `  '${esc(s)}',`).join('\n')}
];

${thinBlock}${docs.supersedes}
export const CM_${prefix}_SUPERSEDES: Record<string, string> = ${JSON.stringify(supersedes)};

export const CM_${prefix}_ROSTERS: Record<string, BakedPlayer[]> = {
`;
  for (const club of clubs) {
    out += `  '${esc(club)}': [\n`;
    for (const p of rosters[club]) out += `    { n: '${esc(p.n)}', p: '${p.p}', a: ${p.a}, v: ${p.v}, r: ${p.r} },\n`;
    out += `  ],\n`;
  }
  out += `};

${docs.nationalities}
export const CM_${prefix}_NATIONALITIES: Record<string, string> = {
${Object.keys(nationalities).sort().map(n => `  '${esc(n)}': '${esc(nationalities[n])}',`).join('\n')}
};
`;
  return out;
}
