/**
 * Derive the career identities Active Players Only may use from the three
 * committed 2026 evidence sources. World Cup and stale-sweep evidence has a
 * nationality. The transfer overlay does not, so an overlay name is usable
 * only when it is unique in both the overlay and the career identity pool.
 */

const unquoteSql = value => value.replace(/''/g, "'");

export function parseWorldCupIdentities(sql) {
  const rows = [];
  for (const match of String(sql).replaceAll('\r\n', '\n').matchAll(/^\('((?:[^']|'')*)','((?:[^']|'')*)',/gm)) {
    rows.push({ name: unquoteSql(match[1]), nationality: unquoteSql(match[2]) });
  }
  return rows;
}

function counts(values) {
  const out = new Map();
  for (const value of values) out.set(value, (out.get(value) ?? 0) + 1);
  return out;
}

export function deriveVerifiedActiveIdentities({ careerPlayers, careerNameUniverse = careerPlayers, worldCupRows, staleRows, overlayRows, identityKey }) {
  const nameKey = name => identityKey(name, '').split('|')[0];
  const careerNameCounts = counts(careerNameUniverse.map(player => nameKey(player.name)));
  const candidateNameCounts = counts(careerPlayers.map(player => nameKey(player.name)));
  const overlayNameCounts = counts(overlayRows.map(player => nameKey(player.name)));
  const direct = new Map();
  const directByName = new Map();

  for (const [source, rows] of [['world-cup', worldCupRows], ['stale-sweep', staleRows]]) {
    for (const player of rows) {
      if (!player?.name || !player?.nationality) continue;
      const key = identityKey(player.name, player.nationality);
      const sources = direct.get(key) ?? new Set();
      sources.add(source);
      direct.set(key, sources);
      const namesakes = directByName.get(nameKey(player.name)) ?? new Set();
      namesakes.add(key);
      directByName.set(nameKey(player.name), namesakes);
    }
  }

  const identities = [];
  for (const player of careerPlayers) {
    if (!player?.name || !player?.nationality) continue;
    const key = identityKey(player.name, player.nationality);
    const name = nameKey(player.name);
    if (careerNameCounts.get(name) !== 1 || candidateNameCounts.get(name) !== 1) continue;
    const directSources = directByName.get(name)?.size === 1 ? direct.get(key) : undefined;
    const uniqueOverlay = overlayNameCounts.get(name) === 1
      && careerNameCounts.get(name) === 1
      && !directByName.has(name);
    if (!directSources && !uniqueOverlay) continue;
    identities.push({
      key,
      name: player.name,
      nationality: player.nationality,
      sources: [...(directSources ?? []), ...(uniqueOverlay ? ['transfer-overlay'] : [])].sort(),
    });
  }

  identities.sort((a, b) => a.key.localeCompare(b.key));
  return identities;
}

export function verifiedActiveModule(identities) {
  const rows = identities.map(identity => `  '${identity.key.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`).join('\n');
  return `/**
 * Verified 2026 active identities for Transfer Path.
 *
 * Generated by scripts/genTransferPathHints.mjs from three committed,
 * two-source evidence sets: the 2026 World Cup squads, the verified 2026
 * transfer overlay, and the 2026 stale-player sweep. Eligibility is keyed by
 * normalized name plus nationality. Do not add a raw name or infer a season.
 */
export const VERIFIED_ACTIVE_IDENTITY_KEYS = [
${rows}
] as const;

export const VERIFIED_ACTIVE_IDENTITIES = new Set<string>(VERIFIED_ACTIVE_IDENTITY_KEYS);
`;
}
