/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART_COUNT = 32;

/** Which part holds a path's entry: FNV-1a over the path, modulo the count. */
export const seoMetaPart = (path: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < path.length; i += 1) {
    h ^= path.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0) % SEO_META_PART_COUNT;
};

export interface SeoMetaPartModule {
  SEO_META_PART: Record<string, SeoMeta>;
}

/** One loader per part, so each part is its own chunk and a page fetches one. */
export const SEO_META_PARTS: ReadonlyArray<() => Promise<SeoMetaPartModule>> = [
  () => import('./seoMetaPart00'),
  () => import('./seoMetaPart01'),
  () => import('./seoMetaPart02'),
  () => import('./seoMetaPart03'),
  () => import('./seoMetaPart04'),
  () => import('./seoMetaPart05'),
  () => import('./seoMetaPart06'),
  () => import('./seoMetaPart07'),
  () => import('./seoMetaPart08'),
  () => import('./seoMetaPart09'),
  () => import('./seoMetaPart10'),
  () => import('./seoMetaPart11'),
  () => import('./seoMetaPart12'),
  () => import('./seoMetaPart13'),
  () => import('./seoMetaPart14'),
  () => import('./seoMetaPart15'),
  () => import('./seoMetaPart16'),
  () => import('./seoMetaPart17'),
  () => import('./seoMetaPart18'),
  () => import('./seoMetaPart19'),
  () => import('./seoMetaPart20'),
  () => import('./seoMetaPart21'),
  () => import('./seoMetaPart22'),
  () => import('./seoMetaPart23'),
  () => import('./seoMetaPart24'),
  () => import('./seoMetaPart25'),
  () => import('./seoMetaPart26'),
  () => import('./seoMetaPart27'),
  () => import('./seoMetaPart28'),
  () => import('./seoMetaPart29'),
  () => import('./seoMetaPart30'),
  () => import('./seoMetaPart31'),
];
