/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 20 of 32: 2 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/career": {
    title: "Career Quiz: Guess the Soccer Player by Clubs",
    description: "A footballer's whole career sits there season by season with the boxes covered. Reveal as few clubs and stats as you can and name him. Free soccer quiz.",
  },
  "/list-quiz": {
    title: "Name Them All: Sports Champions List Quiz",
    description: "Pick a list and empty your brain: Super Bowl MVPs, F1 world champions, Masters winners and more, all real history. Free sports list quizzes, no sign up.",
  },
};
