/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 28 of 32: 5 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/wonderkid-factory": {
    title: "Wonderkid Factory: Idle Soccer Academy Game",
    description: "Scout generated kids, coach them toward hidden ceilings and sell each one at the perfect moment. A free idle football academy game with no real players.",
  },
  "/front-office": {
    title: "NFL Front Office: Football GM Simulator",
    description: "Take over any of the 32 teams with real rosters and run it all: the cap, free agency, trades and the draft. Chase a dynasty in this free NFL GM sim.",
  },
  "/mlb-front-office": {
    title: "MLB Front Office: Baseball GM Simulator",
    description: "Run a real MLB franchise: payroll under the tax line, trades the AI weighs, a 162 game season and October, drafts and dynasties. A free baseball GM sim.",
  },
  "/perfect-season-nhl": {
    title: "82-0 NHL Perfect Season: Hockey Draft Sim",
    description: "Every spin lands on a real NHL franchise and decade. Fill six slots from a century of hockey, then the sim plays 82 games. Can you go unbeaten? Free.",
  },
  "/f1-driver": {
    title: "Guess The F1 Driver: Formula 1 Trivia Game",
    description: "A mystery Formula 1 great hides behind six clues: race wins, titles, teams, nationality and a famous moment. Solve it early to score big. Free daily F1 quiz.",
  },
};
