/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 13 of 32: 2 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/cfb-higher-lower": {
    title: "CFB Higher or Lower: College Football QB Quiz",
    description: "Two quarterbacks, one question: who threw for more passing yards in college? Not the pros, college. Free daily college football trivia game.",
  },
  "/champ-or-not": {
    title: "Champ or Not: True or False Sports Champions",
    description: "Ten claims about champions across the NFL, NBA, MLB, NHL, college, soccer and footy. True or false, ten seconds each. Spot the fakes. Free daily sports quiz.",
  },
};
