/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 4 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/alphabet-sprint": {
    title: "Alphabet Sprint: Timed Soccer Player Name Quiz",
    description: "A letter drops and you name a footballer whose surname starts with it before the clock runs out. Streak bonuses, no repeats. Free soccer trivia against time.",
  },
  "/soccer-grid": {
    title: "Soccer Grid: Daily Football Player Grid Puzzle",
    description: "Fill the daily 3x3 board with players who match both the row and the column. Rarity scores reward picks nobody else made. Free soccer trivia grid game.",
  },
  "/ball-iq": {
    title: "Ball Knowledge IQ: Sports Trivia IQ Test",
    description: "Twelve sports questions ramping from layups to deep cuts, with the hard ones worth the most. Get your Ball Knowledge IQ and settle it. Free daily quiz.",
  },
  "/emoji-guess": {
    title: "Emoji Guess: Soccer Emoji Riddle Quiz",
    description: "Five football riddles a day told entirely in emoji: players, clubs, managers and iconic moments. Three guesses each and a hint after a miss. Free soccer quiz.",
  },
};
