/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 6 of 32: 5 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nfl-higher-lower": {
    title: "NFL Higher or Lower: Football Stats Game",
    description: "Two NFL stars, one career stat. Pick who has the bigger number across touchdowns, receptions, rushing yards and more. Free daily football trivia.",
  },
  "/college-grid": {
    title: "College Grid: Daily College Football Trivia",
    description: "A daily 3x3 college football grid. Name a player who fits the school and the column, from positions to Heisman winners and draft picks. Free CFB trivia.",
  },
  "/cbb-grid": {
    title: "College Basketball Grid: Daily CBB Trivia",
    description: "Fill the 3x3 college basketball grid with players who match the school and the career achievement. New board daily plus unlimited mode. Free CBB trivia.",
  },
  "/cfb-dynasty": {
    title: "CFB Dynasty: College Football Program Sim",
    description: "Run a real college football program: NIL recruiting, the transfer portal, conference title races and the 12 team Playoff, across unlimited seasons. Free.",
  },
  "/mlb-grid": {
    title: "MLB Franchise Grid: Daily Baseball Trivia",
    description: "Nine cells, nine legends. Fill the 3x3 MLB grid with players whose careers match both the row and the column. Daily board plus unlimited. Free baseball.",
  },
};
