/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 24 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nfl-connect-4": {
    title: "NFL Connect 4: Football Trivia Grid Game",
    description: "Four in a row, but every piece costs an NFL answer. Name a player who matches the column and the row where it lands to claim the cell. Free football trivia.",
  },
  "/missing-eleven": {
    title: "Missing Eleven: Super Bowl Lineup NFL Quiz",
    description: "A real Super Bowl starting lineup, offense or defense, with one name blanked out. Three guesses to name who started. Free daily NFL football quiz.",
  },
  "/buzzer-beater": {
    title: "Buzzer Beater: Basketball Jump Shot Game",
    description: "Set the arc, fade off the closeout and time the strength bar over ten jump shots, backing up each time. Daily and unlimited. A free basketball shooting game.",
  },
  "/hockey-career": {
    title: "NHL Career Path: Guess the Hockey Player",
    description: "One mystery hockey player and a stack of clues on country, draft, teams, stats and awards. Swing early for the full score. Free daily NHL trivia game.",
  },
};
