/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 0 of 32: 3 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nfl-my-career": {
    title: "NFL My Career: Football Career Simulator",
    description: "Create a prospect, get drafted by a real NFL team and live a whole career of stat lines, contracts, injuries and rings. Free pro football life sim.",
  },
  "/conquest-mlb": {
    title: "MLB Conquest: Baseball Imperialism Map Game",
    description: "Every territory starts with its nearest MLB park, and every winner annexes the loser's whole empire. Two clubs start with nothing. Free baseball map game.",
  },
  "/aussie-rules-manager": {
    title: "Aussie Rules Manager: Free Footy Season Game",
    description: "Run a fictional Aussie rules club through 23 rounds, the finals and the draft. Pick your 23, call the quarters, chase a flag. Free footy manager.",
  },
};
