/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 29 of 32: 6 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/contract-chaos": {
    title: "Contract Chaos: Soccer Agent Contract Game",
    description: "Be the agent for a generated footballer. Compare wages, role, bonuses and release clauses, sign one deal and watch five seasons play out. Free soccer game.",
  },
  "/football-connect-4": {
    title: "Soccer Connect 4: Football Trivia Grid Game",
    description: "Classic four in a row where every disc costs a soccer answer. Name a player who fits the column and the row to claim the cell. Free two player trivia game.",
  },
  "/missing-five": {
    title: "Missing Five: NBA Finals Starting Lineup Quiz",
    description: "A real starting five from a famous NBA Finals night with one name blanked out. Can you remember who actually started? Free daily basketball quiz.",
  },
  "/missing-nine": {
    title: "Missing Nine: World Series Lineup MLB Quiz",
    description: "A real World Series starting nine in batting order with one name blanked out. Can you remember who actually started? Free daily baseball quiz.",
  },
  "/fight-promoter": {
    title: "Fight Promoter: MMA and Boxing Management Sim",
    description: "Run a free MMA or boxing promotion. Sign fictional fighters, book cards, crown division champions and manage ticket prices, contracts and event costs.",
  },
  "/silverware-sort": {
    title: "Silverware Sort: Sports Titles Ranking Quiz",
    description: "Five teams from one competition, one question: who has more titles? Stack them in order across the NFL, NBA, MLB, NHL, college and soccer. Free sports quiz.",
  },
};
