/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 16 of 32: 3 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/stadium-tycoon": {
    title: "Stadium Tycoon: Free Idle Soccer Club Game",
    description: "Grow a tiny football club into an empire with live toy matches, ten divisions and a staff payroll. It keeps earning while you are away. Free idle soccer game.",
  },
  "/nba-gauntlet-draft": {
    title: "Gauntlet Draft: NBA Starting Five Draft Game",
    description: "Draft an NBA starting five one slot at a time from five real players, then survive a five round knockout cup. Free daily basketball draft game.",
  },
  "/nhl-connections": {
    title: "NHL Connections: Hockey Grouping Puzzle",
    description: "Twenty NHL players, four hidden groups of five sharing a franchise or a career milestone. Find all four on four lives. Free daily hockey puzzle.",
  },
};
