/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 7 of 32: 2 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/clue-auction": {
    title: "Clue Auction: Mystery Soccer Player Game",
    description: "A secret footballer, a bank of 100 points and clues for sale. Buy what you need, guess when you dare and keep whatever is left. Free soccer guessing game.",
  },
  "/nba-connect-4": {
    title: "NBA Connect 4: Basketball Trivia Grid Game",
    description: "The classic 7 by 6 board, but every cell costs an NBA answer. Name a player who fits the row and the column to drop your piece. Free basketball trivia.",
  },
};
