/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 3 of 32: 3 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nba-my-career": {
    title: "NBA My Career: Basketball Career Simulator",
    description: "Create a prospect, land on a real NBA team and live a whole career: stat lines, contracts, trade demands, rings and a legacy verdict. Free basketball sim.",
  },
  "/conquest-nhl": {
    title: "NHL Conquest: Hockey Imperialism Map Game",
    description: "Every patch of the map starts loyal to its nearest NHL arena. Win and you annex the loser's whole empire, and five clubs start with nothing. Free hockey game.",
  },
  "/tennis-higher-lower": {
    title: "Tennis Higher or Lower: Grand Slam Titles Quiz",
    description: "Who won more Grand Slam singles titles? Ten rounds of legends from both tours in one pool, from the 1920s to today. Free daily tennis trivia game.",
  },
};
