/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 9 of 32: 9 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/sign-the-player": {
    title: "Sign the Player: Soccer Transfer Auction Game",
    description: "Outbid two AI moguls with a billion pounds each for real footballers, fill your XI, then let a simulated mini league settle it. Free soccer auction game.",
  },
  "/footle": {
    title: "Footle: Daily Soccer Player Guessing Game",
    description: "Guess the mystery soccer player in eight tries. Colored tiles and arrows compare every guess on club, age, number and more. Free daily football puzzle.",
  },
  "/higher-lower": {
    title: "Soccer Higher or Lower: Career Stats Game",
    description: "Your player's stats are face up and the challenger's are hidden. Pick appearances, goals or caps where yours wins and keep the streak going. Free soccer game.",
  },
  "/nfl-gauntlet-draft": {
    title: "Gauntlet Draft: NFL Offense Draft Challenge",
    description: "Draft a seven man NFL offense, one slot at a time from five real players, then survive a five round knockout cup. Free daily football draft game.",
  },
  "/nba-connections": {
    title: "NBA Connections: Basketball Grouping Puzzle",
    description: "Twenty NBA players hide four groups of five tied by a franchise, a milestone, a birth country or a draft slot. Find them all. Free daily basketball puzzle.",
  },
  "/mlb-higher-lower": {
    title: "MLB Higher or Lower: Home Run Baseball Quiz",
    description: "Two legends side by side: who hit more career home runs? Finished careers only, Ruth through Ortiz, so every number is final. Free daily MLB baseball quiz.",
  },
  "/nhl-front-office": {
    title: "NHL Front Office: Hockey GM Simulator",
    description: "Run a real NHL franchise: a hard cap, waivers, trades the AI weighs, a points race and four best of seven rounds to the Cup. Free hockey GM sim game.",
  },
  "/afl-higher-lower": {
    title: "AFL Higher or Lower: Aussie Rules Goals Quiz",
    description: "Two VFL and AFL greats side by side: who kicked more career goals? Sixty retired legends, so no total ever moves. Free daily Aussie rules footy trivia.",
  },
  "/rank-em": {
    title: "Rank 'Em: Sports Stats Ranking Quiz",
    description: "One career stat, five greats, one shot at the right order, most to fewest. A new daily ranking across the NBA, NHL and MLB plus unlimited. Free sports quiz.",
  },
};
