/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 25 of 32: 5 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/soccer-perfect-season": {
    title: "Soccer Perfect Season: Draft Your XI",
    description: "Draft a fictional soccer XI with 55 tokens, then simulate 38 matches. Play free Daily or Unlimited and see if your choices can win them all.",
  },
  "/rebuild": {
    title: "Rebuild Challenge: Soccer Club Management Game",
    description: "Take over a real club, spin the wheel for each shirt, keep the player or sell him and answer to the board. Free soccer rebuild game for up to four players.",
  },
  "/search-and-discard": {
    title: "Search and Discard: Soccer Squad Duel Game",
    description: "Two managers share one pool of real footballers. Search three, keep one, bin the rest for good, then a simulated season settles it. Free soccer duel vs CPU.",
  },
  "/mlb-my-career": {
    title: "MLB My Career: Baseball Career Simulator",
    description: "Create a prospect, join a real MLB team and live a full career of stat lines, contracts, injuries and rings, then see if Cooperstown calls. Free baseball sim.",
  },
  "/perfect-lineup-f1": {
    title: "Perfect Lineup: F1 Dream Driver Squad Game",
    description: "Fill five F1 driver seats where three come with a team, era or country rule, then simulate a season and share your result. Free Formula 1 puzzle game.",
  },
};
