/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 2 of 32: 3 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/missing-xi": {
    title: "Missing XI: Guess the Missing Soccer Player",
    description: "A famous real starting lineup with one player blanked out. Name the missing man in three guesses. Free daily soccer puzzle plus an unlimited archive.",
  },
  "/ufc": {
    title: "UFC Guesser: Guess the MMA Fighter Game",
    description: "Eight guesses to name a mystery UFC fighter. Every guess lights up green, yellow or red with arrows on each stat. Deduction, not luck. Free MMA trivia game.",
  },
  "/quiz-board": {
    title: "Sports Quiz Board: Daily Sports Trivia Game",
    description: "Five categories, five money rows, twenty five clues. Pick a value, answer the clue, and a wrong answer costs you the full amount. Free daily sports trivia.",
  },
};
