/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 17 of 32: 8 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/budget-builder": {
    title: "$1B Budget Builder: Soccer Squad Building Game",
    description: "You get $1 billion and real market values. Pick a formation, sign eleven soccer players and see what rating your money actually bought. Free, no sign up.",
  },
  "/dart-draft": {
    title: "Dart Draft: Throw Darts, Draft a Soccer XI",
    description: "Call a position, throw a timed dart at a real world map and draft a real footballer from the country you hit. Eleven throws build your XI. Free soccer game.",
  },
  "/who-am-i": {
    title: "Who Am I? Guess the Secret Soccer Player Game",
    description: "Name any footballer and get a similarity score from 0 to 100 against the secret player, with clues on club, nation, position, age and value. Free soccer game.",
  },
  "/player-bingo": {
    title: "Player Bingo: Soccer Player Trivia Bingo",
    description: "Real footballers appear one at a time, name only. Tap the square each one fits and complete a line on the 5x5 board before three strikes. Free football bingo.",
  },
  "/free-kick": {
    title: "Free Kick: Bend It Past the Wall Soccer Game",
    description: "Aim, bend and time your power over ten free kicks, past a growing wall and a keeper who reads you. Daily and unlimited. A free soccer skill game to play.",
  },
  "/squad-deal": {
    title: "Squad Deal: Blind Box Soccer Squad Builder",
    description: "Every position is a wall of mystery boxes. Claim one blind, dodge the banker's offers, then simulate your soccer squad and see the grade. Free team builder.",
  },
  "/nba-chain": {
    title: "NBA Chain: Basketball Teammate Chain Game",
    description: "Start from one NBA star, name a teammate, then a teammate of his, and keep the chain going. One wrong link ends the run. Free basketball trivia game.",
  },
  "/score-predictor": {
    title: "Score Predictor: Famous Sports Scores Quiz",
    description: "Call the exact final score of a famous match from the teams, the competition, the date and a hint. Soccer, NFL and NBA classics. Free sports trivia game.",
  },
};
