/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 30 of 32: 8 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/world-cup-bracket": {
    title: "World Cup 2026 Bracket: Soccer Predictor Game",
    description: "Build your 2026 World Cup bracket, every group and knockout round plus the awards, then score it against how the tournament really went. Free soccer game.",
  },
  "/soccer-career": {
    title: "Soccer Career: Free Football Career Simulator",
    description: "Start at 16 in a youth academy and live a whole soccer career: transfers, trophies, feuds, scandals and a legacy verdict. A free football life sim game.",
  },
  "/football-grid": {
    title: "NFL Grid: Daily Pro Football Trivia Grid",
    description: "Name a player for each cell of the daily 3x3 NFL grid who fits both the row and the column. Rarity scores reward deep cuts. Free football trivia.",
  },
  "/nfl-connections": {
    title: "NFL Connections: Football Grouping Puzzle",
    description: "Twenty NFL players hide four groups of five: a franchise, a college, a draft slot or a milestone. Find them before you run out. Free daily football puzzle.",
  },
  "/nhl-connect-4": {
    title: "NHL Connect 4: Hockey Trivia Grid Game",
    description: "Four in a row, hockey style. Pick a column and name a real NHL player who fits the row where your piece lands to claim it. Free pass and play trivia.",
  },
  "/perfect-lineup-nhl": {
    title: "Perfect Lineup: NHL Hockey Dream Line Game",
    description: "Build an NHL dream line of three forwards, two defensemen and a goalie where slots demand a random team or era, then simulate. Free hockey puzzle game.",
  },
  "/golf-higher-lower": {
    title: "Golf Higher or Lower: Major Championships Quiz",
    description: "Two golf champions side by side: who won more majors? The pool runs from Old Tom Morris to Scottie Scheffler. Free daily golf trivia, ten rounds a go.",
  },
  "/idle-arena": {
    title: "Idle Arena: Free Sports Clicker Game",
    description: "Tap to score, sign a squad of eight archetypes that scores for you and lift trophies that make every run stronger. Free idle sports clicker, no sign up.",
  },
};
