/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 14 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/gauntlet-draft": {
    title: "Gauntlet Draft: Soccer Draft and Knockout Cup",
    description: "Pick your XI from five real players per slot, then survive a five round knockout cup against stronger and stronger teams. Free daily soccer draft game.",
  },
  "/mlb-gauntlet-draft": {
    title: "Gauntlet Draft: MLB Lineup Card Draft Game",
    description: "Fill an MLB lineup card one spot at a time from five real players, then survive a five round October against stronger teams. Free daily baseball draft.",
  },
  "/ufc-chain": {
    title: "Combat Chain: MMA Fighter Chain Trivia Game",
    description: "Name a fighter who beat your current fighter, then one who beat them, and build the longest chain of real MMA results. One miss ends it. Free fight trivia.",
  },
  "/olympics": {
    title: "The Medal Games: Guess the Olympic Athlete",
    description: "A mystery Olympic athlete from the Summer or Winter Games hides behind a stack of clues, starting with the sport. Guess early. Free daily sports trivia.",
  },
};
