/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 18 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/soccer-conquest": {
    title: "Soccer Conquest: Europe Imperialism Map Game",
    description: "96 clubs from the top five leagues share one map of Europe, and every winner annexes the loser's whole empire until one club rules. Free soccer map game.",
  },
  "/world-xi": {
    title: "World XI: International Soccer Squad Quiz",
    description: "Pick a formation, spin in 11 random countries and name a real footballer from each nation who fits the slot. Optional timer. Free soccer trivia game.",
  },
  "/fantasy-draft": {
    title: "Fantasy Draft: Soccer XI Draft Against the AI",
    description: "Take turns with an AI rival drafting from one player pool under the day's squad rule, then a season is simulated and votes pick the winner. Free soccer draft.",
  },
  "/nba-career": {
    title: "NBA Career Path: Guess the Basketball Player",
    description: "A mystery NBA player hides behind a stack of clues, starting with just a position. Every clue makes it easier and pays less. Free daily basketball trivia.",
  },
};
