/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 31 of 32: 1 entry. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/transfer-path": {
    title: "Transfer Path: Connect Soccer Players Puzzle",
    description: "Link two footballers through real teammates, where every step needs the same club in the same season. Six degrees of separation for soccer, free and daily.",
  },
};
