/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 12 of 32: 5 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/club-manager": {
    title: "Club Manager: Free Football Management Game",
    description: "Manage any of 368 real clubs across 22 leagues, today or in a real past season. Transfers, tactics, the board and the sack race. Free soccer management sim.",
  },
  "/rarity-round": {
    title: "Rarity Round: Rarest Answer Wins Soccer Quiz",
    description: "Name a valid soccer answer nobody else would think of, because the obvious one scores worst. Five rounds, real data, plus a Crowd Says mode. Free and daily.",
  },
  "/conquest": {
    title: "NFL Conquest: Football Imperialism Map Game",
    description: "America split into 32 NFL empires. Every winner annexes the loser's whole territory until one team rules the map. Free football strategy game.",
  },
  "/hof-or-bust": {
    title: "Hall of Fame or Bust? Sports Stats Quiz",
    description: "An anonymous career stat line from a real player. Vote Hall of Famer or bust, then see the name and how everyone else called it. Free sports trivia game.",
  },
  "/hall-of-champions": {
    title: "Hall of Champions: Idle Sports Museum Game",
    description: "Build a museum out of real championship history, from Super Bowl I to this year. Admission keeps paying while you are away. A free idle sports game.",
  },
};
