/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 27 of 32: 5 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nfl-career": {
    title: "NFL Career Path: Guess the Football Player",
    description: "One mystery NFL player, six career clues from draft round to team history. Guess early for a bigger score. Free daily pro football trivia game.",
  },
  "/guess-cbb-team": {
    title: "Guess The CBB Program: College Basketball Quiz",
    description: "One college basketball program hides behind six locked clues, from blue bloods to mid majors. Solve it early for more points. Free daily CBB trivia.",
  },
  "/perfect-lineup-nba": {
    title: "Perfect Lineup: NBA Starting Five Puzzle",
    description: "Build an NBA starting five where three slots demand a player from a random franchise or decade, then simulate the game and share it. Free basketball puzzle.",
  },
  "/teammates": {
    title: "Teammates or Not? NFL, NBA and Soccer Quiz",
    description: "Two athletes from the NFL, NBA or soccer. Did they ever wear the same shirt? Call it yes or no and learn which careers crossed. Free sports trivia game.",
  },
  "/face-off": {
    title: "Face Off: Sports Stats Duel Against a Rival",
    description: "Two athletes, one stat, ten seconds. Tap who has more before the rival does, over ten rounds across ten sports, plus a daily duel. Free sports trivia game.",
  },
};
