/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 8 of 32: 1 entry. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/nba-grid": {
    title: "NBA Franchise Grid: Daily Basketball Trivia",
    description: "Fill the 3x3 NBA grid with players whose careers match the row and the column, from franchises to milestones. Daily board plus unlimited. Free basketball.",
  },
};
