/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 26 of 32: 7 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/perfect-season-nfl": {
    title: "17-0 NFL Perfect Season: Football Draft Sim",
    description: "Spin real pro football team seasons from 1999 to 2024, draft a cross era offense and simulate a 17 game season. Can you go unbeaten? Free NFL game.",
  },
  "/cbb-dynasty": {
    title: "CBB Dynasty: College Basketball Program Sim",
    description: "Run a real college hoops program: NIL recruiting, one and done freshmen, the portal, conference tournaments and a 32 team March. Free college basketball sim.",
  },
  "/nba-starting-5": {
    title: "NBA Starting 5: Basketball Lineup Builder",
    description: "Spin a stat challenge, then build a starting five with each pick from a random NBA franchise. Your memory of who played where is the game. Free basketball.",
  },
  "/conquest-nba": {
    title: "NBA Conquest: Basketball Imperialism Map Game",
    description: "Pick a team, inherit the land around its arena and try to own the country. Every NBA winner annexes the loser's whole empire. Free basketball strategy game.",
  },
  "/baseball-connections": {
    title: "MLB Connections: Baseball Grouping Puzzle",
    description: "Twenty baseball players hide four groups of five tied by a franchise, an award or a country. Find every group before you run out. Free daily MLB puzzle.",
  },
  "/nascar-chain": {
    title: "NASCAR Chain: Cup Series Champions Trivia",
    description: "Name a driver who beat the current one to a NASCAR Cup Series title, then who beat that driver, and keep going. One wrong link ends it. Free racing trivia.",
  },
  "/fight-gym": {
    title: "Fight Gym: Boxing Gym Management Sim",
    description: "Sign fighters nobody wanted, find them the right nights and decide when a man has had enough. The money is yours, the damage is his. Free boxing gym sim.",
  },
};
