/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 21 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/hockey-higher-lower": {
    title: "NHL Higher or Lower: Hockey Career Points Quiz",
    description: "Two hockey players side by side: who finished with more career points? Ten quick rounds and a streak bonus that snowballs. Free daily NHL trivia game.",
  },
  "/guess-tennis-player": {
    title: "Guess The Player: ATP and WTA Tennis Quiz",
    description: "A mystery tennis player from either tour hides behind six clues, from a vibe word to Grand Slam details. Commit early for a bigger score. Free daily trivia.",
  },
  "/tennis-chain": {
    title: "Tennis Chain: Grand Slam Defeats Trivia Game",
    description: "Start from a tennis legend and name a player who beat them at a Grand Slam, then who beat that player. One mistake ends the run. Free tennis trivia game.",
  },
  "/guess-the-year": {
    title: "Guess The Year: Sports History Trivia Game",
    description: "Six things happened across the sports world in one year. Each clue is a different sport, so guess the year as early as you can. Free daily sports trivia.",
  },
};
