/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 10 of 32: 3 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/stat-detective": {
    title: "Stat Detective: Guess the NBA Player Quiz",
    description: "A real NBA season with the name scrubbed off: the decade, the position and the per 36 line. Name the player in eight guesses. Free basketball trivia game.",
  },
  "/hockey-grid": {
    title: "NHL Franchise Grid: Daily Hockey Trivia",
    description: "Every row and column is an NHL franchise or a career milestone, and each cell wants a player who fits both. Daily 3x3 board plus unlimited. Free hockey.",
  },
  "/f1-constructor": {
    title: "Guess The Constructor: F1 Team Trivia Quiz",
    description: "A mystery Formula 1 team hides behind six clues: its country, era, titles, livery and a famous driver. Every clue cuts your score. Free daily F1 quiz.",
  },
};
