/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not
   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what
   has fallen behind, and simSeoTitles section 6 fails if the committed copy
   is not what the source makes. */
/* Part 22 of 32: 4 entries. */
import type { SeoMeta } from '../seoMeta';

export const SEO_META_PART: Record<string, SeoMeta> = {
  "/build-your-xi": {
    title: "Build Your XI: Soccer Lineup Builder Game",
    description: "A slot machine gives each position a random club or country. Name a player who fits each slot, then an AI grades your XI and a season plays out. Free soccer.",
  },
  "/nba-front-office": {
    title: "NBA Front Office: Basketball GM Simulator",
    description: "Run a real NBA franchise: the cap sheet, waivers, trades the AI weighs, the play in and best of seven series, drafts and dynasties. A free basketball GM sim.",
  },
  "/nhl-my-career": {
    title: "NHL My Career: Hockey Career Simulator",
    description: "Create a prospect, join a real NHL team and live a full career of stat lines, contracts, injuries and rings, then see if the Hall calls. Free hockey life sim.",
  },
  "/whod-they-beat": {
    title: "Who'd They Beat? Sports Finals Runner Up Quiz",
    description: "We name the champion and the year across the NFL, NBA, MLB, NHL and WNBA. You pick who they beat in the final from four real options. Free daily sports quiz.",
  },
};
