/**
 * Round 1052: a gathered league's squads for Club Manager, generated OFFLINE
 * from ONE committed file, its research (no database, no network):
 *
 *   node scripts/genClubManagerGathered.mjs <id>           writes the file
 *   node scripts/genClubManagerGathered.mjs <id> --check   writes nothing and
 *        exits 1 when the file on disk is not a fresh generation
 *
 * <id> is a row of scripts/lib/gatheredLeagues.mjs (russia2026, ...). The
 * research file (scripts/data/gatheredSquads/<id>/research.json) holds, a
 * club, the squad lists it was read on and the rows that passed the round's
 * rules; this script ships a club's `rows` and never its `leftOut` list.
 *
 * The rules are scripts/lib/gatheredLeague.mjs, the same code the A-League
 * is generated by, with the later leagues' rules switched on:
 * - a man's rating and value come off the shared curve
 *   (scripts/lib/cmValueCurve.mjs: since Round 1102 the value curve plus
 *   points for his age); a man with no value is rated from the curve's floor
 *   value at his age and listed in the NO_VALUE export, never given a value;
 * - his position is the detailed position a host prints for him. Where that
 *   sits outside the group two hosts agree on it still ships, because the
 *   group's default would be a position no host states, and he is listed in
 *   the POSITION_THIN export; only a man with no detailed position the game
 *   knows gets his group's default, and he is listed there too (Release AO:
 *   until then ten men shipped a default, two wide men as centre backs and
 *   eight wingers as central midfielders);
 * - his age needs two hosts and must be 14 to 45; his nationality ships only
 *   with two hosts;
 * - a club that ships fewer than 8 men, or where more than half have no
 *   value, is in the PARTIAL export (the CM_PARTIAL shape);
 * - every club stands on at least two squad lists on different hosts, none
 *   of them a wiki, and every man is on at least two of his club's lists;
 * - a name that is already in the baked world, the A-League file, another
 *   gathered league's file or the free agent pool fails closed, by exact
 *   spelling and under the engine's own name fold; so does a name whose
 *   nationality the modern map holds differently. The supersedes table is
 *   EMPTY on purpose: Round 1052 may not move a man out of an existing squad,
 *   so such a man stays in the research file's leftOut list for the lead.
 *
 * FAILS CLOSED, writing nothing, on any row it cannot resolve. Line endings
 * are folded to LF before anything is compared or hashed (the release gate
 * runs in a CRLF clone).
 */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { buildGatheredLeague, renderGatheredFile, nowBlockOf } from './lib/gatheredLeague.mjs';
import { GATHERED_LEAGUES, gatheredLeague } from './lib/gatheredLeagues.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lf = s => s.split('\r\n').join('\n');
const readText = f => lf(fs.readFileSync(path.join(ROOT, f), 'utf8'));

/** Everything the generator decides, with nothing written: the harness calls
 *  this too, so "the file on disk is a fresh generation" is one comparison. */
export function generateGathered(id, researchOverride) {
  const row = gatheredLeague(id);
  if (!row) return { errors: [`${id} is not a row of scripts/lib/gatheredLeagues.mjs (${GATHERED_LEAGUES.map(l => l.id).join(', ')})`] };
  const research = researchOverride ?? JSON.parse(readText(row.research));
  const errors = [];
  const engines = research.clubs.map(c => c.engine);
  if (new Set(engines).size !== engines.length) errors.push('two research clubs share an engine name');
  if (research.clubs.length !== row.clubs) errors.push(`expected ${row.clubs} clubs, the research holds ${research.clubs.length}`);
  const clubs = research.clubs.map(c => ({
    engine: c.engine, sources: c.sources,
    rows: c.rows.map(r => ({
      name: r.name, group: r.group, tmPosition: r.tmPosition, valueEur: r.valueEur, age: r.age, ageHosts: r.ageHosts,
      nationality: r.nationality, nationalityHosts: r.nationalityHosts, hosts: r.hosts, foldedNamesake: r.foldedNamesake,
    })),
  }));
  const nowBlockText = nowBlockOf(readText('src/data/playerNationalities.ts'));
  if (nowBlockText === null) return { errors: ['src/data/playerNationalities.ts has no modern block to read'] };
  const others = [{ label: 'the A-League file', text: readText('src/data/clubManagerALeague2026.ts') }];
  for (const o of GATHERED_LEAGUES) {
    if (o.id === id || !fs.existsSync(path.join(ROOT, o.out))) continue;
    others.push({ label: `the ${o.label} file`, text: readText(o.out) });
  }
  const built = buildGatheredLeague({
    clubs, supersedes: {}, bakedText: readText('src/data/clubManagerRosters.ts'), nowBlockText,
    options: {
      receipts: 'the research rows', minMen: 8, twoSquadSources: true, foldedCheck: true, statedPosition: true,
      freeAgentText: readText('src/data/clubManagerFreeAgents2026.ts'), otherGeneratedTexts: others,
    },
  });
  errors.push(...built.errors);
  if (errors.length) return { errors };
  const reads = research.clubs.flatMap(c => c.sources.map(s => s.read)).sort();
  const total = built.stats.total;
  const text = renderGatheredFile({
    prefix: row.prefix,
    header: `// Round 1052: the ${research.league} ${research.season}, ${research.clubs.length} real squads for Club Manager.
// GENERATED by scripts/genClubManagerGathered.mjs ${id} from one committed
// file, ${row.research}: every man is on at least two
// independent squad lists of his club for this season, matched by birth
// date, with the lists and the men left out (and why) recorded there.
// Values in £m to two decimals, ratings 48-94 on the same curve as every
// other league (scripts/lib/cmValueCurve.mjs). ${total} players, ${research.clubs.length} clubs.
// Regenerate with: node scripts/genClubManagerGathered.mjs ${id}
// DO NOT EDIT BY HAND.`,
    docs: {
      partial: `/** Clubs that ship fewer than 8 real players, or where more than half of them have no market value. */`,
      noValue: `/** Players with no value on their club's page, as "name|club": each one is
 *  rated from the curve's floor value at his age, never given an invented value. */`,
      positionThin: `/** Players whose position is not inside the group two squad lists agree on,
 *  as "name|club". Each ships the detailed position the one list that prints
 *  one gives him, against the broader line of the other two, or his group's
 *  default where no list prints a detailed position the game knows. */`,
      supersedes: `/** Empty on purpose: this round moves nobody out of an existing squad, so a
 *  man the game already holds elsewhere is left out of this file instead. */`,
      nationalities: `/** Nationality where two hosts agree; a name missing here is unknown and
 *  shows no flag. */`,
    },
    meta: { label: row.label, read: reads[0], readTo: reads[reads.length - 1], players: total, clubs: research.clubs.length },
    rosters: built.rosters, partial: built.partial, noValue: built.noValue, positionThin: built.positionThin, supersedes: {}, nationalities: built.nationalities,
  });
  return { errors: [], row, research, built, text };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const id = process.argv[2];
  const CHECK = process.argv.includes('--check');
  const g = generateGathered(id);
  if (g.errors.length) {
    console.error('FAILED CLOSED, nothing written. Problems:');
    for (const e of g.errors) console.error('  - ' + e);
    process.exit(1);
  }
  const outPath = path.join(ROOT, g.row.out);
  const sha = createHash('sha256').update(g.text).digest('hex');
  if (CHECK) {
    const onDisk = fs.existsSync(outPath) ? lf(fs.readFileSync(outPath, 'utf8')) : null;
    if (onDisk !== g.text) { console.error(`STALE: ${g.row.out} is not a fresh generation from ${g.row.research} (expected sha256 ${sha}, LF)`); process.exit(1); }
    console.log(`${g.row.out} is a fresh generation from ${g.row.research} (sha256 ${sha}, LF)`);
  } else {
    fs.writeFileSync(outPath, g.text);
    const { built } = g;
    const noNat = Object.values(built.rosters).flat().filter(p => !built.nationalities[p.n]).map(p => p.n);
    console.log(`Wrote ${g.row.out}: ${built.stats.total} players, ${Object.keys(built.rosters).length} clubs, ${built.noValue.length} with no value, ${Object.keys(built.nationalities).length} nationalities, ${built.positionThin.length} positions outside the agreed group (${built.stats.groupWon} of them a group default), partial ${JSON.stringify(built.partial)} (sha256 ${sha}, LF)`);
    console.log(`No nationality two hosts agree on (no flag): ${noNat.length ? noNat.join(', ') : 'nobody'}`);
    for (const club of Object.keys(built.rosters).sort()) {
      const l = built.rosters[club];
      const xi = l.map(p => p.r).sort((a, b) => b - a).slice(0, 11);
      console.log(`${club.padEnd(22)} ${String(l.length).padStart(3)}  XI ${(xi.reduce((s, r) => s + r, 0) / 11).toFixed(1)}  top ${l[0].n} (£${l[0].v}m, ${l[0].r})`);
    }
  }
}
