/**
 * Round 1033: the real free agents Club Manager opens a modern career with.
 *
 * Reads the ledger scripts/data/cmFreeAgents2026.json (every 'Without Club'
 * row of the 2026 value table, each one checked on the web: two sources for a
 * man who ships, a reason for a man who does not) and writes
 * src/data/clubManagerFreeAgents2026.ts.
 *
 * Rated and valued exactly as the roster bake rates and values a squad
 * player (scripts/bakeClubManagerRosters.mjs, ratingOf and gbpM), so a real
 * free agent sits on the same scale as the men he would play beside.
 * simFreeAgents section 18 holds the two curves to each other.
 *
 * FAILS CLOSED, writing nothing, when:
 *   - a shipped man has fewer than two sources, or two from one publisher;
 *   - a shipped man is in a baked 2026 squad (he cannot be unattached and on
 *     a club's books at once: that is a bake question, not a pool one);
 *   - the ledger's rows do not add up to its population, or a name repeats;
 *   - a table position has no engine position.
 *
 *   node scripts/genClubManagerFreeAgents.mjs          write the file
 *   node scripts/genClubManagerFreeAgents.mjs --check  exit 1 if the file is stale
 *
 * Offline: reads two committed files, writes one. No database, no network.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
/* The roster bake's position map and curves. Release AH: Round 1035 lifted
   them into scripts/lib/cmValueCurve.mjs, so this imports that module as the
   bake does instead of keeping a copy beside it. */
import { POS_MAP, ratingOf, gbpM } from './lib/cmValueCurve.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEDGER = path.join(ROOT, 'scripts/data/cmFreeAgents2026.json');
const OUT = path.join(ROOT, 'src/data/clubManagerFreeAgents2026.ts');
const ROSTERS = path.join(ROOT, 'src/data/clubManagerRosters.ts');

export function buildFreeAgents(ledger, rosterSrc) {
  const problems = [];
  const all = [...(ledger.unattached ?? []), ...(ledger.dropped ?? [])];
  const names = all.map(r => r.name);
  if (all.length !== ledger.population) problems.push(`the ledger holds ${all.length} rows, its population is ${ledger.population}`);
  const dupes = names.filter((n, i) => names.indexOf(n) !== i);
  if (dupes.length) problems.push(`names repeat in the ledger: ${dupes.join(', ')}`);
  const baked = new Set([...rosterSrc.matchAll(/\bn: '((?:[^'\\]|\\.)+)'/g)].map(m => m[1].replace(/\\'/g, "'")));
  if (baked.size < 1000) problems.push(`only ${baked.size} baked names read from the rosters, so the squad check is not checking`);
  const rows = [];
  for (const u of ledger.unattached ?? []) {
    const srcs = u.sources ?? [];
    const pubs = new Set(srcs.map(s => s.publisher));
    if (srcs.length < 2 || pubs.size < 2) problems.push(`${u.name} ships on ${srcs.length} source(s) from ${pubs.size} publisher(s), two independent ones are the rule`);
    if (srcs.some(s => /wikipedia/i.test(`${s.publisher} ${s.url}`))) problems.push(`${u.name} cites Wikipedia, which is a spot check and never a source`);
    if (baked.has(u.name)) problems.push(`${u.name} is in a baked 2026 squad, so he cannot also be a free agent`);
    const position = POS_MAP[u.tablePosition];
    if (!position) problems.push(`${u.name}: no engine position for '${u.tablePosition}'`);
    if (!(u.age >= 16 && u.age <= 45)) problems.push(`${u.name}: age ${u.age} is not a footballer's`);
    if (!(u.valueUsd > 0)) problems.push(`${u.name}: no value in the table`);
    rows.push({ name: u.name, position, age: u.age, value: gbpM(u.valueUsd), rating: ratingOf(u.valueUsd) });
  }
  rows.sort((a, b) => b.rating - a.rating || a.name.localeCompare(b.name));
  return { rows, problems };
}

export function renderFile(ledger, rows) {
  const q = s => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  const lines = rows.map(r => `  { name: ${q(r.name)}, position: '${r.position}', age: ${r.age}, value: ${r.value}, rating: ${r.rating} },`);
  return [
    `// AUTO-GENERATED by scripts/genClubManagerFreeAgents.mjs (Round 1033). DO NOT EDIT BY HAND.`,
    `// Real footballers who were without a club on ${ledger.checkedOn}, each on two`,
    `// independent sources recorded in scripts/data/cmFreeAgents2026.json, which`,
    `// also says why every other 'Without Club' row of the 2026 table is not here.`,
    `// Ages and values are the table's; ratings and values use the roster bake's`,
    `// own curves. A modern career opens with these men in its free agent pool,`,
    `// once, on day one of season one.`,
    `import type { Position } from '@/types/game';`,
    ``,
    `export interface RealFreeAgent {`,
    `  name: string;`,
    `  position: Position;`,
    `  /** Age in August 2026, as the table records it. */`,
    `  age: number;`,
    `  /** Market value in pounds, millions. */`,
    `  value: number;`,
    `  /** Game rating off the value curve the squads use. */`,
    `  rating: number;`,
    `}`,
    ``,
    `export const CM_REAL_FREE_AGENTS_CHECKED_ON = '${ledger.checkedOn}';`,
    ``,
    `export const CM_REAL_FREE_AGENTS: RealFreeAgent[] = [`,
    ...lines,
    `];`,
    ``,
  ].join('\n');
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const ledger = JSON.parse(fs.readFileSync(LEDGER, 'utf8'));
  const { rows, problems } = buildFreeAgents(ledger, fs.readFileSync(ROSTERS, 'utf8'));
  if (problems.length) {
    for (const p of problems) console.error(`FAIL ${p}`);
    console.error(`genClubManagerFreeAgents: ${problems.length} problem(s), nothing written`);
    process.exit(1);
  }
  const text = renderFile(ledger, rows);
  if (process.argv.includes('--check')) {
    const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').replaceAll('\r\n', '\n') : '';
    if (now !== text) { console.error('genClubManagerFreeAgents --check: src/data/clubManagerFreeAgents2026.ts is stale, rerun the generator'); process.exit(1); }
    console.log(`genClubManagerFreeAgents --check: up to date, ${rows.length} men`);
  } else {
    fs.writeFileSync(OUT, text);
    console.log(`genClubManagerFreeAgents: wrote ${rows.length} real free agents (${ledger.dropped.length} rows dropped with reasons) to src/data/clubManagerFreeAgents2026.ts`);
  }
}
