/**
 * Round 1035: the A-League Men 2026-27 for Club Manager, generated OFFLINE
 * from committed files only (no database, no network):
 *
 *   scripts/data/gatheredSquads/aleague2026/<club>.json   Round 1034's ledgers:
 *       who is in each squad, two hosts a player, his position group and
 *       (where two hosts agreed) his birth date
 *   scripts/data/gatheredSquads/aleague2026/_values.json  each player's
 *       Transfermarkt 26/27 value and detailed position, by player id
 *   scripts/data/gatheredSquads/aleague2026/_people.json  nationality on two
 *       hosts or null, and the age with its two hosts
 *
 * and writes src/data/clubManagerALeague2026.ts in the BakedPlayer shape of
 * src/data/clubManagerRosters.ts. scripts/bakeClubManagerRosters.mjs is not
 * used: it reads the live value table, which holds 4 of these 312 men.
 *
 * Rules (the Round 1035 brief, section 1):
 * - Rating and value come from scripts/lib/cmValueCurve.mjs, the bake's own
 *   curve: EUR at the house rate to USD, USD and the man's age to a 48 to
 *   94 rating (Round 1102: the value curve plus points for age), USD to
 *   pounds. A player with no value on his club's page is NOT given one: he
 *   gets FLOOR_USD (the curve's floor, a positive value), is rated from it at
 *   his age like anybody else, and is listed in CM_ALEAGUE_NO_VALUE. Values are written to two decimals, because one
 *   decimal rounds a $50k player to zero.
 * - Position: Transfermarkt's detailed position through the bake's map.
 *   Where it falls outside the ledger's two source group (or is generic, like
 *   "Striker"), the group wins and the player takes the group's default.
 * - A ledger row with no group is skipped (two rows, both unsettled).
 * - A club where more than half its ledger rows (the group-less ones
 *   included) have no value is in CM_ALEAGUE_PARTIAL, the CM_PARTIAL shape.
 * - Nationality ships only where _people.json found two hosts agreeing.
 *
 * Round 1052: the rules themselves moved to scripts/lib/gatheredLeague.mjs,
 * so the leagues gathered after this one (scripts/genClubManagerGathered.mjs)
 * are generated by the same code and not a copy of it. This file is now the
 * A-League's caller: it reads its four inputs, turns them into the library's
 * rows and writes the file. The lift was proven by output: the file this
 * writes is byte identical to the one Round 1035 shipped.
 *
 * Regenerate with: node scripts/genClubManagerALeague.mjs
 * FAILS CLOSED, writing nothing, on any row it cannot resolve.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ENGINE_NAME } from './lib/aleagueClubs.mjs';
import { buildGatheredLeague, renderGatheredFile, nowBlockOf } from './lib/gatheredLeague.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'scripts/data/gatheredSquads/aleague2026');
const OUT = path.join(ROOT, 'src/data/clubManagerALeague2026.ts');
const read = f => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8'));

const errors = [];
const membership = read('_membership.json');
const values = read('_values.json');
const people = read('_people.json');
const valueOf = new Map();
for (const c of values.clubs) for (const p of c.players) valueOf.set(`${c.slug}|${p.name}`, { ...p, url: c.url });
const personOf = new Map(people.players.map(p => [`${p.club}|${p.name}`, p]));

/* The ledgers, as the library's rows. A row with no group is passed on with
   its value only: the library skips it and still counts it toward the
   club's partial mark. */
const clubs = [];
for (const club of membership.clubs) {
  const engine = ENGINE_NAME[club.slug];
  if (!engine) { errors.push(`no engine name for ${club.slug}`); continue; }
  const ledger = read(`${club.slug}.json`);
  const rows = [];
  for (const row of ledger.rows) {
    const val = valueOf.get(`${club.slug}|${row.name}`);
    const person = personOf.get(`${club.slug}|${row.name}`);
    if (!row.group) { rows.push({ name: row.name, group: null, valueEur: val?.valueEur ?? null }); continue; }
    if (!val) { errors.push(`${row.name} (${club.slug}) has no _values.json row`); continue; }
    if (!person) { errors.push(`${row.name} (${club.slug}) has no _people.json row`); continue; }
    rows.push({
      name: row.name, group: row.group, tmPosition: val.tmPosition, valueEur: val.valueEur,
      age: person.age, ageHosts: person.ageHosts, nationality: person.nationality, nationalityHosts: person.nationalityHosts,
    });
  }
  clubs.push({ engine, rows });
}

/* The baked world must not carry these men too. A name already in
   src/data/clubManagerRosters.ts is either the same man on a stale row
   there (the value table's snapshot is older than these ledgers) or a
   namesake, and only a person can tell which. So every such name must be
   listed here with the proof, or the run fails. A listed man is dropped from
   that baked club where the two files are joined
   (src/data/clubManagerWorldRosters.ts); the A-League ledger, read
   2026-10-06 on four hosts, is the newer truth. */
const SUPERSEDES = {
  /* Same man: born 1994-02-24, a Scottish winger. The Round 1034 ledger has
     him in Macarthur FC's 2026-27 squad on the club page, ESPN (153012),
     Transfermarkt (146795) and FotMob (230916), all with that birth date.
     The baked Southampton row (age 31, LW) is the value table's old club. */
  'Ryan Fraser': 'Southampton',
};
const bakedText = fs.readFileSync(path.join(ROOT, 'src/data/clubManagerRosters.ts'), 'utf8').split('\r\n').join('\n');
/* nationalityOf reads the modern map first, so an A-League man whose name is
   already there must carry the same nationality, or the flag would be the
   other entry's. */
const natText = fs.readFileSync(path.join(ROOT, 'src/data/playerNationalities.ts'), 'utf8').split('\r\n').join('\n');
const nowBlockText = nowBlockOf(natText);
if (nowBlockText === null) { console.error('FATAL: src/data/playerNationalities.ts has no modern block to read'); process.exit(1); }

const built = buildGatheredLeague({ clubs, supersedes: SUPERSEDES, bakedText, nowBlockText });
errors.push(...built.errors);
const { rosters, partial, noValue, nationalities } = built;
const { total, groupWon, skipped } = built.stats;
if (Object.keys(rosters).length !== 12) errors.push(`expected 12 clubs, got ${Object.keys(rosters).length}`);

if (errors.length) {
  console.error('FAILED CLOSED, nothing written. Problems:');
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}

const clubNames = Object.keys(rosters).sort();
const out = renderGatheredFile({
  prefix: 'ALEAGUE',
  header: `// Round 1035: the A-League Men 2026-27, twelve real squads for Club Manager.
// GENERATED by scripts/genClubManagerALeague.mjs from committed files only:
// the Round 1034 squad ledgers (two hosts a player), each player's
// Transfermarkt 26/27 value (_values.json, read ${values.read}) and his
// nationality and age receipts (_people.json). Values in £m to two decimals,
// ratings 48-94 on the same curve as every other league
// (scripts/lib/cmValueCurve.mjs). ${total} players, ${clubNames.length} clubs.
// Regenerate with: node scripts/genClubManagerALeague.mjs
// DO NOT EDIT BY HAND.`,
  docs: {
    partial: `/** Clubs where more than half of the club's ledger rows (Round 1034's gathered squad, the rows with no position group included) have no market value. */`,
    noValue: `/** Players with no value on their club's page, as "name|club": each one is
 *  rated at the curve's floor at every age, never given an invented value. */`,
    supersedes: `/** Men the baked file still carries at an older club, by name: the join
 *  drops each from that club (proof in the generator's SUPERSEDES). */`,
    nationalities: `/** Nationality where two hosts agree (_people.json); a name missing here is
 *  unknown and shows no flag. */`,
  },
  meta: { read: values.read, players: total, clubs: clubNames.length },
  rosters, partial, noValue, supersedes: SUPERSEDES, nationalities,
});
fs.writeFileSync(OUT, out);
console.log(`Wrote src/data/clubManagerALeague2026.ts: ${total} players, ${clubNames.length} clubs, ${noValue.length} with no value, ${Object.keys(nationalities).length} nationalities, ${groupWon} positions set by the ledger group, ${skipped} rows skipped (no group), partial ${JSON.stringify(partial)}`);
for (const club of clubNames) {
  const l = rosters[club];
  const xi = l.map(p => p.r).sort((a, b) => b - a).slice(0, 11);
  console.log(`${club.padEnd(26)} ${String(l.length).padStart(3)}  XI ${(xi.reduce((s, r) => s + r, 0) / 11).toFixed(1)}  top ${l[0].n} (£${l[0].v}m, ${l[0].r})`);
}
