/* The names a NASCAR Chain or Tennis Chain link can hold, for the restore.

   Round 645 part three, second fix. NASCAR Chain and Tennis Chain are
   validated on the server (nascar-chain-validate, tennis-chain-validate), so
   the daily record their hooks file (src/lib/chainDaily.ts) is all a reload
   has, and the two restores trusted every name in it: a hand edited part
   played record holding today's starter and forty invented names resumed at
   8000 points and recorded that on Give Up. Combat Chain never could, because
   its results are bundled and its restore checks every link against them.

   The two validators accept a link only when the guessed name is a champion
   in one table, and they hand back that table's own spelling as fullName,
   which is the name the hook files:
     nascar-chain-validate  public.nascar_champions.driver_name
     tennis-chain-validate  public.tennis_grand_slam_winners.champion
   So every link past the starter is one of those names, and this writes each
   table's distinct names, sorted, into src/data. The restore refuses a part
   played chain holding any other name, which bounds its length too: no name
   comes twice, so never more links than these names plus the starter.

   This mirrors the validators' own source, not the world. It is never shown
   to a player and never edited by hand. When a champion is added to either
   table, run this again. Until then a part played chain holding that new
   champion is dealt fresh from its starter, which is the direction this is
   meant to fail in: nothing was recorded for the part played chain, so
   nothing is recorded twice.

   Run: node scripts/genChainChampions.mjs           (needs the database)
        node scripts/genChainChampions.mjs --check   (exit 1 if either file
                                                      differs from its table)
*/
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const client = fs.readFileSync(path.join(ROOT, 'src', 'integrations', 'supabase', 'client.ts'), 'utf8');
const URL_ = client.match(/SUPABASE_URL\s*=\s*["']([^"']+)["']/)[1];
const KEY = client.match(/SUPABASE_PUBLISHABLE_KEY\s*=\s*["']([^"']+)["']/)[1];
const HEAD = { apikey: KEY, Authorization: `Bearer ${KEY}` };

/* Paged and ordered, because PostgREST caps a select at 1000 rows without
   saying so, and tennis_grand_slam_winners holds more than that (the cap
   that hid nineteen US Open champions from the validator until Round 487). */
async function pull(table, column, order) {
  const rows = [];
  for (let from = 0; ; from += 1000) {
    const res = await fetch(`${URL_}/rest/v1/${table}?select=${column}&order=${order}`, { headers: { ...HEAD, Range: `${from}-${from + 999}` } });
    if (!res.ok) throw new Error(`${table}: HTTP ${res.status}, nothing written`);
    const page = await res.json();
    if (!Array.isArray(page)) throw new Error(`${table}: not a row list, nothing written`);
    rows.push(...page);
    if (page.length < 1000) break;
  }
  return rows;
}

const SPORTS = [
  {
    file: 'src/data/nascarChampionNames.json',
    table: 'nascar_champions', column: 'driver_name', order: 'year.asc,driver_name.asc',
    validator: 'nascar-chain-validate', game: 'NASCAR Chain',
  },
  {
    file: 'src/data/tennisChampionNames.json',
    table: 'tennis_grand_slam_winners', column: 'champion', order: 'year.asc,tournament.asc,champion.asc',
    validator: 'tennis-chain-validate', game: 'Tennis Chain',
  },
];

let drift = 0;
for (const s of SPORTS) {
  const rows = await pull(s.table, s.column, s.order);
  const names = [...new Set(rows.map(r => r[s.column]).filter(n => typeof n === 'string' && n.trim() !== ''))].sort();
  if (rows.length === 0 || names.length === 0) throw new Error(`${s.table} came back empty, nothing written`);
  const doc = {
    note: `Generated by scripts/genChainChampions.mjs from public.${s.table}.${s.column}, the table ${s.validator} accepts a link from and takes its spelling from. The ${s.game} restore refuses a part played daily chain holding any other name past its starter. Rerun the script when the table changes; never edit this by hand.`,
    source: `public.${s.table}.${s.column}`,
    names,
  };
  const text = JSON.stringify(doc, null, 1) + '\n';
  const target = path.join(ROOT, s.file);
  const was = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').split('\r\n').join('\n') : null;
  if (CHECK) {
    if (was !== text) { drift += 1; console.error(`  DRIFT: ${s.file} differs from public.${s.table} (${names.length} names in the table)`); }
    else console.log(`   ${s.file}: ${names.length} names, matches public.${s.table}`);
    continue;
  }
  fs.writeFileSync(target, text);
  console.log(`   ${s.file}: ${names.length} names from ${rows.length} rows of public.${s.table}${was === text ? ' (unchanged)' : ''}`);
}
if (CHECK && drift > 0) {
  console.error(`\ngenChainChampions --check: ${drift} file(s) out of date, run node scripts/genChainChampions.mjs`);
  process.exit(1);
}
