/* Round 829: MLB Front Office's 26 man rosters, generated from the committed
   record, with no network and no clock.

   Reads   scripts/data/mlbRosters2026.json  (each club's 40 man list on the
                                              last day of the 2026 regular
                                              season, from MLB's Stats API,
                                              and the ESPN spot check)
           scripts/data/mlbStats2026.json    (the league's 2026 regular season
                                              lines, the rating pools)
   Writes  src/data/mlbFoRosters2026.ts      (the game's data file)
           scripts/data/mlbRostersLeftOut2026.json (every man on a list who is
                                              not shipped, with the reason)

   The rules (the 26, the ratings, the partial mark, the age) live once in
   scripts/lib/mlbFoRecord.mjs and are copied into the data file's header
   below, word for word in substance.

   It refuses to write when the spot check is missing or more than 3 percent
   of the men it checked disagree with ESPN, and when a club cannot field 26.

     node scripts/genMlbFrontOfficeRoster.mjs          write both files
     node scripts/genMlbFrontOfficeRoster.mjs --check  exit 1 if either file
                                                       differs from the record */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GAME_TEAMS, SPOT_LIMIT, ROSTER_SIZE, selectTwentySix, gameNames, buildPools, rateMan, ageOn, caughtGames } from './lib/mlbFoRecord.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const RECORD = path.join(ROOT, 'scripts', 'data', 'mlbRosters2026.json');
const STATS = path.join(ROOT, 'scripts', 'data', 'mlbStats2026.json');
const OUT = path.join(ROOT, 'src', 'data', 'mlbFoRosters2026.ts');
const LEFT = path.join(ROOT, 'scripts', 'data', 'mlbRostersLeftOut2026.json');
const CHECK = process.argv.includes('--check');

const die = msg => { console.error(`genMlbFrontOfficeRoster: ${msg}`); process.exit(1); };
const record = JSON.parse(fs.readFileSync(RECORD, 'utf8'));
const stats = JSON.parse(fs.readFileSync(STATS, 'utf8'));

const sc = record.spotCheck;
if (!sc || !sc.checkedMen) die('the record has no spot check, run node scripts/fetchMlbFoRecord.mjs --spot');
if (sc.mismatches / sc.checkedMen > SPOT_LIMIT) die(`the spot check disagrees on ${sc.mismatches} of ${sc.checkedMen}, over the ${SPOT_LIMIT * 100} percent limit. Stop and report, do not ship.`);
for (const a of GAME_TEAMS) if (!record.teams[a]) die(`${a} is not in the record`);

const pools = buildPools(stats);
const ROLE = p => (p.pos === 'SP' ? 1 : p.pos === 'RP' || p.pos === 'CL' ? 2 : 0);
const rosters = {};
const left = {};
const partial = [];
let shipped = 0;
const caught = caughtGames(stats);
const selected = Object.fromEntries(GAME_TEAMS.map(a => [a, selectTwentySix(record.teams[a].players, caught)]));
const shownAs = gameNames(Object.fromEntries(GAME_TEAMS.map(a => [a, selected[a].men])));
const renamed = [...shownAs.entries()].filter(([id, n]) => GAME_TEAMS.some(a => selected[a].men.some(m => m.id === id && m.name !== n))).map(([, n]) => n);
for (const a of GAME_TEAMS) {
  const { men, leftOut } = selected[a];
  if (men.length !== ROSTER_SIZE) die(`${a}: only ${men.length} men on the major league roster on ${record.meta.rosterDate}`);
  const rows = men.map(m => {
    const r = rateMan(m, pools);
    return { name: shownAs.get(m.id), pos: r.pos, age: ageOn(m.birthDate, record.meta.rosterDate), ovr: r.ovr, partial: r.partial };
  }).sort((x, y) => ROLE(x) - ROLE(y) || y.ovr - x.ovr || (x.name < y.name ? -1 : x.name > y.name ? 1 : 0));
  for (const r of rows) if (r.partial) partial.push(r.name);
  rosters[a] = rows;
  shipped += rows.length;
  left[a] = leftOut.sort((x, y) => x.id - y.id).map(m => ({ id: m.id, name: m.name, status: m.status, reason: m.reason }));
}
const names = Object.values(rosters).flat().map(r => r.name);
if (new Set(names).size !== names.length) die('a name appears on two clubs');
partial.sort();

const q = s => JSON.stringify(s);
/* A real player whose surname is also a product's name is a person, not the
   product. scripts/simNoRivalNames.mjs would flag him, so his row carries
   its inline marker with the reason, the way src/data/aflGoalKickers.ts does.
   Add a surname here only when that harness names a real man in this file. */
const NAME_IS_A_PERSON = ['Madden']; // surnames of real players only: rival-names-allow
const personNote = r => (NAME_IS_A_PERSON.some(w => r.name.split(/\s+/).includes(w)) ? ' // a real player, not the football video game: rival-names-allow' : '');
const row = r => `    { name: ${q(r.name)}, pos: ${q(r.pos)}, age: ${r.age}, ovr: ${r.ovr}${r.partial ? ', partial: true' : ''} },${personNote(r)}`;
const leftN = Object.values(left).reduce((s, l) => s + l.length, 0);
const ts = `// GENERATED by scripts/genMlbFrontOfficeRoster.mjs from scripts/data/mlbRosters2026.json and
// scripts/data/mlbStats2026.json. Do not hand edit: change the record or the rule, then rerun it.
//
// Round 829. Every club's real 26, from MLB's own Stats API (statsapi.mlb.com): its 40 man list on
// ${record.meta.rosterDate}, the last day of the 2026 regular season, read ${[...new Set(GAME_TEAMS.map(a => record.teams[a].read))].join(' and ')}.
//
// THE 26. The September active roster is 28, so the 26 come by one rule from the club's major
// league roster that day (the active list and every injured list; optioned men are in the minors):
// the 13 position players and 13 pitchers who carried the most of its 2026. Position players: the
// two catchers with the most plate appearances, then the most plate appearances; a club with fewer
// than two men listed at C makes up the pair with whoever caught the most 2026 games (the API
// labels some real catchers DH; such a man is shown at C).
// Pitchers: the five with the most games started (the rotation), then the most outs recorded.
// ${leftN} men on the lists are left out, each with the reason, in scripts/data/mlbRostersLeftOut2026.json.
//
// THE RATINGS, 2026 regular season only, one stat per role for everyone:
//   position players: OPS percentile among every hitter with 300+ PA, mapped to 66 to 97, pulled
//     toward 66 in proportion to how far short of 300 PA he is;
//   starters: FIP-lite (13 HR + 3 BB - 2 K per inning) percentile among pitchers who started at
//     least half their games and threw 100+ innings, 66 to 96, pulled toward 66 by innings short of 100;
//   relievers: the same FIP-lite among pitchers who started under half their games and threw 40+
//     innings, 64 to 92, pulled toward 64 by innings short of 40; 20+ saves makes him the closer (CL), +2.
// A pitcher is SP if he is in the rotation or started half his games. A two way man is listed where
// he hits (DH). A rating resting on under a third of the full sample (under 100 PA, a starter under
// 100 outs, a reliever under 40 outs) is marked partial: still his own numbers, and the game says so.
// ${partial.length} of ${shipped} are partial (MLB_FO_PARTIAL).
//
// AGES are whole years on ${record.meta.rosterDate} from the birth date the API gives.
//
// NAMESAKES. The game keeps one name to a man in a league. When two shipped men share a name
// (compared without accents or case) the older keeps it as the API gives it and the younger carries
// his birth year after it. This round that is ${renamed.length ? renamed.join(' and ') : 'nobody'}.
//
// SECOND SOURCE: ESPN, as a spot check, not a pipeline. ${sc.rule.split('. ')[0]}. ${sc.checkedMen} men compared
// (membership, birth date, bats, throws), ${sc.mismatches} disagree, read ${sc.read}. Full detail in the record.
//
// Every salary, contract and potential the engine puts on top of these seeds is fictional.

export interface MlbFoRosterSeed {
  name: string;
  pos: string; // C 1B 2B 3B SS LF CF RF OF DH SP RP CL
  age: number;
  ovr: number;
  /** the rating rests on under a third of a full 2026 sample */
  partial?: true;
}

export const MLB_FO_ROSTER_DATE = ${q(record.meta.rosterDate)};

export const MLB_FO_ROSTERS_2026: Record<string, MlbFoRosterSeed[]> = {
${GAME_TEAMS.map(a => `  ${a}: [\n${rosters[a].map(row).join('\n')}\n  ],`).join('\n')}
};

/** Men whose rating rests on thin 2026 numbers, the same honesty rule as Club Manager's CM_PARTIAL. */
export const MLB_FO_PARTIAL: string[] = [
${partial.map(n => `  ${q(n)},`).join('\n')}
];
`;
const leftJson = `${JSON.stringify({
  generatedBy: 'scripts/genMlbFrontOfficeRoster.mjs',
  rosterDate: record.meta.rosterDate,
  rule: 'Everyone on a club\'s 40 man list on the record date who is not in its shipped 26: optioned to the minors, or outside the 13 position players or 13 pitchers by 2026 playing time.',
  total: leftN,
  clubs: left,
}, null, 1)}\n`;

const norm = s => s.split('\r\n').join('\n');
if (CHECK) {
  const bad = [];
  if (!fs.existsSync(OUT) || norm(fs.readFileSync(OUT, 'utf8')) !== ts) bad.push(path.relative(ROOT, OUT));
  if (!fs.existsSync(LEFT) || norm(fs.readFileSync(LEFT, 'utf8')) !== leftJson) bad.push(path.relative(ROOT, LEFT));
  if (bad.length) die(`out of date against the record: ${bad.join(', ')}. Run node scripts/genMlbFrontOfficeRoster.mjs`);
  console.log(`genMlbFrontOfficeRoster --check: both files match the record (${shipped} men, ${partial.length} partial, ${leftN} left out)`);
} else {
  fs.writeFileSync(OUT, ts);
  fs.writeFileSync(LEFT, leftJson);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${shipped} men, ${partial.length} partial) and ${path.relative(ROOT, LEFT)} (${leftN} left out)`);
}
