import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(root, 'package.json'));
const hash = value => createHash('sha256').update(value).digest('hex');
const readSource = file => fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
const unpack = set => set.rows.map(row => Object.fromEntries(set.headers.map((key, i) => [key, row[i]])));

export async function generateNbaOpeningRatings(options = {}) {
  const inputFile = options.inputs ?? path.join(root, 'scripts/data/nbaFoRatingInputs2026.json');
  const seedFile = options.seed ?? path.join(root, 'src/data/conquestDataNba.ts');
  const modelFile = options.model ?? path.join(root, 'scripts/lib/nbaFoRatingModel.mjs');
  const outputFile = options.output ?? path.join(root, 'src/data/nbaOpeningRatings.ts');
  const snapshot = JSON.parse(fs.readFileSync(inputFile, 'utf8'));
  const source = readSource(seedFile);
  assert.equal(hash(source), snapshot.seed.sourceSha256, 'NBA opening seed source hash drift, refuse before writing');
  const start = source.indexOf('export const NBA_TEAMS');
  const end = source.indexOf('export const NBA_TEAM_MAP', start);
  assert.ok(start >= 0 && end > start, 'actual NBA seed export');
  const transformed = await require('esbuild').transform(source.slice(start, end), { loader: 'ts', format: 'esm' });
  const { NBA_TEAMS } = await import('data:text/javascript;base64,' + Buffer.from(transformed.code).toString('base64'));
  const seeds = NBA_TEAMS.flatMap(team => team.players.map(player => ({ team: team.id, ...player })));
  assert.equal(seeds.length, 300, 'unchanged 300-entry seed');
  assert.equal(hash(JSON.stringify(seeds)), snapshot.seed.canonicalSha256, 'NBA canonical seed hash drift, refuse before writing');
  const inputs = Object.fromEntries(Object.entries(snapshot.observations).map(([key, set]) => {
    assert.equal(new Set(set.headers).size, set.headers.length, 'unique observed fields');
    assert.ok(set.rows.every(row => row.length === set.headers.length), 'observed row shape');
    const rows = unpack(set);
    assert.equal(new Set(rows.map(row => row.PLAYER_ID)).size, rows.length, 'unique observed identities');
    return [key, rows];
  }));
  const model = await import(pathToFileURL(modelFile).href);
  assert.equal(model.MODEL_VERSION, snapshot.version, 'model version must match reviewed snapshot');
  const generated = model.generateModel(seeds, inputs);
  assert.deepEqual(generated.config, snapshot.checkpoint.config, 'reviewed model configuration held');
  assert.deepEqual(generated.cohorts, snapshot.checkpoint.cohorts, 'dated feature reference counts held');
  assert.deepEqual(generated.calibration, snapshot.checkpoint.calibration, 'reviewed fitted calibration held, no silent refit');
  const salaryFor = overall => Math.round(Math.max(2, (overall - 68) * 2.1 - 4) * 10) / 10;
  const finance = model.openingFinance(seeds, generated, salaryFor);
  assert.equal(finance.length, 30, 'all original club budgets');
  for (const team of finance) assert.equal(team.candidateBudget, team.originalBudget, 'exact opening payroll budget');
  const prices = new Map(finance.flatMap(team => team.players.map(player => [`${team.team}|${player.name}`, player.salary])));
  const tuples = generated.players.map(player => [player.team, player.name, player.position, player.model.overall,
    prices.get(`${player.team}|${player.name}`), player.model.offense, player.model.defense, player.model.role,
    player.model.currentAvailable ? 'box-score-proxy' : player.model.priorAvailable ? 'prior-only' : 'unmeasured-prior']);
  assert.equal(hash(JSON.stringify(snapshot.checkpoint.tuples)), snapshot.checkpoint.tupleSha256, 'reviewed tuple checkpoint integrity');
  assert.equal(hash(JSON.stringify(tuples)), snapshot.checkpoint.tupleSha256, 'all reviewed grades/prices/basis held before writing');
  assert.deepEqual(tuples, snapshot.checkpoint.tuples, 'all 300 reviewed tuples held');
  const grouped = {};
  for (const [team, name, position, ovr, salary, offense, defense, role, basis] of tuples) {
    const key = `${name}|${position}`;
    grouped[team] ??= {};
    assert.ok(!Object.hasOwn(grouped[team], key), 'unique opening player key');
    grouped[team][key] = { ovr, salary, evidence: { modelVersion: snapshot.version,
      originKey: `${team}|${name}|${position}`, openingOvr: ovr, basis, partial: true } };
  }
  const output = `// Generated by scripts/genNbaOpeningRatings.mjs. Simulation grades and prices, not historical facts.\n// Partial box-score defense and unchanged seed positions; prior-only and unmeasured rows stay distinct.\nexport interface NbaOpeningRatingEvidence {\n  modelVersion: string;\n  originKey: string;\n  openingOvr: number;\n  basis: 'box-score-proxy' | 'prior-only' | 'unmeasured-prior';\n  partial: true;\n}\nexport interface NbaOpeningRating { ovr: number; salary: number; evidence: NbaOpeningRatingEvidence }\nexport const NBA_OPENING_RATING_VERSION = ${JSON.stringify(snapshot.version)};\nexport const NBA_OPENING_RATING_WINDOW = ${JSON.stringify(snapshot.window)};\nexport const NBA_OPENING_RATINGS: Record<string, Record<string, NbaOpeningRating>> = ${JSON.stringify(grouped, null, 2)};\n`;
  fs.writeFileSync(outputFile, output);
  return { players: tuples.length, clubs: finance.length, version: snapshot.version, window: snapshot.window,
    tupleSha256: snapshot.checkpoint.tupleSha256, sourceSha256: snapshot.seed.sourceSha256,
    basis: Object.fromEntries(['box-score-proxy', 'prior-only', 'unmeasured-prior'].map(basis => [basis, tuples.filter(t => t[8] === basis).length])),
    outputSha256: hash(output), outputBytes: Buffer.byteLength(output) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const options = {};
  for (let i = 2; i < process.argv.length; i += 2) {
    const key = process.argv[i].slice(2);
    assert.ok(['inputs', 'seed', 'model', 'output'].includes(key) && process.argv[i + 1], 'known generator option and value');
    options[key] = path.resolve(process.argv[i + 1]);
  }
  console.log(JSON.stringify(await generateNbaOpeningRatings(options)));
}
