import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(root, 'package.json'));
const hash = value => createHash('sha256').update(value).digest('hex');
const readSource = file => fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n');

export async function generateNhlOpeningRatings(options = {}) {
  const inputFile = options.inputs ?? path.join(root, 'scripts/data/nhlFoRatingInputs2026.json');
  const seedFile = options.seed ?? path.join(root, 'src/data/nhlFoPlayers.ts');
  const modelFile = options.model ?? path.join(root, 'scripts/lib/nhlFoRatingModel.mjs');
  const outputFile = options.output ?? path.join(root, 'src/data/nhlOpeningRatings.ts');
  const snapshot = JSON.parse(fs.readFileSync(inputFile, 'utf8'));
  const source = readSource(seedFile);
  assert.equal(hash(source), snapshot.seed.sourceSha256, 'NHL seed source drift, refuse before writing');
  assert.equal(hash(readSource(modelFile)), snapshot.checkpoint.modelSha256, 'NHL reviewed model source drift, refuse before writing');
  assert.equal(hash(JSON.stringify(snapshot.observations)), snapshot.observationsSha256, 'NHL dated input drift, refuse before writing');
  const transformed = await require('esbuild').transform(source, { loader: 'ts', format: 'esm' });
  const { NHL_FO_ROSTERS } = await import('data:text/javascript;base64,' + Buffer.from(transformed.code).toString('base64'));
  const seeds = Object.entries(NHL_FO_ROSTERS).flatMap(([team, rows]) => rows.map(row => ({ team, ...row })));
  assert.equal(seeds.length, 416, 'All416 original NHL seed rows');
  assert.equal(hash(JSON.stringify(seeds)), snapshot.seed.canonicalSha256, 'NHL canonical seed drift, refuse before writing');
  const data = { seed: seeds };
  for (const [key, set] of Object.entries(snapshot.observations)) {
    assert.equal(new Set(set.headers).size, set.headers.length, 'Unique observed fields');
    assert.ok(set.rows.every(row => row.length === set.headers.length), 'Observed row shape');
    data[key] = set.rows.map(row => Object.fromEntries(set.headers.map((field, i) => [field, row[i]])));
  }
  const model = await import(pathToFileURL(modelFile).href);
  assert.equal(model.MODEL.version, snapshot.version, 'Reviewed model version');
  assert.equal(snapshot.runtimeVersion, `${model.MODEL.version}-economy-flat-v1`, 'Reviewed runtime version');
  assert.equal(snapshot.window, '2024-25 and 2025-26 regular seasons', 'Retained regular-season window');
  assert.deepEqual(model.MODEL, snapshot.checkpoint.model, 'Reviewed model configuration');
  const result = model.buildCandidate(data), finance = model.openingPrices(result.output);
  assert.deepEqual(result.refs, snapshot.checkpoint.refs, 'Dated fitted references held, no silent refit');
  assert.deepEqual(finance.clubs, snapshot.checkpoint.clubs, 'Every original opening club budget held');
  const tuples = result.output.map(p => [p.team, p.name, p.pos, p.rating, finance.prices[p.key], p.basis, p.partial, p.confidence, p.partialReasons]);
  assert.equal(hash(JSON.stringify(snapshot.checkpoint.tuples)), snapshot.checkpoint.tupleSha256, 'Reviewed tuple integrity');
  assert.equal(hash(JSON.stringify(tuples)), snapshot.checkpoint.tupleSha256, 'Every reviewed grade/price/basis held before writing');
  const quoteFactor = (result.output.reduce((n, p) => n + model.fictionalSalaryFor(p.ovr), 0) - .7 * seeds.length)
    / result.output.reduce((n, p) => n + Math.max(0, Math.max(.7, (p.rating - 70) * .4) - .7), 0);
  assert.equal(quoteFactor, snapshot.checkpoint.quoteFactor, 'Reviewed flat future quote factor');
  const grouped = {};
  for (const [team, name, position, ovr, salary, basis, partial] of tuples) {
    assert.ok(Number.isInteger(ovr) && ovr >= 0 && ovr <= 99 && Number.isFinite(salary) && salary >= .7, 'Valid opening grade and price');
    grouped[team] ??= {};
    const key = `${name}|${position}`;
    assert.ok(!Object.hasOwn(grouped[team], key), 'Unique opening player key');
    grouped[team][key] = { ovr, salary, evidence: { modelVersion: snapshot.runtimeVersion,
      originKey: `${team}|${name}|${position}`, openingOvr: ovr, basis, partial } };
  }
  assert.equal(Object.keys(grouped).length, 32, 'All32 clubs');
  const output = `// Generated by scripts/genNhlOpeningRatings.mjs. Original simulation grades and fictional prices.\n// Frozen seed membership/ages; defensive and goalie limits, unresolved identities remain qualified.\nexport interface NhlOpeningRatingEvidence {\n  modelVersion: string;\n  originKey: string;\n  openingOvr: number;\n  basis: 'offensive-production' | 'offense-usage-proxy' | 'save-rate-proxy' | 'unmeasured-prior';\n  partial: boolean;\n}\nexport interface NhlOpeningRating { ovr: number; salary: number; evidence: NhlOpeningRatingEvidence }\nexport const NHL_OPENING_RATING_VERSION = ${JSON.stringify(snapshot.runtimeVersion)};\nexport const NHL_OPENING_RATING_WINDOW = ${JSON.stringify(snapshot.window)};\nexport const NHL_OPENING_QUOTE_FACTOR = ${quoteFactor};\nexport const NHL_OPENING_RATINGS: Record<string, Record<string, NhlOpeningRating>> = ${JSON.stringify(grouped, null, 2)};\n`;
  fs.writeFileSync(outputFile, output);
  return { players: tuples.length, clubs: Object.keys(grouped).length, partial: tuples.filter(t => t[6]).length,
    tupleSha256: snapshot.checkpoint.tupleSha256, quoteFactor, outputSha256: hash(output), outputBytes: Buffer.byteLength(output) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const options = {};
  for (let i = 2; i < process.argv.length; i += 2) {
    const key = process.argv[i].slice(2);
    assert.ok(['inputs', 'seed', 'model', 'output'].includes(key) && process.argv[i + 1], 'Known generator option and value');
    options[key] = path.resolve(process.argv[i + 1]);
  }
  console.log(JSON.stringify(await generateNhlOpeningRatings(options)));
}
