/**
 * Round 830: bake NHL Front Office's full rosters, offline and deterministically.
 *
 * IN   scripts/data/nhlRosters2026.json, written by scripts/fetchNhlFoRoster.mjs
 *      from the NHL's own API (every club's published roster on the day read, and
 *      every 2025-26 regular season line), with the ESPN spot check that
 *      scripts/checkNhlFoRosterEspn.mjs wrote into it.
 * OUT  src/data/nhlFoRosters2026.ts, the 32 rosters a new NHL Front Office league
 *      starts from, and scripts/data/nhlRosters2026LeftOut.json, every man on a
 *      published roster who is not in the game and why.
 *
 * The rules (rating, the 23, the spot check sample) are in
 * scripts/lib/nhlFoRosterRules.mjs and are written out in the data file's header.
 * Nothing here reads the network or the clock: the same record always bakes the
 * same bytes, and `--check` proves the committed files are that bake.
 *
 *   node scripts/genNhlFrontOfficeRoster.mjs          write both files
 *   node scripts/genNhlFrontOfficeRoster.mjs --check  exit 1 if either file differs
 *
 * The bake refuses a record whose spot check is missing, was made on another day,
 * or found more than two mismatches in fifty: that is the stop and report bar.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ACTIVE_LIMIT, PARTIAL_RATING, ageOn, buildRatings, chooseTwentyThree, gamePos, groupOf, SPOT_CHECK_RULE } from './lib/nhlFoRosterRules.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const RECORD = path.join(ROOT, 'scripts/data/nhlRosters2026.json');
export const DATA = path.join(ROOT, 'src/data/nhlFoRosters2026.ts');
export const LEFT_OUT = path.join(ROOT, 'scripts/data/nhlRosters2026LeftOut.json');
const MISMATCH_LIMIT = 2;

const quote = s => (s.includes("'") ? JSON.stringify(s) : `'${s}'`);

/** The whole bake as strings, so --check and the fence can compare without writing. */
export function bake(rec) {
  const spot = rec.espnSpotCheck;
  if (!spot) throw new Error('the record carries no ESPN spot check; run scripts/checkNhlFoRosterEspn.mjs first');
  if (spot.read !== rec.meta.read) throw new Error(`the spot check (${spot.read}) was not made on the day the record was read (${rec.meta.read})`);
  if (spot.mismatches > MISMATCH_LIMIT) throw new Error(`the spot check found ${spot.mismatches} mismatches, over the bar of ${MISMATCH_LIMIT}: stop and report, do not bake`);
  const disputed = new Map();
  for (const c of spot.clubs) for (const r of c.rows) if (!r.match) disputed.set(`${c.team}:${r.id}`, r.problems.join('; '));

  const rate = buildRatings(rec.stats2025_26);
  const teams = {};
  const partial = [];
  const leftOut = [];
  let kept = 0;
  for (const abbr of Object.keys(rec.teams).sort()) {
    const choice = chooseTwentyThree(rec.teams[abbr].players, rate);
    for (const x of choice.leftOut) leftOut.push({ team: abbr, id: x.p.id, name: x.p.name, pos: x.p.pos, gp2025_26: x.r.gp, reason: x.reason });
    const rows = [];
    for (const x of choice.kept) {
      const why = disputed.get(`${abbr}:${x.p.id}`);
      if (why) { leftOut.push({ team: abbr, id: x.p.id, name: x.p.name, pos: x.p.pos, gp2025_26: x.r.gp, reason: `the second source disagrees: ${why}` }); continue; }
      if (!x.p.birthDate) throw new Error(`${abbr} ${x.p.name}: no birth date in the record, so no real age`);
      const pos = gamePos(x.p.pos);
      rows.push({ name: x.p.name, pos, age: ageOn(x.p.birthDate, rec.meta.read), ovr: x.r.ovr, partial: x.r.partial });
    }
    const rank = r => ({ C: 0, W: 0, D: 1, G: 2 })[r.pos];
    rows.sort((a, b) => rank(a) - rank(b) || b.ovr - a.ovr || a.name.localeCompare(b.name, 'en'));
    const keys = rows.map(r => `${abbr}:${r.pos}:${r.name}`);
    if (new Set(keys).size !== keys.length) throw new Error(`${abbr}: two kept men share a position and a name, so the partial list cannot tell them apart`);
    for (const r of rows) if (r.partial) partial.push(`${abbr}:${r.pos}:${r.name}`);
    teams[abbr] = rows;
    kept += rows.length;
  }

  const counts = Object.values(teams).map(r => r.length);
  const lines = [];
  lines.push('// GENERATED by scripts/genNhlFrontOfficeRoster.mjs from scripts/data/nhlRosters2026.json.');
  lines.push('// Do not hand-edit: change the record or the rules and rerun the generator.');
  lines.push('//');
  lines.push(`// Round 830. The real NHL rosters a new NHL Front Office league starts from: ${Object.keys(teams).length} clubs, ${kept} men,`);
  lines.push(`// ${Math.min(...counts)} to ${Math.max(...counts)} a club. Each club's roster is the one the NHL's own API published on ${rec.meta.read}`);
  lines.push('// (api-web.nhle.com/v1/roster/{TEAM}/current), while some clubs still carried camp rosters. A club at or under the');
  lines.push(`// ${ACTIVE_LIMIT} man active limit keeps every man on it and is never padded; a club still carrying a camp`);
  lines.push('// roster keeps the 2 goalies, 12 forwards and 6 defensemen with the most 2025-26 NHL games, then the 3');
  lines.push(`// skaters left with the most. The ${leftOut.length} men that leaves out are listed with the reason in`);
  lines.push('// scripts/data/nhlRosters2026LeftOut.json.');
  lines.push('//');
  lines.push(`// Second source, a spot check against ESPN's team rosters on ${spot.read}. The sample is fixed in advance:`);
  const words = SPOT_CHECK_RULE.split(' ');
  let row = '//  ';
  for (const w of words) {
    if (row.length + w.length + 1 > 110) { lines.push(row); row = '//  '; }
    row += ` ${w}`;
  }
  lines.push(`${row}.`);
  lines.push(`// ${spot.checked - spot.mismatches} of ${spot.checked} agree on club, position group and birth date.`);
  lines.push('//');
  lines.push('// Ratings come from real 2025-26 regular season numbers (api.nhle.com stats), one rule per position,');
  lines.push('// the same rule as the Aug 5 2026 bake in nhlFoPlayers.ts:');
  lines.push('//   forwards: points per game percentile among forwards with 30+ games, mapped to 66..97;');
  lines.push('//   defensemen: the same among defensemen with 30+ games, mapped to 66..95;');
  lines.push('//   goalies: 60 percent save percentage percentile plus 40 percent wins percentile among goalies with');
  lines.push('//   15+ games, mapped to 66..95.');
  lines.push(`// A man under his threshold or with no 2025-26 NHL season gets ${PARTIAL_RATING} and is listed in NHL_FO_PARTIAL: that`);
  lines.push('// number is a stand in, not a rating his stats produced. Ages are whole years on the day read, from');
  lines.push('// NHL-listed birth dates. Every contract and salary the game attaches to these men is fictional.');
  lines.push('');
  lines.push("import type { NhlFoSeed } from './nhlFoPlayers';");
  lines.push('');
  lines.push('/** The day the rosters were read from the NHL. */');
  lines.push(`export const NHL_FO_FULL_READ = '${rec.meta.read}';`);
  lines.push('');
  lines.push('export const NHL_FO_FULL_ROSTERS: Record<string, NhlFoSeed[]> = {');
  for (const [abbr, rows] of Object.entries(teams)) {
    lines.push(`  ${abbr}: [`);
    for (const r of rows) lines.push(`    { name: ${quote(r.name)}, pos: '${r.pos}', age: ${r.age}, ovr: ${r.ovr} },`);
    lines.push('  ],');
  }
  lines.push('};');
  lines.push('');
  lines.push('/** Thin data, the CM_PARTIAL shape: every man whose rating is the stand in, as CLUB:POS:Name. */');
  lines.push('export const NHL_FO_PARTIAL: string[] = [');
  for (const k of partial) lines.push(`  ${quote(k)},`);
  lines.push('];');
  const ts = `${lines.join('\n')}\n`;

  const left = {
    read: rec.meta.read,
    what: 'Every man on a club roster the NHL published on the day read who is not in NHL Front Office, and why. Written by scripts/genNhlFrontOfficeRoster.mjs.',
    count: leftOut.length,
    leftOut,
  };
  return { ts, leftJson: `${JSON.stringify(left, null, 1)}\n`, teams, partial, leftOut, kept };
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const rec = JSON.parse(fs.readFileSync(RECORD, 'utf8'));
  const out = bake(rec);
  const norm = s => s.replace(/\r\n/g, '\n');
  if (process.argv.includes('--check')) {
    const stale = [[DATA, out.ts], [LEFT_OUT, out.leftJson]].filter(([f, want]) => !fs.existsSync(f) || norm(fs.readFileSync(f, 'utf8')) !== want);
    if (stale.length) {
      console.error(`genNhlFrontOfficeRoster --check: ${stale.map(([f]) => path.relative(ROOT, f)).join(' and ')} differ from a fresh bake of the record`);
      process.exit(1);
    }
    console.log(`genNhlFrontOfficeRoster --check: both files are the bake of the ${rec.meta.read} record (${out.kept} men, ${out.partial.length} partial, ${out.leftOut.length} left out)`);
  } else {
    fs.writeFileSync(DATA, out.ts);
    fs.writeFileSync(LEFT_OUT, out.leftJson);
    console.log(`wrote ${path.relative(ROOT, DATA)} (${out.kept} men on ${Object.keys(out.teams).length} clubs, ${out.partial.length} partial) and ${path.relative(ROOT, LEFT_OUT)} (${out.leftOut.length} left out)`);
  }
}
