/* Round 401: every evidenced NFL grid answer is a name the search box can offer.

   The NFL grid's autocomplete searches nflfastr_rosters, which starts in
   2002, with validateOnly set, so a name the table does not carry cannot be
   typed at all. Round 350's evidence ledger (scripts/data/nflGridPool350.json)
   names 687 real players across the 42 newest boards, and a Jim Kelly or an
   O.J. Simpson is exactly the answer a board about the Bills is built around.
   PlayerAutocomplete has carried a localNames prop for this since Round 84
   (Missing XI and NFL Career use it); the NFL grid never did.

   This generator derives src/data/nflGridLocalNames.ts from the ledger: every
   distinct example name, sorted, nothing typed by hand. The committed file is
   held to this derivation by scripts/simGridPuzzlePool.mjs section 5, so a
   ledger edit that forgets to regenerate goes red rather than quietly leaving
   a new answer untypeable.

   Run: node scripts/genNflGridLocalNames.mjs
        node scripts/genNflGridLocalNames.mjs --check   (print, write nothing)
*/
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEDGER = path.join(ROOT, 'scripts', 'data', 'nflGridPool350.json');
const OUT = path.join(ROOT, 'src', 'data', 'nflGridLocalNames.ts');

export function namesFromLedger(ledgerPath = LEDGER) {
  const ledger = JSON.parse(fs.readFileSync(ledgerPath, 'utf8'));
  const names = new Set();
  for (const puzzle of ledger.accepted ?? []) {
    for (const cell of puzzle.evidence ?? []) {
      for (const ex of cell.examples ?? []) {
        const name = typeof ex === 'string' ? ex : ex.player;
        if (typeof name === 'string' && name.trim()) names.add(name.trim());
      }
    }
  }
  return [...names].sort((a, b) => a.localeCompare(b, 'en'));
}

export function renderModule(names) {
  const body = names.map(n => `  ${JSON.stringify(n)},`).join('\n');
  return `/* GENERATED by scripts/genNflGridLocalNames.mjs from scripts/data/nflGridPool350.json.
   Do not edit by hand: re-run the generator after a ledger change.
   Round 401: the ${names.length} real players the Round 350 evidence names, offered by
   the NFL grid's search box beside the roster table search, so a legend the
   2002 onward roster table does not carry (Jim Kelly, O.J. Simpson) can be
   typed for the board that was built around him. Offering a name is not
   accepting it: every guess still goes through football-grid-validate. */
export const NFL_GRID_LOCAL_NAMES: string[] = [
${body}
];
`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const names = namesFromLedger();
  const text = renderModule(names);
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8').split('\r\n').join('\n') : '';
    console.log(current === text ? `up to date: ${names.length} names` : `STALE: the committed file differs from the derivation (${names.length} names)`);
    process.exit(current === text ? 0 : 1);
  }
  fs.writeFileSync(OUT, text);
  console.log(`wrote ${path.relative(ROOT, OUT)} with ${names.length} names`);
}
