/**
 * Round 372: bake the Record Books tables into a committed file, so a crawler
 * actually receives them.
 *
 * THE PROBLEM. /records served 13 section headings, 25 lines of intro prose and
 * ZERO champion names to a crawler. No Yankees, no Patriots, no Celtics, no
 * Lakers. It is a reference page whose entire value is its champion tables, and
 * search engines saw none of it.
 *
 * IT WAS NOT A PRERENDER BUG, and that distinction is the whole reason this
 * script exists rather than a patch to the prerenderer. prerender.mjs:331
 * leaves every Supabase request hanging on purpose: "a fulfilled request bakes
 * today's data into a file that outlives today". That rule is correct and it
 * stays. The page fetched its sections at runtime and rendered a spinner until
 * they arrived, so a spinner is what got captured.
 *
 * THE RESOLUTION IS TO NOTICE WHAT KIND OF DATA THIS IS. Champion tables are
 * not today's data. They are historical facts that move about once a year, so
 * they belong in a committed file that a build regenerates, exactly like
 * src/data/gridArchive.json. Then the page renders them synchronously, the
 * prerenderer captures them, and rule 1 is never bent.
 *
 * IT CALLS THE PAGE'S OWN FETCHERS. Each section in RECORD_SECTIONS carries its
 * own fetch(), including the column mapping and the server side filters (the
 * soccer section narrows 1,631 rows to one league). This script invokes those
 * rather than reimplementing them in SQL, so there is exactly one definition of
 * what each section contains. Reimplementing them here would be the same
 * duplicate-rule drift this repo has paid for repeatedly.
 *
 * A WELCOME SIDE EFFECT, given the Round 370 Disk IO incident: /records issued
 * 13 Supabase queries on every single visit. Rendering from a committed file
 * removes all 13.
 *
 * Run: node scripts/genRecordBooks.mjs   (needs the database)
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = path.join(os.tmpdir(), 'recordBooksEntry.mjs');
const BUNDLE = path.join(os.tmpdir(), 'recordBooks.bundle.mjs');
const rel = r => path.join(ROOT, r).replaceAll('\\', '/');

/* Dynamic import so the localStorage shim runs before the Supabase client reads
   it at module scope. A static import is hoisted above the assignment. */
fs.writeFileSync(ENTRY, [
  'globalThis.localStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {} };',
  `const m = await import('${rel('src/lib/records.ts')}');`,
  'export const RECORD_SECTIONS = m.RECORD_SECTIONS;',
].join('\n'));
execSync(`"${path.join(ROOT, 'node_modules', '.bin', 'esbuild')}" "${ENTRY}" --bundle --format=esm --platform=node --outfile="${BUNDLE}" --log-level=error`);
const { RECORD_SECTIONS } = await import(pathToFileURL(BUNDLE).href);

/* A section that comes back empty is a broken build, not an empty sport. The
   whole point of this file is that the rows are present, so refuse to write a
   file that would ship a page as hollow as the one being fixed. */
const MIN_ROWS = 10;

const sections = {};
let total = 0;
for (const def of RECORD_SECTIONS) {
  let rows = null;
  for (let attempt = 0; attempt <= 2 && !rows; attempt++) {
    if (attempt) await new Promise(r => setTimeout(r, 600 * attempt));
    try { rows = await def.fetch(); } catch { rows = null; }
    if (rows && rows.length === 0) rows = null;
  }
  if (!rows) {
    console.error(`${def.key}: fetched nothing after three attempts, so nothing was written`);
    process.exit(1);
  }
  if (rows.length < MIN_ROWS) {
    console.error(`${def.key}: only ${rows.length} rows, below the floor of ${MIN_ROWS}, which means a broken read rather than a short sport`);
    process.exit(1);
  }
  /* Sorted newest first, which is how the page shows them, so the file is
     deterministic rather than however the rows happened to arrive. */
  rows.sort((a, b) => b.year - a.year || String(a.champion).localeCompare(String(b.champion)));
  sections[def.key] = rows;
  total += rows.length;
  console.log(`   ${def.key.padEnd(26)} ${String(rows.length).padStart(5)} rows, ${rows[0].year} back to ${rows[rows.length - 1].year}`);
}

const out = {
  note: "Generated by scripts/genRecordBooks.mjs from the same RECORD_SECTIONS fetchers the page defines, so there is one definition of what each section contains. Committed so the champion tables reach a crawler: the prerenderer leaves Supabase requests hanging on purpose, and a page that fetches its data at runtime is captured as a spinner.",
  sections,
};
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'recordBooks.json'), JSON.stringify(out, null, 1) + '\n');
console.log(`wrote ${Object.keys(sections).length} sections, ${total} rows to src/data/recordBooks.json`);
