/**
 * Round 148: the sitemap generator, built the day Search Console showed
 * "Page with redirect, validation failed" (owner screenshots, 2026-08-17).
 * The r54 sitemap was generated once and drifted two ways at once: six
 * retired routes that now 301 to other pages were still being submitted
 * (/world-cup, /football-draft, /guess-soccer-club, /guess-transfer-value,
 * /perfect-lineup, /grade-transfer), and games added after r54 (Stadium
 * Tycoon) were missing. Both drift classes end here:
 *
 *   node scripts/genSitemap.mjs        rewrites public/sitemap.xml
 *
 * Sources of truth, no hand lists of games anywhere:
 *  - src/App.tsx: a <Route> whose element is <Navigate ...> is a redirect
 *    and can NEVER be submitted; everything else with a literal path is a
 *    real page.
 *  - src/data/gameRegistry.ts: every registered game must be in the map.
 *  - STATIC_PAGES below: the handful of non-game pages, curated.
 *
 * scripts/simSitemap.mjs asserts all of this on every suite run, so the
 * next retired game or new release cannot recreate today's Search Console
 * failure quietly.
 */
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://douknowball.com';

/* Non-game pages, with their crawl hints.
   Round 198: /college joined the list. It is a real hub with its own copy
   and links to every college game, but it was in no menu and no sitemap,
   so nothing on the web pointed at it and nothing ever would. It got a
   link from the home page's College Sports heading in the same round,
   because a sitemap entry with no inbound link is a page Google is
   entitled to ignore. */
const STATIC_PAGES = [
  { p: '/', freq: 'daily', pri: '1.0' },
  { p: '/leaderboard', freq: 'daily', pri: '0.7' },
  { p: '/college', freq: 'weekly', pri: '0.6' },
  { p: '/whats-new', freq: 'weekly', pri: '0.5' },
  { p: '/about', freq: 'yearly', pri: '0.4' },
  { p: '/contact', freq: 'yearly', pri: '0.4' },
  { p: '/privacy', freq: 'yearly', pri: '0.3' },
  { p: '/terms', freq: 'yearly', pri: '0.3' },
];

/* ---- routes from App.tsx ---- */
const app = fs.readFileSync(path.join(ROOT, 'src/App.tsx'), 'utf8');
const redirects = new Set();
const liveRoutes = new Set();
for (const m of app.matchAll(/<Route\s+path="([^"]+)"\s+element={\s*(<Navigate\b)?/g)) {
  const p = m[1];
  if (p.includes(':') || p === '*') continue;
  if (m[2]) redirects.add(p); else liveRoutes.add(p);
}
if (!liveRoutes.size || !redirects.size) {
  console.error('FATAL: route parse found nothing, App.tsx shape changed');
  process.exit(1);
}

/* ---- games from the registry (house bundle pattern) ---- */
const ENTRY = '/tmp/sitemapEntry.mjs';
const BUNDLE = '/tmp/sitemap.bundle.mjs';
fs.writeFileSync(ENTRY, `
const reg = await import('${ROOT}/src/data/gameRegistry.ts');
export const paths = (reg.ALL_GAMES ?? reg.CATEGORIES.flatMap(c => c.games)).map(g => g.path);
`);
execSync(`${ROOT}/node_modules/.bin/esbuild ${ENTRY} --bundle --format=esm --platform=node --outfile=${BUNDLE} --log-level=error`, { stdio: 'inherit' });
const { paths: gamePaths } = await import(BUNDLE);

let bad = 0;
for (const p of gamePaths) {
  if (redirects.has(p)) { bad += 1; console.error(`FATAL: registry game ${p} is a redirect route`); }
  if (!liveRoutes.has(p)) { bad += 1; console.error(`FATAL: registry game ${p} has no route in App.tsx`); }
}
if (bad) process.exit(1);

/* Legacy live routes that stay submitted although they left the registry:
 * they are real pages kept for direct links and data continuity. Anything
 * else that is a live route but neither game, static nor listed here is
 * deliberately NOT submitted (retired pages kept only for direct links). */
const LEGACY_LIVE = ['/jeopardy'];
for (const p of LEGACY_LIVE) {
  if (!liveRoutes.has(p)) { console.error(`FATAL: legacy page ${p} lost its route`); process.exit(1); }
}

const today = new Date().toISOString().slice(0, 10);
const row = (p, freq, pri) =>
  /* Round 198: the root is submitted WITH its trailing slash, because that
     is exactly what PageSeo puts in the home page's canonical tag. The two
     disagreed until now (sitemap bare, canonical slashed), which is a
     crawler being told about one URL and pointed at another. */
  `  <url><loc>${SITE}${p === '/' ? '/' : p}</loc><lastmod>${today}</lastmod><changefreq>${freq}</changefreq><priority>${pri}</priority></url>`;

const seen = new Set();
const rows = [];
for (const s of STATIC_PAGES) { seen.add(s.p); rows.push(row(s.p, s.freq, s.pri)); }
for (const p of [...gamePaths, ...LEGACY_LIVE]) {
  if (seen.has(p)) continue;
  seen.add(p);
  rows.push(row(p, 'daily', '0.8'));
}

const out = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/genSitemap.mjs from src/App.tsx routes plus
  src/data/gameRegistry.ts on ${today} (Round 148). Redirect routes are
  excluded mechanically: submitting them is exactly the "Page with
  redirect" Search Console failure this generator was built to end.
  Regenerate with: node scripts/genSitemap.mjs
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${rows.join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(ROOT, 'public/sitemap.xml'), out);
console.log(`sitemap.xml: ${rows.length} URLs (${gamePaths.length} games, ${STATIC_PAGES.length} static, ${LEGACY_LIVE.length} legacy)`);
console.log(`redirect routes excluded: ${[...redirects].filter(p => !p.includes(':')).length}`);
