/* Round 675: writes the g and dp cap rows of public.game_scale_caps.

   docs/design/POINTS-ECONOMY-V2.md sections 4 (conflict 3), 5 (E1, E3b) and
   13 (Round 675). A game on the knowledge line records day points on scale
   dp, worth them as they are (cap 100 for every game). A game whose line is 0
   and whose ceiling every board reaches records its raw result on scale g,
   valued at its engine ceiling. Which scale a game records on is
   public.game_rules' (the door stamps it from there, src/data/pointsFamilies.ts
   decides it); these rows only make sure a cap exists for either choice.

   THE ROWS, one period each, open from -infinity to infinity (tagged rows
   exist only from the new client, so no earlier row can meet them):
     dp  every completion key in src/data/pointsFamilies.ts, at 100;
     g   every key scripts/lib/scoreCeilingTable.mjs gives an engine ceiling,
         at that ceiling, read off the code that records the score. These
         replace what Round 646's migration wrote into game_score_caps (646
         is deleted in this round), and scripts/simCapsAreCeilings.mjs
         sections 4 and 6 hold them to the engines and to the live table.

   NOT APPLIED UNTIL E3b (Round 691, the day before the release): E3b loads
   this file from the frozen release tree. Until then it is checked, never
   applied: scripts/simEconomyMigrations.mjs section 11 loads it over E1 in
   PGlite (no overlap, the foreign keys hold, a tagged row is valued at its
   cap), and scripts/simOneWorth.mjs holds every paying key's scale to it.

   Run: node scripts/genScaleCaps.mjs          writes scripts/data/scaleCapsSeed.sql
        node scripts/genScaleCaps.mjs --check  writes nothing; prints the md5 and
                                               exits 1 when the committed file
                                               is not what the tree generates */
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { writeFileAtomic } from './lib/atomicWrite.mjs';
import { loadFamilies, familyRows } from './lib/gameRulesSeed.mjs';
import { CEILINGS, bundleCeilingModules, resolveCeiling } from './lib/scoreCeilingTable.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const SCALE_SEED_FILE = 'scripts/data/scaleCapsSeed.sql';
const CHECK = process.argv.includes('--check');
const md5 = text => crypto.createHash('md5').update(text.replace(/\r\n/g, '\n')).digest('hex');
const q = s => `'${String(s).replace(/'/g, "''")}'`;

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'scaleCaps-'));
let code = 0;
try {
  const families = familyRows(await loadFamilies(ROOT, tmp)).map(([key]) => key);
  const { CAPS } = await import(pathToFileURL(path.join(ROOT, 'scripts', 'data', 'gameScoreCaps.mjs')).href);
  const capGames = new Set(CAPS.map(([game]) => game));
  const { mods } = await bundleCeilingModules(ROOT, tmp);
  const problems = [];
  const keys = new Set(families);
  if (keys.size !== families.length) problems.push('a key is filed twice in the family table');
  const rows = [];
  for (const key of [...keys].sort()) {
    if (!capGames.has(key)) problems.push(`${key} has no row in game_score_caps (scripts/data/gameScoreCaps.mjs), so its cap row would break the foreign key`);
    rows.push([key, 'dp', 100, 'day points, 0 to 100']);
  }
  for (const [key, entry] of Object.entries(CEILINGS).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
    if (!keys.has(key)) problems.push(`${key} has an engine ceiling but no rule in src/data/pointsFamilies.ts`);
    const r = resolveCeiling(mods, entry);
    if (r.error) { problems.push(`${key}: ${r.error}`); continue; }
    if (!Number.isInteger(r.value) || r.value < 1) { problems.push(`${key}: ${entry[0]} ${entry[1]} gives ${r.value}, not a positive whole number`); continue; }
    rows.push([key, 'g', r.value, `engine ceiling: ${entry[1]}, ${entry[0]}`]);
  }
  if (problems.length) throw new Error(`the tree cannot generate the scale caps:\n  ${problems.join('\n  ')}`);
  rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0));
  const g = rows.filter(r => r[1] === 'g').length;
  const seed = [
    '-- public.game_scale_caps, the g and dp rows, generated by scripts/genScaleCaps.mjs from',
    '-- src/data/pointsFamilies.ts and scripts/lib/scoreCeilingTable.mjs. Never edit by hand.',
    '-- Applied by economy step E3b (Round 691), never before it.',
    `-- ${rows.length} rows: ${g} g at their engine ceilings, ${rows.length - g} dp at 100.`,
    'insert into public.game_scale_caps (game, scale, valid_from, valid_until, cap, note) values',
    ...rows.map(([key, scale, cap, note], i) => `  (${q(key)}, ${q(scale)}, '-infinity', 'infinity', ${cap}, ${q(note)})${i === rows.length - 1 ? ';' : ','}`),
    '',
  ].join('\n');
  const target = path.join(ROOT, SCALE_SEED_FILE);
  if (CHECK) {
    const committed = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : null;
    console.log(`md5 ${md5(seed)}`);
    if (committed === seed) console.log(`genScaleCaps --check: ${SCALE_SEED_FILE} is what the tree generates (${g} g rows, ${rows.length - g} dp rows).`);
    else {
      const have = committed === null ? [] : committed.split('\n');
      const differ = seed.split('\n').filter(l => !have.includes(l)).concat(have.filter(l => !seed.split('\n').includes(l)));
      console.error(`genScaleCaps --check: ${committed === null ? `${SCALE_SEED_FILE} is missing` : `${SCALE_SEED_FILE} is stale, ${differ.length} line(s) differ, first: ${differ[0]}`}. Run node scripts/genScaleCaps.mjs and commit it.`);
      code = 1;
    }
  } else {
    writeFileAtomic(target, seed);
    console.log(`genScaleCaps: wrote ${SCALE_SEED_FILE}, ${g} g rows and ${rows.length - g} dp rows, md5 ${md5(seed)}.`);
  }
} catch (e) {
  console.error(`genScaleCaps: ${e.message ?? e}`);
  code = 1;
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
process.exit(code);
