/**
 * Round 700: a game page loads its own search title, not all 127 of them.
 *
 * Round 642 moved every game's search title and description into
 * src/data/seoMeta.ts and loaded it as one lazy chunk, which kept the text out
 * of the entry chunk but still sent all 127 entries (9.2K gzipped) to every
 * game page to read one of them. sweepWeight named that as the next cut.
 *
 * This script splits the one source into small parts under
 * src/data/seoMetaParts/, and PageSeo loads only the part that holds its page.
 * src/data/seoMeta.ts stays the only place anyone edits: the parts are written
 * from it and never by hand.
 *
 * WHY PARTS BY A HASH OF THE PATH, AND NOT ONE FILE PER GAME OR PER SPORT.
 * Measured on the Round 700 baseline, gzipped:
 *   one file per game    each page fetches 0.2K, but the table of 127 hashed
 *                        chunk names that picks the file lives in the entry
 *                        chunk, about 2.2K, and the home page pays it too
 *   one file per sport   Soccer holds 33 games, so every soccer page (Club
 *                        Manager and Soccer Career among them) still fetches
 *                        3.1K
 *   32 parts by hash     the entry carries 32 short loaders, about 0.35K, and
 *                        a game page fetches a part of 1 to 9 entries, 0.2K to
 *                        1.0K
 * The hash is FNV-1a over the path, so a part depends on nothing but the path:
 * adding a game or reordering the registry moves no other game, and changes
 * one part file.
 *
 *   node scripts/genSeoMetaParts.mjs          rewrite whatever has fallen behind
 *   node scripts/genSeoMetaParts.mjs --check  write nothing, exit 1 if anything has
 *
 * Every vite build runs it too (the dukb-seo-meta-parts plugin in
 * vite.config.ts), so a build always ships parts made from the source it was
 * given. simSeoTitles section 6 fences the committed copy against the source
 * and checks that the page's own lookup finds every entry in the part it loads.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const PART_COUNT = 32;
export const PART_DIR = 'src/data/seoMetaParts';
const SOURCE = 'src/data/seoMeta.ts';

/* The one copy of the part function. It is written into the generated index
   as the page's lookup AND run here to place the entries, so the two cannot
   disagree about where a path lives. */
const PART_BODY = [
  '  let h = 0x811c9dc5;',
  '  for (let i = 0; i < path.length; i += 1) {',
  '    h ^= path.charCodeAt(i);',
  '    h = Math.imul(h, 0x01000193);',
  '  }',
  '  return (h >>> 0) % SEO_META_PART_COUNT;',
].join('\n');
// eslint-disable-next-line no-new-func
const partFn = new Function('path', 'SEO_META_PART_COUNT', PART_BODY);
export const partOf = p => partFn(p, PART_COUNT);

const partName = i => `seoMetaPart${String(i).padStart(2, '0')}`;
const HEADER = [
  '/* GENERATED by scripts/genSeoMetaParts.mjs from src/data/seoMeta.ts. Do not',
  '   edit this folder: edit src/data/seoMeta.ts. Every vite build rewrites what',
  '   has fallen behind, and simSeoTitles section 6 fails if the committed copy',
  '   is not what the source makes. */',
].join('\n');

/** src/data/seoMeta.ts, evaluated: the TypeScript stripped by esbuild, then imported. */
async function readSource(root) {
  const { transform } = await import('esbuild');
  const ts = fs.readFileSync(path.join(root, SOURCE), 'utf8');
  const { code } = await transform(ts, { loader: 'ts', format: 'esm' });
  const mod = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
  if (!mod.SEO_META || typeof mod.SEO_META !== 'object') throw new Error(`${SOURCE} exports no SEO_META`);
  return mod.SEO_META;
}

function partFile(i, entries) {
  const rows = entries.map(([p, e]) => [
    `  ${JSON.stringify(p)}: {`,
    `    title: ${JSON.stringify(e.title)},`,
    `    description: ${JSON.stringify(e.description)},`,
    '  },',
  ].join('\n'));
  return [
    HEADER,
    `/* Part ${i} of ${PART_COUNT}: ${entries.length} ${entries.length === 1 ? 'entry' : 'entries'}. */`,
    "import type { SeoMeta } from '../seoMeta';",
    '',
    'export const SEO_META_PART: Record<string, SeoMeta> = {',
    ...rows,
    '};',
    '',
  ].join('\n');
}

function indexFile() {
  const loaders = Array.from({ length: PART_COUNT }, (_, i) => `  () => import('./${partName(i)}'),`);
  return [
    HEADER,
    "import type { SeoMeta } from '../seoMeta';",
    '',
    `export const SEO_META_PART_COUNT = ${PART_COUNT};`,
    '',
    '/** Which part holds a path\'s entry: FNV-1a over the path, modulo the count. */',
    'export const seoMetaPart = (path: string): number => {',
    PART_BODY,
    '};',
    '',
    'export interface SeoMetaPartModule {',
    '  SEO_META_PART: Record<string, SeoMeta>;',
    '}',
    '',
    '/** One loader per part, so each part is its own chunk and a page fetches one. */',
    'export const SEO_META_PARTS: ReadonlyArray<() => Promise<SeoMetaPartModule>> = [',
    ...loaders,
    '];',
    '',
  ].join('\n');
}

/** Every file the source makes, by name inside PART_DIR, with LF line endings. */
export async function seoMetaPartFiles(root) {
  const meta = await readSource(root);
  const parts = Array.from({ length: PART_COUNT }, () => []);
  for (const [p, e] of Object.entries(meta)) parts[partOf(p)].push([p, e]);
  const files = new Map();
  parts.forEach((entries, i) => files.set(`${partName(i)}.ts`, partFile(i, entries)));
  files.set('index.ts', indexFile());
  return files;
}

/**
 * Compare the folder with what the source makes and, unless check is set,
 * bring it up to date. Returns one line per file that differed (empty when in
 * step). Line endings are ignored, so a CRLF checkout is in step.
 */
export async function writeSeoMetaParts(root, { check = false } = {}) {
  const files = await seoMetaPartFiles(root);
  const dir = path.join(root, PART_DIR);
  const lf = s => s.replace(/\r\n/g, '\n');
  const changed = [];
  const stale = [];
  for (const [name, text] of files) {
    const file = path.join(dir, name);
    const cur = fs.existsSync(file) ? lf(fs.readFileSync(file, 'utf8')) : null;
    if (cur === text) continue;
    changed.push(`${PART_DIR}/${name} ${cur === null ? 'is missing' : 'is not what the source makes'}`);
    stale.push(name);
  }
  const stray = fs.existsSync(dir) ? fs.readdirSync(dir).filter(n => !files.has(n)) : [];
  for (const n of stray) changed.push(`${PART_DIR}/${n} is not a file the source makes`);
  if (!check && changed.length) {
    fs.mkdirSync(dir, { recursive: true });
    for (const name of stale) fs.writeFileSync(path.join(dir, name), files.get(name));
    for (const n of stray) fs.rmSync(path.join(dir, n), { force: true });
  }
  return changed;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const check = process.argv.includes('--check');
  const changed = await writeSeoMetaParts(root, { check });
  for (const line of changed) console.log(`  ${check ? 'DRIFT' : 'wrote'}: ${line}`);
  if (check && changed.length) {
    console.error(`genSeoMetaParts: ${changed.length} file(s) in ${PART_DIR} are not what ${SOURCE} makes; run node scripts/genSeoMetaParts.mjs`);
    process.exit(1);
  }
  console.log(`genSeoMetaParts: ${PART_DIR} ${changed.length ? `brought up to date (${changed.length} file(s))` : 'already matches'} ${SOURCE}, ${PART_COUNT} parts.`);
}
