/**
 * Round 294: write the migration that puts a true minimum and a true hint on
 * every Transfer Path puzzle.
 *
 * Input is the pull taken through the database console on 2026-08-26 and
 * kept in scripts/data/transferPathPull/ (the sandbox cannot reach Supabase
 * itself): careers.txt is every career_players row with its career_seasons
 * compacted to spells, puzzles.txt is every transfer_path_puzzles row as
 * id|a|b|old_min. Output is supabase/migrations/20260826_transfer_path_hints_temporal.sql,
 * one UPDATE per puzzle, keyed by puzzle_id, applied through the console.
 *
 * Re-run after any change to the career tables, then apply the new file and
 * run simTransferPathHints against the live tables.
 *
 * Run: node scripts/genTransferPathHints.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGraph, deriveHint, expandCompactCareers, hintProblems } from './lib/transferPathHints.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PULL = path.join(ROOT, 'scripts/data/transferPathPull');
const OUT = path.join(ROOT, 'supabase/migrations/20260826_transfer_path_hints_temporal.sql');

const players = expandCompactCareers(fs.readFileSync(path.join(PULL, 'careers.txt'), 'utf8'));
const puzzles = fs.readFileSync(path.join(PULL, 'puzzles.txt'), 'utf8').split('\n').filter(Boolean).map(l => {
  const [id, a, b, min] = l.split('|');
  return { id, a, b, oldMin: Number(min) };
});
const graph = buildGraph(players);
console.log(`${players.length} players, ${graph.names.length} in the graph, ${puzzles.length} puzzles`);

const q = s => `'${String(s).replace(/'/g, "''")}'`;
/* Corrections to the career tables that the pull in careers.txt already
   carries, so the hints below are derived from the corrected graph. Each one
   names its source. Add here, patch careers.txt the same way, re-run. */
const CORRECTIONS = [
  {
    why: 'Alisson joined Roma in July 2016 (from Internacional); the row named "Alisson" carried Roma seasons from 2014, which put him in the same dressing room as Ashley Cole. The row named "Alisson Becker" was already right. The duplicate name itself is left alone because the daily picks in Career Ladder and the Career game index the pool.',
    sql: "delete from public.career_seasons s using public.career_players p where p.id = s.player_id and p.player_name = 'Alisson' and s.club = 'Roma' and s.season in ('2014-2015', '2015-2016');",
  },
];
const lines = [
  '-- Round 294: every Transfer Path minimum and hint re-derived under the game\'s own rule',
  '-- (same club, same season). Generated by scripts/genTransferPathHints.mjs from the',
  '-- 2026-08-26 pull in scripts/data/transferPathPull/. Do not edit by hand; re-run the generator.',
  'begin;',
  ...CORRECTIONS.flatMap(c => [`-- ${c.why}`, c.sql]),
];
let unreachable = 0, minChanged = 0, byMin = {};
for (const p of puzzles) {
  const d = deriveHint(graph, p.a, p.b);
  if (!d) { unreachable += 1; console.error(`  UNREACHABLE: ${p.id} ${p.a} -> ${p.b}`); continue; }
  const problems = hintProblems(graph, p.a, p.b, d.minSteps, d.hint);
  if (problems.length) { console.error(`  GENERATOR CONTRADICTS ITS OWN FENCE on ${p.id}: ${problems.join('; ')}`); process.exit(1); }
  if (/[\u2013\u2014]/.test(d.hint)) { console.error(`  long dash in ${p.id}`); process.exit(1); }
  if (d.minSteps !== p.oldMin) minChanged += 1;
  byMin[d.minSteps] = (byMin[d.minSteps] ?? 0) + 1;
  lines.push(`update public.transfer_path_puzzles set min_steps = ${d.minSteps}, hint = ${q(d.hint)} where puzzle_id = ${q(p.id)};`);
}
lines.push('commit;');
if (unreachable) { console.error(`${unreachable} puzzle(s) have no path; the migration was not written`); process.exit(1); }
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`wrote ${path.relative(ROOT, OUT)}: ${puzzles.length} updates, minimum changed on ${minChanged}, by minimum ${JSON.stringify(byMin)}`);
for (const id of ['tp-19', 'tp-20', 'tp-3', 'tpa-29', 'tpa-945']) {
  const p = puzzles.find(x => x.id === id);
  if (p) { const d = deriveHint(graph, p.a, p.b); console.log(`  ${id}: ${p.oldMin} -> ${d.minSteps}, ${d.path.join(' > ')}\n     "${d.hint}"`); }
}

/* The fallback pool the page shows when the table is down is a different,
   smaller graph (src/data/careerPlayers.ts, 151 players), so the fallback
   puzzles get their own derivation from it. Puzzles with no path there are
   dropped from the fallback, never guessed. */
{
  const { build } = await import('esbuild');
  const { pathToFileURL } = await import('node:url');
  const entry = '/tmp/gen-tph-entry.mjs', out = '/tmp/gen-tph-bundle.mjs';
  globalThis.localStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {} };
  fs.writeFileSync(entry, `export { default as fallbackPuzzles } from '${ROOT}/src/data/transferPathPuzzles.ts';\nexport { careerPlayers as fallbackPlayers } from '${ROOT}/src/data/careerPlayers.ts';\n`);
  await build({ entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', outfile: out, logLevel: 'error', alias: { '@': path.join(ROOT, 'src') } });
  const site = await import(pathToFileURL(out).href);
  const fg = buildGraph(site.fallbackPlayers);
  const kept = [], dropped = [];
  for (const p of site.fallbackPuzzles) {
    const d = deriveHint(fg, p.playerA, p.playerB);
    if (!d) { dropped.push(p.id); continue; }
    const problems = hintProblems(fg, p.playerA, p.playerB, d.minSteps, d.hint);
    if (problems.length) { console.error(`  fallback ${p.id}: ${problems.join('; ')}`); process.exit(1); }
    kept.push({ id: p.id, playerA: p.playerA, playerB: p.playerB, minSteps: d.minSteps, oneOptimalPath: d.path, hint: d.hint });
  }
  const js = s => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  const body = kept.map(p => `  {\n    id: ${js(p.id)}, playerA: ${js(p.playerA)}, playerB: ${js(p.playerB)}, minSteps: ${p.minSteps},\n    oneOptimalPath: [${p.oneOptimalPath.map(js).join(', ')}],\n    hint: ${js(p.hint)},\n  },`).join('\n');
  const file = `export interface TransferPathPuzzle {
  id: string;
  playerA: string;
  playerB: string;
  minSteps: number;
  oneOptimalPath?: string[];
  hint: string;
}

/**
 * The fallback pool, served only when transfer_path_puzzles cannot be read.
 * Round 294: every minimum, path and hint below is derived from
 * src/data/careerPlayers.ts (the fallback player pool) under the game's own
 * rule, same club in the same season, by scripts/genTransferPathHints.mjs.
 * GENERATED: do not edit by hand, re-run the generator. The live table is
 * derived the same way from the live career tables and carries its own
 * hints, which differ where the pools differ.
 */
const transferPathPuzzles: TransferPathPuzzle[] = [
${body}
];

export default transferPathPuzzles;
`;
  fs.writeFileSync(path.join(ROOT, 'src/data/transferPathPuzzles.ts'), file);
  console.log(`rewrote src/data/transferPathPuzzles.ts: ${kept.length} fallback puzzles kept${dropped.length ? `, dropped (no path on the fallback pool): ${dropped.join(', ')}` : ''}`);
}
