// Actual built Trophy Cabinet journeys. Run only in remote CI.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { createServer } from 'node:net';
import { spawn, execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';
import pw from './lib/playwrightLoader.mjs';
assert(process.env.CI, 'Native Trophy Cabinet proof runs only in remote CI');
process.env.CAREER_TROPHY_RUNS_IMPORT_ONLY = '1';
const { expectedCampaign } = await import('./simCareerTrophyRuns.mjs');
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), OUT = path.resolve(ROOT, process.env.SHOTS || '.tmp-fx/career-trophy-runs/native');
const INPUT = path.resolve(ROOT, process.env.CAREER_TROPHY_RUNS_ARTIFACTS || '.tmp-fx/career-trophy-runs/outcomes');
const CACHE = path.resolve(ROOT, process.env.FREE_KICK_FONT_CACHE || '.tmp-fx/career-trophy-runs/font-cache');
const KEY = 'soccerCareerSave', NOW = 1791586800000, copy = value => JSON.parse(JSON.stringify(value)), sha = value => createHash('sha256').update(value).digest('hex');
const files = ['src/components/soccer-career/TrophyCabinet.tsx', 'src/pages/SoccerCareer.tsx', 'src/lib/soccerCareerEngine.ts', 'src/lib/soccerSeasonCompetitions.ts', 'scripts/playCareerTrophyRuns.mjs'];
function sourceHashes() { const hashes = {}; for (const file of files) { const bytes = fs.readFileSync(path.join(ROOT, file)); hashes[file] = sha(bytes); } return hashes; }
fs.mkdirSync(OUT, { recursive: true });
const write = (name, value) => fs.writeFileSync(path.join(OUT, `${name}.json`), JSON.stringify(value, null, 2));
const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();
const report = { head: git('rev-parse', 'HEAD'), tree: git('rev-parse', 'HEAD^{tree}'), cases: [], controls: [], checks: 0, failed: 0, forwardedExternalRequests: 0, sourceBefore: sourceHashes() };
const fonts = new Map(JSON.parse(fs.readFileSync(path.join(CACHE, 'manifest.json'), 'utf8')).map(entry => { assert(['https://fonts.googleapis.com', 'https://fonts.gstatic.com'].includes(new URL(entry.url).origin)); const body = fs.readFileSync(path.join(CACHE, entry.file)); assert.equal(sha(body), entry.sha256); return [entry.url, { body, contentType: entry.contentType }]; }));
const fixtures = JSON.parse(fs.readFileSync(path.join(INPUT, 'native-fixtures.json'), 'utf8'));
assert.equal(fixtures.cases.length, 4);
const oracleBuild = await build({ stdin: { contents: "export * as soccer from './src/lib/soccerCareerEngine'; export * as moments from './src/components/soccer-career/careerMoments';", resolveDir: ROOT, loader: 'ts' }, bundle: true, platform: 'browser', format: 'iife', globalName: '__trophyOracle', write: false, jsx: 'automatic', alias: { '@': path.join(ROOT, 'src') }, define: { 'import.meta.env': '{"DEV":false,"PROD":true,"MODE":"production"}' }, loader: { '.css': 'empty', '.svg': 'empty', '.png': 'empty', '.jpg': 'empty', '.webp': 'empty' }, logLevel: 'error' });
const layoutFailures = o => [o.stable < 4 && 'stable-frames', !o.inside && 'viewport', !o.painted && 'painted-center', Number(o.opacity) !== 1 && 'opacity', o.finite !== 0 && 'animations', o.overflow && 'horizontal-overflow', o.controls.some(control => control.points.some(point => !point.painted)) && 'painted-controls'].filter(Boolean);
const restoreFailures = o => [!o.actual.focus && 'focus', o.actual.top !== o.expected.top && 'list-position', o.actual.inline !== o.expected.inline && 'inline-overflow', o.actual.computed !== o.expected.computed && 'computed-overflow', o.actual.y !== o.expected.y && 'page-position'].filter(Boolean);
const campaignFailures = o => [JSON.stringify(o.expected) !== JSON.stringify(o.actual) && 'saved-campaign'].filter(Boolean);
function detector(name, baseline, mutate, predicate, expected) {
  assert.deepEqual(predicate(baseline), []); const faulty = copy(baseline), undo = mutate(faulty); assert.equal(typeof undo, 'function'); assert.notDeepEqual(faulty, baseline);
  const failed = predicate(faulty); assert.deepEqual(failed, expected); write(`control-${name}-baseline`, baseline); write(`control-${name}-mutated`, faulty); undo(); assert.deepEqual(faulty, baseline); assert.deepEqual(predicate(faulty), []);
  report.controls.push({ name, changed: true, failed, restored: true, scope: 'Copied actual browser observation, not a served product mutation' }); console.log(`CONTROL FIRED(native ${name}): ${failed.join(', ')}`);
}
const port = await new Promise((resolve, reject) => { const probe = createServer(); probe.once('error', reject); probe.listen(0, '127.0.0.1', () => { const value = probe.address().port; probe.close(error => error ? reject(error) : resolve(value)); }); });
const BASE = `http://127.0.0.1:${port}`, server = spawn(process.execPath, ['scripts/lib/hostLikeServer.mjs', 'dist', String(port)], { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true });
let serverLog = '', browser;
const ready = new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Owned server did not start')), 15000); server.once('error', error => { clearTimeout(timer); reject(error); }); server.once('exit', code => { clearTimeout(timer); reject(new Error(`Owned server exited ${code}: ${serverLog}`)); }); server.stdout.on('data', data => { serverLog += data; if (serverLog.includes('host-like server:')) { clearTimeout(timer); resolve(); } }); server.stderr.on('data', data => { serverLog += data; }); });
try {
  await ready; browser = await pw.chromium.launch({ headless: true });
  for (const profile of [{ width: 320, height: 568, touch: true }, { width: 390, height: 844, touch: true }, { width: 1280, height: 900, touch: false }]) for (const input of fixtures.cases) {
    const id = `${profile.width}-${input.id}`, row = { id, ...profile, case: input.id, checks: [], errors: [], assetErrors: [], intercepted: [], writes: [], layouts: [], reloads: [], readings: [] }; report.cases.push(row);
    const check = (ok, label) => { report.checks++; if (!ok) report.failed++; row.checks.push({ ok: !!ok, label }); console.log(`${ok ? 'ok  ' : 'FAIL'} ${id}: ${label}`); assert(ok, `${id}: ${label}`); };
    // Other winning rows are explicit held display inputs without invented match details.
    const fixture = copy(fixtures.carrier), selected = copy(input.row), titleField = input.category === 'ucl' ? 'championsLeague' : 'clubCupTitle';
    fixture.seasons = Array.from({ length: 12 }, (_, i) => ({ ...copy(selected), year: selected.year + 9 - i, [titleField]: input.category === 'ucl' ? true : selected.clubCupTitle, clubCupRun: undefined }));
    fixture.seasons[9] = selected; fixture.seasons.sort((a, b) => a.year - b.year); fixture.phase = 'playing'; fixture.retired = false; fixture.pendingSummary = null; fixture.pendingBallonDor = null; fixture.pendingEvents = []; fixture.pendingNews = []; fixture.lastUCLResult = null; fixture.currentClub = fixture.seasons.at(-1).club; fixture.currentClubCountry = fixture.seasons.at(-1).clubCountry; fixture.currentClubTier = fixture.seasons.at(-1).clubTier;
    write(`${id}-fixture`, { simulation: input.simulation, selectedSourceSeed: input.seed, note: 'The 11 other trophy rows are explicitly held fictional navigation inputs with no match details.', fixture });
    const context = await browser.newContext({ viewport: { width: profile.width, height: profile.height }, hasTouch: profile.touch, isMobile: profile.touch, colorScheme: 'dark', reducedMotion: 'reduce', serviceWorkers: 'block', storageState: { cookies: [], origins: [{ origin: BASE, localStorage: [{ name: KEY, value: JSON.stringify(fixture) }, { name: 'cookie-consent', value: 'essential' }, { name: 'dukb-theme', value: 'dark' }, { name: 'dukb-guest-handle', value: 'SteadyVolley-18' }] }] } });
    const oracleContext = await browser.newContext(), oracle = await oracleContext.newPage();
    const clock = now => { const OldDate = Date; window.Date = class extends OldDate { constructor(...args) { super(...(args.length ? args : [now])); } static now() { return now; } }; };
    await context.addInitScript(clock, NOW); await oracle.addInitScript(clock, NOW);
    await context.addInitScript(() => { const old = Math.random; window.__trophyReadDraws = []; Math.random = () => { const value = old(); window.__trophyReadDraws.push(value); return value; }; });
    await context.route('**/*', route => {
      const request = route.request(), url = new URL(request.url()); if (url.origin === BASE) { assert(['GET', 'HEAD'].includes(request.method())); return route.continue(); }
      row.intercepted.push({ method: request.method(), origin: url.origin, path: url.pathname, blocked: true }); if (!['GET', 'HEAD', 'OPTIONS'].includes(request.method())) row.writes.push({ method: request.method(), path: url.pathname, blocked: true });
      if (request.method() === 'GET' && fonts.has(url.href)) return route.fulfill({ status: 200, ...fonts.get(url.href) });
      if (['fonts.googleapis.com', 'fonts.gstatic.com'].includes(url.hostname)) { row.assetErrors.push(`Uncached font ${url.href}`); return route.abort(); }
      if (request.resourceType() === 'image') return route.fulfill({ status: 200, contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="12"/>' });
      return route.fulfill({ status: 200, contentType: request.resourceType() === 'stylesheet' ? 'text/css' : 'application/json', body: request.resourceType() === 'stylesheet' ? '' : '[]' });
    }); await context.routeWebSocket('**/*', socket => socket.close());
    const page = await context.newPage(); page.setDefaultTimeout(15000); page.on('pageerror', error => row.errors.push(String(error))); page.on('requestfailed', request => { if (request.url().startsWith(BASE)) row.assetErrors.push(`${request.url()}: ${request.failure()?.errorText}`); }); page.on('response', response => { if (response.url().startsWith(BASE) && response.status() >= 400) row.assetErrors.push(`${response.url()}: ${response.status()}`); });
    const bytes = () => page.evaluate(key => localStorage.getItem(key), KEY), body = () => page.evaluate(() => ({ inline: document.body.style.overflow, computed: getComputedStyle(document.body).overflow, y: scrollY }));
    const activate = async button => { await button.scrollIntoViewIfNeeded(); await button.focus(); if (profile.touch) await button.tap(); else await button.press('Enter'); };
    let canonical, canonicalBytes, readDraws, observedCampaign, observedRestore, observedLayout;
    const unchanged = async name => { const actual = await bytes(), draws = await page.evaluate(() => window.__trophyReadDraws); row.readings.push({ name, expectedSha256: sha(canonicalBytes), actualSha256: sha(actual), bytes: Buffer.byteLength(actual), drawCount: draws.length - readDraws.length }); check(actual === canonicalBytes, `${name}: every complete saved byte is held`); check(JSON.stringify(draws) === JSON.stringify(readDraws), `${name}: reading draws no global random values`); };
    const capture = async (target, name) => {
      await page.bringToFront(); await page.waitForFunction(() => !document.querySelector('[data-sonner-toast]'), undefined, { timeout: 10000 });
      const layout = await target.evaluate(async element => {
        let previous = '', stable = 0, last; const started = performance.now();
        while (performance.now() - started < 2500) {
          await new Promise(resolve => requestAnimationFrame(resolve)); const r = element.getBoundingClientRect(), style = getComputedStyle(element), center = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2);
          const controls = [...element.querySelectorAll('button')].flatMap(control => { const b = control.getBoundingClientRect(), css = getComputedStyle(control), clip = control.closest('[data-trophy-scroll]')?.getBoundingClientRect(); if (!control.getClientRects().length || css.visibility === 'hidden' || b.y < 0 || b.bottom > innerHeight + 1 || (clip && (b.y < clip.y || b.bottom > clip.bottom))) return []; return [{ label: control.getAttribute('aria-label') || control.innerText, width: b.width, height: b.height, points: [[.5,.5],[.25,.25],[.75,.25],[.25,.75],[.75,.75]].map(([x,y]) => { const hit = document.elementFromPoint(b.x + b.width * x, b.y + b.height * y); return { painted: !!hit && control.contains(hit) }; }) }]; });
          last = { x: r.x, y: r.y, width: r.width, height: r.height, viewport: [innerWidth, innerHeight], opacity: style.opacity, inside: r.width > 0 && r.height > 0 && r.x >= 0 && r.right <= innerWidth + 1 && r.y >= 0 && r.bottom <= innerHeight + 1, painted: !!center && element.contains(center), finite: document.getAnimations().filter(a => a.playState === 'running' && a.effect?.getTiming().iterations !== Infinity).length, overflow: document.documentElement.scrollWidth > innerWidth + 1, controls };
          const signature = JSON.stringify(last); stable = signature === previous ? stable + 1 : 1; previous = signature; if (stable >= 4 && last.inside && last.painted && Number(last.opacity) === 1 && last.finite === 0 && !last.overflow && controls.every(control => control.points.every(point => point.painted))) break;
        } return { ...last, stable };
      }); row.layouts.push({ name, ...layout }); write(`${id}-${name}-layout`, layout); check(layoutFailures(layout).length === 0, `${name}: painted and stable for four frames without overflow or finite animation`); check(layout.controls.length > 0 && layout.controls.every(control => control.width >= 44 && control.height >= 44), `${name}: every visible cabinet button has a 44 pixel target`); await page.screenshot({ path: path.join(OUT, `${id}-${name}.png`) }); return layout;
    };
    const loaded = async () => { await page.getByRole('button', { name: 'How to play', exact: true }).waitFor({ timeout: 45000 }); await page.locator(`[data-trophy-category="${input.category}"]`).waitFor(); await page.evaluate(() => document.fonts.ready); };
    const reload = async name => { const before = await bytes(); await page.reload({ waitUntil: 'domcontentloaded' }); await loaded(); const after = await bytes(); write(`${id}-${name}-reload-bytes`, { before, after }); row.reloads.push({ name, equal: before === after, beforeSha256: sha(before), afterSha256: sha(after), bytes: Buffer.byteLength(before) }); check(before === after, `${name}: reload keeps every complete raw save byte`); readDraws = await page.evaluate(() => window.__trophyReadDraws); };
    try {
      await oracle.goto('about:blank'); await oracle.addScriptTag({ content: oracleBuild.outputFiles[0].text }); const expectedLoad = await oracle.evaluate(input => { const E = window.__trophyOracle; const state = E.soccer.repairCareer(structuredClone(input)); E.moments.settleLoadedMoments(state); return JSON.parse(JSON.stringify(state)); }, fixture);
      await page.goto(`${BASE}/soccer-career`, { waitUntil: 'domcontentloaded' }); await loaded(); canonicalBytes = await bytes(); canonical = JSON.parse(canonicalBytes); write(`${id}-canonical-loader`, { input: fixture, expected: expectedLoad, actual: canonical }); check(JSON.stringify(canonical) === JSON.stringify(expectedLoad), 'Independent unchanged Chromium loader matches every first-load field and key'); readDraws = await page.evaluate(() => window.__trophyReadDraws); await reload('canonical-second-load');
      const open = page.locator(`[data-trophy-category="${input.category}"]`), selector = `[data-trophy-category="${input.category}"]`; await open.scrollIntoViewIfNeeded(); await open.focus(); const before = await body(); await activate(open);
      const dialog = page.locator('[data-trophy-cabinet] [role="dialog"]'); await dialog.waitFor(); await page.waitForFunction(() => document.querySelector('[data-trophy-cabinet]')?.contains(document.activeElement), undefined, { timeout: 2000 }); check((await body()).computed === 'hidden', 'Opening the real cabinet locks body scrolling');
      const scroll = dialog.locator('[data-trophy-scroll]'), wins = canonical.seasons.filter(season => !!season[titleField]).sort((a,b) => b.year - a.year); check(await dialog.locator('[data-trophy-win]').count() === wins.length && wins.length === 12, 'Actual category lists exactly the saved 12 winning rows');
      const tile = dialog.locator(`[data-trophy-win="${selected.year}"]`); await tile.scrollIntoViewIfNeeded(); await tile.focus(); const listBefore = { top: await scroll.evaluate(element => element.scrollTop), ...await body() }; if (profile.width === 320) check(listBefore.top > 0, 'Short phone actually scrolls the winning-season list');
      await activate(tile); await dialog.locator(`[data-trophy-detail="${selected.year}"]`).waitFor(); check(await dialog.locator('h3').evaluate(element => document.activeElement === element), 'Selected winning season places focus on its heading');
      const expected = expectedCampaign(canonical, canonical.seasons.find(season => season.year === selected.year)), actual = await dialog.locator('[data-trophy-campaign]').evaluate(element => { const get = (root, key) => root.querySelector(`[data-trophy-campaign-${key}]`)?.textContent ?? null; return { missing: !!element.querySelector('[data-trophy-campaign-missing]'), name: get(element,'name'), result: get(element,'result'), goals: get(element,'goals'), format: get(element,'format'), matches: [...element.querySelectorAll('[data-trophy-campaign-match]')].map(row => Object.fromEntries(['round','opponent','score','home','player-goals','note','extra-time'].map(key => [{ 'player-goals':'playerGoals','extra-time':'extraTime' }[key] ?? key,get(row,key)]))) }; });
      if (expected.missing) { check(actual.missing && actual.matches.length === 0 && actual.result === null && actual.goals === null, 'Older trophy save independently shows missing details, no games and no borrowed campaign goals'); observedCampaign = { scope: 'Independent missing/no rows/no campaign result or goals contract', expected: { missing: true, matches: [], result: null, goals: null }, actual }; }
      else { observedCampaign = { expected, actual }; check(campaignFailures(observedCampaign).length === 0, 'Every actual first-stage game and knockout leg shows its exact saved opponent, score, venue, player goals and settlement facts'); }
      write(`${id}-campaign-observation`, observedCampaign); observedLayout = await capture(dialog, 'campaign-top');
      if (actual.matches.length > 0) { await dialog.locator('[data-trophy-campaign-match]').last().scrollIntoViewIfNeeded(); await capture(dialog, 'campaign-last-game'); }
      await unchanged('selected-campaign'); await activate(dialog.locator('[data-trophy-all-wins]')); await dialog.locator('[data-trophy-wins]').waitFor();
      observedRestore = { expected: listBefore, actual: { top: await scroll.evaluate(element => element.scrollTop), ...await body(), focus: await tile.evaluate(element => document.activeElement === element) } }; write(`${id}-list-restoration`, observedRestore); check(restoreFailures(observedRestore).length === 0, 'All wins restores exact selected tile focus, list offset, body lock and page position');
      await activate(dialog.getByRole('button', { name: 'Trophy cabinet help', exact: true })); await dialog.locator('[data-trophy-help]').waitFor(); const rules = await dialog.locator('[data-trophy-help]').innerText(); check(/saved/i.test(rules) && /simulated/i.test(rules) && /aggregate/i.test(rules) && /penalt/i.test(rules), 'Reopenable cabinet help explains saved simulated campaigns and settlement facts'); await capture(dialog, 'rules'); await activate(dialog.locator('[data-trophy-help-back]')); await dialog.locator('[data-trophy-wins]').waitFor(); check(await scroll.evaluate(element => element.scrollTop) === listBefore.top, 'Help also restores the winning list offset');
      for (const key of ['Tab','Tab','Shift+Tab','Shift+Tab']) { await page.keyboard.press(key); check(await dialog.evaluate(element => element.contains(document.activeElement)), `${key}: focus stays in the cabinet`); }
      await activate(dialog.locator('[data-trophy-back="career"]')); await dialog.waitFor({ state:'hidden' }); await page.waitForFunction(({selector,before}) => document.activeElement?.matches(selector) && document.body.style.overflow === before.inline && getComputedStyle(document.body).overflow === before.computed && scrollY === before.y, {selector,before}, { timeout:2000 }).catch(() => {});
      const closed = { expected: { ...before, top: 0 }, actual: { ...await body(), top: 0, focus: await open.evaluate(element => document.activeElement === element) } }; write(`${id}-career-restoration`, closed); check(restoreFailures(closed).length === 0, 'Back restores exact page position, body styles and the actual category opener'); await unchanged('cabinet-back');
      await activate(open); await dialog.waitFor(); await page.waitForFunction(() => document.querySelector('[data-trophy-cabinet] [role="dialog"]')?.contains(document.activeElement),undefined,{timeout:2000}); await page.keyboard.press('Escape'); await dialog.waitFor({state:'hidden'});
      await page.waitForFunction(({selector,before}) => document.activeElement?.matches(selector) && document.body.style.overflow === before.inline && getComputedStyle(document.body).overflow === before.computed && scrollY === before.y,{selector,before},{timeout:2000}).catch(()=>{});
      const escaped={expected:{...before,top:0},actual:{...await body(),top:0,focus:await open.evaluate(element=>document.activeElement===element)}};write(`${id}-escape-restoration`,escaped);check(restoreFailures(escaped).length===0,'Escape restores exact opener focus, body styles and page position'); await unchanged('cabinet-escape'); await reload('completed-read-only');
      await open.scrollIntoViewIfNeeded();await open.focus();const beforeReloaded=await body();await activate(open); await dialog.waitFor(); await activate(dialog.locator(`[data-trophy-win="${selected.year}"]`)); await dialog.locator(`[data-trophy-detail="${selected.year}"]`).waitFor(); const reloaded = await dialog.locator('[data-trophy-campaign]').innerText(); check(expected.missing ? /not kept/.test(reloaded) : reloaded.includes(expected.name) && expected.matches.every(match => reloaded.includes(match.score) && reloaded.includes(match.opponent)), 'Reload retains the same selected saved campaign details'); await page.keyboard.press('Escape'); await dialog.waitFor({state:'hidden'});
      await page.waitForFunction(({selector,before}) => document.activeElement?.matches(selector) && document.body.style.overflow === before.inline && getComputedStyle(document.body).overflow === before.computed && scrollY === before.y,{selector,before:beforeReloaded},{timeout:2000}).catch(()=>{});
      const reloadedEscape={expected:{...beforeReloaded,top:0},actual:{...await body(),top:0,focus:await open.evaluate(element=>document.activeElement===element)}};write(`${id}-reloaded-escape-restoration`,reloadedEscape);check(restoreFailures(reloadedEscape).length===0,'Reloaded detail Escape restores exact opener focus, body styles and page position');await unchanged('reloaded-campaign');
      if (!report.controls.length && !expected.missing) {
        const beforeControls = await bytes(); detector('wrong-score', observedCampaign, o => { const old = o.actual.matches[0].score; o.actual.matches[0].score = '99-99'; return () => { o.actual.matches[0].score = old; }; }, campaignFailures, ['saved-campaign']);
        detector('paint', observedLayout, o => { const old = o.opacity; o.opacity = '0'; return () => { o.opacity = old; }; }, layoutFailures, ['opacity']);
        detector('return', observedRestore, o => { const old = { ...o.actual }; o.actual.focus = false; o.actual.top++; o.actual.inline='incorrect';o.actual.computed='incorrect';o.actual.y++; return () => { o.actual = old; }; }, restoreFailures, ['focus','list-position','inline-overflow','computed-overflow','page-position']); check(await bytes() === beforeControls, 'Copied observation controls leave the actual saved career unchanged');
      }
      check(row.errors.length === 0 && row.assetErrors.length === 0, 'No page or owned asset errors'); check(row.writes.every(write => write.blocked) && report.forwardedExternalRequests === 0, 'All external write attempts are blocked with zero forwarding'); row.ok = true;
    } catch (error) { report.failed++; row.ok = false; row.error = String(error.stack || error); console.log(`FAIL ${id}: ${row.error}`); await page.screenshot({path:path.join(OUT,`${id}-failure.png`)}).catch(() => {}); }
    finally { await context.close(); await oracleContext.close(); write(`${id}-report`,row); }
  }
  report.sourceAfter = sourceHashes(); assert.deepEqual(report.sourceAfter,report.sourceBefore); report.fontManifestEntries = fonts.size;
} finally { await browser?.close(); server.kill(); write('report',report); }
console.log(`Trophy Cabinet native: ${report.checks} checks,${report.failed} failed,${report.cases.filter(row=>row.ok).length}/${report.cases.length} journeys,${report.controls.length} copied detector controls; artifacts ${OUT}`);
assert.equal(report.cases.length,12); assert.equal(report.controls.length,3); assert.equal(report.failed,0); assert(report.cases.every(row=>row.ok));
