// Actual production route. Browser runtime executes only on remote Actions.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createServer} from 'node:http';
import {ROOT,OUT,KEY,NOW,copy,sha,held,bundleUcl} from './qa/managerUclLeagueKit.mjs';
import {chromium} from './lib/playwrightLoader.mjs';
assert(process.env.CI,'Native manager proof is remote-only');
const output=path.join(OUT,'native');fs.mkdirSync(output,{recursive:true});
const cache=path.resolve(process.env.MANAGER_WORLD_FONT_CACHE||path.join(OUT,'font-cache'));
const manifest=JSON.parse(fs.readFileSync(path.join(cache,'manifest.json'),'utf8'));
const assets=new Map();for(const item of manifest){const bytes=fs.readFileSync(path.join(cache,item.file));assert.equal(sha(bytes),item.sha256);assets.set(item.url,{...item,bytes});}
const files=['src/lib/clubManager.ts','src/lib/clubManagerUclLeague.ts','src/lib/clubManagerCalendar.ts','src/hooks/useClubManager.ts','src/pages/ClubManager.tsx','src/components/club-manager/CalendarCard.tsx','src/components/club-manager/UclGroupsCard.tsx','src/components/club-manager/UclBracketCard.tsx','src/components/club-manager/LeagueTableCard.tsx','src/components/club-manager/CalendarScreen.tsx','scripts/playManagerUclLeague.mjs','scripts/qa/managerUclLeagueKit.mjs','package.json','package-lock.json'];
const report={sourceBefore:held(files),bootstrapAssets:[],cases:[],controls:[],fontManifest:manifest.map(({url,file,sha256})=>({url,file,sha256})),forwardedRequests:0,scope:{startup:'All startup draws and stacks retained, no isolated-engine equality credit.',actions:'Entire post-startup read/action vectors, no filtering.',controls:'Four separate pure copied-product controls. Native faulty copies test observation detectors only.',touch:'The new rules link is44px. Existing manager/calendar/table controls are measured without claiming a44px repair.',navigation:'Existing page tiles and Club home. No modal or focus restoration repair claimed.'}};
const save=()=>fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));
const server=createServer((request,response)=>{
 const url=new URL(request.url,'http://127.0.0.1');if(url.pathname==='/__oracle'){response.writeHead(200,{'Content-Type':'text/html'});response.end('<!doctype html><title>Isolated unchanged engine</title>');return;}
 let file=path.resolve(ROOT,'dist','.'+decodeURIComponent(url.pathname));if(!file.startsWith(path.join(ROOT,'dist')+path.sep)&&file!==path.join(ROOT,'dist')){response.writeHead(400);response.end();return;}
 if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file))file=path.join(ROOT,'dist','index.html');const ext=path.extname(file),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'};response.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});response.end(fs.readFileSync(file));
});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
const bundle=await bundleUcl({browser:true});report.oracleLoaded=bundle.loaded;const browser=await chromium.launch({headless:true});
const fixtures=JSON.parse(fs.readFileSync(path.join(OUT,'native-fixtures.json'),'utf8'));
function viewportFailures(o){return[o.innerWidth===o.width&&o.clientWidth===o.width&&o.innerHeight===o.height&&o.visualWidth===o.width&&o.visualHeight===o.height&&o.scale===1?null:'viewport',o.scrollWidth<=o.width?null:'horizontal-overflow'].filter(Boolean);}
function geometryFailures(o){return[...viewportFailures(o),o.fontsLoaded&&o.finite===0&&o.stable>=4?null:'readiness',o.targets.every(t=>t.inside&&t.points.every(p=>p.hit))?null:'painted-bounds',o.targets.every(t=>t.touch===0||t.rect.width>=t.touch&&t.rect.height>=t.touch)?null:'touch-target'].filter(Boolean);}
async function inspect(page,targets,profile){return page.evaluate(async({selectors,width,height})=>{
 const read=()=>{
  const box=element=>{const r=element.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};};
  const target=({selector,touch})=>{const e=document.querySelector(selector);if(!e)return{selector,touch,missing:true,inside:false,points:[],rect:{width:0,height:0}};const rect=box(e),style=getComputedStyle(e);let inside=rect.x>=0&&rect.y>=0&&rect.right<=width&&rect.bottom<=height&&rect.width>0&&rect.height>0;
   for(let p=e.parentElement;p;p=p.parentElement){const s=getComputedStyle(p),r=p.getBoundingClientRect();if(/auto|scroll|hidden|clip/.test(s.overflowX)&& (rect.x<r.left||rect.right>r.right))inside=false;if(/auto|scroll|hidden|clip/.test(s.overflowY)&&(rect.y<r.top||rect.bottom>r.bottom))inside=false;}
   const dx=Math.min(10,rect.width/4),dy=Math.min(10,rect.height/4),locations=[[rect.x+rect.width/2,rect.y+rect.height/2],[rect.x+dx,rect.y+rect.height/2],[rect.right-dx,rect.y+rect.height/2],[rect.x+rect.width/2,rect.y+dy],[rect.x+rect.width/2,rect.bottom-dy]];
   const points=locations.map(([x,y])=>{const hit=document.elementFromPoint(x,y);return{x,y,hit:!!hit&&(hit===e||e.contains(hit)),hitTag:hit?.tagName,hitText:hit?.textContent?.slice(0,80)};});
   return{selector,touch,rect,inside:inside&&style.visibility==='visible'&&Number(style.opacity)>0,points,text:e.textContent,style:{opacity:style.opacity,overflow:style.overflow,fontFamily:style.fontFamily},scrollTop:e.scrollTop};};
  return{width,height,innerWidth:innerWidth,innerHeight:innerHeight,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,visualWidth:visualViewport.width,visualHeight:visualViewport.height,scale:visualViewport.scale,y:scrollY,fontsLoaded:document.fonts.status==='loaded'&&[...document.fonts].some(f=>f.status==='loaded'),finite:document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).length,targets:selectors.map(target)};
 };
 const start=performance.now();let last='',stable=0,out;
 while(performance.now()-start<10000){await new Promise(requestAnimationFrame);out=read();const signature=JSON.stringify(out);stable=signature===last?stable+1:1;last=signature;if(stable>=4&&out.fontsLoaded&&out.finite===0)break;}
 return{...out,stable,elapsed:performance.now()-start};
 },{selectors:targets,width:profile.width,height:profile.height});}
async function center(target){await target.evaluate(e=>e.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));}
async function selectorOf(target){return target.evaluate(e=>{const parts=[];while(e!==document.body){parts.unshift(e.tagName.toLowerCase()+':nth-child('+(Array.from(e.parentElement.children).indexOf(e)+1)+')');e=e.parentElement;}return'body > '+parts.join(' > ');});}
function bodyState(page){return page.evaluate(()=>({y:scrollY,declarations:Array.from(document.body.style).map(name=>[name,document.body.style.getPropertyValue(name),document.body.style.getPropertyPriority(name)]),computed:{overflow:getComputedStyle(document.body).overflow,pointerEvents:getComputedStyle(document.body).pointerEvents,position:getComputedStyle(document.body).position}}));}
async function beginTape(page,seed){await page.evaluate(seed=>{let a=seed>>>0;window.__savedRandom=Math.random;window.__draws=[];Math.random=()=>{a+=0x6d2b79f5;let n=a;n=Math.imul(n^n>>>15,n|1);n^=n+Math.imul(n^n>>>7,n|61);const v=((n^n>>>14)>>>0)/4294967296;window.__draws.push(v);return v;};},seed);}
async function endTape(page){return page.evaluate(()=>{const values=window.__draws;Math.random=window.__savedRandom;return values;});}
async function raw(page){return page.evaluate(key=>localStorage.getItem(key),KEY);}
async function oracle(input,op,seed){const context=await browser.newContext();const page=await context.newPage();await page.goto(origin+'/__oracle');await page.addScriptTag({content:bundle.value});const result=await page.evaluate(({input,op,seed,key,now})=>{
 Date.now=()=>now;localStorage.setItem(key,JSON.stringify(input));const loaded=UclOracle.E.loadCareer();UclOracle.E.saveCareer(loaded);
 let a=seed>>>0;const old=Math.random,draws=[];Math.random=()=>{a+=0x6d2b79f5;let n=a;n=Math.imul(n^n>>>15,n|1);n^=n+Math.imul(n^n>>>7,n|61);const v=((n^n>>>14)>>>0)/4294967296;draws.push(v);return v;};
 let result=loaded;if(op==='quick'){result=UclOracle.E.playNextEntry(loaded,{skipHalftime:true});UclOracle.E.saveCareer(result.state);}
 const bytes=localStorage.getItem(key);Math.random=old;return{input,loaded,result,bytes,draws,rows:UclOracle.L.sortedUclLeague(loaded.uclGroup),calendar:[...UclOracle.C.seasonDays(loaded).entryDays.values()].filter(d=>d.competition==='uclGroup'),};
 },{input,op,seed,key:KEY,now:NOW});await context.close();return result;}
const pair=(row,label,actual,expected)=>{const file=row.id+'-'+label+'.json';fs.writeFileSync(path.join(output,file),JSON.stringify({label,actual,expected},null,2));row.pairs.push({label,file});assert.deepEqual(actual,expected,label+' entire state/bytes/vector');row.checks++;};
try{
 for(const profile of[{width:320,height:568},{width:390,height:844},{width:1280,height:900}])for(const fixture of fixtures){
  const row={id:profile.width+'-'+fixture.id,profile,club:fixture.club,position:fixture.position,pairs:[],reloads:[],startup:[],layouts:[],shots:[],checks:0,errors:[],requests:[],ok:false};report.cases.push(row);save();const context=await browser.newContext({viewport:profile,isMobile:profile.width<640,hasTouch:profile.width<640});const page=await context.newPage();
  page.on('pageerror',e=>row.errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)row.errors.push('HTTP '+r.status()+' '+r.url());});
  await context.route('**/*',async route=>{const request=route.request(),url=request.url();if(url.startsWith(origin)){await route.continue();return;}const dependency=assets.get(url);if(dependency){await route.fulfill({status:200,body:dependency.bytes,contentType:dependency.contentType});return;}row.requests.push({url,method:request.method(),forwarded:false});await route.fulfill({status:200,body:url.includes('flagcdn.com')?'':request.method()==='GET'?'[]':'{}',contentType:'application/json'});});
  await context.addInitScript(({key,input,now})=>{if(!localStorage.getItem(key)){localStorage.setItem(key,JSON.stringify(input));localStorage.setItem('dukb-guest-handle','PitchVolley-27');}Date.now=()=>now;const original=Math.random;window.__startup=[];window.__startupOriginal=original;Math.random=()=>{const value=original();window.__startup.push({value,stack:new Error('Unfiltered startup draw').stack});return value;};},{key:KEY,input:fixture.afterPo,now:NOW});
  const measure=async(label,targets)=>{const layout=await inspect(page,targets,profile);const file=row.id+'-'+label+'-layout.json';fs.writeFileSync(path.join(output,file),JSON.stringify(layout,null,2));row.layouts.push({label,file});save();assert.deepEqual(geometryFailures(layout),[],label+' requested viewport/readiness/five painted points');row.checks++;return layout;};
  const shot=async(label,targets)=>{await measure(label,targets);const file=row.id+'-'+label+'.png';await page.screenshot({path:path.join(output,file)});row.shots.push({label,file,sha256:sha(fs.readFileSync(path.join(output,file)))});save();};
  const startup=async label=>{const observations=await page.evaluate(()=>{Math.random=window.__startupOriginal;return window.__startup;});assert(observations.every(o=>Number.isFinite(o.value)&&o.value>=0&&o.value<1&&typeof o.stack==='string'));for(const observation of observations){for(const match of observation.stack.matchAll(/https?:\/\/[^\s)]+/g)){const url=match[0].replace(/:\d+:\d+$/,'');if(!url.startsWith(origin+'/assets/'))continue;const relative=new URL(url).pathname.slice(1),file=path.join(ROOT,'dist',relative);assert(fs.existsSync(file),'Owned startup caller bytes exist');if(report.bootstrapAssets.some(a=>a.relative===relative))continue;const bytes=fs.readFileSync(file),receipt=sha(bytes)+'.js';fs.mkdirSync(path.join(output,'startup-source'),{recursive:true});fs.writeFileSync(path.join(output,'startup-source',receipt),bytes);report.bootstrapAssets.push({relative,sha256:sha(bytes),file:'startup-source/'+receipt});}}row.startup.push({label,observations,filtered:false,engineOracleEquality:false});save();};
  const reload=async label=>{const before=await raw(page);await page.reload();await page.getByRole('button',{name:'Resume Career',exact:true}).first().waitFor();await startup(label);const after=await raw(page);row.reloads.push({label,before,after,beforeSha256:sha(before),afterSha256:sha(after)});assert.equal(after,before,label+' raw reload bytes');row.checks++;};
  try{
   await page.goto(origin+'/club-manager');await page.getByRole('button',{name:'Resume Career',exact:true}).first().waitFor();await startup('first-load');const expected=await oracle(fixture.afterPo,'load',71);pair(row,'first-load-whole-bytes',{state:JSON.parse(await raw(page)),bytes:await raw(page)},{state:JSON.parse(expected.bytes),bytes:expected.bytes});
   const cookie=page.getByRole('button',{name:'Essential only',exact:true});if(await cookie.isVisible()){await center(cookie);await cookie.click();await cookie.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>localStorage.getItem('cookie-consent')),'essential');}
   await page.getByRole('button',{name:'Resume Career',exact:true}).first().click();await page.getByRole('button',{name:/Cups/}).first().waitFor();const originalBytes=await raw(page),beforeBody=await bodyState(page);row.initialBody=beforeBody;row.initialReadBytes=originalBytes;save();await beginTape(page,91);
   const cups=page.getByRole('button',{name:/Cups/}).first();await center(cups);await cups.click();const region=page.getByRole('region',{name:'Champions League league table',exact:true});await region.waitFor();
   const rows=await region.locator('[data-club]').evaluateAll(nodes=>nodes.map(e=>({club:e.getAttribute('data-club'),values:Array.from(e.children).map(c=>c.textContent.trim())})));
   assert.equal(rows.length,36);for(let i=0;i<rows.length;i++){const r=expected.rows[i];assert.equal(rows[i].club,r.club);assert.deepEqual(rows[i].values.filter((_,j)=>j!==1),[String(i+1),String(r.w),String(r.d),String(r.l),r.gf+'-'+r.ga,(r.gf-r.ga>0?'+':'')+(r.gf-r.ga),String(r.pts)]);}
   assert((await page.getByText('Example: finish 12th and win your playoff to reach the last 16. Finish 6th and skip the playoff.',{exact:true}).count())===1);assert((await page.getByText(/Real qualifying playoffs, coefficient pots and association limits are not modelled/).count())===1);row.checks+=38;
   const title=region.locator(':scope > div > div').first(),columns=region.locator(':scope > div > div').nth(1),firstRow=region.locator('[data-club]').first(),lastRow=region.locator('[data-club]').last();
   const topScroll=await region.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,total:e.scrollHeight}));assert.equal(topScroll.top,0);await center(firstRow);await shot('table',[{selector:await selectorOf(title),touch:0},{selector:await selectorOf(columns),touch:0},{selector:await selectorOf(firstRow),touch:0}]);
   await center(lastRow);await measure('table-last-row',[{selector:await selectorOf(lastRow),touch:0}]);const bottomScroll=await region.evaluate(e=>({top:e.scrollTop,height:e.clientHeight,total:e.scrollHeight}));assert(bottomScroll.top>topScroll.top,'Actual inner table scroll reaches last saved club');row.tableScroll={before:topScroll,after:bottomScroll,firstClub:expected.rows[0].club,lastClub:expected.rows[35].club,scope:'All36 exact DOM rows plus strict readable first/last contexts; full512px scroll region is not claimed visible at once.'};const link=page.getByRole('link',{name:'Competition rules and format history',exact:true});await center(link);await measure('rules-link',[{selector:'a[href="/champions-league-format-history"]',touch:44}]);
   const bracketTitle=page.getByText('⭐ Champions League bracket',{exact:true});assert.equal(await bracketTitle.count(),1,'One actual Champions League bracket');
   const bracket=bracketTitle.locator('..').locator('..');const r16=bracket.getByText('Round of 16',{exact:true});assert.equal(await r16.count(),1,'One round of16 in the Champions League bracket');
   await r16.waitFor();const section=r16.locator('..');const firstTie=section.locator('div.grid > div').first();await center(firstTie);await shot('bracket',[{selector:await selectorOf(r16),touch:0},{selector:await selectorOf(firstTie),touch:0}]);
   const legText=await bracket.locator('[data-cm-bracket-legs]').evaluateAll(nodes=>nodes.map(e=>e.getAttribute('data-cm-bracket-legs')));assert.deepEqual(legText,fixture.afterPo.uclBracket.filter(t=>t.legs===2&&t.leg1).map(t=>t.leg2?t.homeGoals+'-'+t.awayGoals:'open'));row.checks++;
   await page.getByRole('button',{name:'Club home',exact:true}).click();await page.getByRole('button',{name:/Calendar/}).first().click();await page.getByTestId('cm-calendar-grid').waitFor();
   const md8=expected.calendar.find(d=>/MD8/.test(d.compLabel));assert(md8);let day=page.getByTestId('cm-calendar-grid').getByRole('button',{name:/League MD8/});for(let i=0;i<12&&await day.count()===0;i++){const previous=page.getByRole('button',{name:'Previous month',exact:true});assert(await previous.isEnabled(),'Actual saved MD8 month remains reachable');await center(previous);await previous.click();}assert.equal(await day.count(),1);await center(day);await day.click();const strip=page.getByTestId('cm-calendar-day');await strip.waitFor();assert((await strip.textContent()).includes(md8.opponent));assert((await strip.textContent()).includes(md8.compLabel));await center(strip);await shot('calendar',[{selector:'[data-testid="cm-calendar-day"]',touch:0}]);row.checks+=3;
   await page.getByRole('button',{name:'Club home',exact:true}).click();const readDraws=await endTape(page);pair(row,'read-whole-bytes',await raw(page),originalBytes);pair(row,'read-full-vector',readDraws,[]);const afterBody=await bodyState(page);row.body={before:beforeBody,after:afterBody,scope:'Actual body declarations/computed state. Navigation scroll follows user centering; no unchanged-page-y claim.'};save();assert.deepEqual(afterBody.declarations,beforeBody.declarations);assert.deepEqual(afterBody.computed,beforeBody.computed);
   await reload('read-reload');await page.getByRole('button',{name:'Resume Career',exact:true}).first().click();const playedBefore=JSON.parse(await raw(page)),quick=page.locator('[data-cm-way="quick"]');await quick.waitFor();await center(quick);await measure('actual-quick',[{selector:'[data-cm-way="quick"]',touch:44}]);const action=await oracle(playedBefore,'quick',211);await beginTape(page,211);await quick.click();await page.getByRole('heading',{name:'FULL TIME',exact:true}).waitFor();await page.waitForFunction(({key,before})=>localStorage.getItem(key)!==before,{key:KEY,before:JSON.stringify(playedBefore)});const actionDraws=await endTape(page);pair(row,'actual-quick-whole-bytes',await raw(page),action.bytes);pair(row,'actual-quick-full-vector',actionDraws,action.draws);await reload('played-reload');
   assert.equal(row.errors.length,0);row.ok=true;
  }catch(error){row.error={name:error.name,message:error.message,stack:error.stack};await page.screenshot({path:path.join(output,row.id+'-failure.png')}).catch(()=>{});}finally{row.finalObservation={bytes:await raw(page).catch(()=>null),body:await bodyState(page).catch(()=>null),unfilteredLastTape:await page.evaluate(()=>window.__draws??null).catch(()=>null)};await context.close();save();}
 }
 const healthy=report.cases.find(c=>c.ok);assert(healthy,'At least one real healthy observation for controls');const layout=JSON.parse(fs.readFileSync(path.join(output,healthy.layouts[0].file),'utf8'));
 for(const name of ['viewport','readiness','painted-bounds']){const before=copy(layout),faulty=copy(layout);if(name==='viewport')faulty.innerWidth++;if(name==='readiness')faulty.stable=3;if(name==='painted-bounds')faulty.targets[0].points[0].hit=false;assert.notDeepEqual(faulty,before);assert.deepEqual(geometryFailures(before),[]);assert.deepEqual(geometryFailures(faulty),[name]);const restored=copy(before);assert.deepEqual(restored,before);assert.deepEqual(geometryFailures(restored),[]);report.controls.push({name,kind:'Copied actual observation detector',before,faulty,restored,changed:true,undo:true});}
 for(const asset of report.bootstrapAssets){assert.equal(sha(fs.readFileSync(path.join(ROOT,'dist',asset.relative))),asset.sha256);assert.equal(sha(fs.readFileSync(path.join(output,asset.file))),asset.sha256);}report.sourceAfter=held(files);assert.deepEqual(report.sourceAfter,report.sourceBefore);assert.equal(report.cases.length,9);assert(report.cases.every(c=>c.ok));assert.equal(report.cases.reduce((n,c)=>n+c.shots.length,0),27);assert.equal(report.forwardedRequests,0);report.ok=true;save();console.log('PASS nine actual production journeys,27 native captures, complete browser save/action/read vectors and18 raw reloads.');console.log('PASS three effective observation controls, all source/package bytes held.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));save();}
