// Actual built route. The isolated Chromium oracle uses the unchanged current engine.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createServer} from 'node:net';
import {spawn} from 'node:child_process';
import pw from './lib/playwrightLoader.mjs';
import {OUT,NOW,copy,sha,git,bundleTransferBrief,sourceReceipt} from './qa/careerTransferBriefKit.mjs';
assert(process.env.CI,'Transfer Brief native proof runs remotely');
const out=path.join(OUT,'native');fs.mkdirSync(out,{recursive:true});
const fixtures=JSON.parse(fs.readFileSync(path.join(OUT,'native-fixtures.json'),'utf8'));
const fontManifest=JSON.parse(fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,'manifest.json'),'utf8')),fonts=new Map();for(const item of fontManifest){const body=fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,item.file));assert.equal(sha(body),item.sha256);fonts.set(item.url,{body,contentType:item.contentType});}
const heldFiles=['src/lib/soccerCareerTransferBrief.ts','src/lib/soccerCareerEngine.ts','src/components/soccer-career/AgentBrief.tsx','src/pages/SoccerCareer.tsx','src/components/soccer-career/SoccerOfferReview.tsx','src/components/CookieConsent.tsx','scripts/playCareerTransferBrief.mjs'];
const sourceBefore=sourceReceipt(heldFiles),oracleBundle=(await bundleTransferBrief({browser:true})).value;
const port=await new Promise((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const n=s.address().port;s.close(()=>resolve(n));});}),base='http://127.0.0.1:'+port;
const host=spawn(process.execPath,['scripts/lib/hostLikeServer.mjs','dist',String(port)],{stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host startup timeout')),15000);host.stdout.on('data',v=>{if(String(v).includes('host-like server:')){clearTimeout(timer);resolve();}});host.once('error',reject);host.once('exit',v=>reject(Error('Host exited '+v)));});
const browser=await pw.chromium.launch({headless:true}),report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),cases:[],checks:0,controls:[],forwarded:0,fontManifest,sourceBefore,bootstrapSources:[],bootstrapScope:'Unfiltered site reload-to-ready observations retain every startup value and caller stack. These observations are not paired with the already-loaded engine oracle. Exact read/action RNG comparisons begin after app startup.',scope:'Actual production actions and complete unchanged Chromium helper/engine outputs. Observation controls are copied retained data, not served source mutations.'};
const layoutFailures=v=>[...(Math.abs(v.viewport.inner.width-v.viewport.requested.width)>1||v.viewport.client.width>v.viewport.requested.width+1||(v.viewport.visual&&Math.abs(v.viewport.visual.scale-1)>0.01)?['viewport-scale']:[]),...(v.overflow?['overflow']:[]),...(v.stableFrames<4||v.finiteAnimations||v.fonts!=='loaded'||v.fontFaces.some(f=>f.status==='error')?['readiness']:[]),...(v.required.some(c=>!c.inside||!c.painted)?['painted-target']:[]),...(v.required.some(c=>c.width<43.5||c.height<43.5)?['touch-size']:[])];
const returnFailures=v=>[...(v.focus?[]:['focus']),...(JSON.stringify(v.before)===JSON.stringify(v.after)?[]:['body-page'])];
function diffs(a,b,p='$'){if(JSON.stringify(a)===JSON.stringify(b))return[];if(!a||!b||typeof a!=='object'||typeof b!=='object')return[{path:p,expected:a,actual:b}];return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>diffs(a[k],b[k],p+'.'+k));}
try{for(const width of [320,390,1280])for(const fixture of fixtures){const id=width+'-'+fixture.id,row={id,width,fixture:fixture.id,checks:0,shots:[],layouts:[],pairs:[],reloads:[],rng:[],bootstrap:[],restorations:[],errors:[],assetErrors:[],blocked:[],fontsUsed:[],preparationScope:fixture.scope};report.cases.push(row);
 const context=await browser.newContext({viewport:{width,height:width===320?568:width===390?844:900},hasTouch:width<1000,isMobile:width<1000}),page=await context.newPage(),oracleContext=await browser.newContext(),oracle=await oracleContext.newPage();
 await oracleContext.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body>Isolated engine oracle</body></html>'}));await oracle.goto(base+'/oracle');await oracle.addScriptTag({content:oracleBundle});
 const check=(v,label)=>{assert(v,id+': '+label);row.checks++;report.checks++;};
 const save=(name,value)=>{const file=id+'-'+name+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify(value,null,2));return file;};
 const bytes=()=>page.evaluate(key=>localStorage.getItem(key),fixture.key);
 const bodyState=()=>page.evaluate(()=>({y:scrollY,inline:document.body.style.overflow,computed:getComputedStyle(document.body).overflow,locked:document.body.getAttribute('data-scroll-locked')}));
 const activate=async locator=>{if(width===1280){await locator.focus();await locator.press('Enter');}else await locator.tap();};
 async function expected(op,input,seed=40,priority=null){return oracle.evaluate(({op,input,seed,priority,now})=>{const B=TransferBriefOracle;let n=seed>>>0;const draws=[],old=Math.random,oldNow=Date.now;Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>now;try{let value;switch(op){case 'load':value=B.engine.repairCareer(input);B.moments.settleLoadedMoments(value);break;case 'choose':value=B.brief.setTransferBrief(input,priority);break;case 'preview':value=B.engine.transferBriefPreview(input,B.engine.FALLBACK_CLUBS);break;case 'request':value=B.engine.requestTransferDecision(input,B.engine.FALLBACK_CLUBS);break;case 'sign':value=B.engine.acceptOffer(input,input.transferSituation.offer);break;case 'stay':value=B.engine.stayAtClub(input);break;case 'review':value=B.review.buildSoccerOfferReview(input,input.transferSituation.offer);break;default:throw Error('Unknown oracle operation '+op);}return{value,draws};}finally{Math.random=old;Date.now=oldNow;}},{op,input:copy(input),seed,priority,now:NOW});}
 async function seedPage(seed){await page.evaluate(seed=>{window.__briefOldRandom=Math.random;let n=seed>>>0;window.__briefDraws=[];Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;window.__briefDraws.push(v);return v;};},seed);}
 async function stopSeed(name,wanted){const actual=await page.evaluate(()=>{const d=window.__briefDraws;Math.random=window.__briefOldRandom;return d;});const file=save(name+'-rng',{expected:wanted,actual});row.rng.push({name,file,expectedSha256:sha(JSON.stringify(wanted)),actualSha256:sha(JSON.stringify(actual))});check(JSON.stringify(actual)===JSON.stringify(wanted),name+': exact engine and read RNG vector');}
 async function pair(name,input,wanted,actual){const expectedBytes=JSON.stringify(wanted),actualState=JSON.parse(actual),diff=diffs(wanted,actualState),file=save(name+'-whole-save',{input,expected:wanted,actual:actualState,expectedBytes,actualBytes:actual,expectedSha256:sha(expectedBytes),actualSha256:sha(actual),diff});row.pairs.push({name,file,diffCount:diff.length});check(actual===expectedBytes,name+': complete saved state and bytes equal unchanged Chromium oracle');}
 async function reload(name,held){await page.evaluate(()=>sessionStorage.setItem('brief-reload-monitor','1'));await page.reload({waitUntil:'networkidle'});const actual=await bytes(),file=save(name+'-raw-reload',{before:held,after:actual,beforeSha256:sha(held),afterSha256:sha(actual)});row.reloads.push({name,file});
  const observed=await page.evaluate(()=>{const calls=window.__briefBootstrapCalls;Math.random=window.__briefBootstrapOldRandom;return{calls,draws:calls.map(v=>v.value),elapsedMs:performance.now()-window.__briefBootstrapStart};}),assets=[];
  for(const call of observed.calls)for(const match of call.stack.matchAll(/https?:\/\/[^\s)]+/g)){const url=match[0].replace(/:\d+:\d+$/,'');if(!url.startsWith(base+'/assets/'))continue;const relative='dist'+decodeURIComponent(new URL(url).pathname),raw=fs.readFileSync(relative),receipt={url,file:relative,sha256:sha(raw),bytes:raw.length};if(!assets.some(v=>v.url===url))assets.push(receipt);if(!report.bootstrapSources.some(v=>v.file===relative)){const retained='bootstrap-sources/'+path.basename(relative);fs.mkdirSync(path.join(out,'bootstrap-sources'),{recursive:true});fs.writeFileSync(path.join(out,retained),raw);report.bootstrapSources.push({...receipt,retained});}}
  const observationFile=save(name+'-bootstrap',{...observed,assets,scope:'unfiltered-site-reload-to-ready',startedBeforeModules:true,callerFilter:false,engineOracleComparison:false,rawReload:file,beforeSha256:sha(held),afterSha256:sha(actual)});row.bootstrap.push({name,file:observationFile,rawReload:file,drawCount:observed.draws.length,drawsSha256:sha(JSON.stringify(observed.draws)),callsSha256:sha(JSON.stringify(observed.calls))});check(actual===held,name+': raw reload keeps every saved byte');check(observed.calls.every(v=>Number.isFinite(v.value)&&v.value>=0&&v.value<1&&typeof v.stack==='string'&&v.stack.length>0)&&Number.isFinite(observed.elapsedMs)&&observed.elapsedMs>=0,name+': complete unfiltered startup values and caller stacks retained');return actual;}
 async function measure(name,target,requiredSelectors){await page.evaluate(async()=>{await document.fonts.ready;});const v=await target.evaluate(async(e,{requested,requiredSelectors})=>{const rect=n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,left:r.left,right:r.right,top:r.top,bottom:r.bottom};};const sample=()=>{const viewport={requested,inner:{width:innerWidth,height:innerHeight},client:{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight},visual:visualViewport?{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale}:null};const inspect=n=>{const clip={left:0,right:requested.width,top:0,bottom:requested.height},r=rect(n),s=getComputedStyle(n),ancestor=[];for(let p=n.parentElement;p;p=p.parentElement){const style=getComputedStyle(p),a=rect(p);if(/auto|scroll|hidden/.test(style.overflowY)){clip.top=Math.max(clip.top,a.top);clip.bottom=Math.min(clip.bottom,a.bottom);ancestor.push({tag:p.tagName,top:p.scrollTop});}}const ix=Math.min(10,r.width/4),iy=Math.min(10,r.height/4),points=[[r.x+r.width/2,r.y+r.height/2],[r.left+ix,r.y+r.height/2],[r.right-ix,r.y+r.height/2],[r.x+r.width/2,r.top+iy],[r.x+r.width/2,r.bottom-iy]].map(([x,y])=>{const hit=document.elementFromPoint(x,y);return{x,y,insideTarget:!!hit&&(hit===n||n.contains(hit)),hit:hit?{tag:hit.tagName,label:hit.getAttribute('aria-label')??hit.textContent?.slice(0,120),className:hit.getAttribute('class')}:null};});return{selector:n.getAttribute('data-transfer-priority'),label:n.getAttribute('aria-label')??n.textContent,width:r.width,height:r.height,rect:r,inside:r.left>=clip.left-0.5&&r.right<=clip.right+0.5&&r.top>=clip.top-0.5&&r.bottom<=clip.bottom+0.5,painted:points.every(p=>p.insideTarget)&&s.visibility!=='hidden'&&Number(s.opacity)===1,points,ancestor};};const required=requiredSelectors.map(selector=>{const n=document.querySelector(selector);if(!n)throw Error('Missing actual control '+selector);return{...inspect(n),selector};});return{viewport,rect:rect(e),required,overflow:document.documentElement.scrollWidth>requested.width+1,finiteAnimations:document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).length,fonts:document.fonts.status,fontFaces:[...document.fonts].map(f=>({family:f.family,status:f.status})),pageY:scrollY};};let last='',stableFrames=0,v;const start=performance.now();do{await new Promise(requestAnimationFrame);v=sample();const sig=JSON.stringify(v);stableFrames=sig===last?stableFrames+1:1;last=sig;if(stableFrames>=4&&!v.finiteAnimations&&v.fonts==='loaded')return{...v,stableFrames};}while(performance.now()-start<10000);return{...v,stableFrames};},{requested:page.viewportSize(),requiredSelectors});row.layouts.push({name,...v});check(v.required.length>0&&layoutFailures(v).length===0,name+': actual viewport, five painted points,44px, four stable frames and settled fonts/animations');return v;}
 async function shot(name,target,required){await measure(name,target,required);const file=id+'-'+name+'.png';await page.screenshot({path:path.join(out,file),fullPage:false});row.shots.push({file,sha256:sha(fs.readFileSync(path.join(out,file)))});}
 async function openBrief(){const trigger=page.locator('[data-transfer-brief-open]');await trigger.scrollIntoViewIfNeeded();await trigger.evaluate(e=>e.addEventListener('click',()=>{window.__briefClickState={y:scrollY,inline:document.body.style.overflow,computed:getComputedStyle(document.body).overflow,locked:document.body.getAttribute('data-scroll-locked')};},{capture:true,once:true,passive:true}));await measure('actual-opener',trigger,['[data-transfer-brief-open]']);await activate(trigger);const before=await page.evaluate(()=>window.__briefClickState),dialog=page.locator('[data-transfer-brief]');await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[data-transfer-brief]')?.contains(document.activeElement),null,{timeout:2000});check((await bodyState()).y===before.y,'Modal opening keeps actual click-time position');check((await bodyState()).computed==='hidden','Modal locks body scrolling');return{trigger,before,dialog};}
 async function closeBrief(opened,kind){if(kind==='escape')await page.keyboard.press('Escape');else await activate(opened.dialog.locator(kind==='save'?'[data-transfer-brief-save]':kind==='clear'?'[data-transfer-brief-clear]':'[data-transfer-brief-back]'));await opened.dialog.waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('[data-transfer-brief-open]')===document.activeElement,null,{timeout:2000});const restored={before:opened.before,after:await bodyState(),focus:await opened.trigger.evaluate(e=>e===document.activeElement)};row.restorations.push(restored);check(returnFailures(restored).length===0,'Modal close restores exact opener body and click-time page');return restored;}
 try{await context.route('**/*',async route=>{const req=route.request(),url=req.url();if(url.startsWith(base+'/'))return route.continue();if(fonts.has(url)){row.fontsUsed.push(url);return route.fulfill(fonts.get(url));}if(url.startsWith('data:'))return route.continue();row.blocked.push({url,method:req.method()});if(req.method()!=='GET')return route.fulfill({status:200,contentType:'application/json',body:'{}'});if(url.includes('/rest/v1/'))return route.fulfill({status:200,contentType:'application/json',body:'[]'});return route.abort();});
 await context.addInitScript(({key,value,now})=>{if(!sessionStorage.getItem('brief-fixture:'+key)){localStorage.setItem(key,JSON.stringify(value));localStorage.setItem('dukb-guest-handle','CornerCaptain');sessionStorage.setItem('brief-fixture:'+key,'1');}Date.now=()=>now;if(sessionStorage.getItem('brief-reload-monitor')){sessionStorage.removeItem('brief-reload-monitor');window.__briefBootstrapOldRandom=Math.random;window.__briefBootstrapCalls=[];window.__briefBootstrapStart=performance.now();Math.random=()=>{const value=window.__briefBootstrapOldRandom();window.__briefBootstrapCalls.push({value,stack:new Error('Unfiltered startup Math.random').stack});return value;};}},{key:fixture.key,value:fixture.value,now:NOW});page.on('pageerror',e=>row.errors.push(String(e)));page.on('requestfailed',r=>{if(r.url().startsWith(base+'/assets/'))row.assetErrors.push({url:r.url(),error:r.failure()?.errorText});});page.on('response',r=>{if(r.url().startsWith(base+'/assets/')&&r.status()>=400)row.assetErrors.push({url:r.url(),status:r.status()});});await page.goto(base+'/soccer-career',{waitUntil:'networkidle'});
 const consent=page.getByRole('region',{name:'Cookie choices',exact:true});await consent.waitFor();await consent.scrollIntoViewIfNeeded();const cookie=await measure('actual-cookie-choice',consent,['[aria-label="Cookie choices"] button:first-of-type','[aria-label="Cookie choices"] button:last-of-type']);await activate(consent.getByRole('button',{name:'Essential only',exact:true}));await consent.waitFor({state:'hidden'});check(await page.evaluate(()=>localStorage.getItem('cookie-consent'))==='essential','Actual essential-only consent saved');
 let held=await bytes();const loaded=await expected('load',fixture.value);await pair('first-load',fixture.value,loaded.value,held);await reload('initial',held);
 let restoration=null;
 if(fixture.mandatory||fixture.malformed){check(await page.locator('[data-transfer-brief-open]').count()===0,'Compulsory or invalid held response has no brief editing');check(await page.locator('[data-request-transfer]').count()===0,'Compulsory or invalid held response has no new request');if(fixture.mandatory){check(JSON.parse(held).transferSituation.type==='club_move','Actual already completed club destination retained');check(JSON.parse(held).transferSituation.mode===fixture.mode,'Actual move mode retained');await page.locator('[data-club-move-continue]').scrollIntoViewIfNeeded();await shot('club-arranged-move',page.locator('[data-club-move]'),['[data-club-move-continue]']);}else{check(await page.locator('[data-transfer-brief-result]').count()===0,'Malformed receipt never becomes a verified result');await page.locator('[data-transfer-brief-stay]').scrollIntoViewIfNeeded();await shot('honest-recovery',page.locator('[data-transfer-brief-stay]'),['[data-transfer-brief-stay]']);}
  const input=JSON.parse(held),want=await expected('stay',input,50);await seedPage(50);await activate(page.locator(fixture.mandatory?'[data-club-move-continue]':'[data-transfer-brief-stay]'));await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).phase==='playing',fixture.key,{timeout:5000});held=await bytes();await pair('acknowledge-stay',input,want.value,held);await stopSeed('acknowledge-stay',want.draws);if(fixture.mandatory){check(JSON.parse(held).currentClub===input.currentClub,'Acknowledgement cannot undo the compulsory destination');check(JSON.stringify(JSON.parse(held).loan)===JSON.stringify(input.loan),'Parent loan record is unchanged');}await reload('acknowledged',held);
 }else{await seedPage(20);const opened=await openBrief();await opened.dialog.locator('[data-transfer-brief-help]').waitFor();const help=await opened.dialog.locator('[data-transfer-brief-help]').textContent();for(const text of ['50%','Example:','Club-arranged sales and loans','saved response'])check(help.includes(text),'First rules contain '+text);if(fixture.id==='minutes')await shot('first-rules',opened.dialog,['[data-transfer-brief-back]','[data-transfer-brief-help-open]','[data-transfer-brief-help-open] + button','[data-transfer-brief] > button:last-child']);await activate(opened.dialog.getByRole('button',{name:'Choose a priority',exact:true}));const preview=(await expected('preview',JSON.parse(held))).value;
  for(const option of preview.options){const button=opened.dialog.locator('[data-transfer-priority="'+option.id+'"]');check((await button.textContent()).includes(option.matchingCount+' matching club'),'Preview exact matching count '+option.id);if(option.projection)check((await button.textContent()).includes('about '+option.projection.min+' to '+option.projection.max+' league games'),'Preview exact saved-context projection '+option.id);await button.scrollIntoViewIfNeeded();await measure('priority-'+option.id,opened.dialog,['[data-transfer-priority="'+option.id+'"]']);await activate(button);check(await button.getAttribute('aria-pressed')==='true','Actual choice is visibly selected '+option.id);}
  check(await bytes()===held,'All preview choices are uncommitted and read-only');await activate(opened.dialog.locator('[data-transfer-brief-help-open]'));check(await opened.dialog.locator('[data-transfer-brief-help]').count()===1,'Rules reopen without losing route');await activate(opened.dialog.locator('[data-transfer-brief-back]'));check(await opened.dialog.locator('[data-transfer-brief-preview]').count()===1,'Help Back returns to existing choices');restoration=await closeBrief(opened,'escape');check(await bytes()===held,'Escape leaves every saved field unchanged');await stopSeed('readonly-preview',[]);
  await seedPage(21);const changed=await openBrief();check(await changed.dialog.locator('[data-transfer-brief-help]').count()===0,'Completed first rules persist only their separate guide setting');const choice=changed.dialog.locator('[data-transfer-priority="'+fixture.priority+'"]');await choice.scrollIntoViewIfNeeded();await activate(choice);const input=JSON.parse(held),chosen=await expected('choose',input,21,fixture.priority);await closeBrief(changed,'save');held=await bytes();await pair('save-brief',input,chosen.value,held);await stopSeed('save-brief',chosen.draws);await reload('chosen',held);check((await page.locator('[data-transfer-brief-selection]').textContent()).includes(preview.options.find(v=>v.id===fixture.priority).label),'Saved selected priority survives reload');
  const back=await openBrief();check(await back.dialog.locator('[data-transfer-priority="'+fixture.priority+'"]').getAttribute('aria-pressed')==='true','Reopening preselects saved choice');await activate(back.dialog.locator('[data-transfer-brief-help-open]'));check(await bytes()===held,'Reopening help never rewrites the saved choice');await activate(back.dialog.locator('[data-transfer-brief-back]'));await choiceScreenshot(back);await closeBrief(back,'back');
  const request=page.locator('[data-request-transfer]');await request.scrollIntoViewIfNeeded();await measure('actual-request',request,['[data-request-transfer]']);const before=JSON.parse(held),wanted=await expected('request',before,fixture.seed);await seedPage(fixture.seed);await activate(request);await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).transferSituation?.type==='request_result',fixture.key,{timeout:5000});held=await bytes();await pair('request-once',before,wanted.value,held);await stopSeed('request-once',wanted.draws);const result=JSON.parse(held).transferBrief.result;check(result.status===fixture.status,'Actual engine writes intended request branch');check(await page.locator('[data-transfer-brief-result="'+result.status+'"]').count()===1,'Actual saved response visible');check(await page.locator('[data-request-transfer]').count()===0&&await page.locator('[data-transfer-brief-open]').count()===0,'Consumed result cannot be requested or rebriefed again');if(fixture.id==='saved-offer')check(JSON.stringify(JSON.parse(held).transferSituation)!==JSON.stringify(before.transferSituation),'Request replaces the actual held offer via engine, not fixture editing');await reload('result',held);
  if(fixture.action==='sign'){const offer=JSON.parse(held).transferSituation.offer,review=(await expected('review',JSON.parse(held))).value,trigger=page.getByRole('button',{name:'Review contract with '+offer.club.name,exact:true});await trigger.scrollIntoViewIfNeeded();await activate(trigger);const dialog=page.locator('[data-soccer-offer-review]');await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[data-soccer-offer-review]')?.contains(document.activeElement),null,{timeout:2000});check(Number(await dialog.locator('[data-offer-signed-wage]').getAttribute('data-offer-signed-wage'))===review.signedWage,'Review exactly includes current agent wage effect');check(Number(await dialog.locator('[data-offer-contract-years]').getAttribute('data-offer-contract-years'))===offer.contractYears,'Review retains actual contract years');check(await bytes()===held,'Opening signing review is read-only');await shot('actual-contract',dialog,['[data-soccer-offer-review] button[aria-label="Contract review help"]','[data-soccer-offer-review] button:last-child']);const preSign=JSON.parse(held),signed=await expected('sign',preSign,60);await seedPage(60);await activate(dialog.getByRole('button',{name:'Sign contract',exact:true}));await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).phase==='playing',fixture.key,{timeout:5000});held=await bytes();await pair('sign-once',preSign,signed.value,held);await stopSeed('sign-once',signed.draws);check(!JSON.parse(held).transferBrief,'Signing consumes the valid brief');check(JSON.parse(held).currentClub===offer.club.name,'Actual signed destination equals saved request offer');await reload('signed',held);
  }else{const stay=page.locator('[data-transfer-brief-stay]');await stay.scrollIntoViewIfNeeded();await shot('saved-response',stay,['[data-transfer-brief-stay]']);const input=JSON.parse(held),wanted=await expected('stay',input,60);await seedPage(60);await activate(stay);await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).phase==='playing',fixture.key,{timeout:5000});held=await bytes();await pair('stay-once',input,wanted.value,held);await stopSeed('stay-once',wanted.draws);check(!JSON.parse(held).transferBrief,'Stay consumes the valid brief');check(JSON.parse(held).currentClub===input.currentClub,'Actual Stay retains current club');await reload('stayed',held);}
 }
 async function choiceScreenshot(opened){const selector='[data-transfer-priority="'+fixture.priority+'"]';await opened.dialog.locator(selector).scrollIntoViewIfNeeded();await shot('saved-priority',opened.dialog,[selector,'[data-transfer-brief-back]','[data-transfer-brief-help-open]','[data-transfer-brief-save]','[data-transfer-brief-clear]']);}
 if(restoration&&!report.controls.some(c=>c.name==='restoration')){const faulty=copy(restoration);faulty.focus=false;faulty.after.y+=1;assert.notEqual(JSON.stringify(faulty),JSON.stringify(restoration));assert.deepEqual(returnFailures(faulty),['focus','body-page']);const changed=copy(faulty);faulty.focus=restoration.focus;faulty.after=copy(restoration.after);assert.deepEqual(faulty,restoration);check(returnFailures(faulty).length===0&&await bytes()===held,'Copied restoration detector full undo and actual raw-save hold');report.controls.push({name:'restoration',effective:true,failed:['focus','body-page'],observed:restoration,faulty:changed,restoredObservation:faulty,restored:true});}
 if(!report.controls.some(c=>c.name==='geometry')){const probes=[];check(layoutFailures(cookie).length===0,'Geometry detector starts with actual passing painted control');for(const [name,mutate,failed]of [['painted-size',v=>{v.required[0].points[0].insideTarget=false;v.required[0].painted=false;v.required[0].width=1;},['painted-target','touch-size']],['readiness',v=>{v.stableFrames=3;},['readiness']],['viewport',v=>{v.viewport.inner.width+=51;},['viewport-scale']]]){const faulty=copy(cookie);mutate(faulty);assert.notEqual(JSON.stringify(faulty),JSON.stringify(cookie));assert.deepEqual(layoutFailures(faulty),failed);const changed=copy(faulty);faulty.required=copy(cookie.required);faulty.stableFrames=cookie.stableFrames;faulty.viewport=copy(cookie.viewport);assert.deepEqual(faulty,cookie);check(layoutFailures(faulty).length===0&&await bytes()===held,'Copied '+name+' detector full undo and raw save held');probes.push({name,failed,effective:true,observed:cookie,faulty:changed,restoredObservation:faulty,restored:true});}report.controls.push({name:'geometry',effective:true,restored:true,probes});}
 if(!report.controls.some(c=>c.name==='whole-save')){const observed=JSON.parse(held),faulty=copy(observed);faulty.morale+=1;const failures=diffs(observed,faulty);assert.equal(failures.length,1);assert.equal(failures[0].path,'$.morale');assert.notEqual(JSON.stringify(faulty),held);const changed=copy(faulty);faulty.morale=observed.morale;assert.deepEqual(faulty,observed);check(JSON.stringify(faulty)===held&&await bytes()===held,'Copied complete-state detector full undo and actual raw-save hold');report.controls.push({name:'whole-save',effective:true,failed:['$.morale'],observed,faulty:changed,restoredObservation:faulty,restored:true});}
 check(row.errors.length===0&&row.assetErrors.length===0,'No production page or owned asset exception');check(row.fontsUsed.length>0,'Actual app uses verified font cache');row.ok=true;console.log('PASS '+id+' '+row.checks+' checks');
 }catch(error){row.ok=false;row.error=String(error.stack);row.failureBody=await bodyState().catch(()=>null);row.failureViewport=await page.evaluate(()=>({width:innerWidth,height:innerHeight,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,scale:visualViewport?.scale,overflowing:[...document.querySelectorAll('body *')].map(e=>({tag:e.tagName,className:e.getAttribute('class'),rect:{left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}})).filter(v=>v.rect.right>innerWidth+1||v.rect.left< -1).slice(0,30)})).catch(()=>null);await page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});console.log('FAIL '+id+' '+row.error);}finally{await context.close();await oracleContext.close();}
}}finally{await browser.close();host.kill();report.sourceAfter=sourceReceipt(heldFiles);assert.deepEqual(report.sourceAfter,sourceBefore);report.bootstrapSourceAfter=sourceReceipt(report.bootstrapSources.map(v=>v.file));assert.deepEqual(report.bootstrapSourceAfter,report.bootstrapSources.map(({file,sha256})=>({file,sha256})));report.failed=report.cases.filter(v=>!v.ok).length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
assert.equal(report.cases.length,27);assert.equal(report.controls.length,3);assert.equal(report.forwarded,0);assert.equal(report.failed,0);console.log('Transfer Brief native '+report.checks+' checks,27 journeys,3 copied observation controls,0 failures.');