// Actual built route and actual copied original source layouts. Remote CI only.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {createServer} from 'node:net';
import {spawn} from 'node:child_process';
import pw from './lib/playwrightLoader.mjs';
import {ROOT,BASE,OUT,NOW,KEY,copy,sha,git,held,oracleBundle,prepare,originalLayout} from './qa/soccerResultsLayout.mjs';
assert(process.env.CI,'Results layout browser proof is remote-only');fs.mkdirSync(OUT,{recursive:true});const out=path.join(OUT,'native');fs.mkdirSync(out,{recursive:true});
const files=['src/pages/SoccerCareer.tsx','src/components/soccer-career/InternationalPanel.tsx','src/components/soccer-career/PhonePanel.tsx','src/components/soccer-career/TrainingPanel.tsx','src/lib/soccerCareerEngine.ts','src/lib/soccerCareerCup.ts','scripts/playSoccerResultsLayout.mjs','scripts/qa/soccerResultsLayout.mjs','package.json','package-lock.json'],sourceBefore=held(files);
const engineOriginal=git('show',BASE+':src/lib/soccerCareerEngine.ts').replaceAll('\r\n','\n'),engineCurrent=fs.readFileSync('src/lib/soccerCareerEngine.ts','utf8').replaceAll('\r\n','\n').trim();assert.equal(engineCurrent,engineOriginal,'Engine is exactly the unchanged original base');
const nodeBundle=await oracleBundle(),fixtures=prepare(nodeBundle.value),browserBundle=await oracleBundle(true);
const fontManifest=JSON.parse(fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,'manifest.json'),'utf8')),fonts=new Map();for(const item of fontManifest){const body=fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,item.file));assert.equal(sha(body),item.sha256);fonts.set(item.url,{body,contentType:item.contentType});}
const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),base:BASE,sourceBefore,engineOriginalSha256:sha(engineOriginal),oracleLoaded:nodeBundle.loaded,browserOracleLoaded:browserBundle.loaded,fontManifest,cases:[],controls:[],observationControls:[],checks:0,forwarded:0,bootstrapSources:[],limits:['History Back remains an existing32px control, result Continue remains40px. No44px claim is made for these unchanged controls.','Training previously lacks opener-focus restoration. Actual open/read/close/save/body outcomes are recorded without claiming a focus repair.','World Cup and transfer-window layouts are authentic engine continuation saves, prepared through actual handlers; the newspaper-to-summary Continue is clicked in the actual route.','No release, publication, database or whole-repository acceptance.']};
function diff(a,b,p='$'){if(JSON.stringify(a)===JSON.stringify(b))return[];if(!a||!b||typeof a!=='object'||typeof b!=='object')return[{path:p,expected:a,actual:b}];return[...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>diff(a[k],b[k],p+'.'+k));}
const layoutFailures=v=>[...(Math.abs(v.viewport.inner.width-v.viewport.requested.width)>1||Math.abs(v.viewport.inner.height-v.viewport.requested.height)>1||Math.abs(v.viewport.client.width-v.viewport.requested.width)>1||Math.abs(v.viewport.client.height-v.viewport.requested.height)>1||(v.viewport.visual&&(Math.abs(v.viewport.visual.scale-1)>.01||Math.abs(v.viewport.visual.width-v.viewport.requested.width)>1||Math.abs(v.viewport.visual.height-v.viewport.requested.height)>1))?['viewport-scale']:[]),...(v.overflow?['overflow']:[]),...(v.stableFrames<4||v.finiteAnimations||v.fonts!=='loaded'||v.fontFaces.some(f=>f.status==='error')?['readiness']:[]),...(v.required.some(c=>!c.inside||!c.painted)?['painted-target']:[]),...(v.required.some(c=>c.touchFloor>0&&(c.width<c.touchFloor-.5||c.height<c.touchFloor-.5))?['touch-size']:[])];
const saveFailures=v=>v.actualBytes!==v.expectedBytes?['whole-save']:[],vectorFailures=v=>JSON.stringify(v.actual)!==JSON.stringify(v.expected)?['vector']:[];
const controls=[],browser=await pw.chromium.launch({headless:true});
try{
 for(const [id,file] of [['original-utilities','src/pages/SoccerCareer.tsx'],['original-history','src/components/soccer-career/InternationalPanel.tsx']])controls.push(await originalLayout(id,file));
 const modes=[...[320,390,1280].map(width=>({id:'current',width,dir:'dist'})),...controls.map(c=>({...c,width:320}))];
 for(const mode of modes){
  const id=mode.width+'-'+mode.id,height=mode.width===320?568:mode.width===390?844:900,row={id,width:mode.width,checks:[],shots:[],layouts:[],pairs:[],rng:[],reloads:[],bootstrap:[],restorations:[],history:[],errors:[],assetErrors:[],blocked:[],fontsUsed:[],phaseLayouts:[],legacyControls:[],servedAssets:[],scrolls:[]};report.cases.push(row);
  const port=await new Promise((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});}),base='http://127.0.0.1:'+port,host=spawn(process.execPath,['scripts/lib/hostLikeServer.mjs',mode.dir,String(port)],{stdio:['ignore','pipe','pipe']});
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host startup timeout')),15000);host.stdout.on('data',v=>{if(String(v).includes('host-like server:')){clearTimeout(timer);resolve();}});host.once('error',reject);host.once('exit',v=>reject(Error('Host exited '+v)));});
  const context=await browser.newContext({viewport:{width:mode.width,height},hasTouch:mode.width<1000,isMobile:mode.width<1000}),page=await context.newPage(),oc=await browser.newContext(),oracle=await oc.newPage();
  await oc.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body>Unchanged Chromium engine oracle</body></html>'}));await oracle.goto(base+'/oracle');await oracle.addScriptTag({content:browserBundle.value});
  const save=(name,v)=>{const file=id+'-'+name+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify(v,null,2));return file;};
  const check=(ok,label,group='unchanged')=>{row.checks.push({ok:!!ok,label,group});report.checks++;};
  const bytes=()=>page.evaluate(key=>localStorage.getItem(key),KEY);
  const bodyState=()=>page.evaluate(()=>({y:scrollY,declarations:Array.from(document.body.style).sort().map(name=>({name,value:document.body.style.getPropertyValue(name),priority:document.body.style.getPropertyPriority(name)})),overflow:getComputedStyle(document.body).overflow,pointerEvents:getComputedStyle(document.body).pointerEvents,marginRight:getComputedStyle(document.body).marginRight,position:getComputedStyle(document.body).position,lock:document.body.getAttribute('data-scroll-locked')}));
  const activate=async locator=>{if(mode.width===1280){await locator.focus();await locator.press('Enter');}else await locator.tap();};
  const center=async locator=>{const before=await bodyState();await locator.evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));row.scrolls.push({target:await locator.evaluate(e=>e.getAttribute('aria-label')??e.textContent),before,after:await bodyState(),scope:'Actual target-centered user page/internal scroll before strict five-point reachability, no hidden or moved controls.'});};
  async function expected(op,input,seed=40){return oracle.evaluate(({op,input,seed,now})=>{const B=ResultsOracle,E=B.engine,old=Math.random,oldNow=Date.now,draws=[];let n=seed>>>0;Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>now;try{let value;if(op==='load'){value=E.repairCareer(input);B.moments.settleLoadedMoments(value);}else if(op==='newspaper')value=E.dismissNewspaper(input);else throw Error('Unknown actual operation');return{value,draws};}finally{Math.random=old;Date.now=oldNow;}},{op,input:copy(input),seed,now:NOW});}
  async function tape(seed){await page.evaluate(seed=>{window.__resultsOld=Math.random;window.__resultsDraws=[];let n=seed>>>0;Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;window.__resultsDraws.push(v);return v;};},seed);}
  async function tapeEnd(name,wanted=[]){const actual=await page.evaluate(()=>{const v=window.__resultsDraws;Math.random=window.__resultsOld;return v;});row.rng.push({name,file:save(name+'-rng',{expected:wanted,actual})});check(vectorFailures({expected:wanted,actual}).length===0,name+': complete post-bootstrap read/action vector');}
  async function pair(name,input,wanted,actual){const expectedBytes=JSON.stringify(wanted),actualState=JSON.parse(actual),differences=diff(wanted,actualState);row.pairs.push({name,file:save(name+'-whole-save',{input,expected:wanted,actual:actualState,expectedBytes,actualBytes:actual,expectedSha256:sha(expectedBytes),actualSha256:sha(actual),diff:differences})});check(saveFailures({expectedBytes,actualBytes:actual}).length===0,name+': complete state and every saved byte');}
  async function startup(name,heldBytes){const observed=await page.evaluate(()=>{const calls=window.__resultsStartup;Math.random=window.__resultsStartupOld;return{calls,draws:calls.map(v=>v.value),elapsedMs:performance.now()-window.__resultsStartupStart};}),assets=[];
   for(const call of observed.calls)for(const match of call.stack.matchAll(/https?:\/\/[^\s)]+/g)){const url=match[0].replace(/:\d+:\d+$/,'');if(!url.startsWith(base+'/assets/'))continue;const relative=decodeURIComponent(new URL(url).pathname).slice(1),file=path.join(mode.dir,relative),raw=fs.readFileSync(file),retained='bootstrap-sources/'+mode.id+'-'+path.basename(file);fs.mkdirSync(path.join(out,'bootstrap-sources'),{recursive:true});fs.writeFileSync(path.join(out,retained),raw);const v={url,file,retained,sha256:sha(raw),bytes:raw.length};if(!assets.some(a=>a.url===url))assets.push(v);if(!report.bootstrapSources.some(a=>a.file===file))report.bootstrapSources.push(v);}
   const actual=await bytes();row.bootstrap.push({name,file:save(name+'-startup',{...observed,assets,scope:'unfiltered site startup through readiness',filtered:false,engineOracleComparison:false,beforeSha256:sha(heldBytes),afterSha256:sha(actual)})});check(observed.calls.every(v=>Number.isFinite(v.value)&&v.value>=0&&v.value<1&&typeof v.stack==='string'&&v.stack.length>0),'All unfiltered startup values/stacks retained');return actual;
  }
  async function reload(name,heldBytes){await page.reload({waitUntil:'networkidle'});const actual=await startup(name,heldBytes);row.reloads.push({name,file:save(name+'-raw-reload',{before:heldBytes,after:actual,beforeSha256:sha(heldBytes),afterSha256:sha(actual)})});check(actual===heldBytes,name+': raw reload holds every byte');return actual;}
  async function measure(name,target,required,touch=0,group='geometry'){
   await page.evaluate(async()=>{await document.fonts.ready;});const nodes=await Promise.all(required.map(v=>v.elementHandle()));assert(nodes.every(Boolean),'Actual measured targets exist');
   const value=await target.evaluate(async(e,{requested,nodes,touch})=>{const rect=n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,left:r.left,right:r.right,top:r.top,bottom:r.bottom};};const sample=()=>{const inspect=n=>{const r=rect(n),s=getComputedStyle(n),clip={left:0,right:requested.width,top:0,bottom:requested.height};for(let p=n.parentElement;p;p=p.parentElement){const a=rect(p),style=getComputedStyle(p);if(/auto|scroll|hidden/.test(style.overflowY)){clip.top=Math.max(clip.top,a.top);clip.bottom=Math.min(clip.bottom,a.bottom);}if(/auto|scroll|hidden/.test(style.overflowX)){clip.left=Math.max(clip.left,a.left);clip.right=Math.min(clip.right,a.right);}}
    const ix=Math.min(10,r.width/4),iy=Math.min(10,r.height/4),points=[[r.x+r.width/2,r.y+r.height/2],[r.left+ix,r.y+r.height/2],[r.right-ix,r.y+r.height/2],[r.x+r.width/2,r.top+iy],[r.x+r.width/2,r.bottom-iy]].map(([x,y])=>{const hit=document.elementFromPoint(x,y);return{x,y,hit:hit?{tag:hit.tagName,label:hit.getAttribute('aria-label')??hit.textContent?.slice(0,90)}:null,insideTarget:!!hit&&(hit===n||n.contains(hit))};});return{label:n.getAttribute('aria-label')??n.textContent,...r,clip,position:s.position,translate:s.translate,transform:s.transform,opacity:Number(s.opacity),inside:r.left>=clip.left-.01&&r.right<=clip.right+.01&&r.top>=clip.top-.01&&r.bottom<=clip.bottom+.01,painted:points.every(p=>p.insideTarget)&&s.visibility==='visible'&&Number(s.opacity)===1,points,touchFloor:touch};};
    const faces=Array.from(document.fonts).map(f=>({family:f.family,status:f.status})),finite=document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getTiming().iterations)).map(a=>({name:a.animationName??null,currentTime:a.currentTime,endTime:a.effect?.getComputedTiming().endTime}));return{viewport:{requested,inner:{width:innerWidth,height:innerHeight},client:{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight},visual:visualViewport?{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale}:null},overflow:document.documentElement.scrollWidth>requested.width+1,required:nodes.map(inspect),fonts:document.fonts.status,fontFaces:faces,finiteAnimations:finite.length,finite,pageY:scrollY,target:rect(e)};};
    let last='',stableFrames=0,value,start=performance.now();do{await new Promise(requestAnimationFrame);value=sample();const signature=JSON.stringify(value);stableFrames=signature===last?stableFrames+1:1;last=signature;if(stableFrames>=4&&value.finiteAnimations===0&&value.fonts==='loaded')break;}while(performance.now()-start<10000);return{...value,stableFrames,elapsedMs:performance.now()-start};},{requested:{width:mode.width,height},nodes,touch});
   row.layouts.push({name,...value});check(layoutFailures(value).length===0,name+': strict actual viewport/five painted points/fonts/four frames/touch',group);return value;
  }
  async function shot(name,target,required,touch=0,group='geometry'){await measure(name,target,required,touch,group);const file=id+'-'+name+'.png';await page.screenshot({path:path.join(out,file)});row.shots.push({file,sha256:sha(fs.readFileSync(path.join(out,file)))});}
  const utilities=()=>[page.getByRole('button',{name:'Open the training ground',exact:true}),page.getByRole('button',{name:'Open your phone',exact:true})];
  async function resultLayout(name,card,targets){
   const disjoint=(a,b)=>a.right<=b.left||a.x>=b.right||a.bottom<=b.top||a.y>=b.bottom;
   for(const align of ['end','center']){
    const before=await bodyState();await targets[0].evaluate((e,block)=>e.scrollIntoView({block,behavior:'instant'}),align);
    const edgeState=()=>targets[0].evaluate(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,viewportHeight:innerHeight,pageY:scrollY};}),edge=await edgeState(),scroll={name,align,before,edge,inwardWheel:0,scope:'Actual end/center page scroll plus a small inward wheel only for measured fractional bottom clipping, no utility/style changes. Strict bounds remain unchanged.'};row.scrolls.push(scroll);
    try{if(align==='end'&&edge.bottom>edge.viewportHeight&&edge.bottom-edge.viewportHeight<1){scroll.inwardWheel=Math.ceil(edge.bottom-edge.viewportHeight)+1;await page.mouse.move((edge.left+edge.right)/2,Math.min(edge.viewportHeight-1,(edge.top+edge.bottom)/2));await page.mouse.wheel(0,scroll.inwardWheel);await page.waitForFunction(y=>scrollY!==y,edge.pageY,{timeout:2000});}}
    finally{scroll.afterEdge=await edgeState();scroll.after=await bodyState();}
    const v=await measure(name+'-'+align,card,targets,0,'result-layout'),utilityRects=await Promise.all(utilities().map(l=>l.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{label:e.getAttribute('aria-label'),x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height,position:s.position,translate:s.translate,transform:s.transform};})));
    const actual={phase:JSON.parse(await bytes()).phase,name,align,utilityRects,targets:v.required,disjoint:utilityRects.every(u=>v.required.every(t=>disjoint(u,t))),painted:v.required.every(t=>t.painted),scope:'Actual computed rectangles at logged bottom-aligned or centered user scroll position'};row.phaseLayouts.push(actual);check(actual.disjoint,name+'-'+align+': result text and Continue disjoint from utility rectangles','result-layout');
    if(mode.width<640)check(utilityRects.every(u=>u.position==='relative'),name+'-'+align+': phone utilities are in normal document flow','result-layout');else check(utilityRects.every(u=>u.position==='fixed'),name+'-'+align+': desktop utility dock remains fixed');
    if(align==='end'&&name==='summary-Continue'){const file=id+'-summary-Continue-bottom.png';await page.screenshot({path:path.join(out,file)});row.shots.push({file,sha256:sha(fs.readFileSync(path.join(out,file)))});}
   }
  }
  async function readHistory(heldBytes){
   const input=JSON.parse(heldBytes),wanted=[...(input.intlHistory??[])].reverse();assert(wanted.some(v=>v.short==='World Cup')&&wanted.some(v=>v.short==='Euros'),'Actual saved history has both competitions');
   const open=page.getByRole('button',{name:/Tournaments/});await center(open);await measure('history-opener',open,[open],0);await tape(51);await activate(open);
   const heading=page.getByText('Every tournament',{exact:true}),root=heading.locator('..'),list=heading.locator('xpath=following-sibling::div[1]'),rows=list.locator(':scope > div');await heading.waitFor();check(await rows.count()===wanted.length,'All saved tournament rows present');const observed=[];
   for(let i=0;i<wanted.length;i++){
    const rowLocator=rows.nth(i),w=wanted[i];await center(rowLocator);
    const value=await rowLocator.evaluate((e,w)=>{const leaf=text=>Array.from(e.querySelectorAll('span')).find(n=>n.textContent===text&&!Array.from(n.children).some(c=>c.textContent===text));const observe=n=>{if(!n)return null;const r=n.getBoundingClientRect(),s=getComputedStyle(n);return{text:n.textContent,x:r.x,y:r.y,width:r.width,height:r.height,clientWidth:n.clientWidth,scrollWidth:n.scrollWidth,clientHeight:n.clientHeight,scrollHeight:n.scrollHeight,textOverflow:s.textOverflow,overflow:s.overflow,whiteSpace:s.whiteSpace,maxWidth:s.maxWidth,clipped:n.scrollWidth>n.clientWidth+1||n.scrollHeight>n.clientHeight+1};};return{year:observe(leaf(String(w.year))),short:observe(leaf(w.short)),champion:observe(leaf(w.champion)),result:observe(leaf(w.myResult)),text:e.textContent};},w);
    observed.push({originalIndex:wanted.length-1-i,expected:w,actual:value});check(value.year?.text===String(w.year)&&value.short?.text===w.short&&value.champion?.text===w.champion&&value.result?.text===w.myResult,'Every saved year/name/champion/result exact, no flag text borrowed');
    check(!!value.short&&!!value.champion&&!value.short.clipped&&!value.champion.clipped&&value.short.textOverflow!=='ellipsis'&&value.champion.textOverflow!=='ellipsis','Full saved competition and champion names have no hidden/truncated text','history-names');
   }
   row.history.push({file:save('saved-history',observed)});if(mode.id==='original-history')check(observed.some(v=>v.actual.short?.clipped&&v.actual.short.textOverflow==='ellipsis'),'Original compiled competition name actually clips, not only its champion');await shot('tournament-history',root,[heading],0);const back=root.getByRole('button',{name:/Back/});await center(back);await measure('history-Back',root,[back],0);row.legacyControls.push({name:'History Back',touchFloor:0,height:await back.evaluate(e=>e.getBoundingClientRect().height)});await activate(back);await heading.waitFor({state:'hidden'});await pair('history-Back',input,input,await bytes());await tapeEnd('history-read-and-Back',[]);
  }
  async function readPhone(heldBytes){
   const trigger=utilities()[1];await center(trigger);await measure('actual-phone-trigger',trigger,[trigger],44);await trigger.evaluate(e=>e.addEventListener('click',()=>{window.__resultsClickBody={y:scrollY,declarations:Array.from(document.body.style).sort().map(name=>({name,value:document.body.style.getPropertyValue(name),priority:document.body.style.getPropertyPriority(name)})),overflow:getComputedStyle(document.body).overflow,pointerEvents:getComputedStyle(document.body).pointerEvents,marginRight:getComputedStyle(document.body).marginRight,position:getComputedStyle(document.body).position,lock:document.body.getAttribute('data-scroll-locked')};},{once:true,capture:true,passive:true}));
   await tape(52);await activate(trigger);const dialog=page.getByRole('dialog',{name:'Your phone',exact:true});await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="Your phone"]')?.contains(document.activeElement),null,{timeout:2000});const before=await page.evaluate(()=>window.__resultsClickBody),close=dialog.getByRole('button',{name:'Put phone away',exact:true});await center(close);await measure('phone-close-ready',dialog,[close],44);await activate(close);await dialog.waitFor({state:'hidden'});await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Open your phone',null,{timeout:2000});const after=await bodyState();row.restorations.push({kind:'phone',before,after,focus:await trigger.evaluate(e=>document.activeElement===e)});check(JSON.stringify(before)===JSON.stringify(after),'Phone Back restores every body declaration and actual click-time page');check(await trigger.evaluate(e=>document.activeElement===e),'Phone Back restores exact opener focus');await pair('phone-read-close',JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('phone-read-close',[]);
   const training=utilities()[0];await center(training);await measure('actual-training-trigger',training,[training],44);const trainingBefore=await bodyState();await tape(53);await activate(training);const trainingDialog=page.getByRole('dialog',{name:'Training ground',exact:true});await trainingDialog.waitFor();const trainingClose=trainingDialog.getByRole('button',{name:'Close',exact:true});await center(trainingClose);await measure('training-close-ready',trainingDialog,[trainingClose],44);await activate(trainingClose);await trainingDialog.waitFor({state:'hidden'});const trainingAfter=await bodyState();row.restorations.push({kind:'legacy-training',before:trainingBefore,after:trainingAfter,focus:await training.evaluate(e=>document.activeElement===e),scope:'Existing training opener focus is recorded, not asserted as repaired.'});check(JSON.stringify(trainingBefore)===JSON.stringify(trainingAfter),'Training read/close preserves body/page state');await pair('training-read-close',JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('training-read-close',[]);
  }
  async function installPhase(name,input){await page.evaluate(({key,input})=>localStorage.setItem(key,JSON.stringify(input)),{key:KEY,input});await page.reload({waitUntil:'networkidle'});const actual=await startup(name,JSON.stringify(input)),wanted=await expected('load',input);await pair(name+'-load',input,wanted.value,actual);return actual;}
  try{
   await context.route('**/*',async route=>{const req=route.request(),url=req.url();if(url.startsWith(base+'/'))return route.continue();if(fonts.has(url)){row.fontsUsed.push(url);return route.fulfill(fonts.get(url));}if(url.startsWith('data:'))return route.continue();row.blocked.push({url,method:req.method()});if(req.method()!=='GET')return route.fulfill({status:200,contentType:'application/json',body:'{}'});if(url.includes('/rest/v1/'))return route.fulfill({status:200,contentType:'application/json',body:'[]'});return route.abort();});
   await context.addInitScript(({key,input,now})=>{if(!sessionStorage.getItem('results-layout-fixture')){localStorage.setItem(key,JSON.stringify(input));localStorage.setItem('dukb-guest-handle','CornerCaptain');sessionStorage.setItem('results-layout-fixture','1');}Date.now=()=>now;window.__resultsStartupOld=Math.random;window.__resultsStartup=[];window.__resultsStartupStart=performance.now();Math.random=()=>{const value=window.__resultsStartupOld();window.__resultsStartup.push({value,stack:new Error('Unfiltered site startup').stack});return value;};},{key:KEY,input:fixtures.newspaper,now:NOW});
   page.on('pageerror',e=>row.errors.push(String(e)));page.on('requestfailed',r=>{if(r.url().startsWith(base+'/assets/'))row.assetErrors.push({url:r.url(),error:r.failure()?.errorText});});page.on('response',r=>{if(!r.url().startsWith(base+'/assets/'))return;if(r.status()>=400){row.assetErrors.push({url:r.url(),status:r.status()});return;}const relative=decodeURIComponent(new URL(r.url()).pathname).slice(1);if(!/\.(js|css)$/.test(relative)||row.servedAssets.some(v=>v.relative===relative))return;const file=path.join(mode.dir,relative),raw=fs.readFileSync(file),retained='served-assets/'+mode.id+'-'+path.basename(file);fs.mkdirSync(path.join(out,'served-assets'),{recursive:true});fs.writeFileSync(path.join(out,retained),raw);row.servedAssets.push({relative,file,retained,sha256:sha(raw),bytes:raw.length});});
   await page.goto(base+'/soccer-career',{waitUntil:'networkidle'});const consent=page.getByRole('region',{name:'Cookie choices',exact:true});await consent.waitFor();const essential=consent.getByRole('button',{name:'Essential only',exact:true});await measure('actual-cookie-choice',consent,[essential],0);await activate(essential);await consent.waitFor({state:'hidden'});
   let heldBytes=await startup('initial',JSON.stringify(fixtures.newspaper));const loaded=await expected('load',fixtures.newspaper);await pair('initial-load',fixtures.newspaper,loaded.value,heldBytes);await reload('newspaper',heldBytes);
   const newsContinue=page.getByRole('button',{name:'Continue to Season Summary →',exact:true}),newspaper=newsContinue.locator('..');await tape(54);await resultLayout('newspaper-Continue',newspaper,[newsContinue]);await shot('newspaper',newspaper,[newsContinue],0,'result-layout');await pair('readonly-newspaper',JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('readonly-newspaper',[]);
   const input=JSON.parse(heldBytes),wanted=await expected('newspaper',input,55);await tape(55);await activate(newsContinue);await page.waitForFunction(({key,expected})=>localStorage.getItem(key)===expected,{key:KEY,expected:JSON.stringify(wanted.value)},{timeout:7000});heldBytes=await bytes();await pair('actual-newspaper-Continue',input,wanted.value,heldBytes);await tapeEnd('actual-newspaper-Continue',wanted.draws);check(JSON.parse(heldBytes).phase==='season_summary','Actual newspaper callback opens its recorded summary');
   const summary=page.getByRole('heading',{name:'Season Summary',exact:true}).locator('../..'),cup=summary.locator('[data-cup-exit]'),continueSummary=summary.getByRole('button',{name:'Continue →',exact:true});const expectedCup=await oracle.evaluate(row=>ResultsOracle.cup.cupExitLine(ResultsOracle.cup.readCupRun(row)),JSON.parse(heldBytes).pendingSummary);check(await cup.textContent()===expectedCup,'Cup note is exact unchanged saved-run outcome');
   await tape(56);await resultLayout('summary-cup-note',summary,[cup]);await shot('summary-cup',summary,[cup],0,'result-layout');await resultLayout('summary-Continue',summary,[continueSummary]);await shot('summary-Continue',summary,[continueSummary],0,'result-layout');row.legacyControls.push({name:'Summary Continue',height:await continueSummary.evaluate(e=>e.getBoundingClientRect().height),touchFloor:0});await pair('readonly-summary',JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('readonly-summary',[]);await reload('summary',heldBytes);
   await readHistory(heldBytes);await readPhone(heldBytes);
   for(const[name,state]of [['world-cup',fixtures.world],['transfer-window',fixtures.transfer]]){
    heldBytes=await installPhase(name,state);const headings=page.locator('main h3');check(await headings.count()>0,name+': actual genuine phase renders');const target=name==='world-cup'?page.getByRole('button',{name:'Continue →',exact:true}).first():page.getByRole('button',{name:/Stay|fight for place|Sign Extension|Continue at/}).first();await target.waitFor();const card=target.locator('..');await tape(name==='world-cup'?57:58);await resultLayout(name,card,[target]);await shot(name,card,[target],0,'result-layout');await pair('readonly-'+name,JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('readonly-'+name,[]);await reload(name,heldBytes);
   }
   if(mode.width===1280){await page.locator('footer').evaluate(e=>e.scrollIntoView({block:'end',behavior:'instant'}));const privacy=page.locator('footer a[href="/privacy"]');await tape(59);await measure('desktop-footer-links',page.locator('footer'),[privacy],0);const footerTop=await page.locator('footer').evaluate(e=>e.getBoundingClientRect().top),observed=[];for(const utility of utilities()){await measure('desktop-lifted-utility',utility,[utility],44);const before=await utility.evaluate(e=>({rect:{top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom},translate:getComputedStyle(e).translate,position:getComputedStyle(e).position}));check(before.position==='fixed'&&before.rect.bottom<=footerTop+1,'Desktop utility lift keeps footer links clear');await utility.hover();await page.waitForTimeout(250);const hover=await utility.evaluate(e=>({translate:getComputedStyle(e).translate,transform:getComputedStyle(e).transform}));check(hover.translate===before.translate&&hover.transform!=='none','Actual desktop hover transform preserves independent footer translate');observed.push({before,hover});}save('desktop-footer-lift',observed);await shot('desktop-footer',page.locator('footer'),[privacy],0);await pair('readonly-desktop-footer',JSON.parse(heldBytes),JSON.parse(heldBytes),await bytes());await tapeEnd('readonly-desktop-footer',[]);}
      if(mode.id==='current'&&mode.width===320){
    const heldBytes=await bytes(),saved=JSON.parse(fs.readFileSync(path.join(out,row.pairs.find(v=>v.name==='readonly-newspaper').file),'utf8')),vector=JSON.parse(fs.readFileSync(path.join(out,row.rng.find(v=>v.name==='readonly-newspaper').file),'utf8')),layout=copy(row.layouts.find(v=>v.name==='summary-Continue-end'));
    for(const[id,observed,predicate,mutate,label]of [
     ['raw-save',saved,saveFailures,v=>{v.actual.events=[...v.actual.events,'Copied detector fault'];v.actualBytes=JSON.stringify(v.actual);},'whole-save'],
     ['raw-vector',vector,vectorFailures,v=>v.actual.push(.125),'vector'],
     ['viewport',layout,layoutFailures,v=>{v.viewport.inner.width+=12;v.viewport.inner.height+=12;v.viewport.visual.scale=1.1;},'viewport-scale']
    ]){const baseline=copy(observed),fault=copy(observed);assert.deepEqual(predicate(baseline),[]);mutate(fault);assert.notEqual(JSON.stringify(fault),JSON.stringify(baseline));const failures=predicate(fault);assert.deepEqual(failures,[label]);const restored=copy(baseline);assert.deepEqual(restored,observed);assert.deepEqual(predicate(restored),[]);assert.equal(await bytes(),heldBytes);report.observationControls.push({id,changed:true,restored:true,failures,expectedFailures:[label],file:save('observation-'+id,{baseline,fault,restored,scope:'Copied actual observation detector, not a served product source fault',beforeBytes:heldBytes,afterBytes:await bytes()})});}
   }
   check(row.errors.length===0&&row.assetErrors.length===0,'No page or owned asset exception');check(row.fontsUsed.length>0,'Actual loaded cached fonts used');
   if(mode.id==='original-utilities')check(row.phaseLayouts.some(v=>!v.disjoint||!v.painted),'Original utility dock really intersects saved result text or Continue');
   const failedGroups=[...new Set(row.checks.filter(v=>!v.ok).map(v=>v.group))];row.failedGroups=failedGroups;
   if(mode.id==='current'){assert.deepEqual(failedGroups,[],'Healthy actual route outcomes all pass');row.ok=true;}
   else{const expectedGroups=mode.id==='original-utilities'?['result-layout']:['history-names'];assert.deepEqual(failedGroups,expectedGroups,'Copied original source fails only its intended actual layout outcome');report.controls.push({...mode,dir:undefined,cleanup:undefined,loaded:mode.loaded,failedGroups,expectedGroups,changed:true,allUnrelatedPassed:true});row.ok=true;}
   console.log('PASS '+id+': '+row.checks.length+' actual checks'+(mode.id==='current'?'':', copied original rejected only '+failedGroups.join(',')));
  }catch(error){row.ok=false;row.error=String(error.stack);row.failureBody=await bodyState().catch(()=>null);row.failureSave=await bytes().catch(()=>null);await page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});console.error('FAIL '+id+': '+row.error);}
  finally{await context.close();await oc.close();host.kill();}
 }
}finally{
 await browser.close();for(const row of report.cases)for(const asset of row.servedAssets){assert.equal(sha(fs.readFileSync(asset.file)),asset.sha256,'Actual served asset remains unchanged');assert.equal(sha(fs.readFileSync(path.join(out,asset.retained))),asset.sha256,'Retained actual asset bytes hold');}report.sourceAfter=held(files);assert.deepEqual(report.sourceAfter,sourceBefore,'Every product/package/proof byte unchanged');for(const c of controls){assert(path.basename(c.cleanup).startsWith('results-layout-')&&path.dirname(c.cleanup)===path.resolve(os.tmpdir()),'Owned copied tree cleanup');fs.rmSync(c.cleanup,{recursive:true,force:true});}report.controls.forEach(c=>{c.originalSourceRestored=report.sourceBefore.every((v,i)=>v.sha256===report.sourceAfter[i].sha256);});report.failed=report.cases.filter(v=>!v.ok).length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
}
assert.equal(report.cases.length,5);assert.equal(report.controls.length,2);assert.equal(report.observationControls.length,3);assert.equal(report.forwarded,0);assert.equal(report.failed,0);console.log('Results layout:3 healthy profiles,2 effective actual-original source controls,complete bytes/read vectors held.');
