// Actual production actions. Complete saves are compared with the unchanged current Chromium engine.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createServer} from 'node:net';
import {spawn} from 'node:child_process';
import pw from './lib/playwrightLoader.mjs';
import {OUT,NOW,copy,sha,git,bundlePressMarket,sourceReceipt} from './qa/careerPressMarketKit.mjs';
assert(process.env.CI,'Native Press/Market proof runs remotely');
const out=path.join(OUT,'native');fs.mkdirSync(out,{recursive:true});
const fixtures=JSON.parse(fs.readFileSync(path.join(OUT,'native-fixtures.json'),'utf8'));
const fontManifest=JSON.parse(fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,'manifest.json'),'utf8')),fonts=new Map();for(const item of fontManifest){const body=fs.readFileSync(path.join(process.env.FREE_KICK_FONT_CACHE,item.file));assert.equal(sha(body),item.sha256);fonts.set(item.url,{body,contentType:item.contentType});}
const heldFiles=['src/lib/soccerCareerPress.ts','src/lib/usCareerMarket.ts','src/components/soccer-career/PressRoom.tsx','src/components/us-career/UsCareerBoard.tsx','src/lib/soccerCareerEngine.ts','src/pages/SoccerCareer.tsx','src/components/soccer-career/PressRoomTile.tsx','src/components/CookieConsent.tsx','scripts/playCareerPressMarket.mjs'];
const sourceBefore=sourceReceipt(heldFiles),oracleBundle=(await bundlePressMarket({browser:true})).value;
const port=await new Promise((resolve,reject)=>{const s=createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const n=s.address().port;s.close(()=>resolve(n));});}),base='http://127.0.0.1:'+port;
const host=spawn(process.execPath,['scripts/lib/hostLikeServer.mjs','dist',String(port)],{stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host startup timeout')),15000);host.stdout.on('data',v=>{if(String(v).includes('host-like server:')){clearTimeout(timer);resolve();}});host.once('error',reject);host.once('exit',v=>reject(Error('Host exited '+v)));});
const browser=await pw.chromium.launch({headless:true});const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),cases:[],checks:0,controls:[],forwarded:0,fontManifest,sourceBefore,scope:'Actual production route actions, independent unchanged current Chromium engine outputs and complete raw reload bytes. Copied observation controls are not served source mutations.'};
const viewportFailures=v=>Math.abs(v.inner.width-v.requested.width)>1||v.client.width>v.requested.width+1||(v.visual&&Math.abs(v.visual.scale-1)>0.01)?['viewport-scale']:[];
const layoutFailures=v=>[...viewportFailures(v.viewport),...(v.overflow?['overflow']:[]),...(v.stableFrames<4||v.finiteAnimations||v.fonts!=='loaded'||v.fontFaces.some(f=>f.status==='error')?['readiness']:[]),...(v.required.some(c=>!c.inside||!c.painted)?['painted-target']:[]),...(v.required.some(c=>c.width<43.5||c.height<43.5)?['touch-size']:[])];
const returnFailures=v=>[...(v.focus?[]:['focus']),...(JSON.stringify(v.before)===JSON.stringify(v.after)?[]:['body-page'])];
try{for(const width of [320,390,1280])for(const fixture of fixtures){const id=width+'-'+fixture.slug+'-'+fixture.id,row={id,width,fixture:fixture.id,sport:fixture.sport??'soccer',checks:0,shots:[],layouts:[],pairs:[],reloads:[],rng:[],restorations:[],errors:[],assetErrors:[],blocked:[],fontsUsed:[]};report.cases.push(row);
 const context=await browser.newContext({viewport:{width,height:width===320?568:width===390?844:900},hasTouch:width<1000,isMobile:width<1000}),page=await context.newPage();
 const oracleContext=await browser.newContext(),oracle=await oracleContext.newPage();await oracleContext.route('**/*',r=>r.fulfill({status:200,contentType:'text/html',body:'<!doctype html><html><body>Isolated engine oracle</body></html>'}));await oracle.goto(base+'/oracle');await oracle.addScriptTag({content:oracleBundle});
 const check=(v,label)=>{assert(v,id+': '+label);row.checks++;report.checks++;};
 const save=(name,value)=>{const file=id+'-'+name+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify(value,null,2));return file;};
 const bytes=()=>page.evaluate(key=>localStorage.getItem(key),fixture.key);
 const bodyState=()=>page.evaluate(()=>({y:scrollY,inline:document.body.style.overflow,computed:getComputedStyle(document.body).overflow,locked:document.body.getAttribute('data-scroll-locked')}));
 async function expected(op,input,seed=40,index=0){return oracle.evaluate(({op,input,seed,index,now,sportId})=>{const B=PressMarketOracle,sport=[B.NFL_CAREER_SPORT,B.NBA_CAREER_SPORT,B.MLB_CAREER_SPORT,B.NHL_CAREER_SPORT].find(s=>s.slug===sportId);let n=seed>>>0;const draws=[],old=Math.random,oldNow=Date.now;Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>now;
   try{let value;switch(op){case 'soccer-load':value=B.engine.repairCareer(input);B.moments.settleLoadedMoments(value);break;case 'answer':value=B.press.answerSoccerPress(input,index);break;case 'soccer-season':value=B.engine.advanceProSeason(input,B.engine.FALLBACK_CLUBS);break;case 'view':value=B.press.pressRoomView(input);break;case 'us-load':value=input;sport.repairNetWorth(value.c);B.summer.repairSummerOnLoad(value.c);B.retirement.repairHallOnLoad(value.c);break;
    case 'open':{const talk=input.c.contractYears===1?B.market.openMarketExtension(input.c,sport.slug,sport.buildExtension(input.c,Math.random)):B.market.openMarketFreeAgency(input.c,sport.slug,sport.buildFaWindow(input.c,input.teamQuality,Math.random));value={c:input.c,phase:talk.kind==='extension'?'extension':'freeagency',teamQuality:input.teamQuality,coach:null,contractTalk:talk};break;}
    case 'push':{const talk=input.contractTalk,updated=talk.kind==='extension'?B.market.pushMarketExtension(talk,sport.extPushArgs(input.c,Math.random)):B.market.pushMarketFreeAgency(talk,index,sport.faPushArgs(input.c,Math.random));value={...input,contractTalk:updated};break;}
    case 'ack':value={...input,contractTalk:B.market.acknowledgeMarketWheel(input.contractTalk)};break;
    case 'sign':{const talk=input.contractTalk,c=input.c;let tq=input.teamQuality;if(talk.kind==='extension'){c.contractYears=1+talk.talk.offer.years;c.salary=talk.talk.offer.salary;}else{const offer=talk.window.offers[index];B.fa.applyFaSigning(c,offer);sport.campBattle(c,offer.quality,Math.random);tq=offer.quality;}value={c,phase:'season',teamQuality:tq,coach:null};break;}
    case 'us-season':case 'decline':{const c=input.c,tq=input.teamQuality;sport.campBattle(c,tq,Math.random);const played=sport.simSeason(c,tq,Math.random);sport.progress(c,Math.random);c.headlines=B.social.pushHeadlines(c.headlines,sport.headlinesFor(c,played.line));if(sport.shouldRetire(c))throw Error('Held young fixture retired');const ev=B.summer.startSummer(c,sport,Math.random,B.retirement.talkDeckFilter(c,sport.hall)),quality=ev?tq:sport.rollTeamQuality(tq,Math.random);value={c,phase:ev?'event':'season',teamQuality:quality,coach:null};break;}
    case 'compare':value=B.market.marketOfferComparison(input.contractTalk.window,index);break;default:throw Error('Unknown oracle operation '+op);}return{value,draws};}finally{Math.random=old;Date.now=oldNow;}
 },{op,input:copy(input),seed,index,now:NOW,sportId:fixture.sport});}
 async function seedPage(seed){await page.evaluate(seed=>{window.__pressMarketOldRandom=Math.random;let n=seed>>>0;window.__pressMarketDraws=[];Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;window.__pressMarketDraws.push(v);return v;};},seed);}
 async function stopSeed(name,wanted){const draws=await page.evaluate(()=>{const d=window.__pressMarketDraws;Math.random=window.__pressMarketOldRandom;return d;});const file=save(name+'-rng',{expected:wanted,actual:draws});row.rng.push({name,file,expectedSha256:sha(JSON.stringify(wanted)),actualSha256:sha(JSON.stringify(draws))});check(JSON.stringify(draws)===JSON.stringify(wanted),name+': complete actual engine RNG equals independent Chromium oracle');}
 function diffs(a,b,p='$'){if(JSON.stringify(a)===JSON.stringify(b))return[];if(!a||!b||typeof a!=='object'||typeof b!=='object')return[{path:p,expected:a,actual:b}];return [...new Set([...Object.keys(a),...Object.keys(b)])].flatMap(k=>diffs(a[k],b[k],p+'.'+k));}
 async function pair(name,input,wanted,actual){const expectedBytes=JSON.stringify(wanted),actualState=JSON.parse(actual),diff=diffs(wanted,actualState),file=save(name+'-whole-save',{input,expected:wanted,actual:actualState,expectedBytes,actualBytes:actual,expectedSha256:sha(expectedBytes),actualSha256:sha(actual),diff});row.pairs.push({name,file,expectedSha256:sha(expectedBytes),actualSha256:sha(actual),diffCount:diff.length});check(actual===expectedBytes,name+': complete saved state and serialized bytes equal the independent engine');}
 async function reload(name,held){await page.reload({waitUntil:'networkidle'});const actual=await bytes(),file=save(name+'-raw-reload',{before:held,after:actual,beforeSha256:sha(held),afterSha256:sha(actual)});row.reloads.push({name,file,beforeSha256:sha(held),afterSha256:sha(actual)});check(actual===held,name+': reload preserves every raw saved byte');return actual;}
 async function measure(name,target,requiredSelectors){await page.evaluate(async()=>{await document.fonts.ready;});const v=await target.evaluate(async(e,{requested,requiredSelectors})=>{const rect=n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,left:r.left,right:r.right,top:r.top,bottom:r.bottom};};const sample=()=>{const viewport={requested,inner:{width:innerWidth,height:innerHeight},client:{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight},visual:visualViewport?{width:visualViewport.width,height:visualViewport.height,scale:visualViewport.scale}:null};const inspect=n=>{const clip={left:0,right:requested.width,top:0,bottom:requested.height};const r=rect(n),s=getComputedStyle(n),ancestor=[];for(let p=n.parentElement;p;p=p.parentElement){const style=getComputedStyle(p),a=rect(p);if(/auto|scroll|hidden/.test(style.overflowY)){clip.top=Math.max(clip.top,a.top);clip.bottom=Math.min(clip.bottom,a.bottom);ancestor.push({tag:p.tagName,top:p.scrollTop});}}const insetX=Math.min(10,r.width/4),insetY=Math.min(10,r.height/4),points=[[r.x+r.width/2,r.y+r.height/2],[r.left+insetX,r.y+r.height/2],[r.right-insetX,r.y+r.height/2],[r.x+r.width/2,r.top+insetY],[r.x+r.width/2,r.bottom-insetY]].map(([x,y])=>{const hit=document.elementFromPoint(x,y);return{x,y,insideTarget:!!hit&&(hit===n||n.contains(hit)),hit:hit?{tag:hit.tagName,label:hit.getAttribute('aria-label')??hit.textContent?.slice(0,120),className:hit.getAttribute('class')}:null};});return{label:n.getAttribute('aria-label')??n.textContent,width:r.width,height:r.height,rect:r,inside:r.left>=clip.left-0.5&&r.right<=clip.right+0.5&&r.top>=clip.top-0.5&&r.bottom<=clip.bottom+0.5,painted:points.every(point=>point.insideTarget)&&s.visibility!=='hidden'&&Number(s.opacity)===1,points,ancestor};};const required=requiredSelectors.map(selector=>{const n=document.querySelector(selector);if(!n)throw Error('Required actual control missing '+selector);return{selector,...inspect(n)};});return{viewport,rect:rect(e),overflow:document.documentElement.scrollWidth>requested.width+1,required,finiteAnimations:document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).length,fonts:document.fonts.status,fontFaces:[...document.fonts].map(f=>({family:f.family,status:f.status})),pageY:scrollY};};let last='',stableFrames=0,v;const start=performance.now();do{await new Promise(requestAnimationFrame);v=sample();const sig=JSON.stringify(v);stableFrames=sig===last?stableFrames+1:1;last=sig;if(stableFrames>=4&&!v.finiteAnimations&&v.fonts==='loaded')return{...v,stableFrames};}while(performance.now()-start<10000);return{...v,stableFrames};},{requested:page.viewportSize(),requiredSelectors});row.layouts.push({name,...v});check(v.required.length>0,name+': actual controls measured');check(layoutFailures(v).length===0,name+': requested viewport, painted44px and stable fonts/animation');return v;}
 async function shot(name,target,required){await page.locator(required[required.length-1]).scrollIntoViewIfNeeded();await measure(name,target,required);const file=id+'-'+name+'.png';await page.screenshot({path:path.join(out,file),fullPage:false});row.shots.push({file,sha256:sha(fs.readFileSync(path.join(out,file)))});}
 async function pressOpen(){const open=page.locator('[data-press-room-open]');await open.scrollIntoViewIfNeeded();await open.evaluate(e=>e.addEventListener('click',()=>{window.__pressClicked={y:scrollY,inline:document.body.style.overflow,computed:getComputedStyle(document.body).overflow,locked:document.body.getAttribute('data-scroll-locked')};},{capture:true,once:true,passive:true}));await open.click();const before=await page.evaluate(()=>window.__pressClicked),dialog=page.locator('[data-press-room] [role="dialog"]');await dialog.waitFor();await page.waitForFunction(()=>document.querySelector('[data-press-room] [role="dialog"]')?.contains(document.activeElement),null,{timeout:2000});check((await bodyState()).y===before.y,'Press opening preserves actual click-time page position');check((await bodyState()).computed==='hidden','Press locks body scrolling');return{open,before,dialog};}
 async function pressClose(opened,escape=false){if(escape){await page.keyboard.press('Escape');}else await opened.dialog.locator('[data-press-close]').click();await opened.dialog.waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('[data-press-room-open]')===document.activeElement,null,{timeout:2000});const returned={before:opened.before,after:await bodyState(),focus:await opened.open.evaluate(e=>e===document.activeElement)};row.restorations.push(returned);check(returnFailures(returned).length===0,'Press close restores exact focus body and page');return returned;}
 try{await context.route('**/*',async route=>{const req=route.request(),url=req.url();if(url.startsWith(base+'/'))return route.continue();if(fonts.has(url)){row.fontsUsed.push(url);return route.fulfill(fonts.get(url));}if(url.startsWith('data:'))return route.continue();row.blocked.push({url,method:req.method()});if(req.method()!=='GET')return route.fulfill({status:200,contentType:'application/json',body:'{}'});if(url.includes('/rest/v1/'))return route.fulfill({status:200,contentType:'application/json',body:'[]'});return route.abort();});
 await context.addInitScript(({key,value,now})=>{if(!sessionStorage.getItem('press-market-seed:'+key)){localStorage.setItem(key,JSON.stringify(value));localStorage.setItem('dukb-guest-handle','CornerCaptain');sessionStorage.setItem('press-market-seed:'+key,'1');}Date.now=()=>now;},{key:fixture.key,value:fixture.value,now:NOW});page.on('pageerror',e=>row.errors.push(String(e)));page.on('requestfailed',r=>{if(r.url().startsWith(base+'/assets/'))row.assetErrors.push({url:r.url(),error:r.failure()?.errorText});});page.on('response',r=>{if(r.url().startsWith(base+'/assets/')&&r.status()>=400)row.assetErrors.push({url:r.url(),status:r.status()});});await page.goto(base+'/'+fixture.slug,{waitUntil:'networkidle'});
 const consent=page.getByRole('region',{name:'Cookie choices',exact:true});await consent.waitFor();await consent.scrollIntoViewIfNeeded();const cookie=await measure('actual-cookie-choice',consent,['[aria-label="Cookie choices"] button:first-of-type','[aria-label="Cookie choices"] button:last-of-type']);await consent.getByRole('button',{name:'Essential only',exact:true}).click();await consent.waitFor({state:'hidden'});check(await page.evaluate(()=>localStorage.getItem('cookie-consent'))==='essential','Actual essential-only cookie choice is persisted');
 const soccer=fixture.slug==='soccer-career';if(!soccer){const guide=page.getByRole('dialog',{name:'How to play',exact:true});await guide.waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('[role="dialog"]')].some(e=>e.textContent.includes('How to play')&&e.contains(document.activeElement)),null,{timeout:2000});for(const text of ['The steps','The rules','A worked example'])check(await guide.getByText(text,{exact:true}).count()===1,'Actual first-visit guide section '+text);await guide.getByRole('button',{name:"Let's Play!",exact:true}).click();await guide.waitFor({state:'hidden'});}
 const initialBytes=await bytes(),loaded=await expected(soccer?'soccer-load':'us-load',fixture.value);await pair('first-load',fixture.value,loaded.value,initialBytes);await reload('initial',initialBytes);let held=initialBytes;
 if(soccer){const opened=await pressOpen(),view=(await expected('view',JSON.parse(held))).value;check(await bytes()===held,'Initial Press rules read changes no saved field');await opened.dialog.locator('[data-press-start]').click();
  if(fixture.choice){await opened.dialog.locator('[data-press-screen="question"]').waitFor();check((await opened.dialog.locator('[data-press-question]').textContent())===view.question,'Question exactly describes independent saved season context');check((await opened.dialog.locator('[data-press-stat-line]').textContent())===view.source.statLine,'Question uses saved position-specific stats');await shot('question',opened.dialog,['[data-press-room] button[aria-label="Press room help"]','[data-press-close]']);const before=JSON.parse(held),want=await expected('answer',before,40,fixture.choice);await opened.dialog.locator('[data-press-answer="'+fixture.choice+'"]').scrollIntoViewIfNeeded();await measure('actual-answer-control',opened.dialog,['[data-press-answer="'+fixture.choice+'"]']);await seedPage(40);await opened.dialog.locator('[data-press-answer="'+fixture.choice+'"]').click();await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).pressRoom?.history.length>0,fixture.key,{timeout:2000});held=await bytes();await pair('answer',before,want.value,held);await stopSeed('answer',want.draws);
  }else{check(fixture.prepared,'Only the genuine engine move fixture starts with an existing promise');await opened.dialog.locator('[data-press-history="0"]').click();check((await opened.dialog.locator('[data-press-promise]').textContent()).includes('Waiting for your following season'),'Genuine pre-load engine move preserves pending promise');row.preparationScope=fixture.scope;}
  await opened.dialog.locator('[data-press-receipt]').waitFor();check((await opened.dialog.locator('[data-press-receipt]').textContent()).includes(view.source.club),'Receipt retains actual completed source club');if(!fixture.settlement)await shot('recorded-answer',opened.dialog,['[data-press-room] button[aria-label="Press room help"]','[data-press-close]']);await opened.dialog.getByRole('button',{name:'Press room help',exact:true}).click();check(await bytes()===held,'Reopened Press rules never repeat rewards');await opened.dialog.locator('[data-press-start]').click();const restoration=await pressClose(opened,true);await reload('answered',held);
  if(fixture.settlement){const input=JSON.parse(held),seed=fixture.settlement.seed,want=await expected('soccer-season',input,seed);check(want.value.pressRoom.history[0].promise.outcome===fixture.id,'Independent actual engine reaches the required promise verdict');await seedPage(seed);await page.getByRole('button',{name:'Next Season',exact:true}).first().click();await page.waitForFunction(({key,length})=>JSON.parse(localStorage.getItem(key)).seasons.length===length+1,{key:fixture.key,length:input.seasons.length},{timeout:15000});const actual=await bytes();await pair('next-season',input,want.value,actual);await stopSeed('next-season',want.draws);held=actual;check(JSON.parse(held).pressRoom.history[0].promise.outcome===fixture.id,'Actual NextSeason writes the required promise verdict');await reload('settled',held);const history=await pressOpen();await history.dialog.locator('[data-press-start]').click();if(await history.dialog.locator('[data-press-screen="question"]').count())await history.dialog.getByRole('button',{name:'Your past answers',exact:true}).click();await history.dialog.locator('[data-press-history="0"]').click();check(await history.dialog.locator('[data-press-promise="'+fixture.id+'"]').count()===1,'Actual settled history displays the saved verdict');await shot('settled-history',history.dialog,['[data-press-room] button[aria-label="Press room help"]','[data-press-close]']);await pressClose(history);check(await bytes()===held,'Reading settled history cannot settle twice');
  }
  if(!report.controls.some(c=>c.name==='restoration')){const faulty=copy(restoration);faulty.focus=false;faulty.after.y+=1;assert.deepEqual(returnFailures(faulty),['focus','body-page']);assert.notEqual(JSON.stringify(faulty),JSON.stringify(restoration));faulty.focus=restoration.focus;faulty.after=copy(restoration.after);assert.deepEqual(faulty,restoration);check(returnFailures(faulty).length===0&&await bytes()===held,'Copied restoration detector undo and actual save hold');report.controls.push({name:'restoration',effective:true,failed:['focus','body-page'],restored:true,scope:'Copied actual observation'});}
 }else{const input=JSON.parse(held),want=await expected('open',input,40);await seedPage(40);await page.getByRole('button',{name:/Play the \d+ season/i}).first().click();await page.locator(fixture.kind==='freeagency'?'[data-fa-window]':'[data-extension-talk]').waitFor();held=await bytes();await pair('market-open',input,want.value,held);await stopSeed('market-open',want.draws);check(JSON.parse(held).c.seasons.length===input.c.seasons.length,'Opening contract talks plays no season or camp');await reload('market-open',held);
  if(fixture.kind==='decline'){await shot('decline-offer',page.locator('[data-extension-talk]'),['[data-ext-decline]']);const before=JSON.parse(held),want=await expected('decline',before,60);await seedPage(60);await page.locator('[data-ext-decline]').click();await page.waitForFunction(({key,length})=>JSON.parse(localStorage.getItem(key)).c.seasons.length===length+1,{key:fixture.key,length:before.c.seasons.length},{timeout:15000});held=await bytes();await pair('decline-one-season',before,want.value,held);await stopSeed('decline-one-season',want.draws);check(!JSON.parse(held).contractTalk,'Played contract year clears the prior talk context');await reload('declined',held);check(await page.locator('[data-extension-talk]').count()===0,'Declined year does not reopen after reload');
  }else{const before=JSON.parse(held),kind=fixture.kind,index=0,pushSelector=kind==='extension'?'[data-ext-push]':'[data-fa-push="0"]',odds=await page.locator(kind==='extension'?'[data-market-odds="extension"]':'[data-market-odds="0"]').locator('[data-market-chance]').evaluateAll(es=>Object.fromEntries(es.map(e=>[e.getAttribute('data-market-chance'),Number(e.getAttribute('data-probability'))])));check(Object.values(odds).length===3&&Math.abs(Object.values(odds).reduce((a,b)=>a+b,0)-1)<1e-9,'Actual pre-push odds sum to one');
   if(kind==='freeagency'){await page.locator('[data-market-compare-open]').click();for(const priority of ['annual','total','years','roster']){await page.locator('[data-market-priority="'+priority+'"]').click();const actual=await page.locator('[data-market-compared-offer]').evaluateAll(es=>es.map(e=>Number(e.getAttribute('data-market-compared-offer')))),wanted=(await expected('compare',before,40,priority)).value.map(v=>v.index);check(JSON.stringify(actual)===JSON.stringify(wanted),'Offer comparison '+priority+' preserves true original signing indices');check(await bytes()===held,'Comparison is read-only');}await shot('saved-offer-comparison',page.locator('[data-market-compare]'),['[data-market-compare-back]']);await page.locator('[data-market-compare-back]').click();}else await shot('extension-opening',page.locator('[data-extension-talk]'),['[data-ext-push]']);
   const wanted=await expected('push',before,50,index);await seedPage(50);await page.locator(pushSelector).click();await page.locator('[data-market-wheel]').waitFor();held=await bytes();await pair('one-push',before,wanted.value,held);await stopSeed('one-push',wanted.draws);const receipt=JSON.parse(held).contractTalk.wheel;check(JSON.stringify(receipt.probabilities)===JSON.stringify(odds),'Wheel retains the actual pre-push probabilities');check(receipt.seen===false&&receipt.draws.length>0,'One original negotiation is committed before Spin');await reload('unrevealed-wheel',held);await page.locator('[data-market-wheel]').waitFor();await page.locator('[data-market-skip]').click();await page.locator('[data-market-wheel-outcome]').waitFor();check(await bytes()===held,'Skip reveals without rewriting any committed state');await reload('skipped-wheel',held);await page.locator('[data-market-spin]').click();await page.locator('[data-market-wheel-outcome]').waitFor({timeout:5000});check(await bytes()===held,'Spin after reload never rerolls or rewrites');check(await page.locator('[data-market-wheel]').getAttribute('data-market-result')===receipt.result,'Actual wheel reveals its one saved result');await shot('saved-wheel-result',page.locator('[data-market-wheel]'),['[data-market-continue]']);const beforeAck=JSON.parse(held),ack=await expected('ack',beforeAck);await page.locator('[data-market-continue]').click();await page.locator('[data-market-wheel]').waitFor({state:'hidden'});held=await bytes();await pair('acknowledge',beforeAck,ack.value,held);await reload('acknowledged',held);check(await page.locator('[data-market-wheel]').count()===0,'Acknowledged wheel remains closed after reload');
   const beforeSign=JSON.parse(held),sign=await expected('sign',beforeSign,55,index),button=page.locator(kind==='extension'?'[data-ext-sign]':'[data-fa-sign="0"]');await button.scrollIntoViewIfNeeded();await measure('actual-signing-control',button,[kind==='extension'?'[data-ext-sign]':'[data-fa-sign="0"]']);await seedPage(55);await button.click();await page.waitForFunction(key=>JSON.parse(localStorage.getItem(key)).phase==='season',fixture.key,{timeout:5000});held=await bytes();await pair('signed-once',beforeSign,sign.value,held);await stopSeed('signed-once',sign.draws);check(!JSON.parse(held).contractTalk,'Signing consumes the contract snapshot');await reload('signed',held);check(JSON.parse(held).c.seasons.length===input.c.seasons.length,'Signing never adds a played season');const signed=JSON.parse(held),played=await expected('us-season',signed,65);await seedPage(65);await page.getByRole('button',{name:/Play the \d+ season/i}).first().click();await page.waitForFunction(({key,length})=>JSON.parse(localStorage.getItem(key)).c.seasons.length===length+1,{key:fixture.key,length:signed.c.seasons.length},{timeout:15000});held=await bytes();await pair('normal-camp-and-season',signed,played.value,held);await stopSeed('normal-camp-and-season',played.draws);await reload('played',held);check(!JSON.parse(held).contractTalk,'Actual camp and one season do not resurrect the prior offer');
  }
 }
 if(!report.controls.some(c=>c.name==='painted-target')){const observed=cookie,probes=[];check(layoutFailures(observed).length===0,'Geometry detector begins with a passing actual observation');for(const [name,mutate,expectedFailure]of [
 ['painted-size',v=>{v.required[0].points[0].insideTarget=false;v.required[0].painted=false;v.required[0].width=1;},['painted-target','touch-size']],
 ['readiness',v=>{v.stableFrames=3;},['readiness']],
 ['viewport',v=>{v.viewport.inner.width=v.viewport.requested.width+51;},['viewport-scale']],
]){const faulty=copy(observed);mutate(faulty);assert.notEqual(JSON.stringify(faulty),JSON.stringify(observed));assert.deepEqual(layoutFailures(faulty),expectedFailure);check(true,'Copied '+name+' geometry probe fails exactly its intended detector');const faultyEvidence=copy(faulty);faulty.required=copy(observed.required);faulty.stableFrames=observed.stableFrames;faulty.viewport=copy(observed.viewport);assert.deepEqual(faulty,observed);check(layoutFailures(faulty).length===0&&await bytes()===held,'Copied '+name+' geometry probe restores every observation and holds the actual raw save');probes.push({name,failed:expectedFailure,effective:true,restored:true,observed,faulty:faultyEvidence,restoredObservation:copy(faulty)});}report.controls.push({name:'painted-target',effective:true,failed:['painted-target','touch-size'],probes,restored:true,scope:'Copied actual observations, not served product faults'});}
 if(!report.controls.some(c=>c.name==='whole-save')){const observed=JSON.parse(held),faulty=copy(observed);if(soccer)faulty.morale+=1;else faulty.c.salary+=1;const failures=diffs(observed,faulty);assert.equal(failures.length,1);assert.notEqual(JSON.stringify(faulty),held);const restored=copy(observed);assert.equal(JSON.stringify(restored),held);check(await bytes()===held,'Copied full-save detector catches one changed field and preserves actual save');report.controls.push({name:'whole-save',effective:true,failed:failures.map(v=>v.path),restored:true,scope:'Copied actual outcome'});}
 check(row.errors.length===0&&row.assetErrors.length===0,'No production page or local asset exceptions');check(row.fontsUsed.length>0,'Actual page uses verified offline font cache');row.ok=true;console.log('PASS '+id+' '+row.checks+' checks');
 }catch(error){row.ok=false;row.error=String(error.stack);row.failureBody=await bodyState().catch(()=>null);row.failureViewport=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scale:visualViewport?.scale})).catch(()=>null);await page.screenshot({path:path.join(out,id+'-failure.png')}).catch(()=>{});console.log('FAIL '+id+' '+row.error);}finally{await context.close();await oracleContext.close();}
}}finally{await browser.close();host.kill();report.sourceAfter=sourceReceipt(heldFiles);assert.deepEqual(report.sourceAfter,sourceBefore);report.failed=report.cases.filter(v=>!v.ok).length;fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
assert.equal(report.cases.length,54);assert.equal(report.controls.length,3);assert.equal(report.forwarded,0);assert.equal(report.failed,0);console.log('Press/Market native '+report.checks+' checks,54 journeys,3 effective observation detectors,0 failures.');