// Scratch, not committed: draft scripts/data/careerSeasonAudit/clubMap.json from the proposals plus hand overrides.
import fs from 'node:fs';

const [propFile, outFile] = process.argv.slice(2);
const prop = JSON.parse(fs.readFileSync(propFile, 'utf8'));
const first = list => (list[0] ?? '').split('|');
/* hand overrides, each checked against the proposal list by eye */
const O = {
  'AC Milan': { wikidata: ['Q1543'], marketValue: ['AC Milan'] },
  'Inter Milan': { wikidata: ['Q631'], marketValue: ['Inter Milan'] },
  'Atlético Madrid': { wikidata: ['Q8701'], reserve: ['Q780539', 'Q20921799'], marketValue: ['Atlético de Madrid'] },
  'Real Madrid': { wikidata: ['Q8682'], reserve: ['Q12217', 'Q1246437'], marketValue: ['Real Madrid'] },
  'Real Madrid Castilla': { wikidata: ['Q12217'], marketValue: ['Real Madrid Castilla'] },
  Barcelona: { wikidata: ['Q7156'], reserve: ['Q10467', 'Q2346842', 'Q13562063'], marketValue: ['FC Barcelona'] },
  'Bayern Munich': { wikidata: ['Q15789'], reserve: ['Q994701', 'Q791554'], marketValue: ['Bayern Munich'] },
  'Borussia Dortmund': { wikidata: ['Q41420'], reserve: ['Q865720'], marketValue: ['Borussia Dortmund'] },
  'Borussia Mönchengladbach': { wikidata: ['Q101959'], reserve: ['Q13397712'], marketValue: ['Borussia Mönchengladbach'] },
  'Athletic Bilbao': { wikidata: ['Q8687'], reserve: ['Q794970'], marketValue: ['Athletic Bilbao'] },
  Hamburg: { wikidata: ['Q51974'], marketValue: ['Hamburger SV'] },
  Lyon: { wikidata: ['Q704'], reserve: ['Q3924852'], marketValue: ['Olympique Lyon'] },
  PSG: { wikidata: ['Q483020'], reserve: ['Q2945336'], marketValue: ['Paris Saint-Germain'] },
  'Paris Saint-Germain': { wikidata: ['Q483020'], marketValue: ['Paris Saint-Germain'] },
  Rennes: { wikidata: ['Q19509'], marketValue: ['Stade Rennais FC'] },
  'Red Star Belgrade': { wikidata: ['Q173009'], marketValue: [] },
  'Orlando City': { wikidata: ['Q15214308'], marketValue: ['Orlando City SC'] },
  'Melbourne Victory': { wikidata: [], marketValue: ['Melbourne Victory'] },
  LAFC: { wikidata: ['Q18380286'], marketValue: ['Los Angeles FC'] },
  'LA Galaxy': { wikidata: ['Q204357'], marketValue: ['Los Angeles Galaxy'] },
  'Miami FC': { wikidata: [], marketValue: [] },
  'Delhi Dynamos': { wikidata: ['Q16838244'], marketValue: [] },
  'Western Sydney Wanderers': { wikidata: [], marketValue: [] },
  CSA: { wikidata: ['Q928885'], marketValue: [] },
  'Deportivo La Coruña': { wikidata: ['Q8760'], marketValue: ['Deportivo de La Coruña'] },
  'Guangzhou Evergrande': { wikidata: ['Q130521'], marketValue: ['Guangzhou FC'] },
  'Hebei China Fortune': { wikidata: ['Q402038'], marketValue: [] },
  'NK Zagreb': { wikidata: ['Q462411'], marketValue: [] },
  'Dinamo Zagreb': { wikidata: ['Q172803'], marketValue: ['GNK Dinamo Zagreb'] },
  'New York Red Bulls': { wikidata: ['Q204220'], marketValue: ['Red Bull New York'] },
  'RB Salzburg': { wikidata: ['Q994811'], marketValue: ['Red Bull Salzburg'] },
  'RB Leipzig': { wikidata: ['Q702455'], marketValue: ['RB Leipzig'] },
  'Montreal Impact': { wikidata: ['Q167615'], marketValue: [] },
  'West Brom': { wikidata: ['Q18744'], marketValue: ['West Bromwich Albion'] },
  'West Bromwich Albion': { wikidata: ['Q18744'], marketValue: ['West Bromwich Albion'] },
  'West Ham United': { wikidata: ['Q18747'], marketValue: ['West Ham United'] },
  'West Ham': { wikidata: ['Q18747'], marketValue: ['West Ham United'] },
  'Newcastle United': { wikidata: ['Q18716'], marketValue: ['Newcastle United'] },
  Newcastle: { wikidata: ['Q18716'], marketValue: ['Newcastle United'] },
  'Tottenham Hotspur': { wikidata: ['Q18741'], marketValue: ['Tottenham Hotspur'] },
  Tottenham: { wikidata: ['Q18741'], marketValue: ['Tottenham Hotspur'] },
  'Wolverhampton Wanderers': { wikidata: ['Q19500'], marketValue: ['Wolverhampton Wanderers'] },
  Wolverhampton: { wikidata: ['Q19500'], marketValue: ['Wolverhampton Wanderers'] },
  'Athletico Paranaense': { wikidata: ['Q506832'], marketValue: ['Club Athletico Paranaense'] },
  'Atlético Paranaense': { wikidata: ['Q506832'], marketValue: ['Club Athletico Paranaense'] },
  'Melbourne City': { wikidata: ['Q748725'], marketValue: [] },
  'Mumbai City': { wikidata: ['Q16845355'], marketValue: [] },
  'Al-Ahli': { wikidata: ['Q44441'], marketValue: ['Al-Ahli SFC'] },
  'Al-Ahli Dubai': { wikidata: ['Q424943'], marketValue: [] },
  'Al-Arabi': { wikidata: ['Q283760'], marketValue: ['Al-Arabi SC'] },
  'Al-Duhail': { wikidata: ['Q1056948'], marketValue: ['Al-Duhail SC'] },
  'Al-Ittihad': { wikidata: ['Q309480'], marketValue: ['Al-Ittihad Club'] },
  'Junior FC': { wikidata: ['Q332524'], marketValue: ['Junior FC'] },
  Barranquilla: { wikidata: ['Q3293573'], marketValue: [] },
  'Sporting Gijón': { wikidata: ['Q12278'], reserve: ['Q2982210'], marketValue: ['Sporting Gijón'] },
  Kaiserslautern: { wikidata: ['Q8466'], reserve: ['Q16525407'], marketValue: ['1.FC Kaiserslautern'] },
  'Karlsruher SC': { wikidata: ['Q105853'], reserve: ['Q18704184'], marketValue: [] },
  'Schalke 04': { wikidata: ['Q32494'], reserve: ['Q3736767'], marketValue: ['FC Schalke 04'] },
  Lille: { wikidata: ['Q19516'], reserve: ['Q16591640'], marketValue: ['LOSC Lille'] },
  Monaco: { wikidata: ['Q180305'], reserve: ['Q109500422'], marketValue: ['AS Monaco'] },
  Benfica: { wikidata: ['Q131499'], reserve: ['Q7387221'], marketValue: ['SL Benfica'] },
  Porto: { wikidata: ['Q128446'], reserve: ['Q5423714'], marketValue: ['FC Porto'] },
  PSV: { wikidata: ['Q11938'], reserve: ['Q13534332'], marketValue: ['PSV Eindhoven'] },
  'Real Sociedad': { wikidata: ['Q10315'], reserve: ['Q1067750'], marketValue: ['Real Sociedad'] },
  Valencia: { wikidata: ['Q10333'], reserve: ['Q918044'], marketValue: ['Valencia CF'] },
  Villarreal: { wikidata: ['Q12297'], reserve: ['Q1094113', 'Q20978061'], marketValue: ['Villarreal CF'] },
  Ajax: { wikidata: ['Q81888'], reserve: ['Q15178660'], marketValue: ['Ajax Amsterdam'] },
  Arsenal: { wikidata: ['Q9617'], reserve: ['Q4384231'], marketValue: ['Arsenal FC'] },
  Napoli: { wikidata: ['Q2641'], reserve: ['Q22936201'], marketValue: ['SSC Napoli'] },
  'Manchester City': { wikidata: ['Q50602'], marketValue: ['Manchester City'] },
  'Manchester United': { wikidata: ['Q18656'], marketValue: ['Manchester United'] },
  'Leeds United': { wikidata: ['Q1128631'], marketValue: ['Leeds United'] },
  'Leicester City': { wikidata: ['Q19481'], marketValue: ['Leicester City'] },
  'Coventry City': { wikidata: ['Q19580'], marketValue: ['Coventry City'] },
  'Swansea City': { wikidata: ['Q18659'], marketValue: [] },
  'Oxford United': { wikidata: ['Q48946'], marketValue: [] },
  'Rotherham United': { wikidata: ['Q48950'], marketValue: ['Rotherham United'] },
  'FC Halifax Town': { wikidata: ['Q5214935'], marketValue: [] },
  'Fleetwood Town': { wikidata: ['Q48941'], marketValue: [] },
  'New York City FC': { wikidata: ['Q13361030'], marketValue: ['New York City FC'] },
  'Boca Juniors': { wikidata: ['Q170703'], marketValue: ['CA Boca Juniors'] },
  'Argentinos Juniors': { wikidata: ['Q220621'], marketValue: ['AA Argentinos Juniors'] },
  'São Paulo': { wikidata: ['Q38568'], marketValue: ['São Paulo Futebol Clube'] },
  'São Caetano': { wikidata: ['Q290940'], marketValue: [] },
  'Sparta Prague': { wikidata: ['Q193481'], marketValue: [] },
  'Dukla Prague': { wikidata: ['Q1199965'], marketValue: [] },
  'Spartak Moscow': { wikidata: ['Q29112'], marketValue: [] },
  'Spartak Subotica': { wikidata: ['Q94605'], marketValue: [] },
  'Dinamo Batumi': { wikidata: ['Q1346756'], marketValue: [] },
  "Newell's Old Boys": { wikidata: ['Q221882'], marketValue: [] },
  Fluminense: { wikidata: ['Q80987'], marketValue: ['Fluminense Football Club', 'Fluminense'] },
  Juventus: { wikidata: ['Q1422'], marketValue: ['Juventus FC', 'Juventus'] },
  Porto2: null,
  Internacional: { wikidata: ['Q80845'], marketValue: ['Sport Club Internacional'] },
  Grêmio: { wikidata: ['Q221695'], marketValue: ['Grêmio Foot-Ball Porto Alegrense'] },
  Cruzeiro: { wikidata: ['Q188277'], marketValue: ['Cruzeiro Esporte Clube'] },
  Nacional: { wikidata: ['Q499616'], marketValue: ['Club Nacional'] },
  Vitória: { wikidata: ['Q274465'], marketValue: ['Esporte Clube Vitória'] },
  Botafogo: { wikidata: ['Q80958'], marketValue: [] },
  Vitesse: { wikidata: ['Q219233'], marketValue: ['Vitesse Arnhem'] },
  'Celta Vigo': { wikidata: ['Q8749'], marketValue: ['Celta de Vigo'] },
  'Chicago Fire': { wikidata: ['Q308683'], marketValue: ['Chicago Fire FC'] },
  'Hellas Verona': { wikidata: ['Q8639'], marketValue: ['Hellas Verona'] },
  'Olympiacos': { wikidata: ['Q19628'], marketValue: ['Olympiacos Piraeus'] },
  Marseille: { wikidata: ['Q132885'], marketValue: ['Olympique Marseille'] },
  Nice: { wikidata: ['Q185163'], marketValue: ['OGC Nice'] },
  Heerenveen: { wikidata: ['Q200321'], marketValue: ['SC Heerenveen'] },
  Feyenoord: { wikidata: ['Q134241'], marketValue: ['Feyenoord Rotterdam'] },
  Twente: { wikidata: ['Q19603'], marketValue: ['FC Twente Enschede'] },
  Toulouse: { wikidata: ['Q19518'], marketValue: ['FC Toulouse'] },
  Mallorca: null,
};
const map = {};
for (const club of Object.keys(prop).sort()) {
  if (O[club]) { map[club] = { wikidata: O[club].wikidata, reserve: O[club].reserve ?? [], marketValue: O[club].marketValue }; continue; }
  const [q, label, s] = first(prop[club].wikidata);
  const [mvName, , mvs] = first(prop[club].marketValue);
  map[club] = { wikidata: q && Number(s) === 1 ? [q] : [], reserve: [], marketValue: mvName && Number(mvs) === 1 ? [mvName] : [], _auto: `${label ?? ''} / ${mvName ?? ''}` };
}
fs.writeFileSync(outFile, JSON.stringify(map, null, 1));
for (const [club, m] of Object.entries(map)) if (m._auto !== undefined) console.log(`${club} -> ${m.wikidata.join(',')} ${m._auto}`);
