// Remote gameplay proof. The base is compiled from its original Git sources.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { build } from 'esbuild';
assert(process.env.CI, 'Programme checks run on remote CI');
const root=process.cwd(),out=path.join(root,'career-programme-artifacts');fs.mkdirSync(out,{recursive:true});
const base='a131ed713d65e844aa8d86c92dbb8be396ba55af',baseTree='ebd03b225527047d52a97ccbc9bf594edea536e1';
const git=(...args)=>execFileSync('git',args,{encoding:'utf8',maxBuffer:20*1024*1024}).trim();
assert.equal(git('rev-parse',base+'^{tree}'),baseTree);
const copy=v=>JSON.parse(JSON.stringify(v)),sha=v=>createHash('sha256').update(v).digest('hex');
const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),base,baseTree,neutral:[],fleets:[],controls:[],loaded:[]};
function seeded(seed,fn){const random=Math.random,now=Date.now;let n=seed>>>0;const draws=[];Math.random=()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);const v=((t^t>>>14)>>>0)/4294967296;draws.push(v);return v;};Date.now=()=>1791586800000;try{return{value:fn(),draws};}finally{Math.random=random;Date.now=now;}}
async function bundle(original=false,compatibility=false){const folder=fs.mkdtempSync(path.join(os.tmpdir(),'programme-')),file=path.join(folder,'engine.cjs'),loaded=[];
  const contents="export * as engine from './src/lib/soccerCareerEngine';"+(original?'':"export * as programme from './src/lib/soccerCareerProgramme'; export * as us from './src/lib/usCareerProgramme'; export * as cups from './src/lib/soccerSeasonCompetitions'; export * as squad from './src/lib/soccerClubSquad'; export {NFL_CAREER_SPORT} from './src/lib/nflCareerSport'; export {NBA_CAREER_SPORT} from './src/lib/nbaCareerSport'; export {MLB_CAREER_SPORT} from './src/lib/mlbCareerSport'; export {NHL_CAREER_SPORT} from './src/lib/nhlCareerSport'; export {defaultAppearance} from './src/lib/soccerCareerAppearance';");
  await build({stdin:{contents,resolveDir:root,loader:'ts'},bundle:true,format:'cjs',platform:'node',outfile:file,alias:{'@':path.join(root,'src')},define:{'import.meta.env':'{"PROD":true,"DEV":false}'},loader:{'.css':'empty','.svg':'empty','.png':'empty','.jpg':'empty','.webp':'empty'},logLevel:'error',plugins:[{name:'original-source',setup(b){b.onLoad({filter:/\.(ts|tsx|json)$/},args=>{const rel=path.relative(root,args.path).replaceAll('\\','/');if(!rel.startsWith('src/'))return;const bytes=original?execFileSync('git',['show',base+':'+rel],{maxBuffer:20*1024*1024}):fs.readFileSync(args.path);let contents=bytes.toString('utf8');if(compatibility&&rel==='src/lib/soccerCareerEngine.ts'){assert.equal(contents.split('includeOpening: true,').length,2,'Unique opt-in compatibility anchor');contents=contents.replace('includeOpening: true,','includeOpening: false,');}loaded.push({file:rel,sha256:sha(bytes),compiledSha256:sha(contents),original,compatibility});return{contents,loader:rel.endsWith('.json')?'json':rel.endsWith('.tsx')?'tsx':'ts'};});}}]});
  try{const value=createRequire(path.join(root,'package.json'))(file);report.loaded.push(...loaded);return value;}finally{fs.rmSync(folder,{recursive:true,force:true});}}
const A=await bundle(true),B=await bundle(),C=await bundle(false,true),saved=JSON.parse(fs.readFileSync('scripts/data/careerLeagueWorldSaves1100.json','utf8')).saves.filter(v=>v.kind==='player');
function withoutOpening(value){const normalized=copy(value);let removed=0;for(const row of [...(normalized.seasons??[]),normalized.pendingSummary].filter(Boolean)){if(row.cupRun?.opening){delete row.cupRun.opening;removed++;}}return{normalized,removed};}
for(const fixture of saved)for(let seed=1;seed<=10;seed++){const input=copy(fixture.state),before=copy(input);const a=seeded(seed,()=>A.engine.advanceProSeason(copy(input),A.engine.FALLBACK_CLUBS)),b=seeded(seed,()=>B.engine.advanceProSeason(copy(input),B.engine.FALLBACK_CLUBS)),c=seeded(seed,()=>C.engine.advanceProSeason(copy(input),C.engine.FALLBACK_CLUBS));assert.deepEqual(c,a,'Compatibility arm preserves full original season and RNG');const actual=withoutOpening(b.value),compatible=withoutOpening(c.value);assert.deepEqual(actual.normalized,compatible.normalized,'Actual product only adds saved opening ties');assert.deepEqual(b.draws,a.draws,'Opening tie preserves original global RNG');assert.deepEqual(input,before);const file='neutral-'+fixture.id+'-'+seed+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify({input,original:a,compatibility:c,current:b,openingFields:actual.removed},null,2));report.neutral.push({id:fixture.id,seed,file,output:sha(JSON.stringify(a.value)),draws:sha(JSON.stringify(a.draws)),drawCount:a.draws.length,openingFields:actual.removed});}
assert.equal(report.neutral.length,50);assert(report.neutral.every(v=>v.drawCount>0));
const carrier=B.engine.repairCareer(copy(saved[0].state));Object.assign(carrier,{phase:'playing',age:26,overall:85,position:'ST',currentClub:'Arsenal',currentClubCountry:'England',currentClubTier:1,currentLeague:'Premier League',currentClubColor:'#EF4444',contractYearsLeft:4,weeklyWage:50000,netWorth:2,isClubCaptain:true,captainClub:'Arsenal',loan:{parentClub:'Chelsea',parentCountry:'England',parentTier:1,parentLeague:'Premier League',parentColor:'#2563EB'}});carrier.seriousInjuries=[{year:carrier.seasons.at(-1).year,name:'Knee injury',weeks:16,path:'plan',setback:false}];
for(const [name,choices,field]of[['tactical output',['finisher','creator'],'goals'],['captain discipline',['calm','rally'],'yellowCards']]){const totals=[];for(const choice of choices){let sum=0,played=0;for(let seed=100;seed<160;seed++){const input=B.programme.chooseProgramme(copy(carrier),name==='tactical output'?'tactics':'captain',choice),step=seeded(seed,()=>B.engine.advanceProSeason(input,B.engine.FALLBACK_CLUBS)).value,row=step.seasons.at(-1);if(row.type==='playing'){sum+=row[field];played++;}}totals.push({choice,sum,played});}assert(totals.every(v=>v.played>=50));assert(name==='tactical output'?totals[0].sum>totals[1].sum:totals[0].sum<totals[1].sum,name+': decisions change actual recorded outcomes');report.fleets.push({name,totals});}
const squad=B.squad.squadView(carrier);assert(squad);const expectedSquad={club:squad.club,year:squad.year,source:squad.source,carried:squad.carried,eleven:['ATT','MID','DEF','GK'].flatMap(group=>squad.eleven[group]).map(({name,pos,ovr,me,role,id})=>({name,pos,ovr,me:!!me,role:role??null,id:id??null,source:me?'you':role?'role':id!==undefined?'generated':'real'}))};assert.equal(expectedSquad.eleven.length,11);
const native=[{slug:'soccer-career',key:'soccerCareerSave',value:carrier,expectedSquad}];
const wheel=copy(carrier);wheel.phase='random_events';wheel.pendingEvents=[B.engine.getAllEvents(wheel).find(e=>e.id===16),B.engine.getAllEvents(wheel).find(e=>e.id===2)];native.push({id:'wheel',slug:'soccer-career',key:'soccerCareerSave',value:wheel});
const counter=copy(carrier);counter.agentId='self';counter.phase='transfer_window';counter.loan=null;counter.transferSituation={type:'one_offer',offer:{club:B.engine.FALLBACK_CLUBS.find(c=>c.name==='Chelsea'),contractYears:3,wage:50000,transferFee:20}};native.push({id:'counteroffer',slug:'soccer-career',key:'soccerCareerSave',value:counter});
for(const sport of [B.NFL_CAREER_SPORT,B.NBA_CAREER_SPORT,B.MLB_CAREER_SPORT,B.NHL_CAREER_SPORT]){const pos=sport.create.defaultPos,arch=sport.create.archetypes[pos][0],era=sport.create.eras[0].id,c=seeded(1197,()=>sport.startCareer('Programme Player',pos,arch,Math.random,B.defaultAppearance(),era)).value;c.contractYears=4;c.age=31;c.health=80;c.salary=Math.max(1,c.salary);c.netWorth=2;c.role='starter';native.push({slug:sport.gameSlug,key:sport.saveKey,value:{c,phase:'season',teamQuality:75}});}
fs.writeFileSync(path.join(out,'native-fixtures.json'),JSON.stringify(native,null,2));
const calendarFixtures=[];
for(let seed=1;seed<=800&&calendarFixtures.length<2;seed++){const input=copy(carrier);input.loan=null;const result=seeded(seed,()=>B.engine.advanceProSeason(input,B.engine.FALLBACK_CLUBS)).value,row=result.seasons.at(-1);if(row.type!=='playing'||!row.cupRun?.opening||row.clubCupRun?.qualified)continue;const competitions=B.cups.savedSeasonCompetitions(result,row),domestic=competitions.find(c=>c.id==='domestic');if(!domestic)continue;const kind=domestic.matches[0]?.result==='Through'&&domestic.matches[1]?.opponent?'advance':domestic.matches.length===1&&domestic.matches[0]?.result==='Out'?'exit':null;if(kind&&!calendarFixtures.some(f=>f.id===kind)){const value=copy(result);value.phase='season_summary';value.pendingSummary=copy(row);calendarFixtures.push({id:kind,slug:'soccer-career',key:'soccerCareerSave',seed,input,actualEngineResult:result,value,row,competitions,scope:'Actual seeded engine result. Only presentation phase/pending summary opens its recorded review.'});}}
assert.equal(calendarFixtures.length,2,'Actual advancing and eliminated cup routes found');fs.writeFileSync(path.join(out,'calendar-fixtures.json'),JSON.stringify(calendarFixtures,null,2));report.calendarFixtures=calendarFixtures.map(f=>({id:f.id,seed:f.seed,year:f.row.year,club:f.row.club,matches:f.competitions.find(c=>c.id==='domestic').matches}));
const file='src/lib/soccerCareerProgramme.ts',raw=fs.readFileSync(file),source=raw.toString('utf8'),anchor=/export function chooseProgramme\(prev: CareerState, id: [^,]+, choice: [^)]+\): CareerState \{/;
const match=source.match(anchor);assert(match,'Unique live chooseProgramme source anchor');assert.equal(source.match(new RegExp(anchor.source,'g')).length,1);
const controlRoot=path.join(root,'.sim-control');fs.mkdirSync(controlRoot,{recursive:true});
for(const id of ['tactics','position','set_pieces','promise','negotiation','bonuses','adaptation','fitness','captain','loan']){const faulty=source.replace(match[0],match[0]+"\n  if (id === '"+id+"') return prev;"),temp=fs.mkdtempSync(path.join(controlRoot,'programme-')),patched=path.join(temp,'soccerCareerProgramme.ts'),json=path.join(out,'control-'+id+'.json');assert.notEqual(sha(faulty),sha(source));fs.writeFileSync(patched,faulty);
  try{const run=spawnSync(process.execPath,['node_modules/vitest/vitest.mjs','run','src/lib/soccerCareerProgramme.test.ts','--maxWorkers=1','--minWorkers=1','--reporter=json','--outputFile='+json],{encoding:'utf8',env:{...process.env,NO_DOUBLE_SWAP:JSON.stringify({'@/lib/soccerCareerProgramme':patched})},maxBuffer:10*1024*1024});fs.writeFileSync(path.join(out,'control-'+id+'.log'),run.stdout+run.stderr);assert.equal(run.status,1,id+': loaded fault must fail');const result=JSON.parse(fs.readFileSync(json,'utf8')),failed=result.testResults.flatMap(v=>v.assertionResults).filter(v=>v.status==='failed');assert(failed.length>0);assert(failed.some(v=>v.title.startsWith(id+' ')),id+': primary gameplay proof detects lost decision');assert(failed.every(v=>v.failureMessages.some(m=>/AssertionError|expected|to be|to equal/i.test(m))),'Assertion failure, no import error');report.controls.push({id,originalSha256:sha(source),faultySha256:sha(faulty),failed:failed.map(v=>v.fullName),passed:result.numPassedTests,effective:true});console.log('CONTROL FIRED '+id+': '+failed.map(v=>v.title).join(', '));}finally{fs.rmSync(temp,{recursive:true,force:true});assert.deepEqual(fs.readFileSync(file),raw);}}
const usFile='src/lib/usCareerProgramme.ts',usRaw=fs.readFileSync(usFile),usSource=usRaw.toString('utf8'),usAnchor=/export function saveUsCareerProgramme<T extends UsCareerCore>\(c: T, sport: UsSport, choices: ProgrammeChoices \| null\): T & ProgrammeCareer \{/;
const usMatch=usSource.match(usAnchor);assert(usMatch,'Unique live US choice anchor');assert.equal(usSource.match(new RegExp(usAnchor.source,'g')).length,1);
for(const id of ['workload','tactics','expectation','partnership','bonus','reinvention']){const faulty=usSource.replace(usMatch[0],usMatch[0]+"\n  if (choices && choices."+id+" !== 'normal') return c as T & ProgrammeCareer;"),temp=fs.mkdtempSync(path.join(controlRoot,'us-programme-')),patched=path.join(temp,'usCareerProgramme.ts'),json=path.join(out,'control-us-'+id+'.json');assert.notEqual(sha(faulty),sha(usSource));fs.writeFileSync(patched,faulty);
  try{const run=spawnSync(process.execPath,['node_modules/vitest/vitest.mjs','run','src/lib/usCareerProgramme.test.ts','--maxWorkers=1','--minWorkers=1','--reporter=json','--outputFile='+json],{encoding:'utf8',env:{...process.env,NO_DOUBLE_SWAP:JSON.stringify({'@/lib/usCareerProgramme':patched})},maxBuffer:10*1024*1024});fs.writeFileSync(path.join(out,'control-us-'+id+'.log'),run.stdout+run.stderr);assert.equal(run.status,1,id+': loaded US fault must fail');const result=JSON.parse(fs.readFileSync(json,'utf8')),all=result.testResults.flatMap(v=>v.assertionResults),failed=all.filter(v=>v.status==='failed');assert(failed.some(v=>v.title.startsWith(id+' ')),id+': primary US gameplay check detects lost choice');assert(failed.every(v=>v.failureMessages.some(m=>/AssertionError|expected|to be|to equal/i.test(m))),'Actual assertions detect US fault');report.controls.push({id:'us-'+id,originalSha256:sha(usSource),faultySha256:sha(faulty),failed:failed.map(v=>v.fullName),passed:result.numPassedTests,effective:true});console.log('CONTROL FIRED us-'+id+': '+failed.map(v=>v.title).join(', '));}finally{fs.rmSync(temp,{recursive:true,force:true});assert.deepEqual(fs.readFileSync(usFile),usRaw);}}
for(const c of [
  {id:'ui-scroll',file:'src/components/soccer-career/SoccerCareerProgramme.tsx',alias:'@/components/soccer-career/SoccerCareerProgramme',test:'src/test/soccerCareerProgrammeUi.test.tsx',anchor:'body.current.scrollTop = pending.top;',fault:'body.current.scrollTop = 0;',primary:'restores the list offset'},
  {id:'ui-focus',file:'src/components/soccer-career/SoccerCareerProgramme.tsx',alias:'@/components/soccer-career/SoccerCareerProgramme',test:'src/test/soccerCareerProgrammeUi.test.tsx',anchor:'target?.focus({ preventScroll: true });',fault:'heading.current?.focus({ preventScroll: true });',primary:'restores the list offset'},
  {id:'wheel-roll',file:'src/lib/careerChanceWheel.ts',alias:'@/lib/careerChanceWheel',test:'src/lib/careerChanceWheel.test.ts',anchor:'const result = roll < chance;',fault:'const result = roll >= chance;',primary:'uses one original draw'},
  {id:'wheel-ack',file:'src/lib/careerChanceWheel.ts',alias:'@/lib/careerChanceWheel',test:'src/lib/careerChanceWheel.test.ts',anchor:'seen: true } } : state;',fault:'seen: false } } : state;',primary:'acknowledges once'},
  {id:'wheel-ui',file:'src/components/soccer-career/CareerChanceWheel.tsx',alias:'@/components/soccer-career/CareerChanceWheel',test:'src/test/careerChanceWheelUi.test.tsx',anchor:'receipt.result ? receipt.hit : receipt.miss',fault:'receipt.result ? receipt.miss : receipt.hit',primary:'skipping preserves'}
]){const raw=fs.readFileSync(c.file),source=raw.toString('utf8');assert.equal(source.split(c.anchor).length,2,c.id+': unique actual source anchor');const faulty=source.replace(c.anchor,c.fault),temp=fs.mkdtempSync(path.join(controlRoot,c.id+'-')),patched=path.join(temp,path.basename(c.file)),json=path.join(out,'control-'+c.id+'.json');assert.notEqual(sha(source),sha(faulty));fs.writeFileSync(patched,faulty);
  try{const run=spawnSync(process.execPath,['node_modules/vitest/vitest.mjs','run',c.test,'--maxWorkers=1','--minWorkers=1','--reporter=json','--outputFile='+json],{encoding:'utf8',env:{...process.env,NO_DOUBLE_SWAP:JSON.stringify({[c.alias]:patched})},maxBuffer:10*1024*1024});fs.writeFileSync(path.join(out,'control-'+c.id+'.log'),run.stdout+run.stderr);assert.equal(run.status,1,c.id+': live loaded fault must fail');const result=JSON.parse(fs.readFileSync(json,'utf8')),failed=result.testResults.flatMap(v=>v.assertionResults).filter(v=>v.status==='failed');assert(failed.some(v=>v.title.startsWith(c.primary)),c.id+': intended behavioral check detects fault');assert(failed.every(v=>v.failureMessages.some(m=>/AssertionError|expected|to be|to equal/i.test(m))));report.controls.push({id:c.id,originalSha256:sha(raw),faultySha256:sha(faulty),failed:failed.map(v=>v.fullName),passed:result.numPassedTests,effective:true});console.log('CONTROL FIRED '+c.id);}finally{fs.rmSync(temp,{recursive:true,force:true});assert.deepEqual(fs.readFileSync(c.file),raw);}}
report.wheels=[];
for(const [kind,id,choice]of [['event',9,1],['event',11,1],['event',13,1],['event',15,0],['event',16,1],['event',22,0],['moral','match_fixing',0],['moral','match_fixer_approach',0],['moral','night_out_photo',1],['moral','magazine_shoot',1],['moral','mafia_second_ask',0],['moral','mafia_second_ask',1],['moral','deepfake_scandal',1],['moral','wag_reality_show',0],['moral','ultras_tattoo',1]])for(const seed of[3,15]){const input=copy(carrier);delete input.programme;input.phase=kind==='event'?'random_events':'moral_dilemma';if(kind==='event')input.pendingEvents=[{id,choices:[]},{id:2,choices:[]}];else input.pendingMoralDilemma={id};
  const a=seeded(seed,()=>kind==='event'?A.engine.applyEventChoice(copy(input),choice,A.engine.FALLBACK_CLUBS):A.engine.applyMoralDilemmaChoice(copy(input),choice)),b=seeded(seed,()=>kind==='event'?B.engine.applyEventChoice(copy(input),choice,B.engine.FALLBACK_CLUBS):B.engine.applyMoralDilemmaChoice(copy(input),choice));const receipt=b.value.chanceWheel;assert(receipt&&!receipt.seen&&receipt.result===(receipt.roll<receipt.chance));const normalized=copy(b.value);delete normalized.chanceWheel;assert.deepEqual(normalized,a.value,'Wheel preserves original actual outcome');assert.deepEqual(b.draws,a.draws,'Wheel consumes exactly original draws');const file='wheel-'+kind+'-'+id+'-'+choice+'-'+seed+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify({input,original:a,current:b},null,2));report.wheels.push({kind,id,choice,seed,file,receipt,drawCount:b.draws.length});}
assert.equal(report.wheels.length,30);
function mergePatch(target,patch){for(const[key,value]of Object.entries(patch)){if(value&&typeof value==='object'&&!Array.isArray(value)){if(!target[key]||typeof target[key]!=='object'||Array.isArray(target[key]))target[key]={};mergePatch(target[key],value);}else target[key]=copy(value);}return target;}
function heldCatalog(engine,input,roll){const random=Math.random,now=Date.now,draws=[];Math.random=()=>{draws.push(roll);return roll;};Date.now=()=>1791586800000;try{return{events:engine.getAllEvents(copy(input)),draws};}finally{Math.random=random;Date.now=now;}}
const actionCases=JSON.parse(fs.readFileSync('scripts/data/careerChanceActions1197.json','utf8'));assert.equal(actionCases.base,base);assert.equal(actionCases.baseTree,baseTree);assert.equal(actionCases.actions.length,67);report.secondaryWheels=[];
for(const action of actionCases.actions)for(const seed of[3,15]){const actionLabel=action.file+'/'+action.id+' choice '+action.choice+' seed '+seed;const input=mergePatch(copy(carrier),{netWorth:100,...action.patch});delete input.programme;delete input.chanceWheel;const before=copy(input),catalogA=heldCatalog(A.engine,input,action.catalogRoll),catalogB=heldCatalog(B.engine,input,action.catalogRoll);assert.deepEqual(catalogB.draws,catalogA.draws,'Catalog eligibility stream held: '+actionLabel);const eventA=catalogA.events.find(e=>e.id===action.id),eventB=catalogB.events.find(e=>e.id===action.id);assert(eventA&&eventB,'Actual event remains eligible: '+actionLabel);assert.equal(eventB.title,eventA.title,'Actual catalogue title held: '+actionLabel);assert(eventA.choices[action.choice]&&eventB.choices[action.choice],'Actual choice exists: '+actionLabel);const a=seeded(seed,()=>eventA.choices[action.choice].apply(copy(input))),b=seeded(seed,()=>eventB.choices[action.choice].apply(copy(input)));const receipt=b.value.chanceWheel;assert(receipt&&!receipt.seen&&receipt.result===(receipt.roll<receipt.chance),'Actual choice saves coherent wheel: '+actionLabel);assert.equal(receipt.title,action.title,'Wheel title matches: '+actionLabel);assert.equal(receipt.chance,action.chance,'Wheel odds match: '+actionLabel);assert.equal(receipt.hit,action.hit,'Wheel hit text matches: '+actionLabel);assert.equal(receipt.miss,action.miss,'Wheel miss text matches: '+actionLabel);const normalized=copy(b.value);delete normalized.chanceWheel;assert.deepEqual(normalized,a.value,'Secondary wheel preserves complete original choice outcome: '+actionLabel);assert.deepEqual(b.draws,a.draws,'Secondary wheel uses exact original draw stream: '+actionLabel);assert.deepEqual(input,before,'Held action input unchanged: '+actionLabel);const file='wheel-secondary-'+action.id+'-'+action.choice+'-'+seed+'.json';fs.writeFileSync(path.join(out,file),JSON.stringify({scope:actionCases.scope,action,input,catalog:{title:eventB.title,choice:eventB.choices[action.choice].label,originalDraws:catalogA.draws,currentDraws:catalogB.draws},original:a,current:b},null,2));report.secondaryWheels.push({file,id:action.id,choice:action.choice,seed,source:action.file,receipt,drawCount:b.draws.length});}
assert.equal(report.secondaryWheels.length,134);
fs.writeFileSync(path.join(out,'outcomes.json'),JSON.stringify(report,null,2));console.log('Career programme:50 original/compatibility/full product season pairs with exact RNG,240 opted gameplay seasons,21 effective loaded faults,164 unchanged original chance outcomes,7 native career fixtures.');
