// Focused remote proof. All original sources come from the actual frozen Git base.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {BASE,OUT,copy,git,sha,seeded,bundlePressMarket,sportList,soccerFixture,usFixture,sourceReceipt,writeEvidence} from './qa/careerPressMarketKit.mjs';
assert(process.env.CI,'Press/Market outcomes run on remote CI');
const sourceFiles=['src/lib/soccerCareerPress.ts','src/lib/usCareerMarket.ts','src/lib/soccerCareerEngine.ts','src/components/us-career/UsCareerBoard.tsx'];
const sourceBefore=sourceReceipt(sourceFiles),original=await bundlePressMarket({original:true}),candidate=await bundlePressMarket(),A=original.value,B=candidate.value;
const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),base:git('rev-parse',BASE),baseTree:git('rev-parse',BASE+'^{tree}'),sourceBefore,loaded:[...original.loaded,...candidate.loaded],groups:[],controls:[],neutral:[],fixtures:[]};
async function groups(C,retain=false){const results=[];const run=(name,fn)=>{try{const receipt=fn();if(retain)writeEvidence('outcome-'+name+'.json',receipt);results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:String(error.stack),assertion:error instanceof assert.AssertionError});}};
  run('press-answer-once',()=>{const c=soccerFixture(C),input=copy(c),outcomes=[];for(const choice of ['calm','accountable','ambitious']){const first=seeded(3,()=>C.press.answerSoccerPress(copy(c),choice));assert.equal(first.draws.length,0);assert.equal(first.value.pressRoom.history.length,1);assert.equal(first.value.popularity,c.popularity+(choice==='calm'?-2:choice==='accountable'?3:0));assert.equal(first.value.morale,c.morale+(choice==='calm'?3:choice==='accountable'?-3:-4));const held=copy(first.value),second=seeded(4,()=>C.press.answerSoccerPress(first.value,choice));assert.deepEqual(second.value,held,'Repeated answer retains the complete save');assert.equal(second.draws.length,0);assert.equal(C.press.pressRoomView(JSON.parse(JSON.stringify(held))).eligible,false);outcomes.push({choice,first,second});}assert.deepEqual(c,input);return{input,outcomes};});
  run('press-settlement-once',()=>{const outcomes=[];for(const outcome of ['met','missed','moved','excused']){const c=C.press.answerSoccerPress(soccerFixture(C),'ambitious'),p=c.pressRoom.history[0].promise,prior=copy(c),last=c.seasons.at(-1);const row={...copy(last),year:last.year+1,age:last.age+1,apps:outcome==='excused'?0:30,goals:outcome==='excused'?0:outcome==='missed'?p.target-1:p.target,club:outcome==='moved'?'Arsenal':p.club??last.club};c.seasons.push(row);const step=seeded(5,()=>{C.press.settleSoccerPress(c,row);return c;});assert.equal(step.draws.length,0);assert.equal(c.pressRoom.history[0].promise.outcome,outcome);const sign=outcome==='met'?1:outcome==='missed'?-1:0;assert.equal(c.popularity,prior.popularity+6*sign);assert.equal(c.morale,prior.morale+3*sign);assert.equal(c.pressRoom.credibility,prior.pressRoom.credibility+8*sign);const held=copy(c);C.press.settleSoccerPress(c,row);assert.deepEqual(c,held,'Completed promise cannot pay twice');const reloaded=JSON.parse(JSON.stringify(c));C.press.settleSoccerPress(reloaded,reloaded.seasons.at(-1));assert.deepEqual(reloaded,held,'Reload cannot repeat promise settlement');outcomes.push({outcome,input:prior,row,settled:held,reloaded});}return outcomes;});
  run('press-context',()=>{const c=C.press.answerSoccerPress(soccerFixture(C),'calm'),held=copy(c);c.pressRoom.history[0].source.club='Foreign saved club';assert.equal(C.press.pressRoomView(c).eligible,false);assert.equal(C.press.pressRoomView(c).history.length,0,'Wrong saved row anchor is rejected');const old=soccerFixture(C);delete old.pressRoom;const before=JSON.stringify(old),view=seeded(7,()=>C.press.pressRoomView(old));assert.equal(view.draws.length,0);assert.equal(JSON.stringify(old),before);const zero=copy(old);zero.seasons.at(-1).apps=0;assert.equal(C.press.pressRoomView(zero).eligible,false,'No backsearch past latest zero-app row');return{valid:held,foreign:c,old,view};});
  run('market-push-once',()=>{const outcomes=[];for(const sport of sportList(C)){for(const kind of ['extension','freeagency']){const input=usFixture(C,sport,kind==='extension'?1:0),snapshot=seeded(20,()=>kind==='extension'?C.market.openMarketExtension(input.c,sport.slug,sport.buildExtension(input.c,Math.random)):C.market.openMarketFreeAgency(input.c,sport.slug,sport.buildFaWindow(input.c,75,Math.random))).value;const index=0;const direct=seeded(31,()=>kind==='extension'?C.extension.pushExtension(copy(snapshot.talk),sport.extPushArgs(input.c,Math.random)):C.fa.pushFaOffer(copy(snapshot.window),index,sport.faPushArgs(input.c,Math.random)));const first=seeded(31,()=>kind==='extension'?C.market.pushMarketExtension(copy(snapshot),sport.extPushArgs(input.c,Math.random)):C.market.pushMarketFreeAgency(copy(snapshot),index,sport.faPushArgs(input.c,Math.random)));assert.deepEqual(first.draws,direct.draws,'Wrapper captures exactly the original engine stream');assert.deepEqual(kind==='extension'?first.value.talk:first.value.window,kind==='extension'?direct.value:direct.value.window);assert(first.value.wheel.draws.length>0);const ack=C.market.acknowledgeMarketWheel(first.value),held=copy(ack),second=seeded(32,()=>kind==='extension'?C.market.pushMarketExtension(ack,sport.extPushArgs(input.c,Math.random)):C.market.pushMarketFreeAgency(ack,index,sport.faPushArgs(input.c,Math.random)));assert.deepEqual(second.value,held,'Reloaded consumed offer cannot be negotiated again');assert.equal(second.draws.length,0);outcomes.push({sport:sport.slug,kind,input,snapshot,direct,first,second});}}return outcomes;});
  run('market-context',()=>{const outcomes=[];for(const sport of sportList(C)){const input=usFixture(C,sport,1),saved=seeded(20,()=>C.market.openMarketExtension(input.c,sport.slug,sport.buildExtension(input.c,Math.random))).value;assert.deepEqual(C.market.restoreMarketTalk(copy(saved),input.c,sport.slug),saved);const wrong=copy(saved);wrong.context.year+=1;assert.equal(C.market.restoreMarketTalk(wrong,input.c,sport.slug),null,'Another contract year cannot restore this talk');const before=JSON.stringify(input);const read=seeded(9,()=>C.market.restoreMarketTalk(copy(saved),input.c,sport.slug));assert.equal(read.draws.length,0);assert.equal(JSON.stringify(input),before);outcomes.push({input,saved,wrong,read});}return outcomes;});
  run('market-ack-and-comparison',()=>{const outcomes=[];for(const sport of sportList(C)){const input=usFixture(C,sport,1),saved=seeded(20,()=>C.market.openMarketExtension(input.c,sport.slug,sport.buildExtension(input.c,Math.random))).value,pushed=seeded(31,()=>C.market.pushMarketExtension(saved,sport.extPushArgs(input.c,Math.random))).value;assert.equal(pushed.wheel.result,'raised');const expected=copy(pushed);expected.wheel.seen=true;const ack=seeded(11,()=>C.market.acknowledgeMarketWheel(pushed));assert.deepEqual(ack.value,expected,'Acknowledgement changes only seen in the complete snapshot');assert.equal(ack.draws.length,0);assert.deepEqual(C.market.acknowledgeMarketWheel(ack.value),expected);const expired=usFixture(C,sport,0),window=seeded(22,()=>sport.buildFaWindow(expired.c,75,Math.random)).value,held=JSON.stringify(window),views=[];for(const priority of ['annual','total','years','roster']){const view=C.market.marketOfferComparison(window,priority),expectedOrder=window.offers.map((offer,index)=>({offer,index,value:priority==='annual'?offer.salary:priority==='total'?C.fa.faTotalValue(offer):priority==='years'?offer.years:offer.quality})).filter(v=>!v.offer.gone).sort((a,b)=>b.value-a.value||a.index-b.index);assert.deepEqual(view,expectedOrder,'Saved offers sort without changing signing indices');views.push({priority,view});}assert.equal(JSON.stringify(window),held);outcomes.push({pushed,ack,window,views});}return outcomes;});
  return results;}
const healthy=await groups(B,true);report.groups=healthy;assert(healthy.every(v=>v.ok),JSON.stringify(healthy.filter(v=>!v.ok)));
const recorded=JSON.parse(fs.readFileSync('scripts/data/careerLeagueWorldSaves1100.json','utf8')).saves.filter(v=>v.kind==='player');
for(const fixture of recorded)for(const seed of [101,102,103]){const input=copy(fixture.state);delete input.pressRoom;const originalState=seeded(seed,()=>A.engine.advanceProSeason(copy(input),A.engine.FALLBACK_CLUBS)),current=seeded(seed,()=>B.engine.advanceProSeason(copy(input),B.engine.FALLBACK_CLUBS));assert.deepEqual(current,originalState,'No active Press retains entire original season and RNG');const file=writeEvidence('neutral-soccer-'+fixture.id+'-'+seed+'.json',{input,original:originalState,current});report.neutral.push({file,sport:'soccer',drawCount:current.draws.length});}
for(let i=0;i<4;i++)for(const seed of [101,102,103]){const oldSport=sportList(A)[i],sport=sportList(B)[i];const run=(C,s)=>seeded(seed,()=>{const c=s.startCareer('Neutral Market',s.create.defaultPos,s.create.archetypes[s.create.defaultPos][0],Math.random,C.defaultAppearance(),s.create.eras[0].id),tq=s.rollTeamQuality(null,Math.random);s.assignRole(c,tq,Math.random);const camp=s.campBattle(c,tq,Math.random),season=s.simSeason(c,tq,Math.random);s.progress(c,Math.random);return{c,tq,camp,season};});const a=run(A,oldSport),b=run(B,sport);assert.deepEqual(b,a,'No active Market retains the entire original sport state and RNG');const file=writeEvidence('neutral-'+sport.slug+'-'+seed+'.json',{original:a,current:b});report.neutral.push({file,sport:sport.slug,drawCount:b.draws.length});}
assert.equal(report.neutral.length,27);assert(report.neutral.every(v=>v.drawCount>0));
const controls=[
 {id:'press-repeat',group:'press-answer-once',file:'src/lib/soccerCareerPress.ts',from:'state?.history.some(h => h.source.index === source.index)',to:'false'},
 {id:'press-pay-twice',group:'press-settlement-once',file:'src/lib/soccerCareerPress.ts',from:"h.promise?.outcome === 'pending' && index > h.source.index",to:'!!h.promise && index > h.source.index'},
 {id:'press-wrong-club',group:'press-context',file:'src/lib/soccerCareerPress.ts',from:'row.club === source.club',to:'true'},
 {id:'market-repeat',group:'market-push-once',file:'src/lib/usCareerMarket.ts',from:'saved.declined || saved.talk.pushed || !saved.talk.offer',to:'saved.declined || false || !saved.talk.offer'},
 {id:'market-wrong-year',group:'market-context',file:'src/lib/usCareerMarket.ts',from:'v.year === c.year',to:'true'},
 {id:'market-ack-rewrites',group:'market-ack-and-comparison',file:'src/lib/usCareerMarket.ts',from:'{ ...saved.wheel, seen: true }',to:"{ ...saved.wheel, seen: true, result: 'held' }"},
];
for(const control of controls){const faulty=await bundlePressMarket({patches:[control]}),actual=await groups(faulty.value),failed=actual.filter(v=>!v.ok);assert.deepEqual(failed.map(v=>v.name),[control.group],'Exact intended copied source failure');assert(failed.every(v=>v.assertion),'Reject import/setup errors');assert.equal(actual.filter(v=>v.ok).length,5,'All unrelated outcome groups pass');report.controls.push({id:control.id,faults:faulty.faults,groups:actual,expectedFailure:control.group,unrelatedPassed:5,scope:'Copied production helper loaded into actual engine bundle'});console.log('CONTROL FIRED '+control.id+': '+control.group);}
const native=[];for(const choice of ['calm','accountable'])native.push({id:choice,slug:'soccer-career',key:'soccerCareerSave',value:soccerFixture(B),choice});
for(const desired of ['met','missed','moved','excused']){let input=soccerFixture(B);if(desired==='missed')input.seasons.at(-1).goals=90;if(desired==='excused')input.matchFixBanned=2;let prepared=false;
  if(desired==='moved'){input=B.press.answerSoccerPress(input,'ambitious');const destination=B.engine.FALLBACK_CLUBS.find(c=>c.name!==input.currentClub&&c.name==='Arsenal');assert(destination);input=B.engine.acceptOffer(input,{club:destination,contractYears:4,wage:50000,transferFee:10});assert.equal(input.phase,'playing');prepared=true;}
  const answered=prepared?copy(input):B.press.answerSoccerPress(copy(input),'ambitious');let selected=null;for(let seed=1;seed<=180;seed++){const actual=seeded(seed,()=>B.engine.advanceProSeason(copy(answered),B.engine.FALLBACK_CLUBS));if(actual.value.pressRoom?.history[0]?.promise?.outcome===desired){selected={seed,expected:actual};break;}}assert(selected,'Actual engine fixture exists for '+desired);native.push({id:desired,slug:'soccer-career',key:'soccerCareerSave',value:input,choice:prepared?null:'ambitious',prepared,settlement:selected,scope:prepared?'Promise and actual acceptOffer prepared by real helpers before browser. Native NextSeason settles it.':'Actual browser answer then actual NextSeason.'});}
for(const sport of sportList(B))for(const kind of ['extension','freeagency','decline'])native.push({id:kind,slug:sport.gameSlug,sport:sport.slug,key:sport.saveKey,value:usFixture(B,sport,kind==='freeagency'?0:1),kind});
assert.equal(native.length,18);writeEvidence('native-fixtures.json',native);report.fixtures=native.map(({value,...v})=>({...v,inputSha256:sha(JSON.stringify(value))}));report.sourceAfter=sourceReceipt(sourceFiles);assert.deepEqual(report.sourceAfter,sourceBefore);writeEvidence('outcomes.json',report);console.log('Press/Market:6 outcomes,27 full original state/RNG pairs,6 effective copied source controls,18 native fixture branches.');