// Remote-only complete engine outputs and independently filtered saved search pools.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import {BASE,copy,git,sha,seeded,bundleTransferBrief,recordedPlayers,transferFixture,independentEligible,independentMatching,legacyRequest,findRequest,sourceReceipt,writeEvidence} from './qa/careerTransferBriefKit.mjs';
assert(process.env.CI,'Transfer Brief outcomes run on remote CI');
const files=['src/lib/soccerCareerTransferBrief.ts','src/lib/soccerCareerEngine.ts','src/components/soccer-career/AgentBrief.tsx','src/pages/SoccerCareer.tsx'],sourceBefore=sourceReceipt(files);
const original=await bundleTransferBrief({original:true}),candidate=await bundleTransferBrief(),A=original.value,B=candidate.value;
const report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),base:BASE,baseTree:git('rev-parse',BASE+'^{tree}'),sourceBefore,loaded:[...original.loaded,...candidate.loaded],groups:[],controls:[],neutral:[],fixtures:[]};
for(const fixture of recordedPlayers())for(const seed of [101,102,103]){
 const input=copy(fixture.state);delete input.transferBrief;const before=copy(input),a=seeded(seed,()=>A.engine.advanceProSeason(copy(input),A.engine.FALLBACK_CLUBS)),b=seeded(seed,()=>B.engine.advanceProSeason(copy(input),B.engine.FALLBACK_CLUBS));
 assert.deepEqual(b,a,'Absent brief keeps the full original season and every RNG draw');assert.deepEqual(input,before);
 report.neutral.push({kind:'season',file:writeEvidence('neutral-season-'+fixture.id+'-'+seed+'.json',{input,original:a,current:b}),drawCount:b.draws.length});
 for(const context of ['absent','stale','malformed']){const input=transferFixture(B,fixture.id);if(context==='stale'){const held=B.brief.setTransferBrief(input,'minutes');input.transferBrief=copy(held.transferBrief);input.transferBrief.context.lastYear+=1;}if(context==='malformed')input.transferBrief={version:0,priority:'invalid',context:[]};const before=copy(input),a=seeded(seed,()=>legacyRequest(A,copy(input))),b=seeded(seed,()=>B.engine.requestTransferDecision(copy(input),B.engine.FALLBACK_CLUBS));assert.deepEqual(b,a,'Absent/stale brief keeps the complete actual legacy request action and RNG');assert.deepEqual(input,before);report.neutral.push({kind:context,file:writeEvidence('neutral-request-'+fixture.id+'-'+seed+'-'+context+'.json',{input,original:a,current:b}),drawCount:b.draws.length});}
}
assert.equal(report.neutral.length,60);assert(report.neutral.every(v=>v.drawCount>0));
function groups(C,retain=false){const results=[];const run=(name,fn)=>{try{const receipt=fn();if(retain)writeEvidence('outcome-'+name+'.json',receipt);results.push({name,ok:true});}catch(error){results.push({name,ok:false,error:String(error.stack),assertion:error instanceof assert.AssertionError});}};
 for(const priority of ['minutes','level','home'])run(priority+'-pool',()=>{const receipts=[];for(const id of ['ere','cha','her']){const input=transferFixture(C,id),before=copy(input),chosen=seeded(3,()=>C.brief.setTransferBrief(input,priority));assert.equal(chosen.draws.length,0);assert.deepEqual(input,before,'Choosing never mutates the previous save');const eligible=independentEligible(C,input),matching=independentMatching(C,input,priority),view=seeded(4,()=>C.engine.transferBriefPreview(chosen.value,C.engine.FALLBACK_CLUBS)),option=view.value.options.find(v=>v.id===priority);assert.equal(view.draws.length,0);assert.equal(option.eligibleCount,eligible.length);assert.equal(option.matchingCount,matching.length);assert.deepEqual(C.brief.transferBriefCandidates(chosen.value,eligible,C.engine.projectLeagueApps),matching,'Priority chooses exactly the independently ranked existing clubs');const expectedBands=matching.map(club=>C.engine.projectLeagueApps(input.overall,club.tier,club.name,0));assert.deepEqual(option.projection,expectedBands.length?{min:Math.min(...expectedBands.map(v=>v.min)),max:Math.max(...expectedBands.map(v=>v.max))}:null);const request=findRequest(C,input,priority,'offered'),result=C.brief.transferBriefResult(request.expected.value,C.engine.projectLeagueApps);assert(matching.some(club=>JSON.stringify(club)===JSON.stringify(result.offer.club)),'Actual offered club belongs to the exact matching pool');assert.deepEqual(result.projection,C.engine.projectLeagueApps(input.overall,result.offer.club.tier,result.offer.club.name,0));receipts.push({input,chosen,eligible,matching,view,request});}return receipts;});
 run('no-home-and-declined',()=>{const noHome=transferFixture(C);noHome.nationality='Uganda';assert.equal(C.engine.transferBriefPreview(noHome,C.engine.FALLBACK_CLUBS).options.find(v=>v.id==='home').matchingCount,0,'No eligible home pool');const selected=findRequest(C,noHome,'home','no_match'),home=selected.chosen,before=copy(home),result=selected.expected;assert.equal(C.brief.transferBriefResult(result.value,C.engine.projectLeagueApps).status,'no_match','No eligible home club never falls back abroad');assert.equal(C.brief.transferBriefResult(result.value,C.engine.projectLeagueApps).offer,null);assert.equal(result.draws.length,2,'Empty matching pool retains the original response and tier draws');assert.deepEqual(home,before);const declined=findRequest(C,transferFixture(C),'minutes','no_interest');assert.equal(declined.expected.draws.length,1,'Declined response uses just the unchanged 50 percent draw');assert.equal(declined.expected.value.phase,'transfer_window');assert.equal(declined.expected.value.transferSituation.offer,null);return{noHome:before,result,declined};});
 run('held-result-once',()=>{const selected=findRequest(C,transferFixture(C),'minutes','offered'),held=copy(selected.expected.value),reload=JSON.parse(JSON.stringify(held)),repeat=seeded(72,()=>C.engine.requestTransferDecision(reload,C.engine.FALLBACK_CLUBS));assert.equal(repeat.draws.length,0,'Saved request response cannot draw again');assert.deepEqual(repeat.value,held,'Saved actual offer cannot reroll after reload');const set=seeded(73,()=>C.brief.setTransferBrief(copy(held),'level'));assert.deepEqual(set.value,held,'Completed window cannot change priority');assert.equal(set.draws.length,0);return{selected,reload,repeat,set};});
 run('invalid-context',()=>{const valid=C.brief.setTransferBrief(transferFixture(C),'minutes'),wrong=copy(valid);wrong.transferBrief.context.lastYear+=1;assert.equal(C.brief.readTransferBrief(wrong),null,'Another saved year cannot opt into this request');const broken=copy(valid);broken.transferBrief.context.club='Foreign club';assert.equal(C.brief.readTransferBrief(broken),null,'Another club cannot opt into this request');const input=copy(wrong),a=seeded(44,()=>legacyRequest(A,copy(input))),b=seeded(44,()=>C.engine.requestTransferDecision(copy(input),C.engine.FALLBACK_CLUBS));assert.deepEqual(b,a,'Stale request follows entire unchanged legacy state and draws');return{valid,wrong,broken,original:a,current:b};});
 run('clear-on-sign-stay',()=>{const selected=findRequest(C,transferFixture(C),'minutes','offered'),input=copy(selected.expected.value),oldInput=copy(input);delete oldInput.transferBrief;const offer=copy(input.transferSituation.offer),signed=seeded(40,()=>C.engine.acceptOffer(copy(input),offer)),oldSigned=seeded(40,()=>A.engine.acceptOffer(copy(oldInput),copy(offer)));assert.deepEqual(signed,oldSigned,'Signing consumes only the brief and preserves the complete original acceptance');assert(!Object.prototype.hasOwnProperty.call(signed.value,'transferBrief'));const stay=seeded(41,()=>C.engine.stayAtClub(copy(input))),oldStay=seeded(41,()=>A.engine.stayAtClub(copy(oldInput)));assert.deepEqual(stay,oldStay,'Stay consumes only the brief and preserves the complete original Stay action');assert(!Object.prototype.hasOwnProperty.call(stay.value,'transferBrief'));return{input,originalInputWithoutOptIn:oldInput,signed,oldSigned,stay,oldStay};});
 run('receipt-integrity',()=>{const selected=findRequest(C,transferFixture(C),'minutes','offered'),valid=copy(selected.expected.value);assert(C.brief.readTransferBrief(valid,C.engine.projectLeagueApps));assert.equal(C.brief.readTransferBrief(valid),null,'Offered result requires its actual projection callback');const wrong=copy(valid);wrong.transferBrief.result.projection={min:0,max:38};const actual=C.engine.projectLeagueApps(valid.overall,valid.transferSituation.offer.club.tier,valid.transferSituation.offer.club.name,0);assert.notDeepEqual(wrong.transferBrief.result.projection,actual);assert.equal(C.brief.transferBriefResult(wrong,C.engine.projectLeagueApps),null,'Wrong saved projection cannot become a truthful offer receipt');const before=JSON.stringify(valid);C.brief.transferBriefResult(valid,C.engine.projectLeagueApps);assert.equal(JSON.stringify(valid),before,'Projection reads never rewrite the full valid receipt');return{valid,wrong,actual};}); run('compulsory-moves',()=>{const receipts=[];for(const mode of ['loan','sale']){const input=transferFixture(C),club=C.engine.FALLBACK_CLUBS.find(v=>v.name==='Arsenal'),offer={club,contractYears:3,wage:50000,transferFee:25,...(mode==='loan'?{isLoan:true}:{})};input.transferSituation={type:'frozen_out',mode:mode==='loan'?'loan_listed':'transfer_listed',reasons:['Explicit simulation fixture: club chose destination.'],offers:[offer]};const a=seeded(52,()=>A.engine.completeClubVerdictMove(copy(input))),b=seeded(52,()=>C.engine.completeClubVerdictMove(copy(input)));assert.deepEqual(b,a,'Club-arranged sale/loan retains every original state field and draw');assert.equal(b.value.transferSituation.type,'club_move');const before=copy(b.value),set=C.brief.setTransferBrief(b.value,'minutes');assert.deepEqual(set,before,'Brief cannot cancel or reroute a compulsory move');const request=seeded(53,()=>C.engine.requestTransferDecision(copy(before),C.engine.FALLBACK_CLUBS));assert.deepEqual(request.value,before,'Direct repeat request never reverses compulsory destination');assert.equal(request.draws.length,0);receipts.push({input,original:a,current:b,request});}const loan=transferFixture(C);loan.loan={parentClub:'Arsenal',parentTier:1,parentLeague:'Premier League',parentCountry:'England',parentColor:'#ef0000'};assert.deepEqual(C.brief.setTransferBrief(loan,'home'),loan);return receipts;});
 return results;
}
report.groups=groups(B,true);writeEvidence('outcomes.json',report);assert(report.groups.every(v=>v.ok),JSON.stringify(report.groups.filter(v=>!v.ok)));
// Copied production anchors are filled from the unique actual authored contracts below.
const controls=[
 {id:'minutes-rank',groups:['minutes-pool'],file:'src/lib/soccerCareerTransferBrief.ts',from:'row.band.min === min && row.band.max === max',to:'row.band.min <= min && row.band.max <= max'},
 {id:'level-rank',groups:['level-pool'],file:'src/lib/soccerCareerTransferBrief.ts',from:'club.tier === tier',to:'club.tier >= tier'},
 {id:'home-country',groups:['home-pool','no-home-and-declined'],file:'src/lib/soccerCareerTransferBrief.ts',from:'club.country === career.nationality',to:'true'},
 {id:'wrong-year',groups:['invalid-context'],file:'src/lib/soccerCareerTransferBrief.ts',from:'Object.keys(context).some(key => heldContext[key] !== context[key as keyof TransferBriefContext])',to:"Object.keys(context).filter(key => key !== 'lastYear').some(key => heldContext[key] !== context[key as keyof TransferBriefContext])"},
 {id:'request-reroll',groups:['held-result-once'],file:'src/lib/soccerCareerEngine.ts',from:'if (brief?.result) return prev;',to:'if (brief?.result) { const result = requestTransfer(prev, clubs); return { ...prev, transferSituation: result }; }'},
 {id:'keep-spent-brief',groups:['clear-on-sign-stay'],file:'src/lib/soccerCareerTransferBrief.ts',from:'if (readTransferBrief(previous, project)) delete next.transferBrief;',to:'if (false) delete next.transferBrief;'},
 {id:'wrong-projection',groups:['receipt-integrity'],file:'src/lib/soccerCareerTransferBrief.ts',from:'band.min !== value.result.projection!.min || band.max !== value.result.projection!.max',to:'false'},
 {id:'compulsory-reroute',groups:['compulsory-moves'],file:'src/lib/soccerCareerEngine.ts',from:"|| !['no_interest', 'one_offer', 'dream_club'].includes(prev.transferSituation.type)",to:'|| false'},
];
for(const control of controls){const faulty=await bundleTransferBrief({patches:[control]}),actual=groups(faulty.value),failed=actual.filter(v=>!v.ok);assert.deepEqual(failed.map(v=>v.name),control.groups,'Exact intended copied source failures');assert(failed.every(v=>v.assertion),'Import/setup errors do not count as controls');assert.equal(actual.filter(v=>v.ok).length,9-control.groups.length);report.controls.push({id:control.id,faults:faulty.faults,loaded:faulty.loaded,groups:actual,expectedFailures:control.groups,scope:'One independently compiled copied production fault'});console.log('CONTROL FIRED '+control.id+': '+control.groups.join(','));}
const fixtures=[];for(const [id,priority,status,action]of [['minutes','minutes','offered','sign'],['level','level','offered','stay'],['home','home','offered','sign'],['no-home','home','no_match','stay'],['declined','minutes','no_interest','stay'],['saved-offer','minutes','offered','sign']]){const input=transferFixture(B);if(id==='no-home')input.nationality='Uganda';if(id==='saved-offer'){const club=B.engine.FALLBACK_CLUBS.find(v=>v.name==='Anderlecht');assert(club);input.transferSituation={type:'one_offer',offer:{club,contractYears:2,wage:20000,transferFee:15}};}const request=findRequest(B,input,priority,status);fixtures.push({id,key:'soccerCareerSave',value:input,priority,status,action,seed:request.seed,expected:request.expected,scope:'Captured career with explicitly held game-simulation transfer context. Actual request and offer terms generated by current engine.'});}
for(const mode of ['loan','sale']){const input=transferFixture(B),club=B.engine.FALLBACK_CLUBS.find(v=>v.name==='Arsenal'),offer={club,contractYears:3,wage:50000,transferFee:25,...(mode==='loan'?{isLoan:true}:{})};input.transferSituation={type:'frozen_out',mode:mode==='loan'?'loan_listed':'transfer_listed',reasons:['Explicit simulation fixture: club chose destination.'],offers:[offer]};const moved=seeded(70,()=>B.engine.completeClubVerdictMove(input));fixtures.push({id:'mandatory-'+mode,key:'soccerCareerSave',value:moved.value,mandatory:true,mode,scope:'Actual engine club verdict move prepared before browser. Native only acknowledges the already applied destination.'});}
const malformed=findRequest(B,transferFixture(B),'minutes','no_interest').expected.value;malformed.transferBrief.result.projection={min:99,max:0};fixtures.push({id:'malformed',key:'soccerCareerSave',value:malformed,malformed:true,action:'stay',scope:'Explicit malformed held receipt. Native recover action, no fabricated offer or new search.'});
assert.equal(fixtures.length,9);writeEvidence('native-fixtures.json',fixtures);report.fixtures=fixtures.map(({value,...v})=>({...v,inputSha256:sha(JSON.stringify(value)),file:writeEvidence('fixture-'+v.id+'.json',value)}));report.sourceAfter=sourceReceipt(files);assert.deepEqual(report.sourceAfter,sourceBefore);writeEvidence('outcomes.json',report);console.log('Transfer Brief:9 healthy outcome groups,60 full original state/RNG pairs,8 effective copied source controls,9 prepared native branches.');