/* The Footle fallback pool says what the table says, and nobody typed it.
 *
 * Round 531. src/data/players.ts is generated by scripts/bakePlayers.mjs from
 * player_market_values (year 2026) plus the verified window overlay. It is the
 * pool Footle plays when the table is unreachable and it is read by Squad
 * Deal, Club Manager, Perfect Lineup, Sports Bingo and Gauntlet Draft, so a
 * wrong row there is a wrong answer in six games. Before this round it was 748
 * hand typed rows with one dating comment and no check.
 *
 * WHAT THIS HOLDS:
 *   1. THE HEADER names the bake script and carries its date, so a reader
 *      knows where the rows came from and how old they are.
 *   2. THE SMELL LIST, over every row: age inside the bake's window, value
 *      above zero, whole non negative goals and assists, no duplicate name
 *      (exact or accent folded), a position and a league the Player type
 *      knows (never 'Other'), a nationality, a club, a kit number that is null
 *      or a real squad number. Plus a floor on the pool and on every tier, so
 *      an empty bake cannot pass.
 *   3. THE TABLE, fetched fresh by name: every row agrees with its live row on
 *      club, league (through the bake's own resolver), nationality, position
 *      (a table goalkeeper is GK and nobody else is), age, value, goals and
 *      assists. At least 200 rows must answer or nothing was checked.
 *   4. FRESHNESS: the file equals a fresh bake byte for byte (line endings
 *      aside), so a hand edit, a stale re-import or a moved rule shows here.
 *
 * NEGATIVE CONTROLS (house rule: prove each check can fail), applied to a
 * temporary copy of the file, never to the file itself:
 *   PLAYERS_CONTROL=handedit  one club rewritten; sections 3 and 4 must go red.
 *   PLAYERS_CONTROL=agezero   one age set to 0; section 2 must go red.
 * Each refuses to run if the string it rewrites is not in the file.
 *
 * Needs the database. When it cannot be reached it says so and checks nothing.
 *
 * Run: node scripts/simPlayersPool.mjs
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import {
  AGE_MAX, AGE_MIN, OUT_PATH, ROOT, ROW_SELECT,
  applyOverlay, bake, buildLeagueResolver, leagueUnion, loadApp, rest,
} from './bakePlayers.mjs';

const CONTROL = process.env.PLAYERS_CONTROL || '';
if (CONTROL && CONTROL !== 'handedit' && CONTROL !== 'agezero') {
  console.error(`PLAYERS_CONTROL=${CONTROL} is not a control this harness knows (handedit, agezero)`);
  process.exit(1);
}
const failures = { 1: 0, 2: 0, 3: 0, 4: 0 };
let section = 1;
const fail = m => { failures[section] += 1; console.error('  FAIL: ' + m); };
const abort = m => { console.error(m); process.exit(1); };
const lf = t => t.replace(/\r\n/g, '\n');

/* Floors, from the 2026-09-11 bake: 529 rows, easy 158, hard 200, insane 171. */
const POOL_FLOOR = 400;
const TIER_FLOOR = 100;

/* ---------------- the file, or a doctored copy of it ---------------- */
let text = lf(fs.readFileSync(OUT_PATH, 'utf8'));
if (CONTROL === 'handedit') {
  const old = 'club: "Manchester City"';
  if (!text.includes(old)) abort(`control cannot run: ${old} is not in the file`);
  const doctored = text.replace(old, 'club: "Manchester Blue"');
  if (doctored === text) abort('control changed nothing');
  text = doctored;
  console.log('   NEGATIVE CONTROL ON: one Manchester City row now says Manchester Blue');
}
if (CONTROL === 'agezero') {
  const m = text.match(/age: (\d+),/);
  if (!m) abort('control cannot run: no age field in the file');
  const doctored = text.replace(m[0], 'age: 0,');
  if (doctored === text) abort('control changed nothing');
  text = doctored;
  console.log(`   NEGATIVE CONTROL ON: one age ${m[1]} rewritten to 0`);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'dukb-players-pool-'));
const copy = path.join(tmp, 'players.ts');
fs.writeFileSync(copy, text);
const entry = path.join(tmp, 'entry.ts');
const bundle = path.join(tmp, 'bundle.mjs');
fs.writeFileSync(entry, `export { players } from '${copy.replaceAll('\\', '/')}';\n`);
await build({ entryPoints: [entry], bundle: true, format: 'esm', platform: 'node', outfile: bundle, logLevel: 'silent', alias: { '@': path.join(ROOT, 'src') } });
const { players } = await import(pathToFileURL(bundle).href);
const app = await loadApp();

/* ---------------- 1. header ---------------- */
section = 1;
console.log('1) The header names the bake and its date');
{
  const first = text.split('\n')[0];
  const m = first.match(/^\/\/ GENERATED by scripts\/bakePlayers\.mjs on (\d{4}-\d{2}-\d{2})\./);
  if (!m) fail(`first line does not name the bake and a date: "${first.slice(0, 80)}"`);
  else if (Number.isNaN(Date.parse(m[1])) || Date.parse(m[1]) > Date.now()) fail(`bake date ${m[1]} is not a real past date`);
  else console.log(`   generated ${m[1]} by scripts/bakePlayers.mjs`);
  if (!text.includes('DO NOT EDIT BY HAND')) fail('the header does not warn against hand edits');
  if (!fs.existsSync(path.join(ROOT, 'scripts', 'bakePlayers.mjs'))) fail('the named bake script does not exist');
}

/* ---------------- 2. smell list ---------------- */
section = 2;
console.log(`2) The smell list over every row (${players.length} rows)`);
{
  const typesSrc = fs.readFileSync(path.join(ROOT, 'src', 'types', 'game.ts'), 'utf8');
  const posM = typesSrc.match(/export type Position = ([^;]+);/);
  if (!posM) abort('Position union not found in src/types/game.ts');
  const positions = new Set([...posM[1].matchAll(/'([^']+)'/g)].map(x => x[1]));
  const leagues = leagueUnion();
  const exact = new Set();
  const folded = new Set();
  const tiers = { easy: 0, hard: 0, insane: 0 };
  for (const p of players) {
    const who = p.name || '(no name)';
    if (!p.name || !String(p.name).trim()) fail('a row has no name');
    if (exact.has(p.name)) fail(`${who}: duplicate name`);
    exact.add(p.name);
    const k = app.normalizeName(p.name);
    if (folded.has(k)) fail(`${who}: duplicate name once accents and case are folded`);
    folded.add(k);
    if (!Number.isInteger(p.age) || p.age < AGE_MIN || p.age > AGE_MAX) fail(`${who}: age ${p.age} is outside ${AGE_MIN}..${AGE_MAX}`);
    if (!Number.isInteger(p.marketValue) || p.marketValue <= 0) fail(`${who}: market value ${p.marketValue} is not above zero`);
    if (!Number.isInteger(p.goals) || p.goals < 0) fail(`${who}: goals ${p.goals}`);
    if (!Number.isInteger(p.assists) || p.assists < 0) fail(`${who}: assists ${p.assists}`);
    if (!positions.has(p.position)) fail(`${who}: position "${p.position}" is not in the Position union`);
    if (!leagues.has(p.league) || p.league === 'Other') fail(`${who}: league "${p.league}" is not a real league in the union`);
    if (!p.nationality || !String(p.nationality).trim()) fail(`${who}: no nationality`);
    if (!p.club || !String(p.club).trim() || p.club === 'Without Club') fail(`${who}: no club ("${p.club}")`);
    if (!(p.kitNumber === null || (Number.isInteger(p.kitNumber) && p.kitNumber >= 1 && p.kitNumber <= 99))) fail(`${who}: kit number ${p.kitNumber} is neither null nor a squad number`);
    if (!(p.difficulty in tiers)) fail(`${who}: difficulty "${p.difficulty}"`);
    else tiers[p.difficulty] += 1;
  }
  if (players.length < POOL_FLOOR) fail(`only ${players.length} rows, floor ${POOL_FLOOR}`);
  for (const [t, n] of Object.entries(tiers)) if (n < TIER_FLOOR) fail(`${t} tier has ${n} rows, floor ${TIER_FLOOR}`);
  console.log(`   ${players.length} rows: easy ${tiers.easy}, hard ${tiers.hard}, insane ${tiers.insane}; ${failures[2]} smell(s)`);
}

/* ---------------- 3. the table, fetched fresh ---------------- */
section = 3;
console.log('3) Every row agrees with its live 2026 row');
{
  const names = players.map(p => p.name);
  const live = [];
  for (let i = 0; i < names.length; i += 40) {
    const list = names.slice(i, i + 40).map(n => `"${n.replace(/"/g, '\\"')}"`).join(',');
    let page;
    try {
      ({ rows: page } = await rest(`player_market_values?select=${ROW_SELECT}&year=eq.2026&player_name=in.(${encodeURIComponent(list)})&limit=200`));
    } catch (err) {
      abort(`\n${String(err.message || err)}. NOTHING WAS CHECKED.`);
    }
    live.push(...page);
  }
  applyOverlay(live);
  const resolveLeague = buildLeagueResolver(app);
  const byName = new Map();
  for (const r of live) (byName.get(r.player_name) ?? byName.set(r.player_name, []).get(r.player_name)).push(r);
  let checked = 0;
  let missing = 0;
  for (const p of players) {
    const rows = byName.get(p.name) || [];
    if (rows.length !== 1) { missing += 1; fail(`${p.name}: ${rows.length} live 2026 rows (expected exactly one)`); continue; }
    const r = rows[0];
    checked += 1;
    if (r.club !== p.club) fail(`${p.name}: club "${p.club}" but the table says "${r.club}"`);
    if (r.nationality !== p.nationality) fail(`${p.name}: nationality "${p.nationality}" but the table says "${r.nationality}"`);
    if (r.age !== p.age) fail(`${p.name}: age ${p.age} but the table says ${r.age}`);
    const pos = app.POSITION_NORMALIZE[r.position ?? ''];
    if (pos !== p.position) fail(`${p.name}: position ${p.position} but the table's "${r.position}" normalises to ${pos}`);
    if ((r.position === 'Goalkeeper') !== (p.position === 'GK')) fail(`${p.name}: keeper mismatch (table "${r.position}", file ${p.position})`);
    const lg = resolveLeague(r.club);
    if (lg.league !== p.league) fail(`${p.name}: league "${p.league}" but the club "${r.club}" resolves to ${lg.league ?? `nothing (${lg.reason})`}`);
    if (r.goals !== p.goals || r.assists !== p.assists) fail(`${p.name}: goals/assists ${p.goals}/${p.assists} but the table says ${r.goals}/${r.assists}`);
    const value = Math.max(1, Math.round(Number(r.market_value_usd) / 1_000_000));
    if (value !== p.marketValue) fail(`${p.name}: value ${p.marketValue} but the table's ${r.market_value_usd} rounds to ${value}`);
  }
  if (checked < 200) fail(`only ${checked} rows could be checked against a live row (floor 200)`);
  console.log(`   ${checked} rows checked against the live table, ${missing} without exactly one live row, ${failures[3]} disagreement(s)`);
}

/* ---------------- 4. a fresh bake ---------------- */
section = 4;
console.log('4) The file equals a fresh bake, byte for byte');
{
  let fresh;
  try { fresh = await bake(); } catch (err) { abort(`\n${String(err.message || err)}. NOTHING WAS CHECKED.`); }
  const a = lf(fresh.text);
  if (a !== text) {
    const al = a.split('\n');
    const bl = text.split('\n');
    let i = 0;
    while (i < al.length && i < bl.length && al[i] === bl[i]) i += 1;
    fail(`the file differs from a fresh bake at line ${i + 1}: file "${(bl[i] ?? '(end)').slice(0, 90)}" versus bake "${(al[i] ?? '(end)').slice(0, 90)}"`);
    if (al.length !== bl.length) fail(`the file has ${bl.length} lines, a fresh bake ${al.length}`);
  } else {
    console.log(`   identical: ${fresh.pool.length} rows, dated ${fresh.date}`);
  }
}

fs.rmSync(tmp, { recursive: true, force: true });

/* ---------------- verdict ---------------- */
const total = Object.values(failures).reduce((s, n) => s + n, 0);
if (CONTROL === 'handedit') {
  if (failures[3] > 0 && failures[4] > 0) { console.log(`\nsimPlayersPool control handedit: green. Sections 3 and 4 went red (${failures[3]} and ${failures[4]} findings).`); process.exit(0); }
  console.error(`\nsimPlayersPool control handedit: RED. Sections 3 (${failures[3]}) and 4 (${failures[4]}) had to fail and did not both.`);
  process.exit(1);
}
if (CONTROL === 'agezero') {
  if (failures[2] > 0) { console.log(`\nsimPlayersPool control agezero: green. Section 2 went red (${failures[2]} findings).`); process.exit(0); }
  console.error('\nsimPlayersPool control agezero: RED. Section 2 had to fail and did not.');
  process.exit(1);
}
if (total > 0) { console.error(`\nsimPlayersPool: RED, ${total} failure(s)`); process.exit(1); }
console.log(`\nsimPlayersPool: green (${players.length} rows, header, smell list, live table and fresh bake all hold)`);
