import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {BASE,KEY,OUT,action,agentPlayer,bundleAgentReview,capturedPlayers,copy,evidence,findPlayedSeason,finishAgentYear,git,seeded,sourceReceipt} from './qa/soccerAgentReviewKit.mjs';
const held=['src/lib/soccerAgentReview.ts','src/lib/soccerCareerLife.ts','src/lib/soccerCareerEngine.ts','src/pages/SoccerCareer.tsx','src/components/soccer-career/AgentReviewCard.tsx','scripts/simSoccerAgentReview.mjs','scripts/qa/soccerAgentReviewKit.mjs'];
const rounded=value=>Math.round(value*100)/100;
export function expectedAgent(B,input,target){
 const from=B.life.AGENTS.find(a=>a.id===input.agentId),to=B.life.AGENTS.find(a=>a.id===target),source=input.seasons.at(-1);assert(from&&to&&from.id!==to.id);
 return {...copy(input),agentId:to.id,agentReview:{version:1,sourceCount:input.seasons.length,sourceYear:source.year,sourceAge:source.age,fromAgent:from.id,toAgent:to.id},events:[...input.events,`Changed representation from ${from.name} to ${to.name}. Existing wages and contracts stay the same; future deals use your new agent's terms.`]};
}
export function prepareAgentFixtures(B){
 return B.life.AGENTS.map(agent=>{
  const input=agentPlayer(B,{agentId:agent.id==='cousin'?'shark':'cousin',contractYearsLeft:1}),changed=expectedAgent(B,input,agent.id);
  assert.deepEqual(seeded(10,()=>action(B,'choose',copy(input),agent.id)),{value:changed,draws:[]});
  const played=findPlayedSeason(B,changed,(next,row)=>row.club===input.currentClub&&next.currentClub===input.currentClub&&row.apps>0);
  return{id:agent.id,key:KEY,target:agent.id,input,changed,seed:played.seed,played:played.next,scope:'Explicitly held simulated adult context from a complete captured save. Choice and recorded future year use unchanged helpers and actual engine.'};
 });
}
function actualOffer(B,input){for(let seed=1;seed<=100;seed++){const result=seeded(seed,()=>B.engine.requestTransfer(copy(input),B.engine.FALLBACK_CLUBS));if(result.value.offer?.transferFee>0)return{seed,...result};}throw Error('No actual positive-fee offer in bounded engine preparation');}
function groups(B,O,fixtures,prefix){
 const result=[];const run=(name,fn)=>{const data={};try{fn(data);result.push({name,ok:true,file:evidence(prefix+'-'+name+'.json',data)});}catch(error){result.push({name,ok:false,assertion:error instanceof assert.AssertionError,error:String(error.stack??error),file:evidence(prefix+'-'+name+'.json',data)});}};
 run('change-whole-state',data=>{data.cases=[];for(const f of fixtures){const input=copy(f.input),before=JSON.stringify(input),actual=seeded(20,()=>action(B,'choose',input,f.target)),expected=expectedAgent(B,f.input,f.target);data.cases.push({input:f.input,target:f.target,actual,expected});assert.deepEqual(actual,{value:expected,draws:[]});assert.equal(JSON.stringify(input),before);assert.equal(actual.value.weeklyWage,input.weeklyWage);assert.equal(actual.value.agentFeesPaid,input.agentFeesPaid);}const input=copy(fixtures[0].input);for(const target of [input.agentId,'missing','',null]){const actual=seeded(21,()=>action(B,'choose',input,target));assert.equal(actual.value,input);assert.deepEqual(actual.draws,[]);}});
 run('eligibility-fail-closed',data=>{data.cases=[];for(const patch of [{age:18},{age:45},{retired:true},{phase:'season_summary'},{agentId:null},{agentId:'unknown'},{currentClubTier:99},{pendingSummary:{}},{pendingRehab:{}},{pendingEvents:[{}]},{pendingBallonDor:{}},{pendingWorldCup:{}},{pendingTournament:{}},{pendingRivalryEvent:{}}]){const input={...copy(fixtures[1].input),...patch},read=seeded(30,()=>action(B,'read',input)),actual=seeded(31,()=>action(B,'choose',input,'shark'));data.cases.push({input,read,actual});assert.equal(read.value.eligibility.available,false);assert.deepEqual(read.draws,[]);assert.equal(actual.value,input);assert.deepEqual(actual.draws,[]);}});
 run('receipt-integrity',data=>{data.cases=[];const valid=fixtures[1].changed;for(const patch of [{version:2},{sourceYear:valid.agentReview.sourceYear+1},{sourceCount:valid.seasons.length+1},{sourceAge:valid.age-1},{fromAgent:'unknown'},{toAgent:'unknown'},{fromAgent:valid.agentReview.toAgent},{extra:true}]){const input={...copy(valid),agentReview:{...valid.agentReview,...patch}},before=JSON.stringify(input),read=seeded(40,()=>action(B,'read',input)),actual=seeded(41,()=>action(B,'choose',input,'self'));data.cases.push({input,read,actual});assert.equal(read.value.receipt,null);assert.equal(read.value.eligibility.available,false);assert.deepEqual(read.draws,[]);assert.equal(JSON.stringify(input),before);assert.equal(actual.value,input);assert.deepEqual(actual.draws,[]);}});
 run('same-year-held-once',data=>{data.cases=[];const returned=copy(fixtures[1].changed),offer=actualOffer(B,returned),moved=B.engine.acceptOffer(copy(returned),offer.value.offer);let identity;for(let seed=1;seed<=100&&!identity;seed++){const events=seeded(seed,()=>B.life.getLifeEvents(copy(returned))).value;const event=events.find(e=>e.id===207);if(event){identity=event.choices[1].apply(copy(returned));}}assert(identity,'Actual existing random-agent event available in bounded preparation');assert.equal(identity.agentId,'self','Actual legacy agent dismissal changes identity');for(const input of [returned,action(B,'load',returned),moved,identity]){const actual=seeded(50,()=>action(B,'choose',input,'super')),read=seeded(51,()=>action(B,'read',input));data.cases.push({input,actual,read});assert.equal(read.value.eligibility.available,false);assert.deepEqual(read.draws,[]);assert.equal(actual.value,input);assert.deepEqual(actual.draws,[]);}data.offer=offer;data.scope='Actual signed move and existing catalog agent-event choice preserve the recorded-year receipt.';});
 run('later-recorded-year',data=>{const f=fixtures[1],completed=finishAgentYear(B,seeded(f.seed,()=>action(B,'next',copy(f.changed))).value),input=completed.value,target=B.life.AGENTS.find(a=>a.id!==input.agentId).id,read=seeded(60,()=>action(B,'read',input)),actual=seeded(61,()=>action(B,'choose',input,target));Object.assign(data,{completed,input,target,read,actual});assert.equal(input.seasons.length,f.input.seasons.length+1);assert(read.value.eligibility.available);assert.deepEqual(actual,{value:expectedAgent(B,input,target),draws:[]});});
 run('future-signings',data=>{data.cases=[];for(const f of fixtures){const offer=actualOffer(O,f.changed),input={...copy(f.changed),phase:'transfer_window',transferSituation:offer.value},current=seeded(70,()=>action(B,'sign',copy(input),offer.value.offer)),original=seeded(70,()=>action(O,'sign',copy(input),offer.value.offer)),agent=B.life.AGENTS.find(a=>a.id===f.target),fee=rounded(offer.value.offer.transferFee*agent.transferCut);data.cases.push({input,offer,current,original,fee});assert.deepEqual(current,original);assert.equal(current.value.weeklyWage,Math.round(offer.value.offer.wage*agent.wageMult));assert.equal(current.value.agentFeesPaid,rounded(input.agentFeesPaid+fee));assert.deepEqual(current.draws,[]);assert.equal(current.value.agentReview.sourceCount,input.agentReview.sourceCount);}});
 run('annual-income-economics',data=>{data.cases=[];for(const f of fixtures){const input=copy(f.changed),current=seeded(f.seed,()=>action(B,'next',copy(input))),original=seeded(f.seed,()=>action(O,'next',copy(input))),agent=B.life.AGENTS.find(a=>a.id===f.target),gross=input.weeklyWage*52/1000000+current.value.sponsorshipIncome,fee=rounded(gross*agent.incomeCut);data.cases.push({input,seed:f.seed,current,original,gross,fee});assert.deepEqual(current,original);assert.equal(current.value.agentFeesPaid,rounded(input.agentFeesPaid+fee));assert.equal(current.value.weeklyWage,input.weeklyWage);assert(current.value.seasons.length===input.seasons.length+1);}});
 run('original-offer-chances',data=>{data.cases=[];const source=agentPlayer(O,{overall:80,currentClubTier:2,contractYearsLeft:3,academyClubName:null});for(const a of B.life.AGENTS){const input={...copy(source),agentId:a.id};for(let seed=1;seed<=40;seed++){const original=seeded(seed,()=>O.engine.determineTransferSituation(copy(input),O.engine.FALLBACK_CLUBS)),current=seeded(seed,()=>B.engine.determineTransferSituation(copy(input),B.engine.FALLBACK_CLUBS));data.cases.push({agent:a.id,seed,input,original,current});assert.deepEqual(current,original,'Whole actual original offer output and unfiltered vector');}}assert(data.cases.some(v=>v.agent==='super'&&v.original.value.type==='dream_club'),'Actual super-agent dream-call witness present');});
 return result;
}
if(!process.env.SOCCER_AGENT_REVIEW_IMPORT_ONLY){
 fs.mkdirSync(OUT,{recursive:true});const before=sourceReceipt(held),C=await bundleAgentReview(),A=await bundleAgentReview({original:true}),B=C.value,O=A.value,report={head:git('rev-parse','HEAD'),tree:git('rev-parse','HEAD^{tree}'),base:BASE,baseTree:git('rev-parse',BASE+'^{tree}'),loaded:{current:C.loaded,original:A.loaded},sourceBefore:before,neutral:[],groups:[],controls:[]};
 try{
  for(const captured of capturedPlayers())for(const seed of [101,102,103])for(const kind of ['absent','malformed','future','missing-agent'])for(const age of [captured.state.age,31]){const input=age===31?agentPlayer(B,{},captured.id):copy(captured.state);if(kind==='malformed')input.agentReview={version:1,sourceCount:'unknown'};if(kind==='future')input.agentReview={version:1,sourceCount:input.seasons.length+1,sourceYear:9999,sourceAge:31,fromAgent:'cousin',toAgent:'shark'};if(kind==='missing-agent')input.agentId=null;const bytes=JSON.stringify(input),read=seeded(seed,()=>action(B,'read',input)),original=seeded(seed,()=>action(O,'next',copy(input))),current=seeded(seed,()=>action(B,'next',copy(input)));assert.equal(JSON.stringify(input),bytes);assert.deepEqual(read.draws,[]);assert.deepEqual(current,original);const file=evidence('neutral-'+captured.id+'-'+age+'-'+seed+'-'+kind+'.json',{input,operation:'next',read,original,current});report.neutral.push({file,kind,age,draws:original.draws.length});}
  const fixtures=prepareAgentFixtures(B);evidence('native-fixtures.json',fixtures);report.fixtures=fixtures.map(({id,seed,scope})=>({id,seed,scope}));report.groups=groups(B,O,fixtures,'healthy');assert(report.groups.every(v=>v.ok),JSON.stringify(report.groups.filter(v=>!v.ok)));
  const faults=[
   {id:'wrong-source-year',file:'src/lib/soccerAgentReview.ts',from:'source.year !== value.sourceYear',to:'false',groups:['receipt-integrity']},
   {id:'repeat-recorded-year',file:'src/lib/soccerAgentReview.ts',from:'career.seasons.length <= held.sourceCount || latest.year <= held.sourceYear',to:'false',groups:['same-year-held-once']},
   {id:'ignore-eligibility',file:'src/lib/soccerAgentReview.ts',from:'if (!agentReviewEligibility(prev).available) return prev;',to:'if (false) return prev;',groups:['eligibility-fail-closed','receipt-integrity','same-year-held-once']},
   {id:'instant-wage',file:'src/lib/soccerAgentReview.ts',from:'agentId: to.id,',to:'agentId: to.id, weeklyWage: prev.weeklyWage + 1,',groups:['change-whole-state','later-recorded-year']},
   {id:'no-transfer-commission',file:'src/lib/soccerCareerEngine.ts',from:'const feeRate = agentTransferCutRate(prev.agentId);',to:'const feeRate = 0;',groups:['future-signings']},
   {id:'no-income-commission',file:'src/lib/soccerCareerEngine.ts',from:'const agentCut = Math.round(grossIncome * agentIncomeCutRate(s.agentId) * 100) / 100;',to:'const agentCut = 0;',groups:['annual-income-economics']},
   {id:'lost-super-chance',file:'src/lib/soccerCareerEngine.ts',from:'const dreamChance = state.agentId === "super" ? 0.25 : 0.15;',to:'const dreamChance = 0;',groups:['original-offer-chances']},
  ];
  for(const fault of faults){const compiled=await bundleAgentReview({patches:[fault]}),actual=groups(compiled.value,O,fixtures,'fault-'+fault.id),failed=actual.filter(v=>!v.ok);assert.deepEqual(failed.map(v=>v.name),fault.groups);assert(failed.every(v=>v.assertion));assert.equal(actual.filter(v=>v.ok).length,8-fault.groups.length);report.controls.push({id:fault.id,expectedFailures:fault.groups,faults:compiled.faults,loaded:compiled.loaded,groups:actual});console.log('CONTROL FIRED '+fault.id+': '+fault.groups.join(', '));}
  console.log('PASS original09df complete inactive saves/read tapes/advance vectors: '+report.neutral.length+'.');console.log('PASS actual agent review groups:'+report.groups.length+' and four actual future-year fixtures.');console.log('PASS original offer outputs, exact future signed wages and annual/transfer commissions.');
 }finally{report.sourceAfter=sourceReceipt(held);assert.deepEqual(report.sourceAfter,before);evidence('outcomes.json',report);}
 console.log('PASS agent review product and proof source bytes held.');
}
