/** Round 540: actual Soccer Attack Board and save helpers under queued Web Locks.
 * All maps, targets and results are generated by the real engine. Six cases use
 * jsdom storage only. Exact source controls alter one anchor in an OS-temp copy.
 * Runtime and caught import-backend faults reject with exit 1, never PASS credit.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TEST = 'src/components/conquest/SoccerAttackBoard.saveChoice.test.tsx';
const FILES = { board: 'src/components/conquest/SoccerAttackBoard.tsx' };
const CONTROL = process.env.SIM_SOCCER_ATTACK_SAVE_CHOICE_CONTROL || '';
const CASES = [
 'locks unsaved choice during intro-damaged save and preserves idle fallback',
 'locks unsaved choice during intro-failed save and preserves idle fallback',
 'locks unsaved choice during active-damaged save and preserves idle fallback',
 'locks unsaved choice during active-failed save and preserves idle fallback',
 'rejects a same-event Retry and unsaved click before React disables the button',
 'keeps queued Retry ownership when another board commits a confirmed restart',
];
const board = (test, message, from, to) => ({ file: 'board', test, message, from, to });
const option = label => `<button type="button" onClick={playUnsaved} disabled={working} className={quietButton}>${label}</button>`;
const retryBlock = margin => `            <div className="mt-${margin} flex flex-wrap gap-2">
              <button type="button" onClick={retry} disabled={working} className={quietButton}>Retry save</button>
              ${option('Play this run without saving')}`;
const pending = '    const next = pending?.next ?? state ?? openingState();';
const disable = source => source.replace('onClick={playUnsaved} disabled={working}', 'onClick={playUnsaved}');
const CONTROLS = {
 introdamaged: board(0, 'WORKING CHOICE: intro-damaged unsaved option locks while a save is pending', option('Play without saving'), disable(option('Play without saving'))),
 introfailed: board(1, 'WORKING CHOICE: intro-failed unsaved option locks while a save is pending', retryBlock(3), disable(retryBlock(3))),
 activedamaged: board(2, 'WORKING CHOICE: active-damaged unsaved option locks while a save is pending', option('Continue without saving'), disable(option('Continue without saving'))),
 activefailed: board(3, 'WORKING CHOICE: active-failed unsaved option locks while a save is pending', retryBlock(2), disable(retryBlock(2))),
 idle: board(3, 'IDLE: active-failed unsaved choice is available', retryBlock(2), retryBlock(2).replace('onClick={playUnsaved} disabled={working}', 'onClick={playUnsaved} disabled={true}')),
 busy: board(4, 'SYNCHRONOUS GUARD: pending Retry rejects the same-event unsaved transition',
  '  const playUnsaved = () => {\n    if (busy.current) return;', '  const playUnsaved = () => {'),
 pending: board(3, 'EXACT MOVE: local play reveals the same pending phase', pending, '    const next = state ?? openingState();'),
 seed: board(1, 'SEED: local fallback does not generate a replacement run', pending, '    const next = openingState();'),
 unsaved: board(3, 'UNSAVED: idle fallback visibly enters local play', '    setUnsaved(true);', ''),
 bytes: board(3, 'BYTES: choosing local play preserves the original save', pending, pending + '\n    localStorage.setItem(ATTACK_SAVE_KEY, JSON.stringify(next));'),
 conflict: board(5, 'CONFLICT: the current board restores the latest committed restart',
  "      else if (outcome.status === 'conflict') restoreConflict();", "      else if (outcome.status === 'conflict') {}"),
 runtime: board(0, null, 'export default function SoccerAttackBoard() {',
  "export default function SoccerAttackBoard() {\n  throw new Error('Unexpected Attack save-choice runtime control');"),
 backend: board(0, null, 'export default function SoccerAttackBoard() {',
  "import { supabase as saveChoiceBackend } from '@/integrations/supabase/client';\ntry { void saveChoiceBackend.auth; } catch {}\nexport default function SoccerAttackBoard() {"),
};
if (CONTROL && !Object.hasOwn(CONTROLS, CONTROL)) throw new Error(`Unknown control: ${CONTROL}`);
const parent = fs.realpathSync(os.tmpdir());
const temp = fs.mkdtempSync(path.join(parent, 'dukb-attack-save-choice-'));
const slash = value => value.replaceAll('\\', '/');
let success = false;
try {
  const control = CONTROLS[CONTROL], originalPath = control && path.join(ROOT, FILES[control.file]);
  const copy = path.join(temp, 'source.control.tsx');
  if (control) {
    const original = fs.readFileSync(originalPath, 'utf8').replaceAll('\r\n', '\n');
    const matches = original.split(control.from).length - 1;
    if (matches !== 1 || control.from === control.to) throw new Error(`${CONTROL}: expected one changed source anchor, found ${matches}`);
    const changed = original.replace(control.from, control.to);
    if (changed === original) throw new Error(`${CONTROL}: source control changed nothing`);
    fs.writeFileSync(copy, changed);
    console.log(`CONTROL ${CONTROL}: one exact source anchor changed in a unique OS-temp copy`);
  }
  const reporter = path.join(temp, 'reporter.mjs'), reportPath = path.join(temp, 'report.json');
  fs.writeFileSync(reporter, `import fs from 'node:fs';
export default class {
  onFinished(files, errors) {
    const tests = [], suiteErrors = [];
    const shape = error => ({ name: error.name, message: error.message });
    const visit = task => {
      if (task.type === 'test') tests.push({ name: task.name, mode: task.mode, state: task.result?.state, errors: (task.result?.errors || []).map(shape) });
      else suiteErrors.push(...(task.result?.errors || []).map(shape));
      for (const child of task.tasks || []) visit(child);
    };
    for (const file of files || []) visit(file);
    fs.writeFileSync(${JSON.stringify(reportPath)}, JSON.stringify({ files: (files || []).length, tests, suiteErrors, unhandled: (errors || []).map(shape) }));
  }
}
`);
  const config = path.join(temp, 'vitest.config.mjs');
  fs.writeFileSync(config, `import fs from 'node:fs';
export default {
  root: ${JSON.stringify(slash(ROOT))}, cacheDir: ${JSON.stringify(slash(path.join(temp, 'cache')))}, esbuild: { jsx: 'automatic' },
  plugins: [{ name: 'isolated-attack-save-choice-control', enforce: 'pre', transform(code, id) {
    if (${!!control} && id.split('?')[0].replaceAll('\\\\', '/') === ${JSON.stringify(originalPath ? slash(originalPath) : '')}) return { code: fs.readFileSync(${JSON.stringify(copy)}, 'utf8'), map: null };
  } }],
  test: { environment: 'jsdom', globals: true, setupFiles: [${JSON.stringify(slash(path.join(ROOT, 'src/test/setup.ts')))}], include: [${JSON.stringify(TEST)}] },
  resolve: { alias: { '@': ${JSON.stringify(slash(path.join(ROOT, 'src')))} } },
};
`);
  const args = ['node_modules/vitest/vitest.mjs', 'run', TEST, '--config', config, '--maxWorkers=1', `--reporter=${slash(reporter)}`];
  if (control) args.push('-t', CASES[control.test]);
  const run = spawnSync(process.execPath, args, { cwd: ROOT, encoding: 'utf8', env: { ...process.env, CI: '1', NO_COLOR: '1' }, timeout: 120000, maxBuffer: 8 * 1024 * 1024 });
  if (run.error || run.signal || !fs.existsSync(reportPath)) throw new Error(`Runner did not complete: ${run.error || run.signal || run.stderr}`);
  const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
  if (report.files !== 1 || report.tests.length !== CASES.length || new Set(report.tests.map(test => test.name)).size !== CASES.length
    || report.tests.some(test => !CASES.includes(test.name))) throw new Error('The exact six named outcome tests were not reported');
  if (report.unhandled.length || report.suiteErrors.length) throw new Error(`Unexpected runtime/suite errors: ${JSON.stringify({ unhandled: report.unhandled, suite: report.suiteErrors })}`);
  let exact = true;
  for (const [index, name] of CASES.entries()) {
    const test = report.tests.find(item => item.name === name);
    if (control && index !== control.test) {
      const skipped = (test.mode === 'skip' || test.state === 'skip') && test.errors.length === 0;
      exact &&= skipped; if (!skipped) console.error(JSON.stringify(test)); continue;
    }
    const message = control?.message;
    const matches = message ? test.state === 'fail' && test.errors.length === 1 && test.errors[0].name === 'AssertionError' && test.errors[0].message === message
      : test.state === 'pass' && test.errors.length === 0;
    exact &&= matches;
    console.log(`  ${matches ? (message ? 'EXPECTED RED' : 'PASS') : 'FAIL'} ${name}`);
    if (!matches) console.error(JSON.stringify(test));
  }
  if (!exact || run.status !== (control ? 1 : 0)) throw new Error(`Unexpected result or extra failure (Vitest exit ${run.status}):\n${(run.stdout + run.stderr).slice(-2500)}`);
  console.log(`PASS: ${control ? '1 exact controlled failure' : '6/6 Attack save-choice cases green (real Board, engine and saves)'}; zero unhandled or suite errors`);
  success = true;
} catch (error) {
  console.error(`FAIL: ${error instanceof Error ? error.message : String(error)}`);
} finally {
  const resolved = fs.realpathSync(temp);
  if (path.dirname(resolved) !== parent || !path.basename(resolved).startsWith('dukb-attack-save-choice-')) throw new Error('Refusing cleanup outside the unique Attack save-choice temporary directory');
  fs.rmSync(resolved, { recursive: true, force: true });
  console.log('Temporary Attack save-choice control files cleaned');
}
if (!success) process.exitCode = 1;
