// Copy the real page and its existing tests. Only the captured rapid-click guard changes.
import './lib/offlineTransport.cjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {OUT,ROOT,sha,sourceReceipt,writeEvidence} from './qa/careerTransferBriefKit.mjs';
assert(process.env.CI,'Page source control runs on remote CI');
const pageFile='src/pages/SoccerCareer.tsx',testFile='src/test/soccerTransferBriefPage.test.tsx',before=sourceReceipt([pageFile,testFile]);
const source=fs.readFileSync(pageFile,'utf8').replaceAll('\r\n','\n'),test=fs.readFileSync(testFile,'utf8').replaceAll('\r\n','\n');
const anchor='if (transferRequestInFlight.current === career) return;';assert.equal(source.split(anchor).length,2,'Unique actual rapid-click source guard');
const faulty=source.replace(anchor,'if (false) return;');assert.notEqual(sha(faulty),sha(source),'Effective rapid-click source fault');
assert.equal(test.split("'@/pages/SoccerCareer'").length,2,'Unique actual page test import');const copiedTest=test.replace("'@/pages/SoccerCareer'","'./SoccerCareer'");
const parent=path.resolve(ROOT,'.sim-control');fs.mkdirSync(parent,{recursive:true});const temp=fs.mkdtempSync(path.join(parent,'transfer-brief-page-'));
assert.equal(path.dirname(temp),parent);assert(path.basename(temp).startsWith('transfer-brief-page-'));
const names=['commits one full offered response and draw vector for two captured rapid request clicks','saves one unsuccessful brief response and reloads it without another chance or offer'];
const report={sourceBefore:before,anchorCount:1,sourceHash:sha(source),faultHash:sha(faulty),expectedFailures:names,scope:'Copied actual page guard with actual six page tests, no served mutation or engine patch'};
try{fs.writeFileSync(path.join(temp,'soccerTransferBriefPage.test.tsx'),copiedTest);const config=path.join(temp,'vitest.config.ts');fs.writeFileSync(config,"import base from '../../vitest.config';export default {...base,test:{...base.test,include:["+JSON.stringify(path.relative(ROOT,path.join(temp,'soccerTransferBriefPage.test.tsx')).replaceAll('\\','/'))+"]}};");const run=(mode,pageSource)=>{fs.writeFileSync(path.join(temp,'SoccerCareer.tsx'),pageSource);const file=path.join(OUT,'page-control-'+mode+'.json');fs.mkdirSync(OUT,{recursive:true});const child=spawnSync(process.execPath,['node_modules/vitest/vitest.mjs','run',path.join(temp,'soccerTransferBriefPage.test.tsx'),'--config='+config,'--maxWorkers=1','--minWorkers=1','--reporter=json','--outputFile='+file],{cwd:ROOT,encoding:'utf8',maxBuffer:20*1024*1024,env:process.env});fs.writeFileSync(path.join(OUT,'page-control-'+mode+'.log'),(child.stdout??'')+(child.stderr??''));assert.equal(child.error,undefined,'Vitest process actually started');assert(fs.existsSync(file),'Actual structured Vitest assertions retained');return{exit:child.status,report:JSON.parse(fs.readFileSync(file,'utf8'))};};
 const baseline=run('baseline',source),baseAssertions=baseline.report.testResults.flatMap(v=>v.assertionResults);assert.equal(baseline.exit,0);assert.equal(baseline.report.success,true);assert.equal(baseline.report.numPendingTests,0);assert.equal(baseAssertions.length,6,'All six actual page cases run');assert(baseAssertions.every(v=>v.status==='passed'));for(const name of names)assert(baseAssertions.some(v=>v.title===name));
 const fault=run('fault',faulty),assertions=fault.report.testResults.flatMap(v=>v.assertionResults),failed=assertions.filter(v=>v.status==='failed');assert.equal(fault.exit,1);assert.equal(fault.report.numPendingTests,0);assert.equal(assertions.length,baseAssertions.length);assert.deepEqual(failed.map(v=>v.title),names,'Only the two actual captured rapid-click outcomes fail');assert.equal(assertions.filter(v=>v.status==='passed').length,4,'All four unrelated real page cases still pass');for(const failure of failed){const messages=failure.failureMessages.join('\n');assert(/AssertionError|expect\(received\)\.toEqual|expected .*to (deeply )?equal/s.test(messages),'Reject setup/import/type errors instead of actual equality assertion');}
 report.baseline={exit:baseline.exit,passed:baseAssertions.length};report.fault={exit:fault.exit,failed:failed.map(v=>({title:v.title,messages:v.failureMessages})),unrelatedPassed:4};report.sourceAfter=sourceReceipt([pageFile,testFile]);assert.deepEqual(report.sourceAfter,before);writeEvidence('page-control-receipt.json',report);console.log('CONTROL FIRED captured-rapid-request:2 actual equality failures,4 unrelated page cases pass,6 healthy baseline cases.');
}finally{assert.equal(path.dirname(temp),parent);assert(path.basename(temp).startsWith('transfer-brief-page-'));fs.rmSync(temp,{recursive:true,force:true});}