/* AUTO-GENERATED by scripts/bakeNationalities.mjs. DO NOT EDIT BY HAND.
   FOR SCRIPTS AND TESTS ONLY. The app must never import this file: it pulls every past world
   back onto whatever page imports it, which is the download Round 1042 took off Club Manager,
   Manager Hot Seat and Deadline Day (scripts/simCmDataOnDemand.mjs section 1 fails on it).
   A harness that wants all five worlds at once reads them from here. The maps are the SAME
   objects the registry is handed, never copies, so a negative control that writes into one is
   writing into what nationalityOf reads. */
import { NATIONALITY_WORLD_NOW, registerNationalityWorld } from '../playerNationalities';
import { NATIONALITY_WORLD as ERA2020 } from './era2020';
import { NATIONALITY_WORLD as ERA2015 } from './era2015';
import { NATIONALITY_WORLD as ERA2010 } from './era2010';
import { NATIONALITY_WORLD as ERA2005 } from './era2005';

export const NATIONALITY_BY_WORLD: Record<string, Record<string, string>> = {
  now: NATIONALITY_WORLD_NOW.now,
  era2020: ERA2020.era2020,
  era2015: ERA2015.era2015,
  era2010: ERA2010.era2010,
  era2005: ERA2005.era2005,
};

/** Registers every past world at once, for a script that calls nationalityOf without loading
 *  the engine's eras. In the game each world is registered by its own era gate instead. */
export function registerAllNationalityWorlds(): void {
  for (const key of Object.keys(NATIONALITY_BY_WORLD)) {
    if (key !== 'now') registerNationalityWorld(key, NATIONALITY_BY_WORLD[key]);
  }
}
