create table if not exists public.soccer_grid_puzzles (
  id         uuid        primary key default gen_random_uuid(),
  puzzle_id  text        not null unique,
  rows_json  jsonb       not null,
  cols_json  jsonb       not null,
  sort_order smallint    not null,
  created_at timestamptz not null default now()
);
alter table public.soccer_grid_puzzles enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'soccer_grid_puzzles' and policyname = 'Public read-only') then
    create policy "Public read-only" on public.soccer_grid_puzzles for select to anon, authenticated using (true);
  end if;
end $$;
insert into public.soccer_grid_puzzles (puzzle_id, rows_json, cols_json, sort_order) values
('sg-001', '[{"type":"club","label":"Played for Barcelona"},{"type":"club","label":"Played for Real Madrid"},{"type":"club","label":"Played for Manchester United"}]'::jsonb, '[{"type":"position","label":"Forward (FWD)"},{"type":"champions_league","label":"Champions League Winner"},{"type":"world_cup","label":"World Cup Winner"}]'::jsonb, 0),
('sg-002', '[{"type":"club","label":"Played for Chelsea"},{"type":"club","label":"Played for AC Milan"},{"type":"club","label":"Played for Bayern Munich"}]'::jsonb, '[{"type":"position","label":"Midfielder (MID)"},{"type":"league","label":"Played in Premier League"},{"type":"award","label":"Golden Boot Winner"}]'::jsonb, 1),
('sg-003', '[{"type":"club","label":"Played for Liverpool"},{"type":"club","label":"Played for Juventus"},{"type":"club","label":"Played for PSG"}]'::jsonb, '[{"type":"position","label":"Defender (DEF)"},{"type":"league","label":"Played in La Liga"},{"type":"misc","label":"Over 100 International Caps"}]'::jsonb, 2),
('sg-004', '[{"type":"club","label":"Played for Arsenal"},{"type":"club","label":"Played for Inter Milan"},{"type":"club","label":"Played for Manchester City"}]'::jsonb, '[{"type":"position","label":"Forward (FWD)"},{"type":"league","label":"Played in Serie A"},{"type":"champions_league","label":"Champions League Winner"}]'::jsonb, 3),
('sg-005', '[{"type":"club","label":"Played for Atletico Madrid"},{"type":"club","label":"Played for Borussia Dortmund"},{"type":"club","label":"Played for Tottenham"}]'::jsonb, '[{"type":"position","label":"Goalkeeper (GK)"},{"type":"world_cup","label":"World Cup Winner"},{"type":"league","label":"Played in Bundesliga"}]'::jsonb, 4),
('sg-006', '[{"type":"nationality","label":"Brazilian"},{"type":"nationality","label":"French"},{"type":"nationality","label":"Argentine"}]'::jsonb, '[{"type":"club","label":"Played for Real Madrid"},{"type":"champions_league","label":"Champions League Winner"},{"type":"league","label":"Played in Ligue 1"}]'::jsonb, 5),
('sg-007', '[{"type":"club","label":"Played for Roma"},{"type":"club","label":"Played for Napoli"},{"type":"club","label":"Played for AC Milan"}]'::jsonb, '[{"type":"position","label":"Forward (FWD)"},{"type":"league","label":"Played in Serie A"},{"type":"misc","label":"Over 100 International Caps"}]'::jsonb, 6),
('sg-008', '[{"type":"club","label":"Played for Barcelona"},{"type":"club","label":"Played for Chelsea"},{"type":"club","label":"Played for Bayern Munich"}]'::jsonb, '[{"type":"position","label":"Midfielder (MID)"},{"type":"world_cup","label":"World Cup Winner"},{"type":"league","label":"Played in Premier League"}]'::jsonb, 7),
('sg-009', '[{"type":"nationality","label":"German"},{"type":"nationality","label":"Spanish"},{"type":"nationality","label":"Italian"}]'::jsonb, '[{"type":"position","label":"Defender (DEF)"},{"type":"champions_league","label":"Champions League Winner"},{"type":"world_cup","label":"World Cup Winner"}]'::jsonb, 8),
('sg-010', '[{"type":"club","label":"Played for Manchester City"},{"type":"club","label":"Played for Liverpool"},{"type":"club","label":"Played for Real Madrid"}]'::jsonb, '[{"type":"position","label":"Forward (FWD)"},{"type":"league","label":"Played in La Liga"},{"type":"award","label":"Golden Boot Winner"}]'::jsonb, 9),
('sg-011', '[{"type":"club","label":"Played for PSG"},{"type":"club","label":"Played for Juventus"},{"type":"club","label":"Played for Arsenal"}]'::jsonb, '[{"type":"position","label":"Midfielder (MID)"},{"type":"league","label":"Played in Ligue 1"},{"type":"misc","label":"Over 100 International Caps"}]'::jsonb, 10),
('sg-012', '[{"type":"club","label":"Played for Tottenham"},{"type":"club","label":"Played for Inter Milan"},{"type":"club","label":"Played for Borussia Dortmund"}]'::jsonb, '[{"type":"position","label":"Goalkeeper (GK)"},{"type":"champions_league","label":"Champions League Winner"},{"type":"league","label":"Played in Bundesliga"}]'::jsonb, 11),
('sg-013', '[{"type":"nationality","label":"Portuguese"},{"type":"nationality","label":"Dutch"},{"type":"nationality","label":"English"}]'::jsonb, '[{"type":"position","label":"Forward (FWD)"},{"type":"league","label":"Played in Premier League"},{"type":"champions_league","label":"Champions League Winner"}]'::jsonb, 12),
('sg-014', '[{"type":"club","label":"Played for Barcelona"},{"type":"club","label":"Played for Manchester United"},{"type":"club","label":"Played for AC Milan"}]'::jsonb, '[{"type":"position","label":"Defender (DEF)"},{"type":"world_cup","label":"World Cup Winner"},{"type":"league","label":"Played in Serie A"}]'::jsonb, 13),
('sg-015', '[{"type":"club","label":"Played for Real Madrid"},{"type":"club","label":"Played for Chelsea"},{"type":"club","label":"Played for Liverpool"}]'::jsonb, '[{"type":"misc","label":"Played in MLS"},{"type":"champions_league","label":"Champions League Winner"},{"type":"misc","label":"Over 100 International Caps"}]'::jsonb, 14),
('sg-016', '[{"type":"club","label":"Played for Ajax"},{"type":"club","label":"Played for Porto"},{"type":"club","label":"Played for Benfica"}]'::jsonb, '[{"type":"league","label":"Played in Premier League"},{"type":"position","label":"Forward (FWD)"},{"type":"champions_league","label":"Champions League Winner"}]'::jsonb, 15),
('sg-017', '[{"type":"club","label":"Played for Sevilla"},{"type":"club","label":"Played for Marseille"},{"type":"club","label":"Played for Galatasaray"}]'::jsonb, '[{"type":"league","label":"Played in Premier League"},{"type":"position","label":"Forward (FWD)"},{"type":"nationality","label":"French"}]'::jsonb, 16),
('sg-018', '[{"type":"club","label":"Played for Bayer Leverkusen"},{"type":"club","label":"Played for Lazio"},{"type":"club","label":"Played for Sporting CP"}]'::jsonb, '[{"type":"position","label":"Midfielder (MID)"},{"type":"league","label":"Played in Premier League"},{"type":"champions_league","label":"Champions League Winner"}]'::jsonb, 17),
('sg-019', '[{"type":"nationality","label":"Colombian"},{"type":"nationality","label":"Uruguayan"},{"type":"nationality","label":"Chilean"}]'::jsonb, '[{"type":"club","label":"Played for Barcelona"},{"type":"league","label":"Played in Premier League"},{"type":"misc","label":"Copa América Winner"}]'::jsonb, 18),
('sg-020', '[{"type":"club","label":"Played for Boca Juniors"},{"type":"club","label":"Played for River Plate"},{"type":"nationality","label":"Croatian"}]'::jsonb, '[{"type":"league","label":"Played in Serie A"},{"type":"position","label":"Midfielder (MID)"},{"type":"league","label":"Played in La Liga"}]'::jsonb, 19),
('sg-021', '[{"type":"club","label":"Played for Fiorentina"},{"type":"club","label":"Played for Valencia"},{"type":"club","label":"Played for Villarreal"}]'::jsonb, '[{"type":"nationality","label":"Argentine"},{"type":"league","label":"Played in La Liga"},{"type":"position","label":"Midfielder (MID)"}]'::jsonb, 20),
('sg-022', '[{"type":"club","label":"Played for Celtic"},{"type":"club","label":"Played for PSV"},{"type":"club","label":"Played for Feyenoord"}]'::jsonb, '[{"type":"position","label":"Defender (DEF)"},{"type":"league","label":"Played in Premier League"},{"type":"nationality","label":"Dutch"}]'::jsonb, 21),
('sg-023', '[{"type":"club","label":"Played for Lyon"},{"type":"club","label":"Played for Monaco"},{"type":"club","label":"Played for Lille"}]'::jsonb, '[{"type":"position","label":"Defender (DEF)"},{"type":"league","label":"Played in Ligue 1"},{"type":"league","label":"Played in Serie A"}]'::jsonb, 22),
('sg-024', '[{"type":"nationality","label":"Belgian"},{"type":"nationality","label":"Polish"},{"type":"nationality","label":"Norwegian"}]'::jsonb, '[{"type":"club","label":"Played for Borussia Dortmund"},{"type":"league","label":"Played in Ligue 1"},{"type":"position","label":"Goalkeeper (GK)"}]'::jsonb, 23),
('sg-025', '[{"type":"club","label":"Played for Manchester United"},{"type":"club","label":"Played for Bayern Munich"},{"type":"club","label":"Played for Juventus"}]'::jsonb, '[{"type":"award","label":"Ballon d''Or Winner"},{"type":"world_cup","label":"World Cup Winner"},{"type":"misc","label":"Over 100 International Caps"}]'::jsonb, 24),
('sg-026', '[{"type":"club","label":"Played for Newcastle"},{"type":"club","label":"Played for Everton"},{"type":"club","label":"Played for West Ham"}]'::jsonb, '[{"type":"league","label":"Played in Eredivisie"},{"type":"position","label":"Defender (DEF)"},{"type":"league","label":"Played in Serie A"}]'::jsonb, 25),
('sg-027', '[{"type":"club","label":"Played for Eintracht Frankfurt"},{"type":"club","label":"Played for Schalke"},{"type":"club","label":"Played for Beşiktaş"}]'::jsonb, '[{"type":"league","label":"Played in Premier League"},{"type":"league","label":"Played in Süper Lig"},{"type":"position","label":"Midfielder (MID)"}]'::jsonb, 26),
('sg-028', '[{"type":"nationality","label":"Senegalese"},{"type":"nationality","label":"Ivorian"},{"type":"nationality","label":"Cameroonian"}]'::jsonb, '[{"type":"misc","label":"African Cup of Nations Winner"},{"type":"league","label":"Played in Ligue 1"},{"type":"club","label":"Played for Chelsea"}]'::jsonb, 27),
('sg-029', '[{"type":"club","label":"Played for Real Madrid"},{"type":"club","label":"Played for Bayern Munich"},{"type":"club","label":"Played for Inter Milan"}]'::jsonb, '[{"type":"world_cup","label":"World Cup Winner"},{"type":"misc","label":"UEFA Euro Winner"},{"type":"award","label":"Europa League Winner"}]'::jsonb, 28),
('sg-030', '[{"type":"club","label":"Played for Liverpool"},{"type":"club","label":"Played for Chelsea"},{"type":"club","label":"Played for Manchester City"}]'::jsonb, '[{"type":"misc","label":"Played in Saudi Pro League"},{"type":"position","label":"Goalkeeper (GK)"},{"type":"nationality","label":"Brazilian"}]'::jsonb, 29),
('sg-031', '[{"type":"club","label":"Played for Wolfsburg"},{"type":"club","label":"Played for Shakhtar Donetsk"},{"type":"club","label":"Played for Fenerbahçe"}]'::jsonb, '[{"type":"position","label":"Midfielder (MID)"},{"type":"league","label":"Played in Bundesliga"},{"type":"nationality","label":"Brazilian"}]'::jsonb, 30),
('sg-032', '[{"type":"nationality","label":"Welsh"},{"type":"nationality","label":"Egyptian"},{"type":"nationality","label":"Serbian"}]'::jsonb, '[{"type":"league","label":"Played in Premier League"},{"type":"position","label":"Forward (FWD)"},{"type":"club","label":"Played for Liverpool"}]'::jsonb, 31),
('sg-033', '[{"type":"club","label":"Played for Ajax"},{"type":"club","label":"Played for PSV"},{"type":"club","label":"Played for Lazio"}]'::jsonb, '[{"type":"league","label":"Played in Eredivisie"},{"type":"nationality","label":"Brazilian"},{"type":"position","label":"Forward (FWD)"}]'::jsonb, 32),
('sg-034', '[{"type":"club","label":"Played for Marseille"},{"type":"club","label":"Played for Sevilla"},{"type":"nationality","label":"Moroccan"}]'::jsonb, '[{"type":"league","label":"Played in Ligue 1"},{"type":"league","label":"Played in La Liga"},{"type":"position","label":"Defender (DEF)"}]'::jsonb, 33),
('sg-035', '[{"type":"club","label":"Played for Manchester United"},{"type":"club","label":"Played for Atlético Madrid"},{"type":"club","label":"Played for Valencia"}]'::jsonb, '[{"type":"world_cup","label":"World Cup Winner"},{"type":"award","label":"Europa League Winner"},{"type":"league","label":"Played in Primeira Liga"}]'::jsonb, 34),
('sg-036', '[{"type":"club","label":"Played for Flamengo"},{"type":"club","label":"Played for Atlético Mineiro"},{"type":"club","label":"Played for Santos"}]'::jsonb, '[{"type":"misc","label":"Copa América Winner"},{"type":"position","label":"Midfielder (MID)"},{"type":"world_cup","label":"World Cup Winner"}]'::jsonb, 35),
('sg-037', '[{"type":"nationality","label":"Japanese"},{"type":"nationality","label":"South Korean"},{"type":"nationality","label":"Polish"}]'::jsonb, '[{"type":"league","label":"Played in Bundesliga"},{"type":"position","label":"Midfielder (MID)"},{"type":"position","label":"Forward (FWD)"}]'::jsonb, 36),
('sg-038', '[{"type":"club","label":"Played for Galatasaray"},{"type":"club","label":"Played for Beşiktaş"},{"type":"club","label":"Played for Zenit St. Petersburg"}]'::jsonb, '[{"type":"league","label":"Played in Bundesliga"},{"type":"position","label":"Defender (DEF)"},{"type":"nationality","label":"Brazilian"}]'::jsonb, 37),
('sg-039', '[{"type":"nationality","label":"Croatian"},{"type":"nationality","label":"Danish"},{"type":"nationality","label":"Mexican"}]'::jsonb, '[{"type":"league","label":"Played in Bundesliga"},{"type":"position","label":"Defender (DEF)"},{"type":"league","label":"Played in La Liga"}]'::jsonb, 38),
('sg-040', '[{"type":"club","label":"Played for PSG"},{"type":"club","label":"Played for Monaco"},{"type":"nationality","label":"Argentine"}]'::jsonb, '[{"type":"club","label":"Played for Barcelona"},{"type":"champions_league","label":"Champions League Winner"},{"type":"position","label":"Defender (DEF)"}]'::jsonb, 39),
('sg-041', '[{"type":"club","label":"Played for Real Madrid"},{"type":"club","label":"Played for AC Milan"},{"type":"club","label":"Played for Juventus"}]'::jsonb, '[{"type":"award","label":"Ballon d''Or Winner"},{"type":"misc","label":"UEFA Euro Winner"},{"type":"league","label":"Played in Premier League"}]'::jsonb, 40),
('sg-042', '[{"type":"club","label":"Played for Inter Miami"},{"type":"club","label":"Played for Olympiacos"},{"type":"club","label":"Played for Red Bull Salzburg"}]'::jsonb, '[{"type":"club","label":"Played for Liverpool"},{"type":"position","label":"Midfielder (MID)"},{"type":"position","label":"Forward (FWD)"}]'::jsonb, 41),
('sg-043', '[{"type":"nationality","label":"Nigerian"},{"type":"nationality","label":"Algerian"},{"type":"nationality","label":"Tunisian"}]'::jsonb, '[{"type":"misc","label":"African Cup of Nations Winner"},{"type":"league","label":"Played in Ligue 1"},{"type":"position","label":"Midfielder (MID)"}]'::jsonb, 42),
('sg-044', '[{"type":"club","label":"Played for Tottenham"},{"type":"club","label":"Played for Roma"},{"type":"club","label":"Played for Werder Bremen"}]'::jsonb, '[{"type":"league","label":"Played in Eredivisie"},{"type":"position","label":"Defender (DEF)"},{"type":"nationality","label":"Brazilian"}]'::jsonb, 43),
('sg-045', '[{"type":"club","label":"Played for Atlético Madrid"},{"type":"club","label":"Played for Sevilla"},{"type":"nationality","label":"Uruguayan"}]'::jsonb, '[{"type":"award","label":"Europa League Winner"},{"type":"league","label":"Played in Serie A"},{"type":"position","label":"Defender (DEF)"}]'::jsonb, 44),
('sg-046', '[{"type":"club","label":"Played for Real Sociedad"},{"type":"club","label":"Played for Real Betis"},{"type":"club","label":"Played for Celta Vigo"}]'::jsonb, '[{"type":"league","label":"Played in Premier League"},{"type":"position","label":"Midfielder (MID)"},{"type":"nationality","label":"Mexican"}]'::jsonb, 45),
('sg-047', '[{"type":"club","label":"Played for RB Leipzig"},{"type":"club","label":"Played for Bayer Leverkusen"},{"type":"club","label":"Played for Udinese"}]'::jsonb, '[{"type":"league","label":"Played in Ligue 1"},{"type":"position","label":"Forward (FWD)"},{"type":"nationality","label":"French"}]'::jsonb, 46),
('sg-048', '[{"type":"nationality","label":"Czech"},{"type":"nationality","label":"Greek"},{"type":"nationality","label":"American"}]'::jsonb, '[{"type":"league","label":"Played in Serie A"},{"type":"position","label":"Goalkeeper (GK)"},{"type":"league","label":"Played in Bundesliga"}]'::jsonb, 47),
('sg-049', '[{"type":"club","label":"Played for Bayern Munich"},{"type":"club","label":"Played for Inter Milan"},{"type":"club","label":"Played for Chelsea"}]'::jsonb, '[{"type":"champions_league","label":"Champions League Winner"},{"type":"league","label":"Played in Primeira Liga"},{"type":"position","label":"Defender (DEF)"}]'::jsonb, 48),
('sg-050', '[{"type":"club","label":"Played for Arsenal"},{"type":"club","label":"Played for Lyon"},{"type":"nationality","label":"German"}]'::jsonb, '[{"type":"world_cup","label":"World Cup Winner"},{"type":"league","label":"Played in La Liga"},{"type":"position","label":"Forward (FWD)"}]'::jsonb, 49)
on conflict (puzzle_id) do update set
  rows_json = excluded.rows_json, cols_json = excluded.cols_json, sort_order = excluded.sort_order;
