// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-games.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { CATEGORIES } from "npm:@/data/gameRegistry";
var list_games_default = defineTool({
  name: "list_games",
  title: "List games",
  description: "List all daily sports trivia games available on DoUKnowBall, optionally filtered by sport category.",
  inputSchema: {
    category: z.string().optional().describe("Optional sport category name (e.g. 'Soccer', 'NBA', 'NFL'). Case-insensitive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category ? CATEGORIES.filter((c) => c.name.toLowerCase() === category.toLowerCase()) : CATEGORIES;
    const games = filtered.flatMap(
      (c) => c.games.map((g) => ({
        category: c.name,
        label: g.label,
        path: g.path,
        description: g.description,
        daily: Boolean(g.daily),
        isNew: Boolean(g.isNew)
      }))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(games, null, 2) }],
      structuredContent: { games }
    };
  }
});

// src/lib/mcp/tools/most-played-today.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var SUPABASE_URL = "https://flawuiqbvjobmkfkauhw.supabase.co";
var SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYXd1aXFidmpvYm1rZmthdWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NTUwNzYsImV4cCI6MjA5MTQzMTA3Nn0.L8xWIXikPIaXC0XOL-FLOuPQb6idws2NdliARxBgk_Y";
var most_played_today_default = defineTool2({
  name: "most_played_today",
  title: "Most played today",
  description: "Return the most-played DoUKnowBall games today (UTC), ranked by number of completions across all visitors.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum number of games to return. Defaults to 10. Clamped between 1 and 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ limit }) => {
    const cap = Math.min(Math.max(typeof limit === "number" ? limit : 10, 1), 50);
    const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("game_completions").select("game").eq("completed_on", today);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      counts.set(row.game, (counts.get(row.game) ?? 0) + 1);
    }
    const ranked = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, cap).map(([game, completions]) => ({ game, completions }));
    return {
      content: [{ type: "text", text: JSON.stringify({ date: today, ranked }, null, 2) }],
      structuredContent: { date: today, ranked }
    };
  }
});

// src/lib/mcp/tools/leaderboard.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SUPABASE_URL2 = "https://flawuiqbvjobmkfkauhw.supabase.co";
var SUPABASE_PUBLISHABLE_KEY2 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYXd1aXFidmpvYm1rZmthdWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NTUwNzYsImV4cCI6MjA5MTQzMTA3Nn0.L8xWIXikPIaXC0XOL-FLOuPQb6idws2NdliARxBgk_Y";
var leaderboard_default = defineTool3({
  name: "leaderboard_today",
  title: "Leaderboard for today",
  description: "Return the top scoring players for a given DoUKnowBall game today (UTC). Uses each player's best score for the day.",
  inputSchema: {
    game: z3.string().min(1).describe("Game slug (path without leading slash), e.g. 'soccer-grid' or 'guess-transfer-value'."),
    limit: z3.number().int().optional().describe("Number of leaderboard entries to return. Defaults to 25. Clamped between 1 and 100.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ game, limit }) => {
    const cap = Math.min(Math.max(typeof limit === "number" ? limit : 25, 1), 100);
    const slug = game.replace(/^\//, "");
    const supabase = createClient2(SUPABASE_URL2, SUPABASE_PUBLISHABLE_KEY2);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("game_completions").select("player_name, score").eq("game", slug).eq("completed_on", today).not("score", "is", null).not("player_name", "is", null);
    if (error) {
      return {
        content: [{ type: "text", text: `Error: ${error.message}` }],
        isError: true
      };
    }
    const best = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const prev = best.get(row.player_name) ?? -Infinity;
      if (row.score > prev) best.set(row.player_name, row.score);
    }
    const ranked = [...best.entries()].sort((a, b) => b[1] - a[1]).slice(0, cap).map(([player, score], i) => ({ rank: i + 1, player, score }));
    return {
      content: [{ type: "text", text: JSON.stringify({ date: today, game: slug, ranked }, null, 2) }],
      structuredContent: { date: today, game: slug, ranked }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "douknowball-mcp",
  title: "DoUKnowBall",
  version: "0.1.0",
  instructions: "Tools for DoUKnowBall, a daily sports trivia site. Use `list_games` to discover games, `most_played_today` for today's most popular games, and `leaderboard_today` for the top scores in a given game today.",
  tools: [list_games_default, most_played_today_default, leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
