-- Round 827: the career rows Round 784 saw and left, corrected from two sources.
--
-- GENERATED by scripts/genCareerRowsVerified.mjs from scripts/data/careerRowsVerified2026-10.json, which carries
-- every value below with its sources. Do not edit by hand: change the record and
-- re-run the generator. scripts/simCareerRowsVerified.mjs fails when a value written
-- here does not trace to a record row with two sources, or a record row is missing.
--
--   changed: 21 values on 8 rows (Antoine Griezmann, Erling Haaland, Kevin De Bruyne, Harry Kane)
--   added: 4 seasons (Erling Haaland 2019-2020 RB Salzburg; Harry Kane 2011-2012 Millwall; Harry Kane 2012-2013 Norwich City; Harry Kane 2012-2013 Leicester City)
--   kept as they are, two sources apart and no third readable: 5 rows
--   the duplicate Alisson stays (both ids are referenced); see the record
--
-- Fail closed: every row is written only over the exact row it replaces (matched by
-- id and by every value it holds today), every insert first proves its row is absent,
-- and the after state is checked row for row before the counts close it. The whole
-- block rolls back on the first mismatch.
--
-- Transfer Path plays on the same tables. The new seasons are new links (Kane and
-- Vardy at Leicester City in 2012-2013, Haaland and Szoboszlai at RB Salzburg in
-- 2019-2020, De Bruyne at Chelsea with Salah and Eto'o once his season reads 2013-2014),
-- so the same transaction rewrites the 8 classic and Europe entries and the
-- 1 active entry they shorten, each over the value it replaces. Every new value is
-- deriveHint on the pool after this migration; simTransferPathHints section 7 re-derives
-- them all. An active entry is written over the applied 2026-09-07 value or over the
-- value the pending Round 531 refresh writes, so the two land in either order; the
-- refresh fails closed on it if it comes second and must be regenerated first.
--
-- After applying: node scripts/bakeCareerPlayers.mjs must leave src/data/careerPlayers.ts
-- unchanged except its date stamp.

do $migration$
declare
  n integer;
  total integer;
  desired record;
  updated_this_row integer;
  written integer := 0;
  checked integer := 0;
  updated_rows integer := 0;
begin
  select count(*) into total from public.career_seasons;
  if total <> 3640 then raise exception 'expected 3640 career_seasons rows before this migration, found %', total; end if;
  select count(*) into n from public.career_players;
  if n <> 253 then raise exception 'expected 253 career_players rows, found %', n; end if;

  -- the players this touches, each at its id, each with the rows it has today
  for desired in
    select * from (values
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 16::integer, 16::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 10::integer, 11::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 15::integer, 18::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 18::integer, 18::integer)
    ) as rows(player_id, player_name, rows_before, rows_after)
  loop
    select count(*) into n from public.career_players where id = desired.player_id and player_name = desired.player_name;
    if n <> 1 then raise exception '%: expected one career_players row at %, found %', desired.player_name, desired.player_id, n; end if;
    select count(*) into n from public.career_seasons where player_id = desired.player_id;
    if n <> desired.rows_before then raise exception '%: expected % season rows, found %', desired.player_name, desired.rows_before, n; end if;
  end loop;

  -- the career rows: an update names the row by id and by every value it holds today;
  -- an insert (row_id null) first proves the season is not there
  for desired in
    select * from (values
    ('fcc672a4-bbd6-4854-9bd2-e3b82dbf45b2'::uuid, 'a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, '2009-2010'::text, 'Real Sociedad'::text, 2::integer, 1::integer, 10::integer, 3::integer, 0::smallint, '2009-2010'::text, 'Real Sociedad'::text, 6::integer, null::integer, 40::integer, 3::integer, 0::smallint),
    ('c12c21b0-6417-4291-943c-f6a907c92024'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2018-2019'::text, 'RB Salzburg'::text, 17::integer, 6::integer, 27::integer, 10::integer, 3::smallint, '2018-2019'::text, 'RB Salzburg'::text, 1::integer, null::integer, 5::integer, 10::integer, 3::smallint),
    (null::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, null::text, null::text, null::integer, null::integer, null::integer, null::integer, null::smallint, '2019-2020'::text, 'RB Salzburg'::text, 28::integer, null::integer, 22::integer, 0::integer, 4::smallint),
    ('98555671-d328-499b-b2ed-74934ef341ca'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2019-2020'::text, 'Borussia Dortmund'::text, 16::integer, 4::integer, 18::integer, 60::integer, 4::smallint, '2019-2020'::text, 'Borussia Dortmund'::text, 16::integer, 4::integer, 18::integer, 60::integer, 5::smallint),
    ('e10d1f5d-3abc-4cef-b569-6487b507cff2'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2020-2021'::text, 'Borussia Dortmund'::text, 41::integer, 12::integer, 41::integer, 110::integer, 5::smallint, '2020-2021'::text, 'Borussia Dortmund'::text, 41::integer, 12::integer, 41::integer, 110::integer, 6::smallint),
    ('fe2cf896-4abc-45d7-a9e0-b5eb72891de1'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2021-2022'::text, 'Borussia Dortmund'::text, 29::integer, 8::integer, 30::integer, 150::integer, 6::smallint, '2021-2022'::text, 'Borussia Dortmund'::text, 29::integer, 8::integer, 30::integer, 150::integer, 7::smallint),
    ('26f5b0c5-7885-4415-a3c7-37885b0b8c32'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2022-2023'::text, 'Manchester City'::text, 52::integer, 8::integer, 53::integer, 180::integer, 7::smallint, '2022-2023'::text, 'Manchester City'::text, 52::integer, 8::integer, 53::integer, 180::integer, 8::smallint),
    ('a44bc859-cf7c-4bfa-a290-06caacef6751'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2023-2024'::text, 'Manchester City'::text, 38::integer, 5::integer, 45::integer, 180::integer, 8::smallint, '2023-2024'::text, 'Manchester City'::text, 38::integer, 5::integer, 45::integer, 180::integer, 9::smallint),
    ('9cdfe59e-e1b7-4ede-bc11-318b5b29204d'::uuid, 'a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, '2024-2025'::text, 'Manchester City'::text, 22::integer, 4::integer, 30::integer, 180::integer, 9::smallint, '2024-2025'::text, 'Manchester City'::text, 22::integer, 4::integer, 30::integer, 180::integer, 10::smallint),
    ('9ded1166-c977-41dd-9575-287513f78466'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2011-2012'::text, 'Tottenham'::text, 0::integer, 0::integer, 1::integer, 1::integer, 1::smallint, '2011-2012'::text, 'Tottenham'::text, 1::integer, 0::integer, 6::integer, 1::integer, 1::smallint),
    (null::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, null::text, null::text, null::integer, null::integer, null::integer, null::integer, null::smallint, '2011-2012'::text, 'Millwall'::text, 9::integer, null::integer, 27::integer, 0::integer, 2::smallint),
    ('6eaf906e-462c-4811-8d37-3bb329f85e7b'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2012-2013'::text, 'Tottenham'::text, 2::integer, 0::integer, 14::integer, 2::integer, 2::smallint, '2012-2013'::text, 'Tottenham'::text, 0::integer, 0::integer, 1::integer, 2::integer, 3::smallint),
    (null::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, null::text, null::text, null::integer, null::integer, null::integer, null::integer, null::smallint, '2012-2013'::text, 'Norwich City'::text, 0::integer, null::integer, 5::integer, 0::integer, 4::smallint),
    (null::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, null::text, null::text, null::integer, null::integer, null::integer, null::integer, null::smallint, '2012-2013'::text, 'Leicester City'::text, 2::integer, null::integer, 15::integer, 0::integer, 5::smallint),
    ('f3db5cd4-e570-4aad-aaeb-529e7277afea'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2013-2014'::text, 'Tottenham'::text, 3::integer, 2::integer, 19::integer, 5::integer, 3::smallint, '2013-2014'::text, 'Tottenham'::text, 4::integer, null::integer, 19::integer, 5::integer, 6::smallint),
    ('e6d60998-42c5-433d-8e29-12fa155954b9'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2014-2015'::text, 'Tottenham'::text, 31::integer, 5::integer, 51::integer, 25::integer, 4::smallint, '2014-2015'::text, 'Tottenham'::text, 31::integer, 5::integer, 51::integer, 25::integer, 7::smallint),
    ('ed24e8cc-08ac-4a26-88c6-8e0101408706'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2015-2016'::text, 'Tottenham'::text, 28::integer, 4::integer, 50::integer, 40::integer, 5::smallint, '2015-2016'::text, 'Tottenham'::text, 28::integer, 4::integer, 50::integer, 40::integer, 8::smallint),
    ('c06a9676-6ed5-461f-be19-ede2b6678e4c'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2016-2017'::text, 'Tottenham'::text, 35::integer, 7::integer, 38::integer, 60::integer, 6::smallint, '2016-2017'::text, 'Tottenham'::text, 35::integer, 7::integer, 38::integer, 60::integer, 9::smallint),
    ('c7a6e1b6-cfd6-48fa-a061-e2c913badd4e'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2017-2018'::text, 'Tottenham'::text, 41::integer, 5::integer, 48::integer, 100::integer, 7::smallint, '2017-2018'::text, 'Tottenham'::text, 41::integer, 5::integer, 48::integer, 100::integer, 10::smallint),
    ('72ff937a-0447-474a-83ce-bcad3d6b64f7'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2018-2019'::text, 'Tottenham'::text, 24::integer, 6::integer, 40::integer, 120::integer, 8::smallint, '2018-2019'::text, 'Tottenham'::text, 24::integer, 6::integer, 40::integer, 120::integer, 11::smallint),
    ('581f0166-d414-4d4d-b652-5935349efc5c'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2019-2020'::text, 'Tottenham'::text, 24::integer, 2::integer, 34::integer, 100::integer, 9::smallint, '2019-2020'::text, 'Tottenham'::text, 24::integer, 2::integer, 34::integer, 100::integer, 12::smallint),
    ('65b3c77f-174a-474e-a543-a5d422a7b4d3'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2020-2021'::text, 'Tottenham'::text, 33::integer, 17::integer, 49::integer, 120::integer, 10::smallint, '2020-2021'::text, 'Tottenham'::text, 33::integer, 17::integer, 49::integer, 120::integer, 13::smallint),
    ('e15dfbe3-99c6-499f-82cb-4771ee22e12e'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2021-2022'::text, 'Tottenham'::text, 27::integer, 10::integer, 50::integer, 100::integer, 11::smallint, '2021-2022'::text, 'Tottenham'::text, 27::integer, 10::integer, 50::integer, 100::integer, 14::smallint),
    ('f881ae1e-d019-442e-a542-27bb9222e2f4'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2022-2023'::text, 'Tottenham'::text, 32::integer, 4::integer, 49::integer, 100::integer, 12::smallint, '2022-2023'::text, 'Tottenham'::text, 32::integer, 4::integer, 49::integer, 100::integer, 15::smallint),
    ('f7296742-a64c-4b3b-afad-f3ca18bcc9b6'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2023-2024'::text, 'Bayern Munich'::text, 44::integer, 12::integer, 45::integer, 100::integer, 13::smallint, '2023-2024'::text, 'Bayern Munich'::text, 44::integer, 12::integer, 45::integer, 100::integer, 16::smallint),
    ('0a52bf8b-85b7-4b2a-8085-4fe89f04f03d'::uuid, 'a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, '2024-2025'::text, 'Bayern Munich'::text, 23::integer, 7::integer, 30::integer, 75::integer, 14::smallint, '2024-2025'::text, 'Bayern Munich'::text, 23::integer, 7::integer, 30::integer, 75::integer, 17::smallint),
    ('c8b8d6bb-959e-4fc6-976f-9fa437041e24'::uuid, 'a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, '2012-2013'::text, 'Werder Bremen'::text, 3::integer, 10::integer, 33::integer, 10::integer, 5::smallint, '2012-2013'::text, 'Werder Bremen'::text, 10::integer, 9::integer, 34::integer, 10::integer, 4::smallint),
    ('c4df07be-dba7-40ff-9bf5-ebbc6699bce6'::uuid, 'a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, '2012-2013'::text, 'Chelsea'::text, 0::integer, 0::integer, 3::integer, 7::integer, 4::smallint, '2013-2014'::text, 'Chelsea'::text, 0::integer, null::integer, 9::integer, 7::integer, 5::smallint),
    ('044f4d64-28f8-42ba-b145-9a7c39e15f2d'::uuid, 'a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, '2013-2014'::text, 'VfL Wolfsburg'::text, 10::integer, 21::integer, 37::integer, 22::integer, 6::smallint, '2013-2014'::text, 'VfL Wolfsburg'::text, 3::integer, null::integer, 18::integer, 22::integer, 6::smallint)
    ) as rows(row_id, player_id, player_name, old_season, old_club, old_goals, old_assists, old_appearances, old_market_value, old_sort_order, season, club, goals, assists, appearances, market_value, sort_order)
  loop
    if desired.row_id is null then
      select count(*) into n from public.career_seasons where player_id = desired.player_id and season = desired.season and club = desired.club;
      if n <> 0 then raise exception '% % %: the row to add is already there', desired.player_name, desired.season, desired.club; end if;
      insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order)
      values (desired.player_id, desired.season, desired.club, desired.goals, desired.assists, desired.appearances, desired.market_value, desired.sort_order);
    else
      update public.career_seasons s
      set season = desired.season, club = desired.club, goals = desired.goals, assists = desired.assists,
          appearances = desired.appearances, market_value = desired.market_value, sort_order = desired.sort_order
      where s.id = desired.row_id and s.player_id = desired.player_id
        and s.season = desired.old_season and s.club = desired.old_club and s.goals = desired.old_goals
        and s.assists is not distinct from desired.old_assists and s.appearances = desired.old_appearances
        and s.market_value = desired.old_market_value and s.sort_order = desired.old_sort_order;
      get diagnostics updated_this_row = row_count;
      if updated_this_row <> 1 then raise exception '% % % (row %): expected one row carrying the values read on 2026-10-01, updated %', desired.player_name, desired.old_season, desired.old_club, desired.row_id, updated_this_row; end if;
    end if;
    written := written + 1;
  end loop;
  if written <> 29 then raise exception 'expected 29 career row writes (4 inserts), made %', written; end if;

  -- the after state: every touched player's path, row for row
  for desired in
    select * from (values
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 0::smallint, '2009-2010'::text, 'Real Sociedad'::text, 6::integer, null::integer, 40::integer, 3::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 1::smallint, '2010-2011'::text, 'Real Sociedad'::text, 7::integer, 4::integer, 37::integer, 8::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 2::smallint, '2011-2012'::text, 'Real Sociedad'::text, 10::integer, 5::integer, 38::integer, 12::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 3::smallint, '2012-2013'::text, 'Real Sociedad'::text, 10::integer, 6::integer, 44::integer, 20::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 4::smallint, '2013-2014'::text, 'Real Sociedad'::text, 20::integer, 5::integer, 39::integer, 30::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 5::smallint, '2014-2015'::text, 'Atlético Madrid'::text, 25::integer, 5::integer, 53::integer, 50::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 6::smallint, '2015-2016'::text, 'Atlético Madrid'::text, 32::integer, 7::integer, 54::integer, 80::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 7::smallint, '2016-2017'::text, 'Atlético Madrid'::text, 26::integer, 7::integer, 53::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 8::smallint, '2017-2018'::text, 'Atlético Madrid'::text, 29::integer, 15::integer, 49::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 9::smallint, '2018-2019'::text, 'Atlético Madrid'::text, 21::integer, 10::integer, 48::integer, 120::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 10::smallint, '2019-2020'::text, 'Barcelona'::text, 14::integer, 4::integer, 48::integer, 80::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 11::smallint, '2020-2021'::text, 'Barcelona'::text, 20::integer, 12::integer, 51::integer, 60::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 12::smallint, '2021-2022'::text, 'Atlético Madrid'::text, 9::integer, 9::integer, 39::integer, 35::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 13::smallint, '2022-2023'::text, 'Atlético Madrid'::text, 15::integer, 16::integer, 49::integer, 30::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 14::smallint, '2023-2024'::text, 'Atlético Madrid'::text, 16::integer, 8::integer, 48::integer, 20::integer),
      ('a0000001-0000-0000-0000-000000000030'::uuid, 'Antoine Griezmann'::text, 15::smallint, '2024-2025'::text, 'Atlético Madrid'::text, 8::integer, 5::integer, 25::integer, 15::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 0::smallint, '2016'::text, 'Bryne'::text, 0::integer, null::integer, 16::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 1::smallint, '2017'::text, 'Molde'::text, 4::integer, null::integer, 20::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 2::smallint, '2018'::text, 'Molde'::text, 16::integer, null::integer, 30::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 3::smallint, '2018-2019'::text, 'RB Salzburg'::text, 1::integer, null::integer, 5::integer, 10::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 4::smallint, '2019-2020'::text, 'RB Salzburg'::text, 28::integer, null::integer, 22::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 5::smallint, '2019-2020'::text, 'Borussia Dortmund'::text, 16::integer, 4::integer, 18::integer, 60::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 6::smallint, '2020-2021'::text, 'Borussia Dortmund'::text, 41::integer, 12::integer, 41::integer, 110::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 7::smallint, '2021-2022'::text, 'Borussia Dortmund'::text, 29::integer, 8::integer, 30::integer, 150::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 8::smallint, '2022-2023'::text, 'Manchester City'::text, 52::integer, 8::integer, 53::integer, 180::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 9::smallint, '2023-2024'::text, 'Manchester City'::text, 38::integer, 5::integer, 45::integer, 180::integer),
      ('a0000001-0000-0000-0000-000000000006'::uuid, 'Erling Haaland'::text, 10::smallint, '2024-2025'::text, 'Manchester City'::text, 22::integer, 4::integer, 30::integer, 180::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 0::smallint, '2010-2011'::text, 'Leyton Orient'::text, 5::integer, null::integer, 18::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 1::smallint, '2011-2012'::text, 'Tottenham'::text, 1::integer, 0::integer, 6::integer, 1::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 2::smallint, '2011-2012'::text, 'Millwall'::text, 9::integer, null::integer, 27::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 3::smallint, '2012-2013'::text, 'Tottenham'::text, 0::integer, 0::integer, 1::integer, 2::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 4::smallint, '2012-2013'::text, 'Norwich City'::text, 0::integer, null::integer, 5::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 5::smallint, '2012-2013'::text, 'Leicester City'::text, 2::integer, null::integer, 15::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 6::smallint, '2013-2014'::text, 'Tottenham'::text, 4::integer, null::integer, 19::integer, 5::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 7::smallint, '2014-2015'::text, 'Tottenham'::text, 31::integer, 5::integer, 51::integer, 25::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 8::smallint, '2015-2016'::text, 'Tottenham'::text, 28::integer, 4::integer, 50::integer, 40::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 9::smallint, '2016-2017'::text, 'Tottenham'::text, 35::integer, 7::integer, 38::integer, 60::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 10::smallint, '2017-2018'::text, 'Tottenham'::text, 41::integer, 5::integer, 48::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 11::smallint, '2018-2019'::text, 'Tottenham'::text, 24::integer, 6::integer, 40::integer, 120::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 12::smallint, '2019-2020'::text, 'Tottenham'::text, 24::integer, 2::integer, 34::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 13::smallint, '2020-2021'::text, 'Tottenham'::text, 33::integer, 17::integer, 49::integer, 120::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 14::smallint, '2021-2022'::text, 'Tottenham'::text, 27::integer, 10::integer, 50::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 15::smallint, '2022-2023'::text, 'Tottenham'::text, 32::integer, 4::integer, 49::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 16::smallint, '2023-2024'::text, 'Bayern Munich'::text, 44::integer, 12::integer, 45::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000008'::uuid, 'Harry Kane'::text, 17::smallint, '2024-2025'::text, 'Bayern Munich'::text, 23::integer, 7::integer, 30::integer, 75::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 0::smallint, '2008-2009'::text, 'Genk'::text, 0::integer, null::integer, 2::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 1::smallint, '2009-2010'::text, 'Genk'::text, 3::integer, null::integer, 40::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 2::smallint, '2010-2011'::text, 'Genk'::text, 6::integer, null::integer, 35::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 3::smallint, '2011-2012'::text, 'Genk'::text, 8::integer, null::integer, 36::integer, 0::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 4::smallint, '2012-2013'::text, 'Werder Bremen'::text, 10::integer, 9::integer, 34::integer, 10::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 5::smallint, '2013-2014'::text, 'Chelsea'::text, 0::integer, null::integer, 9::integer, 7::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 6::smallint, '2013-2014'::text, 'VfL Wolfsburg'::text, 3::integer, null::integer, 18::integer, 22::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 7::smallint, '2014-2015'::text, 'VfL Wolfsburg'::text, 16::integer, 28::integer, 51::integer, 40::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 8::smallint, '2015-2016'::text, 'Manchester City'::text, 16::integer, 15::integer, 41::integer, 65::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 9::smallint, '2016-2017'::text, 'Manchester City'::text, 6::integer, 18::integer, 36::integer, 70::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 10::smallint, '2017-2018'::text, 'Manchester City'::text, 12::integer, 21::integer, 52::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 11::smallint, '2018-2019'::text, 'Manchester City'::text, 8::integer, 11::integer, 32::integer, 120::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 12::smallint, '2019-2020'::text, 'Manchester City'::text, 16::integer, 23::integer, 48::integer, 120::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 13::smallint, '2020-2021'::text, 'Manchester City'::text, 10::integer, 18::integer, 40::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 14::smallint, '2021-2022'::text, 'Manchester City'::text, 19::integer, 14::integer, 45::integer, 100::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 15::smallint, '2022-2023'::text, 'Manchester City'::text, 8::integer, 16::integer, 32::integer, 80::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 16::smallint, '2023-2024'::text, 'Manchester City'::text, 4::integer, 10::integer, 18::integer, 45::integer),
      ('a0000001-0000-0000-0000-000000000011'::uuid, 'Kevin De Bruyne'::text, 17::smallint, '2024-2025'::text, 'Manchester City'::text, 3::integer, 7::integer, 20::integer, 30::integer)
    ) as rows(player_id, player_name, sort_order, season, club, goals, assists, appearances, market_value)
  loop
    select count(*) into n from public.career_seasons s
    where s.player_id = desired.player_id and s.sort_order = desired.sort_order and s.season = desired.season and s.club = desired.club
      and s.goals = desired.goals and s.assists is not distinct from desired.assists and s.appearances = desired.appearances and s.market_value = desired.market_value;
    if n <> 1 then raise exception '% after: expected one row % % at sort_order %, found %', desired.player_name, desired.season, desired.club, desired.sort_order, n; end if;
    checked := checked + 1;
  end loop;
  if checked <> 63 then raise exception 'expected to check 63 rows after, checked %', checked; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000030';
  if n <> 16 then raise exception 'Antoine Griezmann: expected 16 season rows after, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000006';
  if n <> 11 then raise exception 'Erling Haaland: expected 11 season rows after, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000008';
  if n <> 18 then raise exception 'Harry Kane: expected 18 season rows after, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000011';
  if n <> 18 then raise exception 'Kevin De Bruyne: expected 18 season rows after, found %', n; end if;
  select count(*) into n from public.career_seasons;
  if n <> 3644 then raise exception 'expected 3644 career_seasons rows after this migration, found %', n; end if;
  select count(*) into n from public.career_players;
  if n <> 253 then raise exception 'expected 253 career_players rows after this migration, found %', n; end if;

  -- Transfer Path: the rule entries the new links shorten, each written only over
  -- the exact value it replaces.
  select count(*) into n from public.transfer_path_puzzles;
  if n <> 885 then raise exception 'expected 885 Transfer Path puzzles, found %', n; end if;
  for desired in
    select * from (values
      ('tpa-110', 'Ederson', 'Mohamed Salah', 'classic', 3, 'Two middle men at least. The first was at Manchester City with Ederson; the last was at Liverpool with Mohamed Salah.', 2, 'One middle man does it. He was at Manchester City with Ederson and at Chelsea with Mohamed Salah.'),
      ('tpa-110', 'Ederson', 'Mohamed Salah', 'europe', 3, 'Two middle men at least. The first was at Manchester City with Ederson; the last was at Liverpool with Mohamed Salah.', 2, 'One middle man does it. He was at Manchester City with Ederson and at Chelsea with Mohamed Salah.'),
      ('tpa-438', 'Rodri', 'Samuel Eto''o', 'classic', 3, 'Two middle men at least. The first was at Atlético Madrid with Rodri; the last was at Chelsea with Samuel Eto''o.', 2, 'One middle man does it. He was at Manchester City with Rodri and at Chelsea with Samuel Eto''o.'),
      ('tpa-438', 'Rodri', 'Samuel Eto''o', 'europe', 3, 'Two middle men at least. The first was at Atlético Madrid with Rodri; the last was at Chelsea with Samuel Eto''o.', 2, 'One middle man does it. He was at Manchester City with Rodri and at Chelsea with Samuel Eto''o.'),
      ('tpa-535', 'Erling Haaland', 'Samuel Eto''o', 'classic', 3, 'Two middle men at least. The first was at Borussia Dortmund with Erling Haaland; the last was at Barcelona with Samuel Eto''o.', 2, 'One middle man does it. He was at Manchester City with Erling Haaland and at Chelsea with Samuel Eto''o.'),
      ('tpa-535', 'Erling Haaland', 'Samuel Eto''o', 'europe', 3, 'Two middle men at least. The first was at Borussia Dortmund with Erling Haaland; the last was at Barcelona with Samuel Eto''o.', 2, 'One middle man does it. He was at Manchester City with Erling Haaland and at Chelsea with Samuel Eto''o.'),
      ('tpa-924', 'Andrew Robertson', 'Kevin De Bruyne', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Manchester City with Kevin De Bruyne.', 2, 'One middle man does it. He was at Liverpool with Andrew Robertson and at Chelsea with Kevin De Bruyne.'),
      ('tpa-924', 'Andrew Robertson', 'Kevin De Bruyne', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Manchester City with Kevin De Bruyne.', 2, 'One middle man does it. He was at Liverpool with Andrew Robertson and at Chelsea with Kevin De Bruyne.')
    ) as rows(puzzle_id, player_a, player_b, rule, old_min_steps, old_hint, min_steps, hint)
  loop
    if desired.rule = 'classic' then
      update public.transfer_path_puzzles p
      set min_steps = desired.min_steps,
          hint = desired.hint
      where p.puzzle_id = desired.puzzle_id
        and p.player_a = desired.player_a
        and p.player_b = desired.player_b
        and p.min_steps = desired.old_min_steps
        and p.hint = desired.old_hint;
    elsif desired.rule = 'europe' then
      update public.transfer_path_puzzles p
      set europe_min_steps = desired.min_steps::smallint,
          europe_hint = desired.hint
      where p.puzzle_id = desired.puzzle_id
        and p.player_a = desired.player_a
        and p.player_b = desired.player_b
        and p.europe_min_steps = desired.old_min_steps
        and p.europe_hint = desired.old_hint;
    else
      raise exception 'unknown Transfer Path rule %', desired.rule;
    end if;
    get diagnostics updated_this_row = row_count;
    if updated_this_row <> 1 then
      raise exception 'Transfer Path % under %: expected one row carrying %, updated %', desired.puzzle_id, desired.rule, desired.old_min_steps, updated_this_row;
    end if;
    updated_rows := updated_rows + 1;
  end loop;
  if updated_rows <> 8 then raise exception 'expected to rewrite 8 Transfer Path entries, rewrote %', updated_rows; end if;

  -- Active players only: written over the applied 2026-09-07 value or over the value
  -- the pending Round 531 refresh writes, whichever the table carries, and nothing else.
  updated_rows := 0;
  for desired in
    select * from (values
      ('tpa-924', 'Andrew Robertson', 'Kevin De Bruyne', 3, 'Two middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Manchester City with Kevin De Bruyne.', 3, 'Two middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Chelsea with Kevin De Bruyne.', 2, 'One middle man does it. He was at Liverpool with Andrew Robertson and at Chelsea with Kevin De Bruyne.')
    ) as rows(puzzle_id, player_a, player_b, applied_min_steps, applied_hint, pending_min_steps, pending_hint, min_steps, hint)
  loop
    update public.transfer_path_puzzles p
    set active_min_steps = desired.min_steps::smallint,
        active_hint = desired.hint
    where p.puzzle_id = desired.puzzle_id
      and p.player_a = desired.player_a
      and p.player_b = desired.player_b
      and ((p.active_min_steps = desired.applied_min_steps and p.active_hint = desired.applied_hint)
        or (p.active_min_steps = desired.pending_min_steps and p.active_hint = desired.pending_hint));
    get diagnostics updated_this_row = row_count;
    if updated_this_row <> 1 then
      raise exception 'Transfer Path % under active: expected one row carrying the applied or the pending refresh value, updated %', desired.puzzle_id, updated_this_row;
    end if;
    updated_rows := updated_rows + 1;
  end loop;
  if updated_rows <> 1 then raise exception 'expected to rewrite 1 active entries, rewrote %', updated_rows; end if;
end
$migration$;
