-- soccer_grid_puzzles: Batch 2A (sg-016 through sg-030), sort_order 15-29. Round 4 Session 1.
INSERT INTO public.soccer_grid_puzzles (puzzle_id, rows_json, cols_json, sort_order) VALUES
  ('sg-016', '[{"label":"Played for Ajax","type":"club"},{"label":"Played for Porto","type":"club"},{"label":"Played for Benfica","type":"club"}]', '[{"label":"Played in Premier League","type":"league"},{"label":"Forward (FWD)","type":"position"},{"label":"Champions League Winner","type":"champions_league"}]', 15),
  ('sg-017', '[{"label":"Played for Sevilla","type":"club"},{"label":"Played for Marseille","type":"club"},{"label":"Played for Galatasaray","type":"club"}]', '[{"label":"Played in Premier League","type":"league"},{"label":"Forward (FWD)","type":"position"},{"label":"French","type":"nationality"}]', 16),
  ('sg-018', '[{"label":"Played for Bayer Leverkusen","type":"club"},{"label":"Played for Lazio","type":"club"},{"label":"Played for Sporting CP","type":"club"}]', '[{"label":"Midfielder (MID)","type":"position"},{"label":"Played in Premier League","type":"league"},{"label":"Champions League Winner","type":"champions_league"}]', 17),
  ('sg-019', '[{"label":"Colombian","type":"nationality"},{"label":"Uruguayan","type":"nationality"},{"label":"Chilean","type":"nationality"}]', '[{"label":"Played for Barcelona","type":"club"},{"label":"Played in Premier League","type":"league"},{"label":"Copa América Winner","type":"misc"}]', 18),
  ('sg-020', '[{"label":"Played for Boca Juniors","type":"club"},{"label":"Played for River Plate","type":"club"},{"label":"Croatian","type":"nationality"}]', '[{"label":"Played in Serie A","type":"league"},{"label":"Midfielder (MID)","type":"position"},{"label":"Played in La Liga","type":"league"}]', 19),
  ('sg-021', '[{"label":"Played for Fiorentina","type":"club"},{"label":"Played for Valencia","type":"club"},{"label":"Played for Villarreal","type":"club"}]', '[{"label":"Argentine","type":"nationality"},{"label":"Played in La Liga","type":"league"},{"label":"Midfielder (MID)","type":"position"}]', 20),
  ('sg-022', '[{"label":"Played for Celtic","type":"club"},{"label":"Played for PSV","type":"club"},{"label":"Played for Feyenoord","type":"club"}]', '[{"label":"Defender (DEF)","type":"position"},{"label":"Played in Premier League","type":"league"},{"label":"Dutch","type":"nationality"}]', 21),
  ('sg-023', '[{"label":"Played for Lyon","type":"club"},{"label":"Played for Monaco","type":"club"},{"label":"Played for Lille","type":"club"}]', '[{"label":"Defender (DEF)","type":"position"},{"label":"Played in Ligue 1","type":"league"},{"label":"Played in Serie A","type":"league"}]', 22),
  ('sg-024', '[{"label":"Belgian","type":"nationality"},{"label":"Polish","type":"nationality"},{"label":"Norwegian","type":"nationality"}]', '[{"label":"Played for Borussia Dortmund","type":"club"},{"label":"Played in Ligue 1","type":"league"},{"label":"Goalkeeper (GK)","type":"position"}]', 23),
  ('sg-025', '[{"label":"Played for Manchester United","type":"club"},{"label":"Played for Bayern Munich","type":"club"},{"label":"Played for Juventus","type":"club"}]', '[{"label":"Ballon d''Or Winner","type":"award"},{"label":"World Cup Winner","type":"world_cup"},{"label":"Over 100 International Caps","type":"misc"}]', 24),
  ('sg-026', '[{"label":"Played for Newcastle","type":"club"},{"label":"Played for Everton","type":"club"},{"label":"Played for West Ham","type":"club"}]', '[{"label":"Played in Eredivisie","type":"league"},{"label":"Defender (DEF)","type":"position"},{"label":"Played in Serie A","type":"league"}]', 25),
  ('sg-027', '[{"label":"Played for Eintracht Frankfurt","type":"club"},{"label":"Played for Schalke","type":"club"},{"label":"Played for Beşiktaş","type":"club"}]', '[{"label":"Played in Premier League","type":"league"},{"label":"Played in Süper Lig","type":"league"},{"label":"Midfielder (MID)","type":"position"}]', 26),
  ('sg-028', '[{"label":"Senegalese","type":"nationality"},{"label":"Ivorian","type":"nationality"},{"label":"Cameroonian","type":"nationality"}]', '[{"label":"African Cup of Nations Winner","type":"misc"},{"label":"Played in Ligue 1","type":"league"},{"label":"Played for Chelsea","type":"club"}]', 27),
  ('sg-029', '[{"label":"Played for Real Madrid","type":"club"},{"label":"Played for Bayern Munich","type":"club"},{"label":"Played for Inter Milan","type":"club"}]', '[{"label":"World Cup Winner","type":"world_cup"},{"label":"UEFA Euro Winner","type":"misc"},{"label":"Europa League Winner","type":"award"}]', 28),
  ('sg-030', '[{"label":"Played for Liverpool","type":"club"},{"label":"Played for Chelsea","type":"club"},{"label":"Played for Manchester City","type":"club"}]', '[{"label":"Played in Saudi Pro League","type":"misc"},{"label":"Goalkeeper (GK)","type":"position"},{"label":"Brazilian","type":"nationality"}]', 29);
