-- Round 1010b, wave 1: the 2025-2026 season for the Liverpool men of the
-- career pool, their 2024-2025 rows corrected, and the Alisson twin removed.
--
-- GENERATED by scripts/genCareerSeasonAdditions.mjs from scripts/data/careerSeason2025.json,
-- which carries every row below with its sources. Do not edit by hand.
-- NOT APPLIED. Apply on or after 2026-10-15 ET, away from midnight ET, after the
-- Round 531 active refresh (20260911190000_refresh_verified_active_transfer_path_hints.sql): this block refuses
-- to run on any other active state. After applying, node scripts/bakeCareerPlayers.mjs
-- must leave src/data/careerPlayers.ts unchanged except its date stamp, then run
-- node scripts/genCareerLadderRoster.mjs (expect an x line for the removed id).
--
--   added: 7 rows for 2025-2026, assists only where two sources agree, market value 0 (n/a)
--   changed: 8 rows of 2024-2025 set to their final all competitions totals, each guarded by its old values
--   removed: Alisson Becker (a0000001-0000-0000-0000-000000000066), kept as Alisson; his 13 season rows go with him (ON DELETE CASCADE)
--   Transfer Path: 13 puzzles renamed, 53 entries rewritten (18 classic, 19 Europe, 16 active),
--   each guarded by the value it replaces and each the search's own on the pool after this migration
--   career_players 253 to 252, career_seasons 3640 to 3634, active entries 212 to 221
--   Career Quiz on 2026-10-15: 60 of the next 60 days deal a different man (Andrew Robertson becomes Rúben Dias);
--   42 of those 60 answers were dealt in the 90 days before (0 without the change).
--   Coverage: 80 men still stop at 2024-2025 after this wave.

do $migration$
declare
  n integer;
  next_order integer;
  desired record;
  updated_this_row integer;
  updated_rows integer := 0;
begin
  select count(*) into n from public.career_players;
  if n <> 253 then raise exception 'expected 253 career_players rows before this migration, found %', n; end if;
  select count(*) into n from public.career_seasons;
  if n <> 3640 then raise exception 'expected 3640 career_seasons rows before this migration, found %', n; end if;
  select count(*) into n from public.transfer_path_puzzles;
  if n <> 885 then raise exception 'expected 885 Transfer Path puzzles, found %', n; end if;
  select count(*) into n from public.transfer_path_puzzles where active_min_steps is not null and active_hint is not null;
  if n <> 212 then raise exception 'expected the 212 active entries of the Round 531 refresh, found %; apply 20260911190000_refresh_verified_active_transfer_path_hints.sql first', n; end if;

  -- Alisson Becker is Alisson twice: the same 13 season and club keys both ways, and exactly the rows the ledger copies
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000066' and player_name = 'Alisson Becker';
  if n <> 1 then raise exception 'Alisson Becker: expected one career_players row at a0000001-0000-0000-0000-000000000066, found %', n; end if;
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000040' and player_name = 'Alisson';
  if n <> 1 then raise exception 'Alisson: expected one career_players row at a0000001-0000-0000-0000-000000000040, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000066' except select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040') x;
  if n <> 0 then raise exception 'Alisson Becker carries % season and club keys Alisson does not', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040' except select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000066') x;
  if n <> 0 then raise exception 'Alisson carries % season and club keys Alisson Becker does not', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000066';
  if n <> 13 then raise exception 'Alisson Becker: expected 13 season rows, found %', n; end if;
  select count(*) into n from public.career_seasons s join (values
    ('2013', 'Internacional', 0, null::integer, 9, 0),
    ('2014', 'Internacional', 0, null::integer, 14, 0),
    ('2015', 'Internacional', 0, 0, 57, 5),
    ('2016', 'Internacional', 0, 0, 20, 8),
    ('2016-2017', 'Roma', 0, 0, 37, 15),
    ('2017-2018', 'Roma', 0, 0, 49, 40),
    ('2018-2019', 'Liverpool', 0, 1, 51, 60),
    ('2019-2020', 'Liverpool', 0, 0, 29, 65),
    ('2020-2021', 'Liverpool', 1, 0, 44, 60),
    ('2021-2022', 'Liverpool', 0, 0, 46, 55),
    ('2022-2023', 'Liverpool', 0, 0, 37, 50),
    ('2023-2024', 'Liverpool', 0, 0, 41, 45),
    ('2024-2025', 'Liverpool', 0, 0, 28, 40)
  ) as v(season, club, goals, assists, appearances, market_value)
    on s.season = v.season and s.club = v.club and s.goals = v.goals and s.assists is not distinct from v.assists and s.appearances = v.appearances and s.market_value = v.market_value
  where s.player_id = 'a0000001-0000-0000-0000-000000000066';
  if n <> 13 then raise exception 'Alisson Becker: only % of his 13 rows are the ones the ledger copies', n; end if;

  -- Alisson 2024-2025 Liverpool: 22 apps 0 goals to 35 apps 0 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000040' and player_name = 'Alisson';
  if n <> 1 then raise exception 'Alisson: expected one career_players row at a0000001-0000-0000-0000-000000000040, found %', n; end if;
  update public.career_seasons set goals = 0, assists = 0, appearances = 35
  where player_id = 'a0000001-0000-0000-0000-000000000040' and season = '2024-2025' and club = 'Liverpool' and goals = 0 and assists is not distinct from 0 and appearances = 22 and market_value = 30;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Alisson 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Andrew Robertson 2024-2025 Liverpool: 22 apps 0 goals to 45 apps 0 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000131' and player_name = 'Andrew Robertson';
  if n <> 1 then raise exception 'Andrew Robertson: expected one career_players row at a0000001-0000-0000-0000-000000000131, found %', n; end if;
  update public.career_seasons set goals = 0, assists = 2, appearances = 45
  where player_id = 'a0000001-0000-0000-0000-000000000131' and season = '2024-2025' and club = 'Liverpool' and goals = 0 and assists is not distinct from 5 and appearances = 22 and market_value = 18;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Andrew Robertson 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Federico Chiesa 2024-2025 Liverpool: 15 apps 3 goals to 14 apps 2 goals (wrong, corrected to the final totals)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000103' and player_name = 'Federico Chiesa';
  if n <> 1 then raise exception 'Federico Chiesa: expected one career_players row at a0000001-0000-0000-0000-000000000103, found %', n; end if;
  update public.career_seasons set goals = 2, assists = 1, appearances = 14
  where player_id = 'a0000001-0000-0000-0000-000000000103' and season = '2024-2025' and club = 'Liverpool' and goals = 3 and assists is not distinct from 2 and appearances = 15 and market_value = 18;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Federico Chiesa 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Mohamed Salah 2024-2025 Liverpool: 30 apps 18 goals to 52 apps 34 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000007' and player_name = 'Mohamed Salah';
  if n <> 1 then raise exception 'Mohamed Salah: expected one career_players row at a0000001-0000-0000-0000-000000000007, found %', n; end if;
  update public.career_seasons set goals = 34, assists = 23, appearances = 52
  where player_id = 'a0000001-0000-0000-0000-000000000007' and season = '2024-2025' and club = 'Liverpool' and goals = 18 and assists is not distinct from 13 and appearances = 30 and market_value = 45;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Mohamed Salah 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Virgil van Dijk 2024-2025 Liverpool: 28 apps 2 goals to 49 apps 5 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000026' and player_name = 'Virgil van Dijk';
  if n <> 1 then raise exception 'Virgil van Dijk: expected one career_players row at a0000001-0000-0000-0000-000000000026, found %', n; end if;
  update public.career_seasons set goals = 5, assists = 1, appearances = 49
  where player_id = 'a0000001-0000-0000-0000-000000000026' and season = '2024-2025' and club = 'Liverpool' and goals = 2 and assists is not distinct from 1 and appearances = 28 and market_value = 25;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Virgil van Dijk 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Diogo Jota 2024-2025 Liverpool: 20 apps 6 goals to 37 apps 9 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000100' and player_name = 'Diogo Jota';
  if n <> 1 then raise exception 'Diogo Jota: expected one career_players row at a0000001-0000-0000-0000-000000000100, found %', n; end if;
  update public.career_seasons set goals = 9, assists = 3, appearances = 37
  where player_id = 'a0000001-0000-0000-0000-000000000100' and season = '2024-2025' and club = 'Liverpool' and goals = 6 and assists is not distinct from 3 and appearances = 20 and market_value = 45;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Diogo Jota 2024-2025 Liverpool: expected one row carrying the old values, updated %', n; end if;

  -- Alexander Isak 2024-2025 Newcastle: 25 apps 18 goals to 42 apps 27 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000060' and player_name = 'Alexander Isak';
  if n <> 1 then raise exception 'Alexander Isak: expected one career_players row at a0000001-0000-0000-0000-000000000060, found %', n; end if;
  update public.career_seasons set goals = 27, assists = null::integer, appearances = 42
  where player_id = 'a0000001-0000-0000-0000-000000000060' and season = '2024-2025' and club = 'Newcastle' and goals = 18 and assists is not distinct from 3 and appearances = 25 and market_value = 90;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Alexander Isak 2024-2025 Newcastle: expected one row carrying the old values, updated %', n; end if;

  -- Florian Wirtz 2024-2025 Bayer Leverkusen: 28 apps 12 goals to 45 apps 16 goals (a mid-season snapshot)
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000056' and player_name = 'Florian Wirtz';
  if n <> 1 then raise exception 'Florian Wirtz: expected one career_players row at a0000001-0000-0000-0000-000000000056, found %', n; end if;
  update public.career_seasons set goals = 16, assists = null::integer, appearances = 45
  where player_id = 'a0000001-0000-0000-0000-000000000056' and season = '2024-2025' and club = 'Bayer Leverkusen' and goals = 12 and assists is not distinct from 9 and appearances = 28 and market_value = 150;
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Florian Wirtz 2024-2025 Bayer Leverkusen: expected one row carrying the old values, updated %', n; end if;

  -- Alisson: 2025-2026 Liverpool after 2024-2025 Liverpool
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000040' and player_name = 'Alisson';
  if n <> 1 then raise exception 'Alisson: expected one career_players row at a0000001-0000-0000-0000-000000000040, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040';
  if n <> 13 then raise exception 'Alisson: expected 13 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Liverpool';
  if n <> 1 then raise exception 'Alisson: the path no longer ends at 2024-2025 Liverpool'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Alisson: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000040';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000040', '2025-2026', 'Liverpool', 0, 0, 35, 0, next_order + 1);

  -- Andrew Robertson: 2025-2026 Liverpool after 2024-2025 Liverpool
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000131' and player_name = 'Andrew Robertson';
  if n <> 1 then raise exception 'Andrew Robertson: expected one career_players row at a0000001-0000-0000-0000-000000000131, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000131';
  if n <> 11 then raise exception 'Andrew Robertson: expected 11 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000131' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Liverpool';
  if n <> 1 then raise exception 'Andrew Robertson: the path no longer ends at 2024-2025 Liverpool'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000131' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Andrew Robertson: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000131';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000131', '2025-2026', 'Liverpool', 3, 2, 36, 0, next_order + 1);

  -- Federico Chiesa: 2025-2026 Liverpool after 2024-2025 Liverpool
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000103' and player_name = 'Federico Chiesa';
  if n <> 1 then raise exception 'Federico Chiesa: expected one career_players row at a0000001-0000-0000-0000-000000000103, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000103';
  if n <> 9 then raise exception 'Federico Chiesa: expected 9 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000103' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Liverpool';
  if n <> 1 then raise exception 'Federico Chiesa: the path no longer ends at 2024-2025 Liverpool'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000103' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Federico Chiesa: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000103';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000103', '2025-2026', 'Liverpool', 3, 3, 36, 0, next_order + 1);

  -- Mohamed Salah: 2025-2026 Liverpool after 2024-2025 Liverpool
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000007' and player_name = 'Mohamed Salah';
  if n <> 1 then raise exception 'Mohamed Salah: expected one career_players row at a0000001-0000-0000-0000-000000000007, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000007';
  if n <> 16 then raise exception 'Mohamed Salah: expected 16 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000007' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Liverpool';
  if n <> 1 then raise exception 'Mohamed Salah: the path no longer ends at 2024-2025 Liverpool'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000007' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Mohamed Salah: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000007';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000007', '2025-2026', 'Liverpool', 12, 10, 41, 0, next_order + 1);

  -- Virgil van Dijk: 2025-2026 Liverpool after 2024-2025 Liverpool
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000026' and player_name = 'Virgil van Dijk';
  if n <> 1 then raise exception 'Virgil van Dijk: expected one career_players row at a0000001-0000-0000-0000-000000000026, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000026';
  if n <> 12 then raise exception 'Virgil van Dijk: expected 12 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000026' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Liverpool';
  if n <> 1 then raise exception 'Virgil van Dijk: the path no longer ends at 2024-2025 Liverpool'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000026' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Virgil van Dijk: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000026';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000026', '2025-2026', 'Liverpool', 8, 3, 55, 0, next_order + 1);

  -- Alexander Isak: 2025-2026 Liverpool after 2024-2025 Newcastle
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000060' and player_name = 'Alexander Isak';
  if n <> 1 then raise exception 'Alexander Isak: expected one career_players row at a0000001-0000-0000-0000-000000000060, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000060';
  if n <> 8 then raise exception 'Alexander Isak: expected 8 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000060' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Newcastle';
  if n <> 1 then raise exception 'Alexander Isak: the path no longer ends at 2024-2025 Newcastle'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000060' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Alexander Isak: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000060';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000060', '2025-2026', 'Liverpool', 4, 1, 22, 0, next_order + 1);

  -- Florian Wirtz: 2025-2026 Liverpool after 2024-2025 Bayer Leverkusen
  select count(*) into n from public.career_players where id = 'a0000001-0000-0000-0000-000000000056' and player_name = 'Florian Wirtz';
  if n <> 1 then raise exception 'Florian Wirtz: expected one career_players row at a0000001-0000-0000-0000-000000000056, found %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000056';
  if n <> 6 then raise exception 'Florian Wirtz: expected 6 season rows, found %', n; end if;
  select count(*) into n from (select season, club from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000056' order by sort_order desc limit 1) t where t.season = '2024-2025' and t.club = 'Bayer Leverkusen';
  if n <> 1 then raise exception 'Florian Wirtz: the path no longer ends at 2024-2025 Bayer Leverkusen'; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000056' and season = '2025-2026' and club = 'Liverpool';
  if n <> 0 then raise exception 'Florian Wirtz: 2025-2026 Liverpool is already there'; end if;
  select max(sort_order) into next_order from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000056';
  insert into public.career_seasons (player_id, season, club, goals, assists, appearances, market_value, sort_order) values
    ('a0000001-0000-0000-0000-000000000056', '2025-2026', 'Liverpool', 7, 8, 49, 0, next_order + 1);

  delete from public.career_players where id = 'a0000001-0000-0000-0000-000000000066' and player_name = 'Alisson Becker';
  get diagnostics n = row_count;
  if n <> 1 then raise exception 'Alisson Becker: expected to delete one career_players row, deleted %', n; end if;
  select count(*) into n from public.career_seasons where player_id = 'a0000001-0000-0000-0000-000000000066';
  if n <> 0 then raise exception 'Alisson Becker: % season rows survived the delete', n; end if;

  select count(*) into n from public.career_players;
  if n <> 252 then raise exception 'expected 252 career_players rows after this migration, found %', n; end if;
  select count(*) into n from public.career_seasons;
  if n <> 3634 then raise exception 'expected 3634 career_seasons rows after this migration, found %', n; end if;

  -- Transfer Path: every puzzle naming a removed man is renamed (never deleted, a delete moves the daily)
  for desired in
    select * from (values
      ('tpa-112', 'Alisson Becker', 'Leroy Sané', 'Alisson', 'Leroy Sané'),
      ('tpa-392', 'Alisson Becker', 'Sergio Ramos', 'Alisson', 'Sergio Ramos'),
      ('tpa-428', 'Alexis Sánchez', 'Alisson Becker', 'Alexis Sánchez', 'Alisson'),
      ('tpa-429', 'Alisson Becker', 'Steven Gerrard', 'Alisson', 'Steven Gerrard'),
      ('tpa-637', 'Alisson Becker', 'Arturo Vidal', 'Alisson', 'Arturo Vidal'),
      ('tpa-639', 'Alisson Becker', 'Sergio Busquets', 'Alisson', 'Sergio Busquets'),
      ('tpa-668', 'Alisson Becker', 'Rúben Dias', 'Alisson', 'Rúben Dias'),
      ('tpa-680', 'Alisson Becker', 'Rafael Leão', 'Alisson', 'Rafael Leão'),
      ('tpa-716', 'Alisson Becker', 'David Alaba', 'Alisson', 'David Alaba'),
      ('tpa-740', 'Alisson Becker', 'Lionel Messi', 'Alisson', 'Lionel Messi'),
      ('tpa-762', 'Alisson Becker', 'Mikel Oyarzabal', 'Alisson', 'Mikel Oyarzabal'),
      ('tpa-779', 'Alisson Becker', 'Arda Güler', 'Alisson', 'Arda Güler'),
      ('tpa-963', 'Alisson Becker', 'Gianluigi Buffon', 'Alisson', 'Gianluigi Buffon')
    ) as rows(puzzle_id, old_player_a, old_player_b, player_a, player_b)
  loop
    update public.transfer_path_puzzles p set player_a = desired.player_a, player_b = desired.player_b
    where p.puzzle_id = desired.puzzle_id and p.player_a = desired.old_player_a and p.player_b = desired.old_player_b;
    get diagnostics updated_this_row = row_count;
    if updated_this_row <> 1 then raise exception 'Transfer Path %: expected one row named % to %, renamed %', desired.puzzle_id, desired.old_player_a, desired.old_player_b, updated_this_row; end if;
    updated_rows := updated_rows + 1;
  end loop;
  if updated_rows <> 13 then raise exception 'expected to rename 13 Transfer Path puzzles, renamed %', updated_rows; end if;
  select count(*) into n from public.transfer_path_puzzles where player_a = 'Alisson Becker' or player_b = 'Alisson Becker';
  if n <> 0 then raise exception '% Transfer Path puzzles still name Alisson Becker', n; end if;

  -- the entries the new pool beats, each written only over the exact value it replaces (null allowed)
  updated_rows := 0;
  for desired in
    select * from (values
      ('tpa-112', 'Alisson', 'Leroy Sané', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with Leroy Sané.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with Leroy Sané.'),
      ('tpa-112', 'Alisson', 'Leroy Sané', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with Leroy Sané.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with Leroy Sané.'),
      ('tpa-112', 'Alisson', 'Leroy Sané', 'active', null::smallint, null::text, 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with Leroy Sané.'),
      ('tpa-120', 'Florian Wirtz', 'Rafael Leão', 'classic', 4, 'Three middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at AC Milan with Rafael Leão.', 3, 'Two middle men at least. The first was at Liverpool with Florian Wirtz; the last was at AC Milan with Rafael Leão.'),
      ('tpa-120', 'Florian Wirtz', 'Rafael Leão', 'europe', 4, 'Three middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at AC Milan with Rafael Leão.', 3, 'Two middle men at least. The first was at Liverpool with Florian Wirtz; the last was at AC Milan with Rafael Leão.'),
      ('tpa-120', 'Florian Wirtz', 'Rafael Leão', 'active', 6, '5 middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at AC Milan with Rafael Leão.', 3, 'Two middle men at least. The first was at Liverpool with Florian Wirtz; the last was at AC Milan with Rafael Leão.'),
      ('tpa-207', 'Alisson', 'Sandro Tonali', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at AC Milan with Sandro Tonali.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Newcastle with Sandro Tonali.'),
      ('tpa-207', 'Alisson', 'Sandro Tonali', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at AC Milan with Sandro Tonali.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Newcastle with Sandro Tonali.'),
      ('tpa-207', 'Alisson', 'Sandro Tonali', 'active', 5, 'Four middle men at least. The first was at Liverpool with Alisson; the last was at Newcastle with Sandro Tonali.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Newcastle with Sandro Tonali.'),
      ('tpa-257', 'Alisson', 'Cristian Pulisic', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Borussia Dortmund with Cristian Pulisic.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Borussia Dortmund with Cristian Pulisic.'),
      ('tpa-257', 'Alisson', 'Cristian Pulisic', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Borussia Dortmund with Cristian Pulisic.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Borussia Dortmund with Cristian Pulisic.'),
      ('tpa-275', 'Darwin Núñez', 'Mikel Oyarzabal', 'active', 4, 'Three middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Real Sociedad with Mikel Oyarzabal.', 3, 'Two middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-286', 'Darwin Núñez', 'Moussa Diaby', 'active', 4, 'Three middle men at least. The first was at Liverpool with Darwin Núñez; the last was at PSG with Moussa Diaby.', 3, 'Two middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Bayer Leverkusen with Moussa Diaby.'),
      ('tpa-296', 'Alejandro Garnacho', 'Alisson', 'europe', 4, 'Three middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Liverpool with Alisson.', 3, 'Two middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Liverpool with Alisson.'),
      ('tpa-392', 'Alisson', 'Sergio Ramos', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Madrid with Sergio Ramos.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Sergio Ramos.'),
      ('tpa-392', 'Alisson', 'Sergio Ramos', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Madrid with Sergio Ramos.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Sergio Ramos.'),
      ('tpa-392', 'Alisson', 'Sergio Ramos', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Sergio Ramos.'),
      ('tpa-412', 'Florian Wirtz', 'Steven Gerrard', 'classic', 4, 'Three middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Liverpool with Steven Gerrard.', 3, 'Two middle men at least. The first was at Liverpool with Florian Wirtz; the last was at Liverpool with Steven Gerrard.'),
      ('tpa-412', 'Florian Wirtz', 'Steven Gerrard', 'europe', 4, 'Three middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Liverpool with Steven Gerrard.', 3, 'Two middle men at least. The first was at Liverpool with Florian Wirtz; the last was at Liverpool with Steven Gerrard.'),
      ('tpa-428', 'Alexis Sánchez', 'Alisson', 'classic', 2, 'One middle man does it. He was at Barcelona with Alexis Sánchez and at Liverpool with Alisson Becker.', 2, 'One middle man does it. He was at Barcelona with Alexis Sánchez and at Liverpool with Alisson.'),
      ('tpa-428', 'Alexis Sánchez', 'Alisson', 'europe', 2, 'One middle man does it. He was at Barcelona with Alexis Sánchez and at Liverpool with Alisson Becker.', 2, 'One middle man does it. He was at Barcelona with Alexis Sánchez and at Liverpool with Alisson.'),
      ('tpa-429', 'Alisson', 'Steven Gerrard', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and, in another season, at Liverpool with Steven Gerrard.', 2, 'One middle man does it. He was at Liverpool with Alisson and, in another season, at Liverpool with Steven Gerrard.'),
      ('tpa-429', 'Alisson', 'Steven Gerrard', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and, in another season, at Liverpool with Steven Gerrard.', 2, 'One middle man does it. He was at Liverpool with Alisson and, in another season, at Liverpool with Steven Gerrard.'),
      ('tpa-450', 'Mikel Oyarzabal', 'Moussa Diaby', 'active', 4, 'Three middle men at least. The first was at Real Sociedad with Mikel Oyarzabal; the last was at PSG with Moussa Diaby.', 3, 'Two middle men at least. The first was at Real Sociedad with Mikel Oyarzabal; the last was at Bayer Leverkusen with Moussa Diaby.'),
      ('tpa-470', 'Rafael Leão', 'Virgil van Dijk', 'active', 6, '5 middle men at least. The first was at AC Milan with Rafael Leão; the last was at Southampton with Virgil van Dijk.', 3, 'Two middle men at least. The first was at AC Milan with Rafael Leão; the last was at Liverpool with Virgil van Dijk.'),
      ('tpa-637', 'Alisson', 'Arturo Vidal', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with Arturo Vidal.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with Arturo Vidal.'),
      ('tpa-637', 'Alisson', 'Arturo Vidal', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with Arturo Vidal.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with Arturo Vidal.'),
      ('tpa-637', 'Alisson', 'Arturo Vidal', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Bayern Munich with Arturo Vidal.'),
      ('tpa-639', 'Alisson', 'Sergio Busquets', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Barcelona with Sergio Busquets.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Barcelona with Sergio Busquets.'),
      ('tpa-639', 'Alisson', 'Sergio Busquets', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Barcelona with Sergio Busquets.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Barcelona with Sergio Busquets.'),
      ('tpa-668', 'Alisson', 'Rúben Dias', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Manchester City with Rúben Dias.', 3, 'Two middle men at least. The first was at Internacional with Alisson; the last was at Manchester City with Rúben Dias.'),
      ('tpa-668', 'Alisson', 'Rúben Dias', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Manchester City with Rúben Dias.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Manchester City with Rúben Dias.'),
      ('tpa-668', 'Alisson', 'Rúben Dias', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Manchester City with Rúben Dias.'),
      ('tpa-680', 'Alisson', 'Rafael Leão', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at AC Milan with Rafael Leão.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at AC Milan with Rafael Leão.'),
      ('tpa-680', 'Alisson', 'Rafael Leão', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at AC Milan with Rafael Leão.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at AC Milan with Rafael Leão.'),
      ('tpa-680', 'Alisson', 'Rafael Leão', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at AC Milan with Rafael Leão.'),
      ('tpa-716', 'Alisson', 'David Alaba', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with David Alaba.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with David Alaba.'),
      ('tpa-716', 'Alisson', 'David Alaba', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Bayern Munich with David Alaba.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Bayern Munich with David Alaba.'),
      ('tpa-716', 'Alisson', 'David Alaba', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Bayern Munich with David Alaba.'),
      ('tpa-740', 'Alisson', 'Lionel Messi', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Barcelona with Lionel Messi.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Barcelona with Lionel Messi.'),
      ('tpa-740', 'Alisson', 'Lionel Messi', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Barcelona with Lionel Messi.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Barcelona with Lionel Messi.'),
      ('tpa-740', 'Alisson', 'Lionel Messi', 'active', null::smallint, null::text, 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at PSG with Lionel Messi.'),
      ('tpa-762', 'Alisson', 'Mikel Oyarzabal', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Sociedad with Mikel Oyarzabal.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-762', 'Alisson', 'Mikel Oyarzabal', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Sociedad with Mikel Oyarzabal.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-762', 'Alisson', 'Mikel Oyarzabal', 'active', null::smallint, null::text, 2, 'One middle man does it. He was at Liverpool with Alisson and at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-779', 'Alisson', 'Arda Güler', 'classic', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Madrid with Arda Güler.', 3, 'Two middle men at least. The first was at Internacional with Alisson; the last was at Real Madrid with Arda Güler.'),
      ('tpa-779', 'Alisson', 'Arda Güler', 'europe', 3, 'Two middle men at least. The first was at Liverpool with Alisson Becker; the last was at Real Madrid with Arda Güler.', 3, 'Two middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Arda Güler.'),
      ('tpa-779', 'Alisson', 'Arda Güler', 'active', null::smallint, null::text, 4, 'Three middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Arda Güler.'),
      ('tpa-846', 'Darwin Núñez', 'Rafael Leão', 'active', 6, '5 middle men at least. The first was at Liverpool with Darwin Núñez; the last was at AC Milan with Rafael Leão.', 4, 'Three middle men at least. The first was at Liverpool with Darwin Núñez; the last was at AC Milan with Rafael Leão.'),
      ('tpa-873', 'Florian Wirtz', 'Paulo Dybala', 'classic', 3, 'Two middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Juventus with Paulo Dybala.', 2, 'One middle man does it. He was at Liverpool with Florian Wirtz and at Juventus with Paulo Dybala.'),
      ('tpa-873', 'Florian Wirtz', 'Paulo Dybala', 'europe', 3, 'Two middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Juventus with Paulo Dybala.', 2, 'One middle man does it. He was at Liverpool with Florian Wirtz and at Juventus with Paulo Dybala.'),
      ('tpa-963', 'Alisson', 'Gianluigi Buffon', 'classic', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Juventus with Gianluigi Buffon.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Juventus with Gianluigi Buffon.'),
      ('tpa-963', 'Alisson', 'Gianluigi Buffon', 'europe', 2, 'One middle man does it. He was at Liverpool with Alisson Becker and at Juventus with Gianluigi Buffon.', 2, 'One middle man does it. He was at Liverpool with Alisson and at Juventus with Gianluigi Buffon.')
    ) as rows(puzzle_id, player_a, player_b, rule, old_min_steps, old_hint, min_steps, hint)
  loop
    if desired.rule = 'classic' then
      update public.transfer_path_puzzles p set min_steps = desired.min_steps, hint = desired.hint
      where p.puzzle_id = desired.puzzle_id and p.player_a = desired.player_a and p.player_b = desired.player_b
        and p.min_steps is not distinct from desired.old_min_steps and p.hint is not distinct from desired.old_hint;
    elsif desired.rule = 'europe' then
      update public.transfer_path_puzzles p set europe_min_steps = desired.min_steps, europe_hint = desired.hint
      where p.puzzle_id = desired.puzzle_id and p.player_a = desired.player_a and p.player_b = desired.player_b
        and p.europe_min_steps is not distinct from desired.old_min_steps and p.europe_hint is not distinct from desired.old_hint;
    elsif desired.rule = 'active' then
      update public.transfer_path_puzzles p set active_min_steps = desired.min_steps, active_hint = desired.hint
      where p.puzzle_id = desired.puzzle_id and p.player_a = desired.player_a and p.player_b = desired.player_b
        and p.active_min_steps is not distinct from desired.old_min_steps and p.active_hint is not distinct from desired.old_hint;
    else
      raise exception 'unknown Transfer Path rule %', desired.rule;
    end if;
    get diagnostics updated_this_row = row_count;
    if updated_this_row <> 1 then raise exception 'Transfer Path % under %: expected one row carrying %, updated %', desired.puzzle_id, desired.rule, desired.old_min_steps, updated_this_row; end if;
    updated_rows := updated_rows + 1;
  end loop;
  if updated_rows <> 53 then raise exception 'expected to rewrite 53 Transfer Path entries, rewrote %', updated_rows; end if;
  select count(*) into n from public.transfer_path_puzzles where active_min_steps is not null and active_hint is not null;
  if n <> 221 then raise exception 'expected 221 active entries after this migration, found %', n; end if;
  select count(*) into n from public.transfer_path_puzzles;
  if n <> 885 then raise exception 'expected 885 Transfer Path puzzles after this migration, found %', n; end if;
end
$migration$;
