-- Round 450 (2026-09-05): the rest of the summer 2026 window reaches the market value table.
-- The 2026 rows are an autumn 2025 snapshot and Round 393 wrote 46 verified moves into them.
-- Four player reports between 2026-08-30 and 2026-09-04 said Player Bingo still showed stale
-- clubs, so this pass adds every COMPLETED summer 2026 move for the players the games draw,
-- each one two source verified and listed in scripts/transferOverlay2026.mjs, the single list
-- driving both the Club Manager roster bake and this table. Keyed on the name alone because
-- no overlay name matches more than one 2026 row (checked before writing, fenced by
-- scripts/simTransferOverlay.mjs section 4). Loans write the club the player is playing for.

update public.player_market_values set club = 'Manchester City' where year = 2026 and player_name = 'Enzo Fernández' and club <> 'Manchester City';
update public.player_market_values set club = 'Manchester City' where year = 2026 and player_name = 'Iliman Ndiaye' and club <> 'Manchester City';
update public.player_market_values set club = 'Manchester City' where year = 2026 and player_name = 'Ayyoub Bouaddi' and club <> 'Manchester City';
update public.player_market_values set club = 'Manchester City' where year = 2026 and player_name = 'Gerónimo Rulli' and club <> 'Manchester City';
update public.player_market_values set club = 'Manchester City' where year = 2026 and player_name = 'Vitor Reis' and club <> 'Manchester City';
update public.player_market_values set club = 'Inter Milan' where year = 2026 and player_name = 'John Stones' and club <> 'Inter Milan';
update public.player_market_values set club = 'Fenerbahce' where year = 2026 and player_name = 'Nathan Aké' and club <> 'Fenerbahce';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'James Trafford' and club <> 'Leeds United';
update public.player_market_values set club = 'Tottenham Hotspur' where year = 2026 and player_name = 'Savinho' and club <> 'Tottenham Hotspur';
update public.player_market_values set club = 'Swansea City' where year = 2026 and player_name = 'Jeremy Monga' and club <> 'Swansea City';
update public.player_market_values set club = 'AS Monaco' where year = 2026 and player_name = 'Mathys Detourbet' and club <> 'AS Monaco';
update public.player_market_values set club = 'SL Benfica' where year = 2026 and player_name = 'Claudio Echeverri' and club <> 'SL Benfica';
update public.player_market_values set club = 'West Ham United' where year = 2026 and player_name = 'Divine Mukasa' and club <> 'West Ham United';
update public.player_market_values set club = 'Atlético de Madrid' where year = 2026 and player_name = 'Cristian Romero' and club <> 'Atlético de Madrid';
update public.player_market_values set club = 'Inter Milan' where year = 2026 and player_name = 'Djed Spence' and club <> 'Inter Milan';
update public.player_market_values set club = 'Juventus FC' where year = 2026 and player_name = 'Guglielmo Vicario' and club <> 'Juventus FC';
update public.player_market_values set club = 'Juventus FC' where year = 2026 and player_name = 'Pape Matar Sarr' and club <> 'Juventus FC';
update public.player_market_values set club = 'Juventus FC' where year = 2026 and player_name = 'Randal Kolo Muani' and club <> 'Juventus FC';
update public.player_market_values set club = 'Sunderland AFC' where year = 2026 and player_name = 'Kevin Danso' and club <> 'Sunderland AFC';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Radu Drăgușin' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Tottenham Hotspur' where year = 2026 and player_name = 'Andrew Robertson' and club <> 'Tottenham Hotspur';
update public.player_market_values set club = 'Tottenham Hotspur' where year = 2026 and player_name = 'Marcos Senesi' and club <> 'Tottenham Hotspur';
update public.player_market_values set club = 'Tottenham Hotspur' where year = 2026 and player_name = 'Tosin Adarabioyo' and club <> 'Tottenham Hotspur';
update public.player_market_values set club = 'Real Madrid' where year = 2026 and player_name = 'Ibrahima Konaté' and club <> 'Real Madrid';
update public.player_market_values set club = 'Inter Milan' where year = 2026 and player_name = 'Curtis Jones' and club <> 'Inter Milan';
update public.player_market_values set club = 'Trabzonspor' where year = 2026 and player_name = 'Mohamed Salah' and club <> 'Trabzonspor';
update public.player_market_values set club = 'Valencia CF' where year = 2026 and player_name = 'Harvey Elliott' and club <> 'Valencia CF';
update public.player_market_values set club = 'Liverpool FC' where year = 2026 and player_name = 'Ronald Araujo' and club <> 'Liverpool FC';
update public.player_market_values set club = 'Liverpool FC' where year = 2026 and player_name = 'Víctor Muñoz' and club <> 'Liverpool FC';
update public.player_market_values set club = 'Al-Hilal SFC' where year = 2026 and player_name = 'Gabriel Martinelli' and club <> 'Al-Hilal SFC';
update public.player_market_values set club = 'FC Barcelona' where year = 2026 and player_name = 'Gabriel Jesus' and club <> 'FC Barcelona';
update public.player_market_values set club = 'Arsenal FC' where year = 2026 and player_name = 'Ezri Konsa' and club <> 'Arsenal FC';
update public.player_market_values set club = 'Arsenal FC' where year = 2026 and player_name = 'Illan Meslier' and club <> 'Arsenal FC';
update public.player_market_values set club = 'Besiktas JK' where year = 2026 and player_name = 'Leandro Trossard' and club <> 'Besiktas JK';
update public.player_market_values set club = 'Borussia Dortmund' where year = 2026 and player_name = 'Ethan Nwaneri' and club <> 'Borussia Dortmund';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Alejandro Garnacho' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Nicolas Jackson' and club <> 'Aston Villa';
update public.player_market_values set club = 'Manchester United' where year = 2026 and player_name = 'Youri Tielemans' and club <> 'Manchester United';
update public.player_market_values set club = 'Al-Hilal SFC' where year = 2026 and player_name = 'Ollie Watkins' and club <> 'Al-Hilal SFC';
update public.player_market_values set club = 'Olympiacos Piraeus' where year = 2026 and player_name = 'Leon Bailey' and club <> 'Olympiacos Piraeus';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Evann Guessand' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Ibrahim Mbaye' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Zion Suzuki' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Matteo Ruggeri' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Taylor Harwood-Bellis' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Leon Goretzka' and club <> 'Aston Villa';
update public.player_market_values set club = 'Aston Villa' where year = 2026 and player_name = 'Aaron Wan-Bissaka' and club <> 'Aston Villa';
update public.player_market_values set club = 'Paris Saint-Germain' where year = 2026 and player_name = 'Lucas Digne' and club <> 'Paris Saint-Germain';
update public.player_market_values set club = 'Chelsea FC' where year = 2026 and player_name = 'Emiliano Martínez' and club <> 'Chelsea FC';
update public.player_market_values set club = 'Como 1907' where year = 2026 and player_name = 'Trevoh Chalobah' and club <> 'Como 1907';
update public.player_market_values set club = 'Nottingham Forest' where year = 2026 and player_name = 'Liam Delap' and club <> 'Nottingham Forest';
update public.player_market_values set club = 'SSC Napoli' where year = 2026 and player_name = 'Benoît Badiashile' and club <> 'SSC Napoli';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Axel Disasi' and club <> 'Crystal Palace';
update public.player_market_values set club = 'RB Leipzig' where year = 2026 and player_name = 'Marc Guiu' and club <> 'RB Leipzig';
update public.player_market_values set club = 'Como 1907' where year = 2026 and player_name = 'Robert Sánchez' and club <> 'Como 1907';
update public.player_market_values set club = 'Chelsea FC' where year = 2026 and player_name = 'Valentín Barco' and club <> 'Chelsea FC';
update public.player_market_values set club = 'Chelsea FC' where year = 2026 and player_name = 'Pep Chavarría' and club <> 'Chelsea FC';
update public.player_market_values set club = 'Chelsea FC' where year = 2026 and player_name = 'Emmanuel Emegha' and club <> 'Chelsea FC';
update public.player_market_values set club = 'Chelsea FC' where year = 2026 and player_name = 'Danny Welbeck' and club <> 'Chelsea FC';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Honest Ahanor' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Everton FC' where year = 2026 and player_name = 'Brennan Johnson' and club <> 'Everton FC';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Dwight McNeil' and club <> 'Crystal Palace';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Beto' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Torino FC' where year = 2026 and player_name = 'Nathan Patterson' and club <> 'Torino FC';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Tim Iroegbunam' and club <> 'Hull City';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Quinten Timber' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Takehiro Tomiyasu' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Óscar Mingueza' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Ben Chilwell' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Anan Khalaili' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Zavier Gozo' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Crystal Palace' where year = 2026 and player_name = 'Darío Osorio' and club <> 'Crystal Palace';
update public.player_market_values set club = 'Nottingham Forest' where year = 2026 and player_name = 'Daniel Muñoz' and club <> 'Nottingham Forest';
update public.player_market_values set club = 'Nottingham Forest' where year = 2026 and player_name = 'Ousmane Diomande' and club <> 'Nottingham Forest';
update public.player_market_values set club = 'Nottingham Forest' where year = 2026 and player_name = 'Xaver Schlager' and club <> 'Nottingham Forest';
update public.player_market_values set club = 'AC Milan' where year = 2026 and player_name = 'Omari Hutchinson' and club <> 'AC Milan';
update public.player_market_values set club = 'LOSC Lille' where year = 2026 and player_name = 'Dilane Bakwa' and club <> 'LOSC Lille';
update public.player_market_values set club = 'Coventry City' where year = 2026 and player_name = 'Taiwo Awoniyi' and club <> 'Coventry City';
update public.player_market_values set club = 'West Ham United' where year = 2026 and player_name = 'Morato' and club <> 'West Ham United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Bazoumana Touré' and club <> 'Newcastle United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Matias Fernandez-Pardo' and club <> 'Newcastle United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Sean Steur' and club <> 'Newcastle United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Lukas Hornicek' and club <> 'Newcastle United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Amar Dedić' and club <> 'Newcastle United';
update public.player_market_values set club = 'Newcastle United' where year = 2026 and player_name = 'Ewen Jaouen' and club <> 'Newcastle United';
update public.player_market_values set club = 'Wolverhampton Wanderers' where year = 2026 and player_name = 'Kieran Trippier' and club <> 'Wolverhampton Wanderers';
update public.player_market_values set club = 'Fulham FC' where year = 2026 and player_name = 'Hugo Larsson' and club <> 'Fulham FC';
update public.player_market_values set club = 'Fulham FC' where year = 2026 and player_name = 'Gonzalo García' and club <> 'Fulham FC';
update public.player_market_values set club = 'Fulham FC' where year = 2026 and player_name = 'César Palacios' and club <> 'Fulham FC';
update public.player_market_values set club = 'Fulham FC' where year = 2026 and player_name = 'David Affengruber' and club <> 'Fulham FC';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Harry Wilson' and club <> 'Leeds United';
update public.player_market_values set club = 'Wolverhampton Wanderers' where year = 2026 and player_name = 'Raúl Jiménez' and club <> 'Wolverhampton Wanderers';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Saša Lukić' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Issa Diop' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Exequiel Palacios' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Abdul Fatawu' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Emersonn' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Daizen Maeda' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Kjell Scherpen' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Ipswich Town' where year = 2026 and player_name = 'Zian Flemming' and club <> 'Ipswich Town';
update public.player_market_values set club = 'Sunderland AFC' where year = 2026 and player_name = 'Malick Fofana' and club <> 'Sunderland AFC';
update public.player_market_values set club = 'Sunderland AFC' where year = 2026 and player_name = 'Thomas Meunier' and club <> 'Sunderland AFC';
update public.player_market_values set club = 'Sunderland AFC' where year = 2026 and player_name = 'Dayann Methalie' and club <> 'Sunderland AFC';
update public.player_market_values set club = 'Ajax Amsterdam' where year = 2026 and player_name = 'Simon Adingra' and club <> 'Ajax Amsterdam';
update public.player_market_values set club = 'Stade Rennais FC' where year = 2026 and player_name = 'Eliezer Mayenda' and club <> 'Stade Rennais FC';
update public.player_market_values set club = 'Rangers FC' where year = 2026 and player_name = 'Dan Neil' and club <> 'Rangers FC';
update public.player_market_values set club = 'Brentford FC' where year = 2026 and player_name = 'Mamadou Sangaré' and club <> 'Brentford FC';
update public.player_market_values set club = 'Brentford FC' where year = 2026 and player_name = 'El Hadji Malick Diouf' and club <> 'Brentford FC';
update public.player_market_values set club = 'Brentford FC' where year = 2026 and player_name = 'Jaidon Anthony' and club <> 'Brentford FC';
update public.player_market_values set club = 'Brentford FC' where year = 2026 and player_name = 'Callum Wilson' and club <> 'Brentford FC';
update public.player_market_values set club = 'Brighton & Hove Albion' where year = 2026 and player_name = 'Pascal Struijk' and club <> 'Brighton & Hove Albion';
update public.player_market_values set club = 'Brighton & Hove Albion' where year = 2026 and player_name = 'Costinha' and club <> 'Brighton & Hove Albion';
update public.player_market_values set club = 'Brighton & Hove Albion' where year = 2026 and player_name = 'Jaouen Hadjam' and club <> 'Brighton & Hove Albion';
update public.player_market_values set club = 'Brighton & Hove Albion' where year = 2026 and player_name = 'Femi Azeez' and club <> 'Brighton & Hove Albion';
update public.player_market_values set club = 'Brighton & Hove Albion' where year = 2026 and player_name = 'Evan Ferguson' and club <> 'Brighton & Hove Albion';
update public.player_market_values set club = 'RB Leipzig' where year = 2026 and player_name = 'Brajan Gruda' and club <> 'RB Leipzig';
update public.player_market_values set club = 'Burnley FC' where year = 2026 and player_name = 'Igor Julio' and club <> 'Burnley FC';
update public.player_market_values set club = 'AFC Bournemouth' where year = 2026 and player_name = 'António Silva' and club <> 'AFC Bournemouth';
update public.player_market_values set club = 'AFC Bournemouth' where year = 2026 and player_name = 'Juanlu Sánchez' and club <> 'AFC Bournemouth';
update public.player_market_values set club = 'AFC Bournemouth' where year = 2026 and player_name = 'Álvaro Rodríguez' and club <> 'AFC Bournemouth';
update public.player_market_values set club = 'AFC Bournemouth' where year = 2026 and player_name = 'Michele Di Gregorio' and club <> 'AFC Bournemouth';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Álex Jiménez' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Getafe CF' where year = 2026 and player_name = 'Enes Ünal' and club <> 'Getafe CF';
update public.player_market_values set club = 'West Ham United' where year = 2026 and player_name = 'Joël Piroe' and club <> 'West Ham United';
update public.player_market_values set club = 'West Ham United' where year = 2026 and player_name = 'Manor Solomon' and club <> 'West Ham United';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Michael Zetterer' and club <> 'Leeds United';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Nico Elvedi' and club <> 'Leeds United';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Tarik Muharemović' and club <> 'Leeds United';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Jean-Mattéo Bahoya' and club <> 'Leeds United';
update public.player_market_values set club = 'Leeds United' where year = 2026 and player_name = 'Melvin Bard' and club <> 'Leeds United';
update public.player_market_values set club = 'Hamburger SV' where year = 2026 and player_name = 'Sebastiaan Bornauw' and club <> 'Hamburger SV';
update public.player_market_values set club = 'Torino FC' where year = 2026 and player_name = 'Lucas Perri' and club <> 'Torino FC';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Wilfried Gnonto' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Elche CF' where year = 2026 and player_name = 'Facundo Buonanotte' and club <> 'Elche CF';
update public.player_market_values set club = 'Burnley FC' where year = 2026 and player_name = 'Largie Ramazani' and club <> 'Burnley FC';
update public.player_market_values set club = 'New England Revolution' where year = 2026 and player_name = 'Jack Harrison' and club <> 'New England Revolution';
update public.player_market_values set club = 'Manchester United' where year = 2026 and player_name = 'Marcus Rashford' and club <> 'Manchester United';
update public.player_market_values set club = 'Celta de Vigo' where year = 2026 and player_name = 'Altay Bayındır' and club <> 'Celta de Vigo';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Mohamed-Ali Cho' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Ilyas Ansah' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Konstantinos Tzolakis' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Nobel Mendy' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Hidemasa Morita' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Jack Butland' and club <> 'Hull City';
update public.player_market_values set club = 'Hull City' where year = 2026 and player_name = 'Matt Targett' and club <> 'Hull City';
update public.player_market_values set club = 'Rangers FC' where year = 2026 and player_name = 'Ivor Pandur' and club <> 'Rangers FC';
update public.player_market_values set club = 'Middlesbrough FC' where year = 2026 and player_name = 'Radek Vítek' and club <> 'Middlesbrough FC';
update public.player_market_values set club = 'Middlesbrough FC' where year = 2026 and player_name = 'Will Lankshear' and club <> 'Middlesbrough FC';
update public.player_market_values set club = 'Middlesbrough FC' where year = 2026 and player_name = 'Ashley Phillips' and club <> 'Middlesbrough FC';
update public.player_market_values set club = 'Coventry City' where year = 2026 and player_name = 'Caleb Yirenkyi' and club <> 'Coventry City';
update public.player_market_values set club = 'Coventry City' where year = 2026 and player_name = 'Aurèle Amenda' and club <> 'Coventry City';
update public.player_market_values set club = 'Coventry City' where year = 2026 and player_name = 'Gustavo Hamer' and club <> 'Coventry City';
update public.player_market_values set club = 'Sint-Truidense VV' where year = 2026 and player_name = 'Kota Takai' and club <> 'Sint-Truidense VV';
update public.player_market_values set club = 'KVC Westerlo' where year = 2026 and player_name = 'Min-hyeok Yang' and club <> 'KVC Westerlo';
update public.player_market_values set club = '1.FC Köln' where year = 2026 and player_name = 'Mikey Moore' and club <> '1.FC Köln';
update public.player_market_values set club = 'Esporte Clube Bahia' where year = 2026 and player_name = 'Alejo Veliz' and club <> 'Esporte Clube Bahia';
update public.player_market_values set club = 'Olympiacos Piraeus' where year = 2026 and player_name = 'David Carmo' and club <> 'Olympiacos Piraeus';
update public.player_market_values set club = 'Olympiacos Piraeus' where year = 2026 and player_name = 'Jota Silva' and club <> 'Olympiacos Piraeus';
update public.player_market_values set club = 'Atlético de Madrid' where year = 2026 and player_name = 'Kang-in Lee' and club <> 'Atlético de Madrid';
update public.player_market_values set club = 'Atlético de Madrid' where year = 2026 and player_name = 'Alejandro Grimaldo' and club <> 'Atlético de Madrid';
update public.player_market_values set club = 'Atlético de Madrid' where year = 2026 and player_name = 'Jonathan David' and club <> 'Atlético de Madrid';
update public.player_market_values set club = 'AS Roma' where year = 2026 and player_name = 'Nahuel Molina' and club <> 'AS Roma';
update public.player_market_values set club = 'Real Madrid' where year = 2026 and player_name = 'Endrick' and club <> 'Real Madrid';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Franco Mastantuono' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Paris Saint-Germain' where year = 2026 and player_name = 'Ferran Torres' and club <> 'Paris Saint-Germain';
update public.player_market_values set club = 'AC Milan' where year = 2026 and player_name = 'Mario Gila' and club <> 'AC Milan';
update public.player_market_values set club = 'AC Milan' where year = 2026 and player_name = 'Diego Moreira' and club <> 'AC Milan';
update public.player_market_values set club = 'RB Leipzig' where year = 2026 and player_name = 'Christopher Nkunku' and club <> 'RB Leipzig';
update public.player_market_values set club = 'FC Porto' where year = 2026 and player_name = 'Santiago Gimenez' and club <> 'FC Porto';
update public.player_market_values set club = 'Besiktas JK' where year = 2026 and player_name = 'Dušan Vlahović' and club <> 'Besiktas JK';
update public.player_market_values set club = 'Olympique Lyon' where year = 2026 and player_name = 'Loïs Openda' and club <> 'Olympique Lyon';
update public.player_market_values set club = 'Juventus FC' where year = 2026 and player_name = 'Douglas Luiz' and club <> 'Juventus FC';
update public.player_market_values set club = 'Juventus FC' where year = 2026 and player_name = 'Nico González' and club <> 'Juventus FC';
update public.player_market_values set club = 'SS Lazio' where year = 2026 and player_name = 'Davide Frattesi' and club <> 'SS Lazio';
update public.player_market_values set club = 'Inter Milan' where year = 2026 and player_name = 'Benjamin Pavard' and club <> 'Inter Milan';
update public.player_market_values set club = 'AS Roma' where year = 2026 and player_name = 'Santiago Castro' and club <> 'AS Roma';
update public.player_market_values set club = 'Bologna FC 1909' where year = 2026 and player_name = 'Artem Dovbyk' and club <> 'Bologna FC 1909';
update public.player_market_values set club = 'RB Leipzig' where year = 2026 and player_name = 'Neil El Aynaoui' and club <> 'RB Leipzig';
update public.player_market_values set club = 'AS Roma' where year = 2026 and player_name = 'Rodrigo Mora' and club <> 'AS Roma';
update public.player_market_values set club = 'Fenerbahce' where year = 2026 and player_name = 'Romelu Lukaku' and club <> 'Fenerbahce';
update public.player_market_values set club = 'Como 1907' where year = 2026 and player_name = 'Moise Kean' and club <> 'Como 1907';
update public.player_market_values set club = 'ACF Fiorentina' where year = 2026 and player_name = 'Pedro Gonçalves' and club <> 'ACF Fiorentina';
update public.player_market_values set club = 'Borussia Dortmund' where year = 2026 and player_name = 'Konstantinos Karetsas' and club <> 'Borussia Dortmund';
update public.player_market_values set club = 'Borussia Dortmund' where year = 2026 and player_name = 'Giannis Konstantelias' and club <> 'Borussia Dortmund';
update public.player_market_values set club = 'Borussia Dortmund' where year = 2026 and player_name = 'Joey Veerman' and club <> 'Borussia Dortmund';
update public.player_market_values set club = 'Olympique Lyon' where year = 2026 and player_name = 'Julien Duranville' and club <> 'Olympique Lyon';
update public.player_market_values set club = 'Bayer 04 Leverkusen' where year = 2026 and player_name = 'Moussa Diaby' and club <> 'Bayer 04 Leverkusen';
update public.player_market_values set club = 'Bayer 04 Leverkusen' where year = 2026 and player_name = 'Guéla Doué' and club <> 'Bayer 04 Leverkusen';
update public.player_market_values set club = 'Bayer 04 Leverkusen' where year = 2026 and player_name = 'Facundo Medina' and club <> 'Bayer 04 Leverkusen';
update public.player_market_values set club = 'Bayer 04 Leverkusen' where year = 2026 and player_name = 'Victor Boniface' and club <> 'Bayer 04 Leverkusen';
update public.player_market_values set club = 'PSV Eindhoven' where year = 2026 and player_name = 'Lutsharel Geertruida' and club <> 'PSV Eindhoven';
update public.player_market_values set club = 'RC Strasbourg Alsace' where year = 2026 and player_name = 'Giovanni Reyna' and club <> 'RC Strasbourg Alsace';
update public.player_market_values set club = 'Fenerbahce' where year = 2026 and player_name = 'Mason Greenwood' and club <> 'Fenerbahce';
update public.player_market_values set club = 'Paris Saint-Germain' where year = 2026 and player_name = 'Maghnes Akliouche' and club <> 'Paris Saint-Germain';
update public.player_market_values set club = 'Paris Saint-Germain' where year = 2026 and player_name = 'Mika Godts' and club <> 'Paris Saint-Germain';
