-- Restore Transfer Path Active Players Only after the verified-identity frontend is live.
-- Generated by scripts/genTransferPathHints.mjs from the same 78 normalized name plus
-- nationality identities used by src/lib/transferPathModes.ts. Apply only after the
-- quarantine companion has cleared active hints on all 885 retained puzzles.

begin;

do $migration$
declare
  desired record;
  matching_rows integer;
  updated_this_row integer;
  updated_rows integer := 0;
begin
  select count(*) into matching_rows from public.transfer_path_puzzles;
  if matching_rows <> 885 then raise exception 'Expected 885 retained Transfer Path rows before active restore, found %', matching_rows; end if;

  for desired in
    select *
    from (values
      ('tpa-26', 'Achraf Hakimi', 'Kevin De Bruyne', 2, 'One middle man does it. He was at Borussia Dortmund with Achraf Hakimi and at Manchester City with Kevin De Bruyne.'),
      ('tpa-27', 'Declan Rice', 'N''Golo Kanté', 3, 'Two middle men at least. The first was at Arsenal with Declan Rice; the last was at Chelsea with N''Golo Kanté.'),
      ('tpa-28', 'David Alaba', 'Son Heung-min', 3, 'Two middle men at least. The first was at Bayern Munich with David Alaba; the last was at Tottenham with Son Heung-min.'),
      ('tpa-34', 'Casemiro', 'Virgil van Dijk', 3, 'Two middle men at least. The first was at Real Madrid with Casemiro; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-36', 'Alexander Isak', 'Edinson Cavani', 3, 'Two middle men at least. The first was at Real Sociedad with Alexander Isak; the last was at Manchester United with Edinson Cavani.'),
      ('tpa-40', 'Pau Cubarsí', 'Vinícius Júnior', 3, 'Two middle men at least. The first was at Barcelona with Pau Cubarsí; the last was at Real Madrid with Vinícius Júnior.'),
      ('tpa-55', 'Lionel Messi', 'Marcus Rashford', 3, 'Two middle men at least. The first was at PSG with Lionel Messi; the last was at Manchester United with Marcus Rashford.'),
      ('tpa-59', 'Enzo Fernández', 'Mikel Oyarzabal', 3, 'Two middle men at least. The first was at Chelsea with Enzo Fernández; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-64', 'Memphis Depay', 'Thibaut Courtois', 3, 'Two middle men at least. The first was at Manchester United with Memphis Depay; the last was at Real Madrid with Thibaut Courtois.'),
      ('tpa-65', 'Bruno Fernandes', 'Endrick', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Real Madrid with Endrick.'),
      ('tpa-68', 'Cristiano Ronaldo', 'Rúben Dias', 2, 'One middle man does it. He was at Juventus with Cristiano Ronaldo and at Manchester City with Rúben Dias.'),
      ('tpa-72', 'Arda Güler', 'Lionel Messi', 2, 'One middle man does it. He was at Real Madrid with Arda Güler and at PSG with Lionel Messi.'),
      ('tpa-75', 'Bruno Fernandes', 'Mohamed Salah', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Liverpool with Mohamed Salah.'),
      ('tpa-78', 'Erling Haaland', 'Thiago Silva', 3, 'Two middle men at least. The first was at Borussia Dortmund with Erling Haaland; the last was at PSG with Thiago Silva.'),
      ('tpa-79', 'Bukayo Saka', 'Yassine Bounou', 3, 'Two middle men at least. The first was at Arsenal with Bukayo Saka; the last was at Al-Hilal with Yassine Bounou.'),
      ('tpa-84', 'Manuel Neuer', 'Rodri', 2, 'One middle man does it. He was at Bayern Munich with Manuel Neuer and at Manchester City with Rodri.'),
      ('tpa-89', 'Marc-André ter Stegen', 'Son Heung-min', 4, 'Three middle men at least. The first was at Barcelona with Marc-André ter Stegen; the last was at Tottenham with Son Heung-min.'),
      ('tpa-91', 'Leroy Sané', 'Martin Ødegaard', 3, 'Two middle men at least. The first was at Bayern Munich with Leroy Sané; the last was at Real Madrid with Martin Ødegaard.'),
      ('tpa-100', 'Arda Güler', 'Marquinhos', 2, 'One middle man does it. He was at Real Madrid with Arda Güler and at PSG with Marquinhos.'),
      ('tpa-101', 'Hugo Lloris', 'Thiago Silva', 4, 'Three middle men at least. The first was at Tottenham with Hugo Lloris; the last was at PSG with Thiago Silva.'),
      ('tpa-104', 'Bernardo Silva', 'Kalidou Koulibaly', 3, 'Two middle men at least. The first was at Manchester City with Bernardo Silva; the last was at Chelsea with Kalidou Koulibaly.'),
      ('tpa-109', 'Kobbie Mainoo', 'Martin Ødegaard', 3, 'Two middle men at least. The first was at Manchester United with Kobbie Mainoo; the last was at Real Madrid with Martin Ødegaard.'),
      ('tpa-117', 'Kevin De Bruyne', 'Pedri', 2, 'One middle man does it. He was at Manchester City with Kevin De Bruyne and at Barcelona with Pedri.'),
      ('tpa-119', 'Bradley Barcola', 'Luka Modrić', 2, 'One middle man does it. He was at PSG with Bradley Barcola and at Real Madrid with Luka Modrić.'),
      ('tpa-120', 'Florian Wirtz', 'Rafael Leão', 7, '6 middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at AC Milan with Rafael Leão.'),
      ('tpa-123', 'Memphis Depay', 'Neymar', 2, 'One middle man does it. He was at Barcelona with Memphis Depay and, in another season, at Barcelona with Neymar.'),
      ('tpa-127', 'Neymar', 'Vinícius Júnior', 2, 'One middle man does it. He was at PSG with Neymar and at Real Madrid with Vinícius Júnior.'),
      ('tpa-132', 'Bukayo Saka', 'Romelu Lukaku', 3, 'Two middle men at least. The first was at Arsenal with Bukayo Saka; the last was at Chelsea with Romelu Lukaku.'),
      ('tpa-137', 'Pau Cubarsí', 'Virgil van Dijk', 3, 'Two middle men at least. The first was at Barcelona with Pau Cubarsí; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-140', 'Edinson Cavani', 'Mikel Oyarzabal', 3, 'Two middle men at least. The first was at Manchester United with Edinson Cavani; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-147', 'David Alaba', 'Hugo Lloris', 3, 'Two middle men at least. The first was at Bayern Munich with David Alaba; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-148', 'Andrew Robertson', 'Lionel Messi', 4, 'Three middle men at least. The first was at Liverpool with Andrew Robertson; the last was at PSG with Lionel Messi.'),
      ('tpa-153', 'Marcus Rashford', 'Thiago Silva', 2, 'One middle man does it. He was at Manchester United with Marcus Rashford and at PSG with Thiago Silva.'),
      ('tpa-157', 'Edinson Cavani', 'Erling Haaland', 3, 'Two middle men at least. The first was at Manchester United with Edinson Cavani; the last was at Borussia Dortmund with Erling Haaland.'),
      ('tpa-160', 'Achraf Hakimi', 'Alejandro Garnacho', 2, 'One middle man does it. He was at Real Madrid with Achraf Hakimi and at Manchester United with Alejandro Garnacho.'),
      ('tpa-164', 'Achraf Hakimi', 'Alisson', 3, 'Two middle men at least. The first was at Real Madrid with Achraf Hakimi; the last was at Liverpool with Alisson.'),
      ('tpa-166', 'Bradley Barcola', 'Bruno Fernandes', 3, 'Two middle men at least. The first was at PSG with Bradley Barcola; the last was at Manchester United with Bruno Fernandes.'),
      ('tpa-167', 'Erling Haaland', 'Leroy Sané', 2, 'One middle man does it. He was at Manchester City with Erling Haaland and, in another season, at Manchester City with Leroy Sané.'),
      ('tpa-174', 'Rodri', 'Romelu Lukaku', 3, 'Two middle men at least. The first was at Atlético Madrid with Rodri; the last was at Inter Milan with Romelu Lukaku.'),
      ('tpa-175', 'David Alaba', 'Neymar', 3, 'Two middle men at least. The first was at Real Madrid with David Alaba; the last was at PSG with Neymar.'),
      ('tpa-181', 'Endrick', 'Marquinhos', 2, 'One middle man does it. He was at Real Madrid with Endrick and at PSG with Marquinhos.'),
      ('tpa-185', 'Alejandro Garnacho', 'Kevin De Bruyne', 4, 'Three middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Manchester City with Kevin De Bruyne.'),
      ('tpa-188', 'Bradley Barcola', 'Leroy Sané', 3, 'Two middle men at least. The first was at PSG with Bradley Barcola; the last was at Manchester City with Leroy Sané.'),
      ('tpa-194', 'Federico Valverde', 'Leroy Sané', 2, 'One middle man does it. He was at Real Madrid with Federico Valverde and at Bayern Munich with Leroy Sané.'),
      ('tpa-199', 'Antoine Griezmann', 'Moisés Caicedo', 2, 'One middle man does it. He was at Atlético Madrid with Antoine Griezmann and at Chelsea with Moisés Caicedo.'),
      ('tpa-200', 'Bruno Fernandes', 'Kalidou Koulibaly', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Al-Hilal with Kalidou Koulibaly.'),
      ('tpa-205', 'Erling Haaland', 'João Félix', 2, 'One middle man does it. He was at Manchester City with Erling Haaland and at Benfica with João Félix.'),
      ('tpa-207', 'Alisson', 'Sandro Tonali', 5, 'Four middle men at least. The first was at Liverpool with Alisson; the last was at Newcastle with Sandro Tonali.'),
      ('tpa-212', 'Joshua Kimmich', 'Kalidou Koulibaly', 3, 'Two middle men at least. The first was at Bayern Munich with Joshua Kimmich; the last was at Chelsea with Kalidou Koulibaly.'),
      ('tpa-215', 'Arturo Vidal', 'Federico Valverde', 2, 'One middle man does it. He was at Bayern Munich with Arturo Vidal and at Real Madrid with Federico Valverde.'),
      ('tpa-218', 'Lamine Yamal', 'Sadio Mané', 2, 'One middle man does it. He was at Barcelona with Lamine Yamal and at Bayern Munich with Sadio Mané.'),
      ('tpa-226', 'Declan Rice', 'Harry Kane', 3, 'Two middle men at least. The first was at Arsenal with Declan Rice; the last was at Tottenham with Harry Kane.'),
      ('tpa-228', 'Bernardo Silva', 'Robert Lewandowski', 2, 'One middle man does it. He was at Manchester City with Bernardo Silva and at Barcelona with Robert Lewandowski.'),
      ('tpa-232', 'Pedri', 'Romelu Lukaku', 3, 'Two middle men at least. The first was at Barcelona with Pedri; the last was at Inter Milan with Romelu Lukaku.'),
      ('tpa-233', 'Neymar', 'Ousmane Dembélé', 2, 'One middle man does it. He was at PSG with Neymar and, in another season, at PSG with Ousmane Dembélé.'),
      ('tpa-239', 'Alejandro Garnacho', 'Endrick', 3, 'Two middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Real Madrid with Endrick.'),
      ('tpa-248', 'Kevin De Bruyne', 'Vinícius Júnior', 3, 'Two middle men at least. The first was at Manchester City with Kevin De Bruyne; the last was at Real Madrid with Vinícius Júnior.'),
      ('tpa-249', 'Harry Kane', 'Thiago Silva', 3, 'Two middle men at least. The first was at Tottenham with Harry Kane; the last was at PSG with Thiago Silva.'),
      ('tpa-273', 'Alexander Isak', 'Rafael Leão', 2, 'One middle man does it. He was at Newcastle with Alexander Isak and at AC Milan with Rafael Leão.'),
      ('tpa-275', 'Darwin Núñez', 'Mikel Oyarzabal', 5, 'Four middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-276', 'Bukayo Saka', 'Hugo Lloris', 4, 'Three middle men at least. The first was at Arsenal with Bukayo Saka; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-284', 'Moisés Caicedo', 'Robert Lewandowski', 2, 'One middle man does it. He was at Chelsea with Moisés Caicedo and at Barcelona with Robert Lewandowski.'),
      ('tpa-285', 'Alisson', 'Thibaut Courtois', 4, 'Three middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Thibaut Courtois.'),
      ('tpa-286', 'Darwin Núñez', 'Moussa Diaby', 5, 'Four middle men at least. The first was at Liverpool with Darwin Núñez; the last was at PSG with Moussa Diaby.'),
      ('tpa-289', 'Declan Rice', 'Mikel Oyarzabal', 2, 'One middle man does it. He was at Arsenal with Declan Rice and at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-291', 'Jamal Musiala', 'Thiago Silva', 3, 'Two middle men at least. The first was at Bayern Munich with Jamal Musiala; the last was at Chelsea with Thiago Silva.'),
      ('tpa-293', 'Antoine Griezmann', 'Kalidou Koulibaly', 2, 'One middle man does it. He was at Atlético Madrid with Antoine Griezmann and at Chelsea with Kalidou Koulibaly.'),
      ('tpa-296', 'Alejandro Garnacho', 'Alisson', 4, 'Three middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Liverpool with Alisson.'),
      ('tpa-299', 'Casemiro', 'Thiago Silva', 3, 'Two middle men at least. The first was at Real Madrid with Casemiro; the last was at PSG with Thiago Silva.'),
      ('tpa-304', 'Bukayo Saka', 'Marcus Rashford', 3, 'Two middle men at least. The first was at Arsenal with Bukayo Saka; the last was at Manchester United with Marcus Rashford.'),
      ('tpa-309', 'Riyad Mahrez', 'Robert Lewandowski', 2, 'One middle man does it. He was at Manchester City with Riyad Mahrez and at Barcelona with Robert Lewandowski.'),
      ('tpa-311', 'Martin Ødegaard', 'Warren Zaïre-Emery', 2, 'One middle man does it. He was at Real Madrid with Martin Ødegaard and at PSG with Warren Zaïre-Emery.'),
      ('tpa-314', 'Marquinhos', 'Sadio Mané', 3, 'Two middle men at least. The first was at PSG with Marquinhos; the last was at Al-Nassr with Sadio Mané.'),
      ('tpa-332', 'Arda Güler', 'Florian Wirtz', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Bayer Leverkusen with Florian Wirtz.'),
      ('tpa-334', 'Alexander Isak', 'Harry Kane', 3, 'Two middle men at least. The first was at Real Sociedad with Alexander Isak; the last was at Tottenham with Harry Kane.'),
      ('tpa-337', 'Antoine Griezmann', 'Mikel Oyarzabal', 4, 'Three middle men at least. The first was at Barcelona with Antoine Griezmann; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-346', 'Bernardo Silva', 'Warren Zaïre-Emery', 2, 'One middle man does it. He was at Monaco with Bernardo Silva and at PSG with Warren Zaïre-Emery.'),
      ('tpa-355', 'Memphis Depay', 'Sergio Ramos', 3, 'Two middle men at least. The first was at Atlético Madrid with Memphis Depay; the last was at PSG with Sergio Ramos.'),
      ('tpa-360', 'Enzo Fernández', 'Son Heung-min', 5, 'Four middle men at least. The first was at Chelsea with Enzo Fernández; the last was at Tottenham with Son Heung-min.'),
      ('tpa-365', 'Arturo Vidal', 'Jude Bellingham', 2, 'One middle man does it. He was at Bayern Munich with Arturo Vidal and at Real Madrid with Jude Bellingham.'),
      ('tpa-380', 'Ousmane Dembélé', 'Thibaut Courtois', 2, 'One middle man does it. He was at PSG with Ousmane Dembélé and at Real Madrid with Thibaut Courtois.'),
      ('tpa-385', 'Alphonso Davies', 'Marquinhos', 3, 'Two middle men at least. The first was at Bayern Munich with Alphonso Davies; the last was at PSG with Marquinhos.'),
      ('tpa-389', 'Jude Bellingham', 'Pedri', 3, 'Two middle men at least. The first was at Real Madrid with Jude Bellingham; the last was at Barcelona with Pedri.'),
      ('tpa-393', 'Achraf Hakimi', 'Florian Wirtz', 3, 'Two middle men at least. The first was at PSG with Achraf Hakimi; the last was at Bayer Leverkusen with Florian Wirtz.'),
      ('tpa-401', 'Achraf Hakimi', 'Rodri', 2, 'One middle man does it. He was at Borussia Dortmund with Achraf Hakimi and at Manchester City with Rodri.'),
      ('tpa-403', 'Erling Haaland', 'Romelu Lukaku', 2, 'One middle man does it. He was at Borussia Dortmund with Erling Haaland and at Inter Milan with Romelu Lukaku.'),
      ('tpa-404', 'James Rodríguez', 'Thiago Silva', 3, 'Two middle men at least. The first was at Bayern Munich with James Rodríguez; the last was at Chelsea with Thiago Silva.'),
      ('tpa-421', 'Alphonso Davies', 'Bradley Barcola', 3, 'Two middle men at least. The first was at Bayern Munich with Alphonso Davies; the last was at PSG with Bradley Barcola.'),
      ('tpa-433', 'Arda Güler', 'Hugo Lloris', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-439', 'Alejandro Garnacho', 'Marc-André ter Stegen', 3, 'Two middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Barcelona with Marc-André ter Stegen.'),
      ('tpa-442', 'Pierre-Emerick Aubameyang', 'Warren Zaïre-Emery', 2, 'One middle man does it. He was at Borussia Dortmund with Pierre-Emerick Aubameyang and at PSG with Warren Zaïre-Emery.'),
      ('tpa-448', 'Robert Lewandowski', 'Thibaut Courtois', 2, 'One middle man does it. He was at Bayern Munich with Robert Lewandowski and at Real Madrid with Thibaut Courtois.'),
      ('tpa-450', 'Mikel Oyarzabal', 'Moussa Diaby', 4, 'Three middle men at least. The first was at Real Sociedad with Mikel Oyarzabal; the last was at PSG with Moussa Diaby.'),
      ('tpa-455', 'Alejandro Garnacho', 'Martin Ødegaard', 3, 'Two middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Real Madrid with Martin Ødegaard.'),
      ('tpa-456', 'Riyad Mahrez', 'Vinícius Júnior', 3, 'Two middle men at least. The first was at Manchester City with Riyad Mahrez; the last was at Real Madrid with Vinícius Júnior.'),
      ('tpa-458', 'Kalidou Koulibaly', 'Kevin De Bruyne', 3, 'Two middle men at least. The first was at Chelsea with Kalidou Koulibaly; the last was at Manchester City with Kevin De Bruyne.'),
      ('tpa-463', 'Enzo Fernández', 'Lamine Yamal', 2, 'One middle man does it. He was at Chelsea with Enzo Fernández and at Barcelona with Lamine Yamal.'),
      ('tpa-467', 'Bruno Fernandes', 'Virgil van Dijk', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-468', 'Pierre-Emerick Aubameyang', 'Rúben Dias', 2, 'One middle man does it. He was at Chelsea with Pierre-Emerick Aubameyang and at Benfica with Rúben Dias.'),
      ('tpa-470', 'Rafael Leão', 'Virgil van Dijk', 6, '5 middle men at least. The first was at AC Milan with Rafael Leão; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-472', 'Cristiano Ronaldo', 'Marc-André ter Stegen', 2, 'One middle man does it. He was at Juventus with Cristiano Ronaldo and at Barcelona with Marc-André ter Stegen.'),
      ('tpa-489', 'Arda Güler', 'Kobbie Mainoo', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Manchester United with Kobbie Mainoo.'),
      ('tpa-490', 'Bradley Barcola', 'Romelu Lukaku', 2, 'One middle man does it. He was at PSG with Bradley Barcola and at Inter Milan with Romelu Lukaku.'),
      ('tpa-491', 'Arturo Vidal', 'Moisés Caicedo', 3, 'Two middle men at least. The first was at Barcelona with Arturo Vidal; the last was at Chelsea with Moisés Caicedo.'),
      ('tpa-496', 'Bukayo Saka', 'Thiago Silva', 2, 'One middle man does it. He was at Arsenal with Bukayo Saka and at Chelsea with Thiago Silva.'),
      ('tpa-506', 'Mikel Oyarzabal', 'Rafael Leão', 3, 'Two middle men at least. The first was at Real Sociedad with Mikel Oyarzabal; the last was at AC Milan with Rafael Leão.'),
      ('tpa-509', 'Arda Güler', 'Yassine Bounou', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Al-Hilal with Yassine Bounou.'),
      ('tpa-517', 'Alphonso Davies', 'Enzo Fernández', 3, 'Two middle men at least. The first was at Bayern Munich with Alphonso Davies; the last was at Chelsea with Enzo Fernández.'),
      ('tpa-520', 'Kylian Mbappé', 'Mikel Oyarzabal', 3, 'Two middle men at least. The first was at Real Madrid with Kylian Mbappé; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-521', 'David Alaba', 'Mohamed Salah', 3, 'Two middle men at least. The first was at Bayern Munich with David Alaba; the last was at Liverpool with Mohamed Salah.'),
      ('tpa-527', 'Andrew Robertson', 'Neymar', 4, 'Three middle men at least. The first was at Liverpool with Andrew Robertson; the last was at PSG with Neymar.'),
      ('tpa-533', 'Achraf Hakimi', 'Rúben Dias', 2, 'One middle man does it. He was at Borussia Dortmund with Achraf Hakimi and at Manchester City with Rúben Dias.'),
      ('tpa-534', 'Joshua Kimmich', 'Luka Modrić', 2, 'One middle man does it. He was at Bayern Munich with Joshua Kimmich and at Real Madrid with Luka Modrić.'),
      ('tpa-536', 'Hugo Lloris', 'Jude Bellingham', 3, 'Two middle men at least. The first was at Tottenham with Hugo Lloris; the last was at Real Madrid with Jude Bellingham.'),
      ('tpa-537', 'João Cancelo', 'Marcus Rashford', 2, 'One middle man does it. He was at Juventus with João Cancelo and at Manchester United with Marcus Rashford.'),
      ('tpa-547', 'Alisson', 'Enzo Fernández', 4, 'Three middle men at least. The first was at Liverpool with Alisson; the last was at Chelsea with Enzo Fernández.'),
      ('tpa-548', 'Bernardo Silva', 'Harry Kane', 2, 'One middle man does it. He was at Manchester City with Bernardo Silva and at Bayern Munich with Harry Kane.'),
      ('tpa-553', 'Andrew Robertson', 'Hugo Lloris', 4, 'Three middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-560', 'Arda Güler', 'Kalidou Koulibaly', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Al-Hilal with Kalidou Koulibaly.'),
      ('tpa-568', 'Pedri', 'Vinícius Júnior', 3, 'Two middle men at least. The first was at Barcelona with Pedri; the last was at Real Madrid with Vinícius Júnior.'),
      ('tpa-570', 'Joshua Kimmich', 'Rodri', 2, 'One middle man does it. He was at Bayern Munich with Joshua Kimmich and at Manchester City with Rodri.'),
      ('tpa-571', 'Hugo Lloris', 'N''Golo Kanté', 4, 'Three middle men at least. The first was at Tottenham with Hugo Lloris; the last was at Leicester City with N''Golo Kanté.'),
      ('tpa-576', 'Jude Bellingham', 'Kobbie Mainoo', 3, 'Two middle men at least. The first was at Real Madrid with Jude Bellingham; the last was at Manchester United with Kobbie Mainoo.'),
      ('tpa-585', 'Arda Güler', 'Bukayo Saka', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Arsenal with Bukayo Saka.'),
      ('tpa-589', 'Cristiano Ronaldo', 'Enzo Fernández', 3, 'Two middle men at least. The first was at Manchester United with Cristiano Ronaldo; the last was at Chelsea with Enzo Fernández.'),
      ('tpa-590', 'Federico Valverde', 'Kobbie Mainoo', 2, 'One middle man does it. He was at Real Madrid with Federico Valverde and at Manchester United with Kobbie Mainoo.'),
      ('tpa-597', 'Sadio Mané', 'Warren Zaïre-Emery', 3, 'Two middle men at least. The first was at Al-Nassr with Sadio Mané; the last was at PSG with Warren Zaïre-Emery.'),
      ('tpa-600', 'Arda Güler', 'Pau Cubarsí', 3, 'Two middle men at least. The first was at Real Madrid with Arda Güler; the last was at Barcelona with Pau Cubarsí.'),
      ('tpa-606', 'Antoine Griezmann', 'Jude Bellingham', 3, 'Two middle men at least. The first was at Barcelona with Antoine Griezmann; the last was at Real Madrid with Jude Bellingham.'),
      ('tpa-610', 'Bernardo Silva', 'Endrick', 2, 'One middle man does it. He was at Monaco with Bernardo Silva and at Real Madrid with Endrick.'),
      ('tpa-612', 'Bruno Fernandes', 'Lamine Yamal', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Barcelona with Lamine Yamal.'),
      ('tpa-618', 'Edinson Cavani', 'Virgil van Dijk', 3, 'Two middle men at least. The first was at Manchester United with Edinson Cavani; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-619', 'Alisson', 'Federico Valverde', 4, 'Three middle men at least. The first was at Liverpool with Alisson; the last was at Real Madrid with Federico Valverde.'),
      ('tpa-621', 'Bradley Barcola', 'Pierre-Emerick Aubameyang', 2, 'One middle man does it. He was at PSG with Bradley Barcola and at Borussia Dortmund with Pierre-Emerick Aubameyang.'),
      ('tpa-622', 'Harry Kane', 'Thibaut Courtois', 2, 'One middle man does it. He was at Tottenham with Harry Kane and at Real Madrid with Thibaut Courtois.'),
      ('tpa-626', 'Bradley Barcola', 'Hugo Lloris', 4, 'Three middle men at least. The first was at PSG with Bradley Barcola; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-627', 'Moisés Caicedo', 'Sadio Mané', 3, 'Two middle men at least. The first was at Chelsea with Moisés Caicedo; the last was at Bayern Munich with Sadio Mané.'),
      ('tpa-630', 'Antoine Griezmann', 'Luka Modrić', 3, 'Two middle men at least. The first was at Barcelona with Antoine Griezmann; the last was at Real Madrid with Luka Modrić.'),
      ('tpa-634', 'Enzo Fernández', 'Pedri', 2, 'One middle man does it. He was at Chelsea with Enzo Fernández and at Barcelona with Pedri.'),
      ('tpa-643', 'João Cancelo', 'Moisés Caicedo', 2, 'One middle man does it. He was at Barcelona with João Cancelo and at Chelsea with Moisés Caicedo.'),
      ('tpa-644', 'Harry Kane', 'Mohamed Salah', 3, 'Two middle men at least. The first was at Bayern Munich with Harry Kane; the last was at Liverpool with Mohamed Salah.'),
      ('tpa-649', 'Jamal Musiala', 'Rodri', 2, 'One middle man does it. He was at Bayern Munich with Jamal Musiala and at Manchester City with Rodri.'),
      ('tpa-651', 'Luka Modrić', 'N''Golo Kanté', 2, 'One middle man does it. He was at Real Madrid with Luka Modrić and at Chelsea with N''Golo Kanté.'),
      ('tpa-654', 'Sandro Tonali', 'Yassine Bounou', 5, 'Four middle men at least. The first was at Newcastle with Sandro Tonali; the last was at Al-Hilal with Yassine Bounou.'),
      ('tpa-656', 'Hugo Lloris', 'Marquinhos', 4, 'Three middle men at least. The first was at Tottenham with Hugo Lloris; the last was at PSG with Marquinhos.'),
      ('tpa-657', 'Florian Wirtz', 'Kobbie Mainoo', 4, 'Three middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Manchester United with Kobbie Mainoo.'),
      ('tpa-662', 'Lionel Messi', 'Mohamed Salah', 4, 'Three middle men at least. The first was at PSG with Lionel Messi; the last was at Liverpool with Mohamed Salah.'),
      ('tpa-665', 'James Rodríguez', 'Pedri', 2, 'One middle man does it. He was at Bayern Munich with James Rodríguez and at Barcelona with Pedri.'),
      ('tpa-682', 'Darwin Núñez', 'Vinícius Júnior', 5, 'Four middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Real Madrid with Vinícius Júnior.'),
      ('tpa-693', 'Kevin De Bruyne', 'Mikel Oyarzabal', 4, 'Three middle men at least. The first was at Manchester City with Kevin De Bruyne; the last was at Real Sociedad with Mikel Oyarzabal.'),
      ('tpa-694', 'Kobbie Mainoo', 'Sergio Ramos', 2, 'One middle man does it. He was at Manchester United with Kobbie Mainoo and at Real Madrid with Sergio Ramos.'),
      ('tpa-709', 'Antoine Griezmann', 'Kevin De Bruyne', 2, 'One middle man does it. He was at Atlético Madrid with Antoine Griezmann and at Manchester City with Kevin De Bruyne.'),
      ('tpa-726', 'Alexander Isak', 'Joshua Kimmich', 3, 'Two middle men at least. The first was at Real Sociedad with Alexander Isak; the last was at Bayern Munich with Joshua Kimmich.'),
      ('tpa-736', 'Marcus Rashford', 'Martin Ødegaard', 2, 'One middle man does it. He was at Manchester United with Marcus Rashford and at Real Madrid with Martin Ødegaard.'),
      ('tpa-741', 'Gavi', 'Thiago Silva', 2, 'One middle man does it. He was at Barcelona with Gavi and at Chelsea with Thiago Silva.'),
      ('tpa-742', 'Romelu Lukaku', 'Sandro Tonali', 5, 'Four middle men at least. The first was at Inter Milan with Romelu Lukaku; the last was at Newcastle with Sandro Tonali.'),
      ('tpa-747', 'Arturo Vidal', 'Marquinhos', 2, 'One middle man does it. He was at Inter Milan with Arturo Vidal and at PSG with Marquinhos.'),
      ('tpa-752', 'Moisés Caicedo', 'Virgil van Dijk', 4, 'Three middle men at least. The first was at Chelsea with Moisés Caicedo; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-758', 'Thibaut Courtois', 'Virgil van Dijk', 4, 'Three middle men at least. The first was at Real Madrid with Thibaut Courtois; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-776', 'Manuel Neuer', 'Marquinhos', 3, 'Two middle men at least. The first was at Bayern Munich with Manuel Neuer; the last was at PSG with Marquinhos.'),
      ('tpa-777', 'Romelu Lukaku', 'Virgil van Dijk', 4, 'Three middle men at least. The first was at Inter Milan with Romelu Lukaku; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-784', 'Lamine Yamal', 'Rafael Leão', 6, '5 middle men at least. The first was at Barcelona with Lamine Yamal; the last was at AC Milan with Rafael Leão.'),
      ('tpa-786', 'Endrick', 'Thiago Silva', 2, 'One middle man does it. He was at Real Madrid with Endrick and at PSG with Thiago Silva.'),
      ('tpa-791', 'Joshua Kimmich', 'Moisés Caicedo', 3, 'Two middle men at least. The first was at Bayern Munich with Joshua Kimmich; the last was at Chelsea with Moisés Caicedo.'),
      ('tpa-794', 'Andrew Robertson', 'Warren Zaïre-Emery', 4, 'Three middle men at least. The first was at Liverpool with Andrew Robertson; the last was at PSG with Warren Zaïre-Emery.'),
      ('tpa-811', 'Florian Wirtz', 'Yassine Bounou', 3, 'Two middle men at least. The first was at Bayer Leverkusen with Florian Wirtz; the last was at Al-Hilal with Yassine Bounou.'),
      ('tpa-816', 'Alphonso Davies', 'Pierre-Emerick Aubameyang', 2, 'One middle man does it. He was at Bayern Munich with Alphonso Davies and at Borussia Dortmund with Pierre-Emerick Aubameyang.'),
      ('tpa-818', 'Edinson Cavani', 'Joshua Kimmich', 3, 'Two middle men at least. The first was at Manchester United with Edinson Cavani; the last was at Bayern Munich with Joshua Kimmich.'),
      ('tpa-822', 'Arturo Vidal', 'Darwin Núñez', 4, 'Three middle men at least. The first was at Bayern Munich with Arturo Vidal; the last was at Liverpool with Darwin Núñez.'),
      ('tpa-823', 'Alexander Isak', 'Hugo Lloris', 4, 'Three middle men at least. The first was at Real Sociedad with Alexander Isak; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-824', 'Robert Lewandowski', 'Virgil van Dijk', 3, 'Two middle men at least. The first was at Bayern Munich with Robert Lewandowski; the last was at Southampton with Virgil van Dijk.'),
      ('tpa-827', 'Moussa Diaby', 'Romelu Lukaku', 2, 'One middle man does it. He was at Al-Ittihad with Moussa Diaby and at Chelsea with Romelu Lukaku.'),
      ('tpa-829', 'Hugo Lloris', 'Kalidou Koulibaly', 5, 'Four middle men at least. The first was at Tottenham with Hugo Lloris; the last was at Chelsea with Kalidou Koulibaly.'),
      ('tpa-830', 'Casemiro', 'Sadio Mané', 2, 'One middle man does it. He was at Real Madrid with Casemiro and at Al-Nassr with Sadio Mané.'),
      ('tpa-831', 'Kalidou Koulibaly', 'Riyad Mahrez', 2, 'One middle man does it. He was at Chelsea with Kalidou Koulibaly and at Leicester City with Riyad Mahrez.'),
      ('tpa-837', 'Alejandro Garnacho', 'Jude Bellingham', 3, 'Two middle men at least. The first was at Manchester United with Alejandro Garnacho; the last was at Real Madrid with Jude Bellingham.'),
      ('tpa-838', 'Marc-André ter Stegen', 'Romelu Lukaku', 2, 'One middle man does it. He was at Barcelona with Marc-André ter Stegen and at Inter Milan with Romelu Lukaku.'),
      ('tpa-839', 'Leroy Sané', 'Moisés Caicedo', 3, 'Two middle men at least. The first was at Bayern Munich with Leroy Sané; the last was at Chelsea with Moisés Caicedo.'),
      ('tpa-846', 'Darwin Núñez', 'Rafael Leão', 7, '6 middle men at least. The first was at Liverpool with Darwin Núñez; the last was at AC Milan with Rafael Leão.'),
      ('tpa-847', 'Hugo Lloris', 'Rafael Leão', 6, '5 middle men at least. The first was at Tottenham with Hugo Lloris; the last was at AC Milan with Rafael Leão.'),
      ('tpa-856', 'Arturo Vidal', 'Sadio Mané', 2, 'One middle man does it. He was at Bayern Munich with Arturo Vidal and, in another season, at Bayern Munich with Sadio Mané.'),
      ('tpa-859', 'Pedri', 'Sergio Ramos', 2, 'One middle man does it. He was at Barcelona with Pedri and at PSG with Sergio Ramos.'),
      ('tpa-865', 'Lamine Yamal', 'Romelu Lukaku', 3, 'Two middle men at least. The first was at Barcelona with Lamine Yamal; the last was at Chelsea with Romelu Lukaku.'),
      ('tpa-868', 'Federico Valverde', 'Manuel Neuer', 2, 'One middle man does it. He was at Real Madrid with Federico Valverde and at Bayern Munich with Manuel Neuer.'),
      ('tpa-872', 'Bruno Fernandes', 'Declan Rice', 3, 'Two middle men at least. The first was at Manchester United with Bruno Fernandes; the last was at Arsenal with Declan Rice.'),
      ('tpa-879', 'Declan Rice', 'Hugo Lloris', 4, 'Three middle men at least. The first was at Arsenal with Declan Rice; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-884', 'Erling Haaland', 'Federico Valverde', 2, 'One middle man does it. He was at Borussia Dortmund with Erling Haaland and at Real Madrid with Federico Valverde.'),
      ('tpa-893', 'Bernardo Silva', 'Marquinhos', 2, 'One middle man does it. He was at Monaco with Bernardo Silva and at PSG with Marquinhos.'),
      ('tpa-894', 'Darwin Núñez', 'Ousmane Dembélé', 5, 'Four middle men at least. The first was at Liverpool with Darwin Núñez; the last was at Barcelona with Ousmane Dembélé.'),
      ('tpa-900', 'Declan Rice', 'Son Heung-min', 4, 'Three middle men at least. The first was at Arsenal with Declan Rice; the last was at Tottenham with Son Heung-min.'),
      ('tpa-912', 'Kobbie Mainoo', 'Lamine Yamal', 4, 'Three middle men at least. The first was at Manchester United with Kobbie Mainoo; the last was at Barcelona with Lamine Yamal.'),
      ('tpa-915', 'Antoine Griezmann', 'Marquinhos', 2, 'One middle man does it. He was at Barcelona with Antoine Griezmann and at PSG with Marquinhos.'),
      ('tpa-922', 'Arturo Vidal', 'Bernardo Silva', 3, 'Two middle men at least. The first was at Inter Milan with Arturo Vidal; the last was at Manchester City with Bernardo Silva.'),
      ('tpa-924', 'Andrew Robertson', 'Kevin De Bruyne', 3, 'Two middle men at least. The first was at Liverpool with Andrew Robertson; the last was at Manchester City with Kevin De Bruyne.'),
      ('tpa-927', 'João Cancelo', 'Son Heung-min', 3, 'Two middle men at least. The first was at Bayern Munich with João Cancelo; the last was at Tottenham with Son Heung-min.'),
      ('tpa-932', 'N''Golo Kanté', 'Rúben Dias', 2, 'One middle man does it. He was at Chelsea with N''Golo Kanté and at Benfica with Rúben Dias.'),
      ('tpa-935', 'Enzo Fernández', 'Hugo Lloris', 5, 'Four middle men at least. The first was at Chelsea with Enzo Fernández; the last was at Tottenham with Hugo Lloris.'),
      ('tpa-950', 'Marquinhos', 'Robert Lewandowski', 2, 'One middle man does it. He was at PSG with Marquinhos and at Barcelona with Robert Lewandowski.'),
      ('tpa-956', 'Endrick', 'Gavi', 3, 'Two middle men at least. The first was at Real Madrid with Endrick; the last was at Barcelona with Gavi.'),
      ('tpa-964', 'Arda Güler', 'Harry Kane', 2, 'One middle man does it. He was at Real Madrid with Arda Güler and at Tottenham with Harry Kane.'),
      ('tpa-966', 'Martin Ødegaard', 'Moussa Diaby', 3, 'Two middle men at least. The first was at Real Madrid with Martin Ødegaard; the last was at PSG with Moussa Diaby.'),
      ('tpa-968', 'Harry Kane', 'Warren Zaïre-Emery', 3, 'Two middle men at least. The first was at Tottenham with Harry Kane; the last was at PSG with Warren Zaïre-Emery.'),
      ('tpa-969', 'Endrick', 'Mikel Oyarzabal', 3, 'Two middle men at least. The first was at Real Madrid with Endrick; the last was at Real Sociedad with Mikel Oyarzabal.')
    ) as rows(puzzle_id, player_a, player_b, active_min_steps, active_hint)
  loop
    select count(*) into matching_rows
    from public.transfer_path_puzzles p
    where p.puzzle_id = desired.puzzle_id
      and p.player_a = desired.player_a
      and p.player_b = desired.player_b
      and p.active_min_steps is null
      and p.active_hint is null;

    if matching_rows <> 1 then raise exception 'Expected one exact null active row for %, found %', desired.puzzle_id, matching_rows; end if;

    update public.transfer_path_puzzles p
    set active_min_steps = desired.active_min_steps::smallint,
        active_hint = desired.active_hint
    where p.puzzle_id = desired.puzzle_id
      and p.player_a = desired.player_a
      and p.player_b = desired.player_b
      and p.active_min_steps is null
      and p.active_hint is null;

    get diagnostics updated_this_row = row_count;
    updated_rows := updated_rows + updated_this_row;
  end loop;

  if updated_rows <> 203 then raise exception 'Expected to restore 203 verified active rows, updated %', updated_rows; end if;

  select count(*) into matching_rows
  from public.transfer_path_puzzles p
  where p.active_min_steps is not null and p.active_hint is not null;
  if matching_rows <> 203 then raise exception 'Expected 203 complete active hints after restore, found %', matching_rows; end if;

  if exists (
    select 1 from public.transfer_path_puzzles p
    where (p.active_min_steps is null) <> (p.active_hint is null)
  ) then raise exception 'Transfer Path has a partial active hint after restore'; end if;
end
$migration$;

commit;
