-- Round 460: Transfer Path's special rules. Every <rule>_min_steps and <rule>_hint below is
-- derived by scripts/genTransferPathHints.mjs on the graph left after the rule's own filter
-- (src/lib/transferPathModes.ts: active players only keeps players with a season touching
-- 2026, Europe only keeps seasons at European clubs) from the 2026-08-26 pull in
-- scripts/data/transferPathPull/. Each row carries the minimum and the two clubs the hint
-- names under each rule; the UPDATE rebuilds the hint text from them (the wording mirrors
-- hintText in scripts/lib/transferPathHints.mjs, and simTransferPathModes proves the live
-- text equals it row by row). A null minimum means the rule has no path for that puzzle.
-- Do not edit by hand; re-run the generator.
begin;
with v(puzzle_id, a_min, a_first, a_last, e_min, e_first, e_last) as (values
  ('tp-3', null, null, null, 2, 'Juventus', 'Manchester United'),
  ('tp-5', null, null, null, 2, 'Liverpool', 'Real Madrid'),
  ('tp-6', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tp-7', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tp-8', null, null, null, 2, 'Manchester United', 'PSG'),
  ('tp-9', null, null, null, 2, 'Barcelona', 'Sevilla'),
  ('tp-10', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tp-11', null, null, null, 2, 'Atlético Madrid', 'Chelsea'),
  ('tp-12', null, null, null, 2, 'Bayern Munich', 'Juventus'),
  ('tp-13', 3, 'Tottenham', 'Real Madrid', 2, 'Tottenham', 'Real Madrid'),
  ('tp-14', null, null, null, 2, 'Chelsea', 'PSG'),
  ('tp-15', null, null, null, 3, 'Liverpool', 'Manchester City'),
  ('tp-16', null, null, null, 2, 'Chelsea', 'Real Madrid'),
  ('tp-17', null, null, null, 2, 'Juventus', 'Liverpool'),
  ('tp-18', null, null, null, 2, 'Chelsea', 'Real Madrid'),
  ('tp-19', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tp-20', null, null, null, 2, 'Bayern Munich', 'Bayern Munich'),
  ('tpa-20', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-21', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-22', null, null, null, 2, 'Fiorentina', 'Bayern Munich'),
  ('tpa-23', null, null, null, 3, 'Real Madrid', 'Manchester United'),
  ('tpa-25', null, null, null, 2, 'Real Madrid', 'AC Milan'),
  ('tpa-26', 2, 'Borussia Dortmund', 'Manchester City', 2, 'Borussia Dortmund', 'Manchester City'),
  ('tpa-27', 2, 'Arsenal', 'Chelsea', 2, 'Arsenal', 'Chelsea'),
  ('tpa-28', null, null, null, 2, 'Real Madrid', 'Tottenham'),
  ('tpa-29', null, null, null, 4, 'Liverpool', 'Manchester United'),
  ('tpa-30', null, null, null, 2, 'Real Madrid', 'Manchester United'),
  ('tpa-31', null, null, null, 2, 'Tottenham', 'Real Madrid'),
  ('tpa-32', null, null, null, 2, 'Arsenal', 'Real Madrid'),
  ('tpa-33', 3, 'Bayern Munich', 'Brighton', 3, 'Bayern Munich', 'Arsenal'),
  ('tpa-34', null, null, null, 3, 'Real Madrid', 'Liverpool'),
  ('tpa-36', null, null, null, 2, 'Borussia Dortmund', 'Manchester United'),
  ('tpa-37', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-38', null, null, null, 2, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-39', null, null, null, 3, 'Inter Milan', 'Real Madrid'),
  ('tpa-40', 4, 'Barcelona', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-41', null, null, null, 2, 'PSG', 'Manchester United'),
  ('tpa-43', null, null, null, 3, 'Liverpool', 'Borussia Dortmund'),
  ('tpa-44', null, null, null, 2, 'Chelsea', 'Real Madrid'),
  ('tpa-45', 3, 'Chelsea', 'Juventus', 3, 'Chelsea', 'Juventus'),
  ('tpa-47', 3, 'Borussia Dortmund', 'Napoli', 3, 'Borussia Dortmund', 'Napoli'),
  ('tpa-48', null, null, null, 3, 'Real Betis', 'Galatasaray'),
  ('tpa-49', null, null, null, 3, 'Borussia Dortmund', 'Fiorentina'),
  ('tpa-50', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-52', null, null, null, 3, 'Borussia Dortmund', 'Galatasaray'),
  ('tpa-53', null, null, null, 3, 'Inter Milan', 'Liverpool'),
  ('tpa-54', 3, 'Barcelona', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-55', 2, 'Barcelona', 'Barcelona', 2, 'Barcelona', 'Manchester United'),
  ('tpa-56', null, null, null, 2, 'Real Madrid', 'Juventus'),
  ('tpa-57', null, null, null, 2, 'Borussia Dortmund', 'Manchester United'),
  ('tpa-58', null, null, null, 3, 'Barcelona', 'Juventus'),
  ('tpa-59', null, null, null, 3, 'Chelsea', 'Real Sociedad'),
  ('tpa-60', 3, 'Juventus', 'PSG', 3, 'Juventus', 'PSG'),
  ('tpa-62', null, null, null, 3, 'Real Madrid', 'Atlético Madrid'),
  ('tpa-64', null, null, null, 2, 'Atlético Madrid', 'Atlético Madrid'),
  ('tpa-65', 3, 'Manchester United', 'Real Madrid', 3, 'Manchester United', 'Real Madrid'),
  ('tpa-66', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-67', null, null, null, 2, 'Chelsea', 'Atlético Madrid'),
  ('tpa-68', null, null, null, 2, 'Juventus', 'Manchester City'),
  ('tpa-69', 3, 'Manchester United', 'Manchester City', 3, 'Manchester United', 'Manchester City'),
  ('tpa-70', null, null, null, 2, 'Atlético Madrid', 'Juventus'),
  ('tpa-71', null, null, null, 3, 'PSG', 'Manchester City'),
  ('tpa-72', 2, 'Real Madrid', 'PSG', 2, 'Real Madrid', 'PSG'),
  ('tpa-73', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-74', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-75', 2, 'Manchester United', 'Chelsea', 2, 'Manchester United', 'Chelsea'),
  ('tpa-76', null, null, null, 3, 'Manchester United', 'Barcelona'),
  ('tpa-77', null, null, null, 3, 'Fiorentina', 'Real Sociedad'),
  ('tpa-78', null, null, null, 3, 'Borussia Dortmund', 'Chelsea'),
  ('tpa-79', null, null, null, 3, 'Arsenal', 'Sevilla'),
  ('tpa-80', 2, 'Atlético Madrid', 'Galatasaray', 2, 'Atlético Madrid', 'Galatasaray'),
  ('tpa-81', null, null, null, 3, 'Napoli', 'PSG'),
  ('tpa-82', null, null, null, 2, 'AC Milan', 'Juventus'),
  ('tpa-83', 3, 'Juventus', 'PSG', 3, 'Juventus', 'PSG'),
  ('tpa-84', null, null, null, 2, 'Bayern Munich', 'Manchester City'),
  ('tpa-86', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-87', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-88', null, null, null, 2, 'Manchester City', 'Tottenham'),
  ('tpa-89', null, null, null, 3, 'Barcelona', 'Tottenham'),
  ('tpa-90', null, null, null, 2, 'Valencia', 'Barcelona'),
  ('tpa-91', 2, 'Manchester City', 'Arsenal', 2, 'Manchester City', 'Arsenal'),
  ('tpa-92', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-93', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-94', 2, 'PSG', 'Barcelona', 2, 'PSG', 'Barcelona'),
  ('tpa-95', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-96', null, null, null, 3, 'Barcelona', 'Arsenal'),
  ('tpa-97', null, null, null, 2, 'Inter Milan', 'Atlético Madrid'),
  ('tpa-98', null, null, null, 3, 'Arsenal', 'Real Madrid'),
  ('tpa-99', null, null, null, 2, 'Liverpool', 'PSV'),
  ('tpa-100', 2, 'Real Madrid', 'PSG', 2, 'Real Madrid', 'PSG'),
  ('tpa-101', null, null, null, 3, 'Tottenham', 'Chelsea'),
  ('tpa-102', null, null, null, 2, 'Tottenham', 'Manchester United'),
  ('tpa-104', null, null, null, 2, 'Manchester City', 'Chelsea'),
  ('tpa-105', 3, 'Bayer Leverkusen', 'PSG', 3, 'Bayer Leverkusen', 'PSG'),
  ('tpa-106', 3, 'Bayern Munich', 'Liverpool', 3, 'Bayern Munich', 'Liverpool'),
  ('tpa-107', null, null, null, 3, 'Bayern Munich', 'Juventus'),
  ('tpa-108', null, null, null, 4, 'Barcelona', 'Juventus'),
  ('tpa-109', 3, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-110', null, null, null, 3, 'Manchester City', 'Liverpool'),
  ('tpa-111', null, null, null, 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-112', 3, 'Liverpool', 'Manchester City', 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-113', null, null, null, 2, 'Bayern Munich', 'Bayern Munich'),
  ('tpa-114', 4, 'Juventus', 'Bayern Munich', 3, 'Juventus', 'Bayern Munich'),
  ('tpa-115', null, null, null, 2, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-116', null, null, null, 2, 'Bayern Munich', 'Manchester City'),
  ('tpa-117', 3, 'Chelsea', 'Barcelona', 2, 'Manchester City', 'Barcelona'),
  ('tpa-118', null, null, null, 2, 'Arsenal', 'Real Madrid'),
  ('tpa-119', 2, 'PSG', 'Real Madrid', 2, 'PSG', 'Real Madrid'),
  ('tpa-120', 3, 'Liverpool', 'AC Milan', 3, 'Liverpool', 'AC Milan'),
  ('tpa-121', null, null, null, 3, 'Chelsea', 'AC Milan'),
  ('tpa-122', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-123', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-124', null, null, null, 2, 'Bayern Munich', 'Porto'),
  ('tpa-125', null, null, null, 3, 'Bayern Munich', 'Arsenal'),
  ('tpa-126', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-127', 2, 'PSG', 'Real Madrid', 2, 'PSG', 'Real Madrid'),
  ('tpa-128', 3, 'Barcelona', 'Galatasaray', 3, 'Barcelona', 'Galatasaray'),
  ('tpa-129', null, null, null, 2, 'Atlético Madrid', 'Manchester United'),
  ('tpa-131', null, null, null, 3, 'Barcelona', 'Chelsea'),
  ('tpa-132', 2, 'Arsenal', 'Chelsea', 2, 'Arsenal', 'Chelsea'),
  ('tpa-133', 4, 'Manchester United', 'PSV', 3, 'Manchester United', 'Tottenham'),
  ('tpa-134', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-136', null, null, null, 2, 'Inter Milan', 'Barcelona'),
  ('tpa-137', 3, 'Barcelona', 'Liverpool', 3, 'Barcelona', 'Liverpool'),
  ('tpa-138', null, null, null, 2, 'Inter Milan', 'Borussia Dortmund'),
  ('tpa-139', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-140', null, null, null, 3, 'Manchester United', 'Real Sociedad'),
  ('tpa-141', null, null, null, 3, 'Manchester City', 'Lyon'),
  ('tpa-142', null, null, null, 2, 'Real Madrid', 'Porto'),
  ('tpa-143', null, null, null, 3, 'Liverpool', 'Galatasaray'),
  ('tpa-145', null, null, null, 2, 'Juventus', 'Atlético Madrid'),
  ('tpa-146', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-147', null, null, null, 2, 'Real Madrid', 'Tottenham'),
  ('tpa-148', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-149', null, null, null, 4, 'Chelsea', 'PSV'),
  ('tpa-150', null, null, null, 3, 'Juventus', 'Arsenal'),
  ('tpa-151', null, null, null, 3, 'Liverpool', 'PSV'),
  ('tpa-152', 4, 'Manchester United', 'Arsenal', 3, 'Manchester United', 'Arsenal'),
  ('tpa-153', null, null, null, 2, 'Manchester United', 'PSG'),
  ('tpa-154', null, null, null, 2, 'Atlético Madrid', 'AC Milan'),
  ('tpa-155', 3, 'Manchester City', 'Roma', 2, 'Manchester City', 'Juventus'),
  ('tpa-156', null, null, null, 3, 'Barcelona', 'Bayer Leverkusen'),
  ('tpa-157', null, null, null, 2, 'Manchester United', 'Borussia Dortmund'),
  ('tpa-158', 3, 'Inter Milan', 'PSG', 3, 'Manchester United', 'PSG'),
  ('tpa-159', 3, 'Barcelona', 'Galatasaray', 3, 'Barcelona', 'Galatasaray'),
  ('tpa-160', 2, 'Borussia Dortmund', 'Manchester United', 2, 'Real Madrid', 'Manchester United'),
  ('tpa-161', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tpa-162', 4, 'Manchester United', 'Liverpool', 4, 'Manchester United', 'Liverpool'),
  ('tpa-163', 4, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-164', null, null, null, 3, 'Inter Milan', 'Liverpool'),
  ('tpa-165', null, null, null, 3, 'Liverpool', 'Galatasaray'),
  ('tpa-166', 3, 'PSG', 'Manchester United', 3, 'PSG', 'Manchester United'),
  ('tpa-167', 2, 'Manchester City', 'Manchester City', 2, 'Manchester City', 'Manchester City'),
  ('tpa-169', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-170', null, null, null, 2, 'Manchester United', 'Barcelona'),
  ('tpa-171', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-172', null, null, null, 3, 'Atlético Madrid', 'PSG'),
  ('tpa-173', null, null, null, 2, 'Barcelona', 'Manchester United'),
  ('tpa-174', 2, 'Manchester City', 'Napoli', 2, 'Atlético Madrid', 'Inter Milan'),
  ('tpa-175', null, null, null, 3, 'Real Madrid', 'PSG'),
  ('tpa-176', null, null, null, 3, 'Real Madrid', 'Manchester United'),
  ('tpa-177', 3, 'Juventus', 'Atlético Madrid', 3, 'Juventus', 'Atlético Madrid'),
  ('tpa-178', null, null, null, 2, 'Manchester City', 'Liverpool'),
  ('tpa-179', null, null, null, 3, 'Chelsea', 'Manchester City'),
  ('tpa-180', null, null, null, 3, 'Barcelona', 'Liverpool'),
  ('tpa-181', 2, 'Real Madrid', 'PSG', 2, 'Real Madrid', 'PSG'),
  ('tpa-182', null, null, null, 2, 'Valencia', 'Manchester United'),
  ('tpa-183', null, null, null, 3, 'Juventus', 'Manchester City'),
  ('tpa-184', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tpa-185', 3, 'Manchester United', 'Napoli', 3, 'Manchester United', 'Napoli'),
  ('tpa-186', null, null, null, 3, 'Inter Milan', 'Tottenham'),
  ('tpa-187', 3, 'Juventus', 'Real Madrid', 3, 'Juventus', 'Real Madrid'),
  ('tpa-188', 3, 'PSG', 'Galatasaray', 3, 'PSG', 'Galatasaray'),
  ('tpa-189', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-190', null, null, null, 3, 'Real Madrid', 'Real Sociedad'),
  ('tpa-191', null, null, null, 2, 'Bayern Munich', 'Fiorentina'),
  ('tpa-192', null, null, null, 2, 'Barcelona', 'Bayern Munich'),
  ('tpa-193', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-194', 3, 'Real Madrid', 'Manchester City', 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-195', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-197', null, null, null, 2, 'Chelsea', 'Liverpool'),
  ('tpa-198', null, null, null, 4, 'Arsenal', 'Tottenham'),
  ('tpa-199', 3, 'Atlético Madrid', 'Chelsea', 2, 'Atlético Madrid', 'Chelsea'),
  ('tpa-200', null, null, null, 3, 'Manchester United', 'Chelsea'),
  ('tpa-201', null, null, null, 3, 'Juventus', 'Liverpool'),
  ('tpa-202', 3, 'Bayern Munich', 'Napoli', 3, 'Bayern Munich', 'Napoli'),
  ('tpa-203', null, null, null, 3, 'Real Madrid', 'Manchester United'),
  ('tpa-204', null, null, null, 3, 'Barcelona', 'Manchester United'),
  ('tpa-205', null, null, null, 2, 'Manchester City', 'Chelsea'),
  ('tpa-206', null, null, null, 4, 'Napoli', 'Liverpool'),
  ('tpa-207', null, null, null, 3, 'Liverpool', 'Newcastle'),
  ('tpa-208', null, null, null, 3, 'Bayern Munich', 'PSG'),
  ('tpa-209', null, null, null, 3, 'Barcelona', 'Chelsea'),
  ('tpa-212', null, null, null, 3, 'Bayern Munich', 'Napoli'),
  ('tpa-213', 3, 'Palmeiras', 'Real Madrid', 3, 'Chelsea', 'Real Madrid'),
  ('tpa-214', 4, 'Barcelona', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-215', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-216', 4, 'Manchester United', 'Galatasaray', 3, 'Manchester United', 'Galatasaray'),
  ('tpa-218', null, null, null, 2, 'Barcelona', 'Bayern Munich'),
  ('tpa-220', null, null, null, 2, 'Lazio', 'Barcelona'),
  ('tpa-221', null, null, null, 3, 'Manchester City', 'Real Madrid'),
  ('tpa-222', 2, 'Atlético Madrid', 'Real Madrid', 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-223', null, null, null, 3, 'Barcelona', 'Atlético Madrid'),
  ('tpa-224', null, null, null, 3, 'Lazio', 'Arsenal'),
  ('tpa-225', null, null, null, 2, 'Bayern Munich', 'Borussia Dortmund'),
  ('tpa-226', 3, 'Arsenal', 'Tottenham', 3, 'Arsenal', 'Tottenham'),
  ('tpa-227', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tpa-228', 2, 'Manchester City', 'Bayern Munich', 2, 'Manchester City', 'Barcelona'),
  ('tpa-229', null, null, null, 2, 'Monaco', 'Manchester United'),
  ('tpa-230', null, null, null, 3, 'Bayern Munich', 'Manchester United'),
  ('tpa-231', null, null, null, 3, 'Juventus', 'Arsenal'),
  ('tpa-232', 2, 'Barcelona', 'Manchester United', 2, 'Barcelona', 'Manchester United'),
  ('tpa-233', null, null, null, 2, 'PSG', 'PSG'),
  ('tpa-234', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-235', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-236', null, null, null, 3, 'Liverpool', 'Barcelona'),
  ('tpa-237', 3, 'Liverpool', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-238', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-239', 3, 'Manchester United', 'Palmeiras', 3, 'Manchester United', 'Real Madrid'),
  ('tpa-240', 2, 'Real Madrid', 'Real Madrid', 2, 'Real Madrid', 'Real Madrid'),
  ('tpa-241', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-242', null, null, null, 3, 'Juventus', 'PSG'),
  ('tpa-243', null, null, null, 3, 'Real Betis', 'Liverpool'),
  ('tpa-244', null, null, null, 3, 'Manchester United', 'Real Madrid'),
  ('tpa-245', null, null, null, 2, 'Real Betis', 'Real Madrid'),
  ('tpa-246', null, null, null, 2, 'Manchester United', 'Barcelona'),
  ('tpa-247', null, null, null, 3, 'Liverpool', 'Manchester United'),
  ('tpa-248', 3, 'Manchester City', 'Real Madrid', 2, 'Chelsea', 'Real Madrid'),
  ('tpa-249', null, null, null, 3, 'Tottenham', 'Chelsea'),
  ('tpa-250', null, null, null, 2, 'Manchester City', 'Barcelona'),
  ('tpa-251', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-252', null, null, null, 3, 'Galatasaray', 'Liverpool'),
  ('tpa-253', null, null, null, 2, 'Chelsea', 'Bayern Munich'),
  ('tpa-254', null, null, null, 2, 'Borussia Dortmund', 'Chelsea'),
  ('tpa-255', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-256', null, null, null, 2, 'Bayern Munich', 'Bayern Munich'),
  ('tpa-257', null, null, null, 3, 'Liverpool', 'Borussia Dortmund'),
  ('tpa-258', null, null, null, 2, 'Borussia Dortmund', 'Bayern Munich'),
  ('tpa-259', 3, 'Bayern Munich', 'Brighton', 3, 'Bayern Munich', 'Arsenal'),
  ('tpa-260', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-261', null, null, null, 2, 'PSG', 'Manchester United'),
  ('tpa-262', 2, 'Real Madrid', 'Juventus', 2, 'Real Madrid', 'Juventus'),
  ('tpa-263', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-264', null, null, null, 2, 'Chelsea', 'Galatasaray'),
  ('tpa-265', 2, 'Benfica', 'Real Madrid', 2, 'Benfica', 'Real Madrid'),
  ('tpa-266', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-267', 4, 'Real Madrid', 'Juventus', 4, 'Real Madrid', 'Juventus'),
  ('tpa-268', 3, 'Liverpool', 'Juventus', 3, 'Liverpool', 'Juventus'),
  ('tpa-269', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tpa-270', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-271', 3, 'Manchester City', 'PSG', 3, 'Manchester City', 'PSG'),
  ('tpa-272', null, null, null, 3, 'Barcelona', 'Galatasaray'),
  ('tpa-273', 2, 'Borussia Dortmund', 'AC Milan', 2, 'Borussia Dortmund', 'AC Milan'),
  ('tpa-274', null, null, null, 3, 'Bayern Munich', 'Tottenham'),
  ('tpa-275', null, null, null, 2, 'Liverpool', 'Real Sociedad'),
  ('tpa-276', null, null, null, 3, 'Arsenal', 'Tottenham'),
  ('tpa-277', null, null, null, 2, 'Borussia Dortmund', 'Manchester United'),
  ('tpa-279', null, null, null, 3, 'Napoli', 'Liverpool'),
  ('tpa-280', null, null, null, 4, 'Juventus', 'Liverpool'),
  ('tpa-281', null, null, null, 2, 'Barcelona', 'Chelsea'),
  ('tpa-282', null, null, null, 3, 'Real Madrid', 'Tottenham'),
  ('tpa-283', null, null, null, 3, 'Arsenal', 'Chelsea'),
  ('tpa-284', 3, 'Chelsea', 'Borussia Dortmund', 2, 'Chelsea', 'Barcelona'),
  ('tpa-285', null, null, null, 2, 'Liverpool', 'Real Madrid'),
  ('tpa-286', 2, 'Liverpool', 'Bayer Leverkusen', 2, 'Liverpool', 'Bayer Leverkusen'),
  ('tpa-287', null, null, null, 3, 'Borussia Dortmund', 'Juventus'),
  ('tpa-288', null, null, null, 3, 'Juventus', 'Liverpool'),
  ('tpa-289', null, null, null, 2, 'Arsenal', 'Real Sociedad'),
  ('tpa-290', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-291', null, null, null, 3, 'Bayern Munich', 'Chelsea'),
  ('tpa-292', null, null, null, 3, 'Real Madrid', 'Chelsea'),
  ('tpa-293', null, null, null, 2, 'Atlético Madrid', 'Chelsea'),
  ('tpa-294', null, null, null, 3, 'Bayern Munich', 'Arsenal'),
  ('tpa-295', null, null, null, 2, 'Juventus', 'PSG'),
  ('tpa-296', null, null, null, 4, 'Manchester United', 'Liverpool'),
  ('tpa-297', null, null, null, 3, 'Chelsea', 'Real Madrid'),
  ('tpa-298', null, null, null, 2, 'Bayern Munich', 'Galatasaray'),
  ('tpa-299', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-301', null, null, null, 3, 'Borussia Dortmund', 'Napoli'),
  ('tpa-303', null, null, null, 3, 'Manchester United', 'Bayern Munich'),
  ('tpa-304', 2, 'Arsenal', 'Aston Villa', 2, 'Arsenal', 'Aston Villa'),
  ('tpa-305', null, null, null, 2, 'Real Madrid', 'Real Betis'),
  ('tpa-306', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-307', null, null, null, 3, 'Lyon', 'Real Sociedad'),
  ('tpa-308', null, null, null, 3, 'Manchester City', 'PSG'),
  ('tpa-309', 2, 'Manchester City', 'Bayern Munich', 2, 'Manchester City', 'Barcelona'),
  ('tpa-311', 3, 'Real Madrid', 'PSG', 2, 'Real Madrid', 'PSG'),
  ('tpa-312', null, null, null, 2, 'Real Madrid', 'Valencia'),
  ('tpa-313', 2, 'Manchester City', 'Bayern Munich', 2, 'Manchester City', 'Barcelona'),
  ('tpa-314', null, null, null, 3, 'PSG', 'Liverpool'),
  ('tpa-315', 4, 'Real Madrid', 'Juventus', 4, 'Real Madrid', 'Juventus'),
  ('tpa-316', null, null, null, 2, 'Manchester United', 'Manchester United'),
  ('tpa-317', null, null, null, 2, 'Inter Milan', 'Borussia Dortmund'),
  ('tpa-318', null, null, null, 3, 'Atlético Madrid', 'Bayern Munich'),
  ('tpa-319', 3, 'Fiorentina', 'Brighton', 3, 'Fiorentina', 'Brighton'),
  ('tpa-320', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-321', null, null, null, 2, 'Chelsea', 'Arsenal'),
  ('tpa-322', null, null, null, 3, 'Lyon', 'Liverpool'),
  ('tpa-323', null, null, null, 2, 'Manchester United', 'Manchester United'),
  ('tpa-324', 3, 'PSG', 'Real Madrid', 3, 'PSG', 'Real Madrid'),
  ('tpa-325', null, null, null, 3, 'Arsenal', 'Sevilla'),
  ('tpa-326', null, null, null, 3, 'Real Madrid', 'Juventus'),
  ('tpa-327', null, null, null, 3, 'Atlético Madrid', 'Liverpool'),
  ('tpa-328', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-329', null, null, null, 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-330', null, null, null, 2, 'Inter Milan', 'Juventus'),
  ('tpa-331', null, null, null, 3, 'Inter Milan', 'Real Sociedad'),
  ('tpa-332', 3, 'Real Madrid', 'Bayer Leverkusen', 3, 'Real Madrid', 'Bayer Leverkusen'),
  ('tpa-333', null, null, null, 3, 'Chelsea', 'Real Madrid'),
  ('tpa-334', 3, 'Liverpool', 'Bayern Munich', 3, 'Liverpool', 'Bayern Munich'),
  ('tpa-335', 4, 'Galatasaray', 'Arsenal', 4, 'Galatasaray', 'Arsenal'),
  ('tpa-336', null, null, null, 2, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-337', null, null, null, 3, 'Barcelona', 'Real Sociedad'),
  ('tpa-338', null, null, null, 3, 'Liverpool', 'Manchester United'),
  ('tpa-339', null, null, null, 3, 'Chelsea', 'Manchester United'),
  ('tpa-340', 2, 'PSG', 'Real Madrid', 2, 'PSG', 'Real Madrid'),
  ('tpa-341', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-342', null, null, null, 3, 'Liverpool', 'Barcelona'),
  ('tpa-343', 4, 'Bayern Munich', 'Juventus', 3, 'Bayern Munich', 'Juventus'),
  ('tpa-344', null, null, null, 2, 'Real Madrid', 'Manchester United'),
  ('tpa-345', null, null, null, 3, 'Borussia Dortmund', 'Real Betis'),
  ('tpa-346', 2, 'Monaco', 'PSG', 2, 'Monaco', 'PSG'),
  ('tpa-347', null, null, null, 2, 'Valencia', 'Real Madrid'),
  ('tpa-348', null, null, null, 3, 'Barcelona', 'Tottenham'),
  ('tpa-349', 2, 'Arsenal', 'Manchester City', 2, 'Arsenal', 'Manchester City'),
  ('tpa-351', 3, 'Real Madrid', 'Tottenham', 2, 'Real Madrid', 'Tottenham'),
  ('tpa-352', null, null, null, 3, 'Arsenal', 'Liverpool'),
  ('tpa-354', null, null, null, 3, 'Barcelona', 'Tottenham'),
  ('tpa-355', null, null, null, 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-356', null, null, null, 2, 'Chelsea', 'Bayern Munich'),
  ('tpa-357', null, null, null, 3, 'Juventus', 'Real Madrid'),
  ('tpa-358', null, null, null, 2, 'Chelsea', 'PSG'),
  ('tpa-359', null, null, null, 2, 'Barcelona', 'Manchester United'),
  ('tpa-360', 4, 'Benfica', 'Tottenham', 3, 'Benfica', 'Tottenham'),
  ('tpa-361', null, null, null, 3, 'Napoli', 'AC Milan'),
  ('tpa-362', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-363', null, null, null, 3, 'Lazio', 'Galatasaray'),
  ('tpa-364', null, null, null, 3, 'AC Milan', 'Manchester United'),
  ('tpa-365', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-366', null, null, null, 3, 'Manchester City', 'Real Madrid'),
  ('tpa-367', null, null, null, 2, 'Liverpool', 'Juventus'),
  ('tpa-368', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-369', null, null, null, 2, 'Liverpool', 'Brighton'),
  ('tpa-370', null, null, null, 2, 'Bayern Munich', 'Barcelona'),
  ('tpa-371', null, null, null, 3, 'Arsenal', 'Juventus'),
  ('tpa-372', 3, 'Manchester United', 'Atlético Madrid', 3, 'Manchester United', 'Barcelona'),
  ('tpa-373', null, null, null, 2, 'Manchester United', 'Atlético Madrid'),
  ('tpa-374', null, null, null, 3, 'Liverpool', 'Manchester United'),
  ('tpa-375', null, null, null, 2, 'Chelsea', 'Atlético Madrid'),
  ('tpa-376', null, null, null, 2, 'Juventus', 'Chelsea'),
  ('tpa-379', null, null, null, 3, 'Porto', 'AC Milan'),
  ('tpa-380', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-381', 4, 'PSG', 'Manchester United', 3, 'PSG', 'Manchester United'),
  ('tpa-382', null, null, null, 2, 'Arsenal', 'Chelsea'),
  ('tpa-383', null, null, null, 3, 'Liverpool', 'Newcastle'),
  ('tpa-384', null, null, null, 3, 'Manchester United', 'Bayern Munich'),
  ('tpa-385', 3, 'Bayern Munich', 'PSG', 3, 'Bayern Munich', 'PSG'),
  ('tpa-386', null, null, null, 2, 'AC Milan', 'Chelsea'),
  ('tpa-387', null, null, null, 3, 'Lyon', 'Newcastle'),
  ('tpa-388', 2, 'Juventus', 'PSG', 2, 'Juventus', 'PSG'),
  ('tpa-389', 3, 'Borussia Dortmund', 'Barcelona', 3, 'Real Madrid', 'Barcelona'),
  ('tpa-390', null, null, null, 3, 'Atlético Madrid', 'Lyon'),
  ('tpa-391', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-392', null, null, null, 3, 'Liverpool', 'Real Madrid'),
  ('tpa-393', 3, 'Borussia Dortmund', 'Liverpool', 3, 'Borussia Dortmund', 'Liverpool'),
  ('tpa-395', 4, 'Manchester United', 'Galatasaray', 3, 'Manchester United', 'Galatasaray'),
  ('tpa-396', null, null, null, 2, 'Manchester United', 'Chelsea'),
  ('tpa-397', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-398', null, null, null, 2, 'Borussia Dortmund', 'AC Milan'),
  ('tpa-399', null, null, null, 2, 'Bayern Munich', 'Barcelona'),
  ('tpa-400', 3, 'Palmeiras', 'PSG', 3, 'Chelsea', 'PSG'),
  ('tpa-401', 2, 'Borussia Dortmund', 'Manchester City', 2, 'Borussia Dortmund', 'Manchester City'),
  ('tpa-402', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-403', 2, 'Borussia Dortmund', 'Inter Milan', 2, 'Borussia Dortmund', 'Inter Milan'),
  ('tpa-404', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-405', null, null, null, 2, 'Manchester City', 'Liverpool'),
  ('tpa-406', 4, 'Arsenal', 'Manchester United', 3, 'Chelsea', 'Manchester United'),
  ('tpa-407', null, null, null, 2, 'Juventus', 'Chelsea'),
  ('tpa-408', null, null, null, 3, 'Newcastle', 'Manchester United'),
  ('tpa-409', null, null, null, 2, 'Real Madrid', 'Napoli'),
  ('tpa-410', null, null, null, 3, 'Manchester United', 'Bayern Munich'),
  ('tpa-411', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-412', null, null, null, 3, 'Liverpool', 'Liverpool'),
  ('tpa-413', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-414', null, null, null, 2, 'Barcelona', 'Bayern Munich'),
  ('tpa-416', null, null, null, 3, 'Galatasaray', 'Manchester City'),
  ('tpa-417', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-418', null, null, null, 2, 'Barcelona', 'Juventus'),
  ('tpa-419', null, null, null, 2, 'Borussia Dortmund', 'Bayern Munich'),
  ('tpa-420', 4, 'Chelsea', 'PSV', 4, 'Chelsea', 'PSV'),
  ('tpa-421', 3, 'Bayern Munich', 'PSG', 3, 'Bayern Munich', 'PSG'),
  ('tpa-422', null, null, null, 2, 'Schalke 04', 'Bayern Munich'),
  ('tpa-423', null, null, null, 3, 'Napoli', 'Real Madrid'),
  ('tpa-424', 3, 'Real Madrid', 'Juventus', 3, 'Real Madrid', 'Juventus'),
  ('tpa-425', null, null, null, 3, 'PSG', 'Real Madrid'),
  ('tpa-426', null, null, null, 2, 'Real Madrid', 'Chelsea'),
  ('tpa-427', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-428', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-429', null, null, null, 2, 'Liverpool', 'Liverpool'),
  ('tpa-430', 2, 'PSG', 'Barcelona', 2, 'PSG', 'Barcelona'),
  ('tpa-431', null, null, null, 3, 'Porto', 'PSG'),
  ('tpa-432', 4, 'PSG', 'Barcelona', 2, 'PSG', 'Barcelona'),
  ('tpa-433', null, null, null, 3, 'Real Madrid', 'Tottenham'),
  ('tpa-434', 3, 'Juventus', 'Chelsea', 3, 'Juventus', 'Chelsea'),
  ('tpa-435', 3, 'Barcelona', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-436', null, null, null, 3, 'Barcelona', 'Napoli'),
  ('tpa-437', 3, 'PSG', 'Liverpool', 3, 'PSG', 'Liverpool'),
  ('tpa-438', null, null, null, 3, 'Atlético Madrid', 'Chelsea'),
  ('tpa-439', null, null, null, 3, 'Manchester United', 'Barcelona'),
  ('tpa-440', null, null, null, 2, 'Atlético Madrid', 'Manchester United'),
  ('tpa-441', 2, 'Real Madrid', 'Borussia Dortmund', 2, 'Real Madrid', 'Manchester United'),
  ('tpa-442', 3, 'Borussia Dortmund', 'PSG', 2, 'Borussia Dortmund', 'PSG'),
  ('tpa-443', null, null, null, 2, 'Atlético Madrid', 'Juventus'),
  ('tpa-444', null, null, null, 2, 'Manchester City', 'Manchester City'),
  ('tpa-445', null, null, null, 3, 'Barcelona', 'Chelsea'),
  ('tpa-448', 3, 'Borussia Dortmund', 'Real Madrid', 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-449', null, null, null, 3, 'Arsenal', 'Bayer Leverkusen'),
  ('tpa-450', null, null, null, 3, 'Real Sociedad', 'Bayer Leverkusen'),
  ('tpa-451', null, null, null, 2, 'Tottenham', 'Manchester City'),
  ('tpa-452', null, null, null, 2, 'Napoli', 'Chelsea'),
  ('tpa-453', null, null, null, 3, 'PSG', 'Manchester United'),
  ('tpa-454', 2, 'PSG', 'Barcelona', 2, 'Inter Milan', 'Barcelona'),
  ('tpa-455', 3, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-456', 3, 'Manchester City', 'Real Madrid', 3, 'Manchester City', 'Real Madrid'),
  ('tpa-457', 2, 'Bayer Leverkusen', 'Al-Ittihad', 3, 'Liverpool', 'Real Madrid'),
  ('tpa-458', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-459', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-460', 2, 'Real Madrid', 'Real Madrid', 2, 'Real Madrid', 'Real Madrid'),
  ('tpa-461', null, null, null, 2, 'Chelsea', 'Real Madrid'),
  ('tpa-462', null, null, null, 3, 'Tottenham', 'Barcelona'),
  ('tpa-463', 3, 'Chelsea', 'Barcelona', 2, 'Chelsea', 'Barcelona'),
  ('tpa-464', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-465', null, null, null, 2, 'Barcelona', 'Borussia Dortmund'),
  ('tpa-466', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-467', 3, 'Manchester United', 'Liverpool', 3, 'Manchester United', 'Liverpool'),
  ('tpa-468', null, null, null, 2, 'Chelsea', 'Benfica'),
  ('tpa-469', null, null, null, 3, 'Napoli', 'Bayern Munich'),
  ('tpa-470', 3, 'AC Milan', 'Liverpool', 3, 'AC Milan', 'Liverpool'),
  ('tpa-471', 3, 'Real Madrid', 'Arsenal', 3, 'Real Madrid', 'Arsenal'),
  ('tpa-472', null, null, null, 2, 'Manchester United', 'Barcelona'),
  ('tpa-473', 3, 'Manchester United', 'Bayern Munich', 3, 'Manchester United', 'Bayern Munich'),
  ('tpa-474', 3, 'Liverpool', 'Manchester City', 3, 'Liverpool', 'Manchester City'),
  ('tpa-475', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-476', null, null, null, 3, 'Bayern Munich', 'Real Betis'),
  ('tpa-477', null, null, null, 3, 'Real Madrid', 'PSG'),
  ('tpa-478', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-479', null, null, null, 3, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-480', 2, 'Borussia Dortmund', 'PSG', 2, 'Borussia Dortmund', 'PSG'),
  ('tpa-481', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-482', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-483', null, null, null, 3, 'Galatasaray', 'Sevilla'),
  ('tpa-484', null, null, null, 2, 'AC Milan', 'AC Milan'),
  ('tpa-485', null, null, null, 2, 'Barcelona', 'Chelsea'),
  ('tpa-486', null, null, null, 2, 'Chelsea', 'Juventus'),
  ('tpa-487', null, null, null, 2, 'Atlético Madrid', 'Barcelona'),
  ('tpa-488', null, null, null, 3, 'Juventus', 'Barcelona'),
  ('tpa-489', 4, 'Real Madrid', 'Manchester United', 3, 'Real Madrid', 'Manchester United'),
  ('tpa-490', 2, 'PSG', 'Inter Milan', 2, 'PSG', 'Inter Milan'),
  ('tpa-491', null, null, null, 3, 'Inter Milan', 'Chelsea'),
  ('tpa-492', null, null, null, 2, 'Juventus', 'Bayern Munich'),
  ('tpa-494', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-495', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-496', null, null, null, 2, 'Arsenal', 'PSG'),
  ('tpa-497', null, null, null, 2, 'Manchester City', 'Barcelona'),
  ('tpa-498', null, null, null, 2, 'PSG', 'PSG'),
  ('tpa-499', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-500', null, null, null, 2, 'Borussia Dortmund', 'Bayern Munich'),
  ('tpa-501', 3, 'Barcelona', 'Galatasaray', 3, 'Barcelona', 'Galatasaray'),
  ('tpa-502', null, null, null, 3, 'Juventus', 'Real Sociedad'),
  ('tpa-504', 3, 'Real Madrid', 'Barcelona', 3, 'Real Madrid', 'Barcelona'),
  ('tpa-505', null, null, null, 3, 'Arsenal', 'Chelsea'),
  ('tpa-506', null, null, null, 3, 'Real Sociedad', 'AC Milan'),
  ('tpa-507', null, null, null, 2, 'Galatasaray', 'Chelsea'),
  ('tpa-508', null, null, null, 3, 'Manchester United', 'PSG'),
  ('tpa-509', null, null, null, 3, 'Real Madrid', 'Sevilla'),
  ('tpa-510', null, null, null, 2, 'Chelsea', 'Chelsea'),
  ('tpa-511', null, null, null, 3, 'Bayern Munich', 'Atlético Madrid'),
  ('tpa-512', null, null, null, 2, 'Chelsea', 'Borussia Dortmund'),
  ('tpa-513', 3, 'Borussia Dortmund', 'PSV', 3, 'Inter Milan', 'Tottenham'),
  ('tpa-514', null, null, null, 2, 'Atlético Madrid', 'Barcelona'),
  ('tpa-515', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-516', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-517', 3, 'Bayern Munich', 'Chelsea', 3, 'Bayern Munich', 'Chelsea'),
  ('tpa-519', null, null, null, 2, 'Manchester City', 'AC Milan'),
  ('tpa-520', null, null, null, 3, 'Monaco', 'Real Sociedad'),
  ('tpa-521', null, null, null, 2, 'Real Madrid', 'Chelsea'),
  ('tpa-522', null, null, null, 2, 'Atlético Madrid', 'Bayern Munich'),
  ('tpa-523', 3, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-524', 2, 'Chelsea', 'Chelsea', 2, 'Chelsea', 'Chelsea'),
  ('tpa-525', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-526', null, null, null, 2, 'Manchester United', 'PSG'),
  ('tpa-527', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-528', null, null, null, 3, 'Arsenal', 'Real Betis'),
  ('tpa-529', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-530', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-531', null, null, null, 2, 'Barcelona', 'Atlético Madrid'),
  ('tpa-532', null, null, null, 2, 'Chelsea', 'AC Milan'),
  ('tpa-533', null, null, null, 2, 'Borussia Dortmund', 'Manchester City'),
  ('tpa-534', 2, 'Bayern Munich', 'Tottenham', 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-535', null, null, null, 3, 'Borussia Dortmund', 'Barcelona'),
  ('tpa-536', null, null, null, 3, 'Tottenham', 'Borussia Dortmund'),
  ('tpa-537', null, null, null, 2, 'Juventus', 'Manchester United'),
  ('tpa-538', null, null, null, 3, 'Arsenal', 'Bayern Munich'),
  ('tpa-539', null, null, null, 2, 'Chelsea', 'Arsenal'),
  ('tpa-540', null, null, null, 2, 'Atlético Madrid', 'Bayern Munich'),
  ('tpa-541', null, null, null, 3, 'Liverpool', 'Galatasaray'),
  ('tpa-542', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-543', null, null, null, 2, 'Real Madrid', 'Borussia Dortmund'),
  ('tpa-544', null, null, null, 3, 'Galatasaray', 'Barcelona'),
  ('tpa-545', 3, 'Manchester City', 'Barcelona', 2, 'Manchester City', 'Barcelona'),
  ('tpa-546', null, null, null, 3, 'Manchester City', 'Real Madrid'),
  ('tpa-547', null, null, null, 3, 'Liverpool', 'Chelsea'),
  ('tpa-548', 2, 'Manchester City', 'Bayern Munich', 2, 'Manchester City', 'Tottenham'),
  ('tpa-549', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-550', 3, 'Real Madrid', 'Arsenal', 3, 'PSG', 'Arsenal'),
  ('tpa-551', null, null, null, 2, 'PSG', 'Chelsea'),
  ('tpa-552', 3, 'Manchester United', 'Barcelona', 3, 'Manchester United', 'Barcelona'),
  ('tpa-553', null, null, null, 3, 'Liverpool', 'Tottenham'),
  ('tpa-554', null, null, null, 2, 'Juventus', 'Atlético Madrid'),
  ('tpa-555', null, null, null, 3, 'Chelsea', 'PSG'),
  ('tpa-556', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-557', null, null, null, 2, 'Porto', 'Liverpool'),
  ('tpa-559', null, null, null, 3, 'Manchester United', 'Arsenal'),
  ('tpa-560', null, null, null, 3, 'Real Madrid', 'Chelsea'),
  ('tpa-561', null, null, null, 2, 'AC Milan', 'Bayern Munich'),
  ('tpa-562', null, null, null, 3, 'Juventus', 'Real Madrid'),
  ('tpa-563', null, null, null, 3, 'West Ham', 'Napoli'),
  ('tpa-565', null, null, null, 2, 'Juventus', 'Atlético Madrid'),
  ('tpa-566', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-567', 3, 'PSG', 'Manchester City', 3, 'PSG', 'Manchester City'),
  ('tpa-568', 3, 'Barcelona', 'Real Madrid', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-569', null, null, null, 3, 'Barcelona', 'Chelsea'),
  ('tpa-570', 3, 'Bayern Munich', 'Manchester City', 2, 'Bayern Munich', 'Manchester City'),
  ('tpa-571', null, null, null, 3, 'Tottenham', 'Chelsea'),
  ('tpa-572', 3, 'Galatasaray', 'Liverpool', 3, 'Galatasaray', 'Southampton'),
  ('tpa-573', null, null, null, 3, 'Manchester United', 'Sevilla'),
  ('tpa-574', null, null, null, 2, 'Porto', 'Manchester United'),
  ('tpa-575', null, null, null, 2, 'Barcelona', 'Chelsea'),
  ('tpa-576', 3, 'Borussia Dortmund', 'Manchester United', 3, 'Real Madrid', 'Manchester United'),
  ('tpa-577', null, null, null, 2, 'Inter Milan', 'Borussia Dortmund'),
  ('tpa-578', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-579', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-580', 3, 'Brighton', 'Juventus', 3, 'Brighton', 'Juventus'),
  ('tpa-581', null, null, null, 2, 'Tottenham', 'Real Madrid'),
  ('tpa-582', null, null, null, 3, 'Napoli', 'Chelsea'),
  ('tpa-583', null, null, null, 2, 'Real Madrid', 'Manchester United'),
  ('tpa-584', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-585', 3, 'Real Madrid', 'Arsenal', 3, 'Real Madrid', 'Arsenal'),
  ('tpa-586', null, null, null, 2, 'Borussia Dortmund', 'Borussia Dortmund'),
  ('tpa-587', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-588', null, null, null, 3, 'Manchester United', 'Liverpool'),
  ('tpa-589', 2, 'Real Madrid', 'Benfica', 2, 'Real Madrid', 'Benfica'),
  ('tpa-590', 4, 'Real Madrid', 'Manchester United', 2, 'Real Madrid', 'Manchester United'),
  ('tpa-591', 3, 'Arsenal', 'Galatasaray', 3, 'West Ham', 'Galatasaray'),
  ('tpa-592', null, null, null, 2, 'Juventus', 'PSG'),
  ('tpa-593', null, null, null, 3, 'Tottenham', 'Borussia Dortmund'),
  ('tpa-594', null, null, null, 2, 'AC Milan', 'Barcelona'),
  ('tpa-595', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-596', null, null, null, 2, 'Manchester United', 'Juventus'),
  ('tpa-597', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-599', null, null, null, 2, 'AC Milan', 'Chelsea'),
  ('tpa-600', 4, 'Real Madrid', 'Barcelona', 3, 'Real Madrid', 'Barcelona'),
  ('tpa-601', 3, 'Chelsea', 'Manchester United', 3, 'Chelsea', 'Manchester United'),
  ('tpa-602', 2, 'Borussia Dortmund', 'Barcelona', 2, 'Chelsea', 'Barcelona'),
  ('tpa-603', null, null, null, 3, 'Borussia Dortmund', 'Barcelona'),
  ('tpa-604', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-606', 3, 'Atlético Madrid', 'Borussia Dortmund', 3, 'Barcelona', 'Real Madrid'),
  ('tpa-607', 3, 'Chelsea', 'Arsenal', 3, 'Chelsea', 'Arsenal'),
  ('tpa-608', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-609', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-610', 2, 'Monaco', 'Real Madrid', 2, 'Monaco', 'Real Madrid'),
  ('tpa-611', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-612', 2, 'Manchester United', 'Barcelona', 2, 'Manchester United', 'Barcelona'),
  ('tpa-613', null, null, null, 3, 'Real Madrid', 'Tottenham'),
  ('tpa-615', null, null, null, 3, 'Manchester United', 'Atlético Madrid'),
  ('tpa-616', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-617', null, null, null, 3, 'Real Madrid', 'Galatasaray'),
  ('tpa-618', null, null, null, 3, 'PSG', 'Liverpool'),
  ('tpa-619', null, null, null, 2, 'Liverpool', 'Real Madrid'),
  ('tpa-620', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-621', 3, 'PSG', 'Borussia Dortmund', 2, 'PSG', 'Borussia Dortmund'),
  ('tpa-622', 2, 'Tottenham', 'Real Madrid', 2, 'Tottenham', 'Real Madrid'),
  ('tpa-623', null, null, null, 3, 'Tottenham', 'Atlético Madrid'),
  ('tpa-624', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-625', null, null, null, 3, 'Arsenal', 'Manchester United'),
  ('tpa-626', null, null, null, 3, 'PSG', 'Tottenham'),
  ('tpa-627', null, null, null, 3, 'Brighton', 'Liverpool'),
  ('tpa-628', null, null, null, 3, 'PSG', 'Real Betis'),
  ('tpa-630', 2, 'Atlético Madrid', 'Real Madrid', 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-632', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-633', null, null, null, 2, 'Manchester City', 'Barcelona'),
  ('tpa-634', 2, 'Chelsea', 'Barcelona', 2, 'Chelsea', 'Barcelona'),
  ('tpa-635', null, null, null, 2, 'Manchester City', 'Chelsea'),
  ('tpa-636', 3, 'Bayern Munich', 'Real Madrid', 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-637', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-638', null, null, null, 3, 'Napoli', 'Bayern Munich'),
  ('tpa-639', 3, 'Liverpool', 'Barcelona', 2, 'Liverpool', 'Barcelona'),
  ('tpa-640', 3, 'Bayern Munich', 'Tottenham', 3, 'Bayern Munich', 'Tottenham'),
  ('tpa-641', null, null, null, 3, 'Liverpool', 'Real Madrid'),
  ('tpa-642', 3, 'Borussia Dortmund', 'Juventus', 2, 'Borussia Dortmund', 'Roma'),
  ('tpa-643', null, null, null, 2, 'Manchester City', 'Chelsea'),
  ('tpa-644', 2, 'Bayern Munich', 'Liverpool', 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-645', 4, 'Manchester City', 'Manchester United', 3, 'Manchester City', 'Manchester United'),
  ('tpa-646', 2, 'Real Madrid', 'Galatasaray', 2, 'Real Madrid', 'Galatasaray'),
  ('tpa-648', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-649', 3, 'Bayern Munich', 'Manchester City', 2, 'Bayern Munich', 'Manchester City'),
  ('tpa-650', null, null, null, 3, 'Chelsea', 'Real Betis'),
  ('tpa-651', 2, 'Real Madrid', 'Al-Ittihad', 2, 'Real Madrid', 'Chelsea'),
  ('tpa-653', null, null, null, 3, 'Napoli', 'Real Madrid'),
  ('tpa-654', null, null, null, 4, 'Newcastle', 'Sevilla'),
  ('tpa-655', 3, 'Benfica', 'Manchester City', 3, 'Real Madrid', 'Bayern Munich'),
  ('tpa-656', null, null, null, 3, 'Tottenham', 'PSG'),
  ('tpa-657', 4, 'Liverpool', 'Manchester United', 4, 'Liverpool', 'Manchester United'),
  ('tpa-658', null, null, null, 3, 'Manchester City', 'Bayer Leverkusen'),
  ('tpa-659', null, null, null, 3, 'Manchester United', 'Real Madrid'),
  ('tpa-660', null, null, null, 3, 'Real Betis', 'Bayern Munich'),
  ('tpa-661', 3, 'PSG', 'Galatasaray', 3, 'PSG', 'Galatasaray'),
  ('tpa-662', 2, 'Barcelona', 'Liverpool', 2, 'Barcelona', 'Liverpool'),
  ('tpa-663', null, null, null, 3, 'Real Madrid', 'Liverpool'),
  ('tpa-665', null, null, null, 2, 'Bayern Munich', 'Barcelona'),
  ('tpa-667', null, null, null, 2, 'Real Madrid', 'Manchester United'),
  ('tpa-668', null, null, null, 3, 'Liverpool', 'Manchester City'),
  ('tpa-669', 3, 'Real Madrid', 'Arsenal', 3, 'Real Madrid', 'Arsenal'),
  ('tpa-670', null, null, null, 3, 'Chelsea', 'Arsenal'),
  ('tpa-671', null, null, null, 3, 'PSG', 'Manchester United'),
  ('tpa-672', null, null, null, 2, 'Chelsea', 'Atlético Madrid'),
  ('tpa-673', 3, 'Real Madrid', 'Manchester City', 3, 'Real Madrid', 'Manchester City'),
  ('tpa-674', 2, 'Borussia Dortmund', 'Chelsea', 2, 'Borussia Dortmund', 'Chelsea'),
  ('tpa-675', null, null, null, 3, 'Real Madrid', 'Valencia'),
  ('tpa-676', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-677', 2, 'Chelsea', 'Manchester City', 2, 'Chelsea', 'Manchester City'),
  ('tpa-678', null, null, null, 3, 'Chelsea', 'Lyon'),
  ('tpa-679', null, null, null, 3, 'Real Madrid', 'Chelsea'),
  ('tpa-680', 3, 'Liverpool', 'AC Milan', 3, 'Liverpool', 'AC Milan'),
  ('tpa-682', 2, 'Liverpool', 'Real Madrid', 2, 'Liverpool', 'Real Madrid'),
  ('tpa-683', null, null, null, 2, 'Benfica', 'PSG'),
  ('tpa-685', null, null, null, 2, 'Juventus', 'Manchester United'),
  ('tpa-686', null, null, null, 2, 'Atlético Madrid', 'Real Madrid'),
  ('tpa-687', null, null, null, 3, 'Barcelona', 'Monaco'),
  ('tpa-688', 2, 'Manchester City', 'Chelsea', 2, 'Manchester City', 'Chelsea'),
  ('tpa-690', 2, 'Chelsea', 'Manchester United', 2, 'Chelsea', 'Manchester United'),
  ('tpa-691', null, null, null, 2, 'Borussia Dortmund', 'Barcelona'),
  ('tpa-692', null, null, null, 2, 'Inter Milan', 'Everton'),
  ('tpa-693', null, null, null, 2, 'Manchester City', 'Real Sociedad'),
  ('tpa-694', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-695', 4, 'PSG', 'PSV', 4, 'PSG', 'Tottenham'),
  ('tpa-696', 2, 'Manchester United', 'Juventus', 2, 'Manchester United', 'Juventus'),
  ('tpa-697', null, null, null, 2, 'AC Milan', 'Bayern Munich'),
  ('tpa-698', null, null, null, 3, 'Juventus', 'Manchester United'),
  ('tpa-699', null, null, null, 2, 'Chelsea', 'Barcelona'),
  ('tpa-700', null, null, null, 2, 'Manchester United', 'Manchester City'),
  ('tpa-701', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-702', 2, 'Barcelona', 'PSG', 2, 'Barcelona', 'PSG'),
  ('tpa-703', null, null, null, 2, 'Manchester City', 'Barcelona'),
  ('tpa-704', null, null, null, 3, 'Real Madrid', 'Tottenham'),
  ('tpa-705', null, null, null, 2, 'Manchester City', 'Manchester City'),
  ('tpa-706', null, null, null, 3, 'Barcelona', 'Arsenal'),
  ('tpa-707', 3, 'Real Madrid', 'AC Milan', 3, 'Real Madrid', 'AC Milan'),
  ('tpa-708', null, null, null, 3, 'Liverpool', 'Manchester United'),
  ('tpa-709', 2, 'Atlético Madrid', 'Manchester City', 2, 'Atlético Madrid', 'Chelsea'),
  ('tpa-711', null, null, null, 2, 'Barcelona', 'Bayern Munich'),
  ('tpa-712', null, null, null, 3, 'Barcelona', 'Atlético Madrid'),
  ('tpa-713', null, null, null, 3, 'Chelsea', 'Fiorentina'),
  ('tpa-714', null, null, null, 3, 'Barcelona', 'Barcelona'),
  ('tpa-715', null, null, null, 3, 'Manchester City', 'Manchester United'),
  ('tpa-716', null, null, null, 2, 'Liverpool', 'Bayern Munich'),
  ('tpa-717', null, null, null, 2, 'PSG', 'Manchester United'),
  ('tpa-718', null, null, null, 2, 'Real Sociedad', 'Real Madrid'),
  ('tpa-719', null, null, null, 2, 'Real Madrid', 'Chelsea'),
  ('tpa-720', null, null, null, 3, 'PSG', 'Barcelona'),
  ('tpa-721', null, null, null, 2, 'Chelsea', 'Manchester United'),
  ('tpa-722', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-723', null, null, null, 3, 'Napoli', 'Manchester United'),
  ('tpa-724', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-725', null, null, null, 2, 'Inter Milan', 'Barcelona'),
  ('tpa-726', 2, 'Borussia Dortmund', 'Bayern Munich', 2, 'Borussia Dortmund', 'Bayern Munich'),
  ('tpa-727', null, null, null, 3, 'Real Madrid', 'Chelsea'),
  ('tpa-728', null, null, null, 2, 'Juventus', 'Bayer Leverkusen'),
  ('tpa-729', null, null, null, 2, 'Manchester City', 'Liverpool'),
  ('tpa-730', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-731', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-733', null, null, null, 2, 'Liverpool', 'Manchester City'),
  ('tpa-734', null, null, null, 3, 'Juventus', 'Real Madrid'),
  ('tpa-735', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-736', 2, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-737', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-738', null, null, null, 3, 'Barcelona', 'Sevilla'),
  ('tpa-739', null, null, null, 4, 'Liverpool', 'Manchester United'),
  ('tpa-740', 3, 'Liverpool', 'Barcelona', 2, 'Liverpool', 'Barcelona'),
  ('tpa-741', null, null, null, 2, 'Barcelona', 'Chelsea'),
  ('tpa-742', 3, 'Inter Milan', 'AC Milan', 3, 'Inter Milan', 'AC Milan'),
  ('tpa-743', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-744', 2, 'Real Madrid', 'Galatasaray', 2, 'Real Madrid', 'Galatasaray'),
  ('tpa-745', null, null, null, 3, 'Borussia Dortmund', 'Arsenal'),
  ('tpa-746', null, null, null, 2, 'Arsenal', 'Real Madrid'),
  ('tpa-747', null, null, null, 2, 'Inter Milan', 'PSG'),
  ('tpa-748', null, null, null, 2, 'Arsenal', 'Chelsea'),
  ('tpa-749', 2, 'Bayern Munich', 'Manchester City', 2, 'Bayern Munich', 'Manchester City'),
  ('tpa-750', null, null, null, 3, 'Real Madrid', 'Liverpool'),
  ('tpa-751', null, null, null, 2, 'Atlético Madrid', 'Barcelona'),
  ('tpa-752', 2, 'Brighton', 'Liverpool', 2, 'Brighton', 'Liverpool'),
  ('tpa-753', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-754', null, null, null, 3, 'AC Milan', 'Liverpool'),
  ('tpa-755', 3, 'Bayern Munich', 'Brighton', 3, 'Tottenham', 'Arsenal'),
  ('tpa-756', null, null, null, 3, 'Manchester City', 'Galatasaray'),
  ('tpa-757', null, null, null, 3, 'PSG', 'Liverpool'),
  ('tpa-758', 2, 'Real Madrid', 'Liverpool', 2, 'Real Madrid', 'Liverpool'),
  ('tpa-759', null, null, null, 2, 'Barcelona', 'Sevilla'),
  ('tpa-760', 3, 'Bayern Munich', 'PSG', 3, 'Bayern Munich', 'AC Milan'),
  ('tpa-761', null, null, null, 2, 'Manchester City', 'Liverpool'),
  ('tpa-762', null, null, null, 2, 'Liverpool', 'Real Sociedad'),
  ('tpa-763', null, null, null, 2, 'Atlético Madrid', 'Manchester City'),
  ('tpa-764', null, null, null, 2, 'Bayern Munich', 'Chelsea'),
  ('tpa-765', null, null, null, 2, 'Barcelona', 'Juventus'),
  ('tpa-766', null, null, null, 3, 'Lyon', 'Manchester City'),
  ('tpa-767', null, null, null, 3, 'Real Madrid', 'Bayern Munich'),
  ('tpa-768', null, null, null, 2, 'Chelsea', 'Real Madrid'),
  ('tpa-769', null, null, null, 2, 'Real Sociedad', 'Real Madrid'),
  ('tpa-770', 3, 'Liverpool', 'Galatasaray', 3, 'Liverpool', 'Galatasaray'),
  ('tpa-771', null, null, null, 3, 'Real Sociedad', 'Liverpool'),
  ('tpa-772', null, null, null, 2, 'Barcelona', 'Atlético Madrid'),
  ('tpa-773', null, null, null, 3, 'Borussia Dortmund', 'Galatasaray'),
  ('tpa-774', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-775', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-776', null, null, null, 3, 'Bayern Munich', 'PSG'),
  ('tpa-777', 3, 'Chelsea', 'Liverpool', 3, 'Manchester United', 'Liverpool'),
  ('tpa-778', 4, 'Barcelona', 'PSV', 4, 'Barcelona', 'Tottenham'),
  ('tpa-779', 2, 'Liverpool', 'Real Madrid', 2, 'Liverpool', 'Real Madrid'),
  ('tpa-780', null, null, null, 3, 'Real Madrid', 'Borussia Dortmund'),
  ('tpa-781', null, null, null, 3, 'Real Madrid', 'Manchester United'),
  ('tpa-782', null, null, null, 3, 'Napoli', 'Bayern Munich'),
  ('tpa-783', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-784', 4, 'Barcelona', 'AC Milan', 3, 'Barcelona', 'AC Milan'),
  ('tpa-785', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-786', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-787', 4, 'Juventus', 'Barcelona', 4, 'Juventus', 'Barcelona'),
  ('tpa-788', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-789', null, null, null, 3, 'Chelsea', 'Tottenham'),
  ('tpa-790', null, null, null, 2, 'Manchester City', 'Liverpool'),
  ('tpa-791', 3, 'Bayern Munich', 'Chelsea', 3, 'Bayern Munich', 'Chelsea'),
  ('tpa-794', null, null, null, 3, 'Liverpool', 'PSG'),
  ('tpa-795', 2, 'Barcelona', 'Chelsea', 2, 'Atlético Madrid', 'Chelsea'),
  ('tpa-796', null, null, null, 2, 'Juventus', 'Chelsea'),
  ('tpa-797', null, null, null, 2, 'Manchester United', 'Chelsea'),
  ('tpa-798', null, null, null, 3, 'Atlético Madrid', 'Tottenham'),
  ('tpa-799', 3, 'Bayern Munich', 'Barcelona', 3, 'Bayern Munich', 'Barcelona'),
  ('tpa-800', null, null, null, 2, 'Napoli', 'Real Madrid'),
  ('tpa-801', null, null, null, 2, 'Barcelona', 'Barcelona'),
  ('tpa-802', null, null, null, 4, 'Chelsea', 'Lyon'),
  ('tpa-803', null, null, null, 3, 'Real Madrid', 'Chelsea'),
  ('tpa-804', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-806', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-807', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-808', 3, 'Juventus', 'PSG', 3, 'Juventus', 'Barcelona'),
  ('tpa-809', null, null, null, 3, 'Napoli', 'AC Milan'),
  ('tpa-810', null, null, null, 3, 'Juventus', 'Tottenham'),
  ('tpa-811', null, null, null, 4, 'Liverpool', 'Sevilla'),
  ('tpa-812', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-814', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-815', null, null, null, 2, 'Real Madrid', 'Real Betis'),
  ('tpa-816', 2, 'Bayern Munich', 'Barcelona', 2, 'Bayern Munich', 'Borussia Dortmund'),
  ('tpa-817', null, null, null, 2, 'Real Madrid', 'Real Betis'),
  ('tpa-818', null, null, null, 3, 'PSG', 'Bayern Munich'),
  ('tpa-819', null, null, null, 2, 'Chelsea', 'Manchester City'),
  ('tpa-820', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-821', null, null, null, 2, 'Real Sociedad', 'Real Madrid'),
  ('tpa-822', null, null, null, 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-823', null, null, null, 3, 'Borussia Dortmund', 'Tottenham'),
  ('tpa-824', 2, 'Bayern Munich', 'Liverpool', 2, 'Bayern Munich', 'Liverpool'),
  ('tpa-825', null, null, null, 3, 'Chelsea', 'Real Madrid'),
  ('tpa-826', null, null, null, 2, 'Manchester City', 'Borussia Dortmund'),
  ('tpa-827', 2, 'Al-Ittihad', 'Chelsea', 2, 'PSG', 'Chelsea'),
  ('tpa-828', 2, 'Real Sociedad', 'Real Madrid', 2, 'Real Sociedad', 'Real Madrid'),
  ('tpa-829', null, null, null, 3, 'Lyon', 'Napoli'),
  ('tpa-830', null, null, null, 3, 'Real Madrid', 'Bayern Munich'),
  ('tpa-831', null, null, null, 2, 'Chelsea', 'Leicester City'),
  ('tpa-833', null, null, null, 2, 'Manchester City', 'Chelsea'),
  ('tpa-835', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-836', 4, 'Brighton', 'PSG', 3, 'Arsenal', 'PSG'),
  ('tpa-837', 2, 'Manchester United', 'Borussia Dortmund', 2, 'Manchester United', 'Borussia Dortmund'),
  ('tpa-838', null, null, null, 2, 'Barcelona', 'Inter Milan'),
  ('tpa-839', 2, 'Manchester City', 'Chelsea', 2, 'Manchester City', 'Chelsea'),
  ('tpa-840', 2, 'Bayern Munich', 'Galatasaray', 2, 'Bayern Munich', 'Galatasaray'),
  ('tpa-841', null, null, null, 2, 'Liverpool', 'Juventus'),
  ('tpa-842', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-843', null, null, null, 3, 'Real Madrid', 'Manchester City'),
  ('tpa-844', 5, 'Juventus', 'Barcelona', 4, 'Juventus', 'Barcelona'),
  ('tpa-846', 3, 'Liverpool', 'AC Milan', 3, 'Liverpool', 'AC Milan'),
  ('tpa-847', null, null, null, 2, 'Tottenham', 'AC Milan'),
  ('tpa-848', null, null, null, 4, 'Napoli', 'Real Betis'),
  ('tpa-849', 4, 'Arsenal', 'Juventus', 4, 'Arsenal', 'Juventus'),
  ('tpa-850', null, null, null, 3, 'Real Sociedad', 'Manchester United'),
  ('tpa-851', 2, 'Benfica', 'Chelsea', 2, 'Benfica', 'Chelsea'),
  ('tpa-852', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-853', null, null, null, 2, 'Barcelona', 'PSG'),
  ('tpa-855', null, null, null, 3, 'Chelsea', 'Tottenham'),
  ('tpa-856', null, null, null, 2, 'Bayern Munich', 'Bayern Munich'),
  ('tpa-857', null, null, null, 2, 'Benfica', 'Real Madrid'),
  ('tpa-858', null, null, null, 3, 'Chelsea', 'Barcelona'),
  ('tpa-859', null, null, null, 2, 'Barcelona', 'PSG'),
  ('tpa-860', 2, 'Real Madrid', 'Manchester United', 2, 'Real Madrid', 'Manchester United'),
  ('tpa-861', null, null, null, 2, 'Barcelona', 'Liverpool'),
  ('tpa-862', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-863', 4, 'Manchester United', 'Real Madrid', 2, 'Manchester United', 'Real Madrid'),
  ('tpa-864', null, null, null, 2, 'Napoli', 'Real Madrid'),
  ('tpa-865', 2, 'Barcelona', 'Manchester United', 2, 'Barcelona', 'Manchester United'),
  ('tpa-866', 3, 'Juventus', 'Barcelona', 3, 'Fiorentina', 'Barcelona'),
  ('tpa-867', null, null, null, 3, 'Inter Milan', 'Liverpool'),
  ('tpa-868', null, null, null, 2, 'Real Madrid', 'Bayern Munich'),
  ('tpa-869', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-870', null, null, null, 2, 'Real Madrid', 'Inter Milan'),
  ('tpa-871', null, null, null, 2, 'Valencia', 'Galatasaray'),
  ('tpa-872', 3, 'Manchester United', 'Arsenal', 3, 'Manchester United', 'Arsenal'),
  ('tpa-873', 2, 'Liverpool', 'Juventus', 2, 'Liverpool', 'Juventus'),
  ('tpa-874', null, null, null, 2, 'Inter Milan', 'PSG'),
  ('tpa-875', null, null, null, 3, 'Borussia Dortmund', 'Manchester United'),
  ('tpa-876', 2, 'Liverpool', 'Liverpool', 2, 'Liverpool', 'Liverpool'),
  ('tpa-877', null, null, null, 3, 'Real Madrid', 'Ajax'),
  ('tpa-878', null, null, null, 2, 'Chelsea', 'Atlético Madrid'),
  ('tpa-879', null, null, null, 3, 'Arsenal', 'Tottenham'),
  ('tpa-880', 3, 'PSG', 'Chelsea', 3, 'PSG', 'Chelsea'),
  ('tpa-881', null, null, null, 2, 'Barcelona', 'Bayern Munich'),
  ('tpa-882', null, null, null, 2, 'PSG', 'Real Madrid'),
  ('tpa-883', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-884', 2, 'Borussia Dortmund', 'Real Madrid', 2, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-885', null, null, null, 3, 'Manchester City', 'Real Madrid'),
  ('tpa-886', null, null, null, 3, 'Juventus', 'Sevilla'),
  ('tpa-887', null, null, null, 2, 'Real Madrid', 'Inter Milan'),
  ('tpa-888', 3, 'Chelsea', 'AC Milan', 3, 'Chelsea', 'AC Milan'),
  ('tpa-889', null, null, null, 3, 'Real Madrid', 'Arsenal'),
  ('tpa-890', null, null, null, 3, 'Juventus', 'Napoli'),
  ('tpa-893', 2, 'Monaco', 'PSG', 2, 'Monaco', 'PSG'),
  ('tpa-894', null, null, null, 3, 'Liverpool', 'Borussia Dortmund'),
  ('tpa-895', null, null, null, 2, 'Chelsea', 'Liverpool'),
  ('tpa-896', null, null, null, 3, 'Porto', 'Napoli'),
  ('tpa-897', null, null, null, 3, 'Barcelona', 'Real Madrid'),
  ('tpa-898', null, null, null, 3, 'Chelsea', 'Chelsea'),
  ('tpa-899', null, null, null, 3, 'Napoli', 'Barcelona'),
  ('tpa-900', 4, 'Arsenal', 'Tottenham', 3, 'Arsenal', 'Tottenham'),
  ('tpa-901', 3, 'PSG', 'Barcelona', 2, 'PSG', 'Barcelona'),
  ('tpa-902', null, null, null, 2, 'Real Madrid', 'Real Madrid'),
  ('tpa-903', null, null, null, 4, 'Juventus', 'Real Sociedad'),
  ('tpa-905', null, null, null, 2, 'Juventus', 'Atlético Madrid'),
  ('tpa-906', null, null, null, 3, 'Inter Milan', 'Tottenham'),
  ('tpa-907', null, null, null, 3, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-908', null, null, null, 3, 'Arsenal', 'Atlético Madrid'),
  ('tpa-909', null, null, null, 2, 'Manchester United', 'Real Madrid'),
  ('tpa-910', null, null, null, 2, 'Bayern Munich', 'Real Madrid'),
  ('tpa-911', null, null, null, 2, 'PSG', 'Monaco'),
  ('tpa-912', 2, 'Manchester United', 'Barcelona', 2, 'Manchester United', 'Barcelona'),
  ('tpa-913', null, null, null, 3, 'Napoli', 'Real Madrid'),
  ('tpa-914', null, null, null, 2, 'AC Milan', 'Borussia Dortmund'),
  ('tpa-915', 2, 'Barcelona', 'PSG', 2, 'Barcelona', 'PSG'),
  ('tpa-916', 4, 'Juventus', 'Brighton', 4, 'Juventus', 'Brighton'),
  ('tpa-917', null, null, null, 3, 'Borussia Dortmund', 'Bayern Munich'),
  ('tpa-918', null, null, null, 3, 'Real Madrid', 'Manchester United'),
  ('tpa-919', null, null, null, 3, 'Galatasaray', 'Sevilla'),
  ('tpa-921', null, null, null, 3, 'Real Madrid', 'Juventus'),
  ('tpa-922', null, null, null, 3, 'Inter Milan', 'Manchester City'),
  ('tpa-923', null, null, null, 2, 'Liverpool', 'Barcelona'),
  ('tpa-924', null, null, null, 3, 'Liverpool', 'Manchester City'),
  ('tpa-926', null, null, null, 2, 'Real Madrid', 'PSG'),
  ('tpa-927', null, null, null, 2, 'Manchester City', 'Tottenham'),
  ('tpa-928', null, null, null, 2, 'PSG', 'Barcelona'),
  ('tpa-929', null, null, null, 2, 'Borussia Dortmund', 'Real Madrid'),
  ('tpa-930', null, null, null, 2, 'Bayern Munich', 'Fiorentina'),
  ('tpa-932', null, null, null, 2, 'Chelsea', 'Benfica'),
  ('tpa-933', null, null, null, 3, 'AC Milan', 'Manchester United'),
  ('tpa-935', null, null, null, 3, 'Benfica', 'Tottenham'),
  ('tpa-936', null, null, null, 2, 'Barcelona', 'Atlético Madrid'),
  ('tpa-937', null, null, null, 3, 'AC Milan', 'Arsenal'),
  ('tpa-938', null, null, null, 2, 'Lazio', 'Barcelona'),
  ('tpa-939', null, null, null, 2, 'Juventus', 'Real Madrid'),
  ('tpa-940', 3, 'Liverpool', 'Galatasaray', 3, 'Liverpool', 'Galatasaray'),
  ('tpa-941', null, null, null, 2, 'Juventus', 'Atlético Madrid'),
  ('tpa-942', null, null, null, 3, 'PSG', 'Real Betis'),
  ('tpa-943', null, null, null, 3, 'PSG', 'Bayern Munich'),
  ('tpa-944', 3, 'Liverpool', 'Real Madrid', 3, 'Liverpool', 'Real Madrid'),
  ('tpa-945', null, null, null, 3, 'Atlético Madrid', 'Juventus'),
  ('tpa-946', null, null, null, 2, 'Inter Milan', 'Juventus'),
  ('tpa-947', null, null, null, 4, 'Chelsea', 'PSV'),
  ('tpa-948', null, null, null, 2, 'Inter Milan', 'PSG'),
  ('tpa-949', null, null, null, 3, 'Real Madrid', 'Real Betis'),
  ('tpa-950', 3, 'PSG', 'Borussia Dortmund', 2, 'PSG', 'Barcelona'),
  ('tpa-952', null, null, null, 3, 'Chelsea', 'Arsenal'),
  ('tpa-953', null, null, null, 2, 'Real Madrid', 'Monaco'),
  ('tpa-954', null, null, null, 3, 'Barcelona', 'Manchester City'),
  ('tpa-955', null, null, null, 3, 'Napoli', 'Barcelona'),
  ('tpa-956', 3, 'Real Madrid', 'Barcelona', 3, 'Real Madrid', 'Barcelona'),
  ('tpa-957', null, null, null, 2, 'Chelsea', 'Arsenal'),
  ('tpa-958', null, null, null, 3, 'PSG', 'Juventus'),
  ('tpa-959', null, null, null, 2, 'Real Madrid', 'Real Madrid'),
  ('tpa-960', null, null, null, 3, 'Real Madrid', 'Barcelona'),
  ('tpa-961', null, null, null, 3, 'Bayern Munich', 'Arsenal'),
  ('tpa-962', null, null, null, 2, 'Juventus', 'Manchester City'),
  ('tpa-963', null, null, null, 2, 'Liverpool', 'Juventus'),
  ('tpa-964', 2, 'Real Madrid', 'Tottenham', 2, 'Real Madrid', 'Tottenham'),
  ('tpa-965', null, null, null, 2, 'Atlético Madrid', 'Chelsea'),
  ('tpa-966', 2, 'Arsenal', 'Aston Villa', 2, 'Arsenal', 'Aston Villa'),
  ('tpa-967', 3, 'Manchester City', 'Bayern Munich', 2, 'Manchester City', 'Tottenham'),
  ('tpa-968', 3, 'Bayern Munich', 'PSG', 3, 'Tottenham', 'PSG'),
  ('tpa-969', null, null, null, 3, 'Real Madrid', 'Real Sociedad')
)
update public.transfer_path_puzzles t set
  active_min_steps = v.a_min::smallint,
  active_hint =
    case
      when v.a_min is null then null
      when v.a_min = 1 then 'Direct link. They were at ' || v.a_first || ' together.'
      when v.a_min = 2 and v.a_first = v.a_last then 'One middle man does it. He was at ' || v.a_first || ' with ' || t.player_a || ' and, in another season, at ' || v.a_last || ' with ' || t.player_b || '.'
      when v.a_min = 2 then 'One middle man does it. He was at ' || v.a_first || ' with ' || t.player_a || ' and at ' || v.a_last || ' with ' || t.player_b || '.'
      else (case v.a_min when 3 then 'Two' when 4 then 'Three' when 5 then 'Four' else (v.a_min - 1)::text end) || ' middle men at least. The first was at ' || v.a_first || ' with ' || t.player_a || '; the last was at ' || v.a_last || ' with ' || t.player_b || '.'
    end,
  europe_min_steps = v.e_min::smallint,
  europe_hint =
    case
      when v.e_min is null then null
      when v.e_min = 1 then 'Direct link. They were at ' || v.e_first || ' together.'
      when v.e_min = 2 and v.e_first = v.e_last then 'One middle man does it. He was at ' || v.e_first || ' with ' || t.player_a || ' and, in another season, at ' || v.e_last || ' with ' || t.player_b || '.'
      when v.e_min = 2 then 'One middle man does it. He was at ' || v.e_first || ' with ' || t.player_a || ' and at ' || v.e_last || ' with ' || t.player_b || '.'
      else (case v.e_min when 3 then 'Two' when 4 then 'Three' when 5 then 'Four' else (v.e_min - 1)::text end) || ' middle men at least. The first was at ' || v.e_first || ' with ' || t.player_a || '; the last was at ' || v.e_last || ' with ' || t.player_b || '.'
    end
from v
where t.puzzle_id = v.puzzle_id;
commit;
