// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded on purpose. The Lovable build injects VITE_ env vars that point at a
// DELETED Supabase project (pzzadswiradjnvvfybol), which made every request fail
// with "Failed to fetch". Live data is in flawuiqbvjobmkfkauhw, so we pin it here
// and ignore env vars entirely. This is safe to ship in the client bundle: the anon
// key is public by design and every table is protected by row-level security.
export const SUPABASE_URL = "https://flawuiqbvjobmkfkauhw.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsYXd1aXFidmpvYm1rZmthdWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4NTUwNzYsImV4cCI6MjA5MTQzMTA3Nn0.L8xWIXikPIaXC0XOL-FLOuPQb6idws2NdliARxBgk_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// This is the SDK's existing default key, so current sessions keep their identity.
const AUTH_STORAGE_KEY = `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`;

function canReadAuthStorage(): boolean {
  try {
    localStorage.getItem(AUTH_STORAGE_KEY);
    return true;
  } catch {
    return false;
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Also check the session key in case only that key is blocked.
    storageKey: AUTH_STORAGE_KEY,
    persistSession: canReadAuthStorage(),
    autoRefreshToken: true,
  }
});
