// AUTO-GENERATED by scripts/genClubManagerFreeAgents.mjs (Round 1033). DO NOT EDIT BY HAND.
// Real footballers who were without a club on 2026-10-06, each on two
// independent sources recorded in scripts/data/cmFreeAgents2026.json, which
// also says why every other 'Without Club' row of the 2026 table is not here.
// Ages and values are the table's; ratings and values use the roster bake's
// own curves. A modern career opens with these men in its free agent pool,
// once, on day one of season one.
import type { Position } from '@/types/game';

export interface RealFreeAgent {
  name: string;
  position: Position;
  /** Age in August 2026, as the table records it. */
  age: number;
  /** Market value in pounds, millions. */
  value: number;
  /** Game rating off the value curve the squads use. */
  rating: number;
}

export const CM_REAL_FREE_AGENTS_CHECKED_ON = '2026-10-06';

export const CM_REAL_FREE_AGENTS: RealFreeAgent[] = [
  { name: 'Dani Parejo', position: 'CM', age: 37, value: 0.8, rating: 65 },
  { name: 'Dele Alli', position: 'CAM', age: 30, value: 0.8, rating: 65 },
  { name: 'Sergio Ramos', position: 'CB', age: 40, value: 0.7, rating: 63 },
  { name: 'Edinson Cavani', position: 'ST', age: 39, value: 0.4, rating: 60 },
  { name: 'Tiemoué Bakayoko', position: 'CDM', age: 32, value: 0.4, rating: 60 },
  { name: 'Wissam Ben Yedder', position: 'ST', age: 36, value: 0.4, rating: 60 },
  { name: 'Willian', position: 'LW', age: 38, value: 0.3, rating: 59 },
];
