// GENERATED by scripts/genConquestSoccer.mjs (Round 358). Do not hand edit:
// simConquestSoccer re-derives every value here from the sources below and fails
// if this file disagrees. Change the generator, re-run it, run the harness.
//
// Sources: FALLBACK_CLUBS (soccerCareerEngine), STRENGTH_PRIORS (clubManager),
// GEO_COUNTRIES (worldMapGeo). One club per country, because the territory unit
// is the country. The field is apportioned across continents by largest
// remainder (africa 9, asia 10, europe 7, namerica 3, samerica 3) rather than taken as the 32 best clubs, which would
// have put 18 in Europe and handed one African club 30 countries at kickoff.
// Every other country belongs to the nearest contestant on its own continent by
// projected distance, which is the NHL map's nearest-arena rule with the arena
// swapped for a home country.
//
// Ratings are simulation strengths, not stat claims. No crests, no kits, no
// player names: club name, country and colour only.
//
// COLOUR: `color` is a DERIVED map palette, not the club's real colour, and it
// is used everywhere in this game so nothing ever shows a club in two different
// colours. The real colours collide badly on a map (two African clubs both on
// #D6202B, three more sharing #FBC403, 65 pairs within 40 in RGB), which makes
// ownership unreadable, so the field is spread around the hue wheel in the order
// of its true hues. Measured minimum pairwise distance: 35.8.
// The club's real colour is kept on every row as `sourceColor`.

export interface SoccerClub {
  id: string;
  name: string;
  country: string;
  iso: string;          // its home territory on the world basemap
  continent: string;
  /** derived map palette, mutually distinguishable; see the note above */
  color: string;
  /** the club's real colour, recorded for provenance */
  sourceColor: string;
  overall: number;
}

export const SOCCER_CLUBS: SoccerClub[] = [
  { id: 'fb-1', name: "Real Madrid", country: "Spain", iso: 'es', continent: 'europe', color: '#6EB814', sourceColor: '#FEBE10', overall: 88 },
  { id: 'fb-6', name: "PSG", country: "France", iso: 'fr', continent: 'europe', color: '#51D6EC', sourceColor: '#004170', overall: 87 },
  { id: 'fb-5', name: "Bayern Munich", country: "Germany", iso: 'de', continent: 'europe', color: '#B351EC', sourceColor: '#DC052D', overall: 87 },
  { id: 'fb-15', name: "Boca Juniors", country: "Argentina", iso: 'ar', continent: 'samerica', color: '#5162EC', sourceColor: '#003DA5', overall: 86 },
  { id: 'fb-17', name: "Flamengo", country: "Brazil", iso: 'br', continent: 'samerica', color: '#9B14B8', sourceColor: '#C8102E', overall: 86 },
  { id: 'fb-10', name: "Arsenal", country: "England", iso: 'gb', continent: 'europe', color: '#ECA051', sourceColor: '#EF0107', overall: 86 },
  { id: 'fb-12', name: "Ajax", country: "Netherlands", iso: 'nl', continent: 'europe', color: '#EC51EA', sourceColor: '#D2122E', overall: 86 },
  { id: 'fb-13', name: "Benfica", country: "Portugal", iso: 'pt', continent: 'europe', color: '#EC6651', sourceColor: '#E30613', overall: 86 },
  { id: 'fb-8', name: "Inter Milan", country: "Italy", iso: 'it', continent: 'europe', color: '#14B8AF', sourceColor: '#0068A8', overall: 85 },
  { id: 'fb-87', name: "Monterrey", country: "Mexico", iso: 'mx', continent: 'namerica', color: '#1C80B0', sourceColor: '#0A2240', overall: 79 },
  { id: 'fb-35', name: "Al Hilal", country: "Saudi Arabia", iso: 'sa', continent: 'asia', color: '#2114B8', sourceColor: '#003DA5', overall: 79 },
  { id: 'fb-33', name: "Fenerbahce", country: "Turkey", iso: 'tr', continent: 'asia', color: '#519CEB', sourceColor: '#0A2C59', overall: 79 },
  { id: 'fb-40', name: "Inter Miami", country: "USA", iso: 'us', continent: 'namerica', color: '#7951EC', sourceColor: '#F7B5CD', overall: 79 },
  { id: 'fb-120', name: "Toronto FC", country: "Canada", iso: 'ca', continent: 'namerica', color: '#5E14B8', sourceColor: '#B81137', overall: 74 },
  { id: 'fb-115', name: "Shanghai Port", country: "China", iso: 'cn', continent: 'asia', color: '#E656AE', sourceColor: '#D6202B', overall: 74 },
  { id: 'fb-109', name: "Atletico Nacional", country: "Colombia", iso: 'co', continent: 'samerica', color: '#14B835', sourceColor: '#00A650', overall: 74 },
  { id: 'fb-116', name: "Zamalek", country: "Egypt", iso: 'eg', continent: 'africa', color: '#DDCF5F', sourceColor: '#FFFFFF', overall: 74 },
  { id: 'fb-114', name: "Persepolis", country: "Iran", iso: 'ir', continent: 'asia', color: '#B11B93', sourceColor: '#D6202B', overall: 74 },
  { id: 'fb-111', name: "Kawasaki Frontale", country: "Japan", iso: 'jp', continent: 'asia', color: '#51ECC7', sourceColor: '#009FE8', overall: 74 },
  { id: 'fb-117', name: "Wydad Casablanca", country: "Morocco", iso: 'ma', continent: 'africa', color: '#B11B5B', sourceColor: '#D6202B', overall: 74 },
  { id: 'fb-113', name: "Al Sadd", country: "Qatar", iso: 'qa', continent: 'asia', color: '#A88124', sourceColor: '#2B2B2B', overall: 74 },
  { id: 'fb-119', name: "Mamelodi Sundowns", country: "South Africa", iso: 'za', continent: 'africa', color: '#89EC51', sourceColor: '#FBC403', overall: 74 },
  { id: 'fb-112', name: "Jeonbuk Motors", country: "South Korea", iso: 'kr', continent: 'asia', color: '#15B772', sourceColor: '#0C6B3E', overall: 74 },
  { id: 'fb-118', name: "Esperance", country: "Tunisia", iso: 'tn', continent: 'africa', color: '#B84914', sourceColor: '#BC0C12', overall: 74 },
  { id: 'fb-151', name: "Atletico Petroleos", country: "Angola", iso: 'ao', continent: 'africa', color: '#51EC53', sourceColor: '#FBC403', overall: 69 },
  { id: 'fb-131', name: "Pyunik", country: "Armenia", iso: 'am', continent: 'asia', color: '#E65678', sourceColor: '#D6202B', overall: 69 },
  { id: 'fb-140', name: "Melbourne Victory", country: "Australia", iso: 'au', continent: 'asia', color: '#1847B4', sourceColor: '#0C2E5C', overall: 69 },
  { id: 'fb-132', name: "Qarabag", country: "Azerbaijan", iso: 'az', continent: 'asia', color: '#9EA824', sourceColor: '#2B2B2B', overall: 69 },
  { id: 'fb-144', name: "TP Mazembe", country: "DR Congo", iso: 'cd', continent: 'africa', color: '#BCDD5F', sourceColor: '#2B2B2B', overall: 69 },
  { id: 'fb-149', name: "Saint George", country: "Ethiopia", iso: 'et', continent: 'africa', color: '#31B814', sourceColor: '#FBC403', overall: 69 },
  { id: 'fb-146', name: "Asante Kotoko", country: "Ghana", iso: 'gh', continent: 'africa', color: '#B11B22', sourceColor: '#D6202B', overall: 69 },
  { id: 'fb-147', name: "Gor Mahia", country: "Kenya", iso: 'ke', continent: 'africa', color: '#51EC8D', sourceColor: '#00954C', overall: 69 },
];

export const SOCCER_CLUB_MAP = new Map(SOCCER_CLUBS.map(c => [c.id, c]));

/** Every one of the basemap's countries, owned at kickoff. */
export const INITIAL_TERRITORIES_SOCCER: Record<string, string> = {
  // africa
  ao: 'fb-151', bf: 'fb-146', bi: 'fb-144', bj: 'fb-146', bw: 'fb-119', cd: 'fb-144',
  cf: 'fb-144', cg: 'fb-144', ci: 'fb-146', cm: 'fb-146', dj: 'fb-149', dz: 'fb-118',
  eg: 'fb-116', eh: 'fb-117', er: 'fb-149', et: 'fb-149', ga: 'fb-144', gh: 'fb-146',
  gm: 'fb-146', gn: 'fb-146', gq: 'fb-144', gw: 'fb-146', ke: 'fb-147', lr: 'fb-146',
  ls: 'fb-119', ly: 'fb-118', ma: 'fb-117', mg: 'fb-147', ml: 'fb-146', mr: 'fb-117',
  mw: 'fb-147', mz: 'fb-119', na: 'fb-119', ne: 'fb-146', ng: 'fb-146', rw: 'fb-147',
  sd: 'fb-149', sl: 'fb-146', sn: 'fb-146', so: 'fb-149', ss: 'fb-149', sz: 'fb-119',
  td: 'fb-116', tg: 'fb-146', tn: 'fb-118', tz: 'fb-147', ug: 'fb-147', za: 'fb-119',
  zm: 'fb-151', zw: 'fb-119',
  // asia
  ae: 'fb-113', af: 'fb-114', am: 'fb-131', au: 'fb-140', az: 'fb-132', bd: 'fb-115',
  bn: 'fb-140', bt: 'fb-115', cn: 'fb-115', fj: 'fb-35', ge: 'fb-131', id: 'fb-140',
  il: 'fb-33', in: 'fb-115', iq: 'fb-131', ir: 'fb-114', jo: 'fb-33', jp: 'fb-111',
  kg: 'fb-114', kh: 'fb-115', kp: 'fb-112', kr: 'fb-112', kw: 'fb-113', kz: 'fb-132',
  la: 'fb-115', lb: 'fb-33', lk: 'fb-115', mm: 'fb-115', mn: 'fb-115', my: 'fb-140',
  nc: 'fb-140', np: 'fb-115', nz: 'fb-140', om: 'fb-113', pg: 'fb-140', ph: 'fb-112',
  pk: 'fb-114', ps: 'fb-33', qa: 'fb-113', sa: 'fb-35', sb: 'fb-140', sy: 'fb-33',
  th: 'fb-115', tj: 'fb-114', tl: 'fb-140', tm: 'fb-114', tr: 'fb-33', tw: 'fb-112',
  uz: 'fb-114', vn: 'fb-115', vu: 'fb-140', ye: 'fb-35',
  // europe
  al: 'fb-8', at: 'fb-5', ba: 'fb-8', be: 'fb-12', bg: 'fb-8', by: 'fb-5',
  ch: 'fb-5', cy: 'fb-8', cz: 'fb-5', de: 'fb-5', dk: 'fb-12', ee: 'fb-5',
  es: 'fb-1', fi: 'fb-5', fr: 'fb-6', gb: 'fb-10', gr: 'fb-8', hr: 'fb-8',
  hu: 'fb-8', ie: 'fb-10', is: 'fb-10', it: 'fb-8', lt: 'fb-5', lu: 'fb-12',
  lv: 'fb-5', md: 'fb-8', me: 'fb-8', mk: 'fb-8', nl: 'fb-12', no: 'fb-5',
  pl: 'fb-5', pt: 'fb-13', ro: 'fb-8', rs: 'fb-8', ru: 'fb-10', se: 'fb-5',
  si: 'fb-8', sk: 'fb-5', ua: 'fb-8', xk: 'fb-8',
  // namerica
  bs: 'fb-40', bz: 'fb-87', ca: 'fb-120', cr: 'fb-87', cu: 'fb-87', do: 'fb-40',
  gl: 'fb-120', gt: 'fb-87', hn: 'fb-87', ht: 'fb-40', jm: 'fb-87', mx: 'fb-87',
  ni: 'fb-87', pa: 'fb-87', pr: 'fb-40', sv: 'fb-87', tt: 'fb-87', us: 'fb-40',
  // samerica
  ar: 'fb-15', bo: 'fb-17', br: 'fb-17', cl: 'fb-15', co: 'fb-109', ec: 'fb-109',
  fk: 'fb-15', gy: 'fb-109', pe: 'fb-109', py: 'fb-17', sr: 'fb-109', uy: 'fb-15',
  ve: 'fb-109',
};
