// Generated by scripts/genNbaOpeningRatings.mjs. Simulation grades and prices, not historical facts.
// Partial box-score defense and unchanged seed positions; prior-only and unmeasured rows stay distinct.
export interface NbaOpeningRatingEvidence {
  modelVersion: string;
  originKey: string;
  openingOvr: number;
  basis: 'box-score-proxy' | 'prior-only' | 'unmeasured-prior';
  partial: true;
}
export interface NbaOpeningRating { ovr: number; salary: number; evidence: NbaOpeningRatingEvidence }
export const NBA_OPENING_RATING_VERSION = "nba894-review-v0.4";
export const NBA_OPENING_RATING_WINDOW = "2024-25 and 2025-26 regular seasons";
export const NBA_OPENING_RATINGS: Record<string, Record<string, NbaOpeningRating>> = {
  "DEN": {
    "Nikola Jokic|C": {
      "ovr": 94,
      "salary": 56.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Nikola Jokic|C",
        "openingOvr": 94,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Aaron Gordon|F": {
      "ovr": 86,
      "salary": 37.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Aaron Gordon|F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Cameron Johnson|F": {
      "ovr": 84,
      "salary": 33.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Cameron Johnson|F",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bruce Brown|G": {
      "ovr": 73,
      "salary": 7.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Bruce Brown|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Zeke Nnaji|F-C": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Zeke Nnaji|F-C",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Christian Braun|G": {
      "ovr": 80,
      "salary": 23.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Christian Braun|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Peyton Watson|G": {
      "ovr": 77,
      "salary": 16.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Peyton Watson|G",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Julian Strawther|G": {
      "ovr": 73,
      "salary": 7.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Julian Strawther|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jonas Valanciunas|C": {
      "ovr": 84,
      "salary": 33.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Jonas Valanciunas|C",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jamal Murray|G": {
      "ovr": 91,
      "salary": 49.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DEN|Jamal Murray|G",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "OKC": {
    "Shai Gilgeous-Alexander|G": {
      "ovr": 93,
      "salary": 53.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Shai Gilgeous-Alexander|G",
        "openingOvr": 93,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Chet Holmgren|C-F": {
      "ovr": 87,
      "salary": 39.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Chet Holmgren|C-F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Isaiah Joe|G": {
      "ovr": 80,
      "salary": 23.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Isaiah Joe|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jared McCain|G": {
      "ovr": 76,
      "salary": 13.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Jared McCain|G",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jalen Williams|F": {
      "ovr": 87,
      "salary": 39.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Jalen Williams|F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Cason Wallace|G": {
      "ovr": 75,
      "salary": 11.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Cason Wallace|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Isaiah Hartenstein|C": {
      "ovr": 84,
      "salary": 32.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Isaiah Hartenstein|C",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Luguentz Dort|G-F": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Luguentz Dort|G-F",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaylin Williams|F-C": {
      "ovr": 80,
      "salary": 23.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Jaylin Williams|F-C",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ajay Mitchell|G": {
      "ovr": 81,
      "salary": 25.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "OKC|Ajay Mitchell|G",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "BOS": {
    "Jayson Tatum|F": {
      "ovr": 89,
      "salary": 36.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Jayson Tatum|F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Paul George|F": {
      "ovr": 86,
      "salary": 30.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Paul George|F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Neemias Queta|C": {
      "ovr": 81,
      "salary": 21.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Neemias Queta|C",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Derrick White|G": {
      "ovr": 89,
      "salary": 36.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Derrick White|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Payton Pritchard|G": {
      "ovr": 89,
      "salary": 36.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Payton Pritchard|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Baylor Scheierman|G": {
      "ovr": 73,
      "salary": 6.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Baylor Scheierman|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jordan Walsh|G": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Jordan Walsh|G",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Nikola Vucevic|C": {
      "ovr": 88,
      "salary": 34.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Nikola Vucevic|C",
        "openingOvr": 88,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Luka Garza|C": {
      "ovr": 79,
      "salary": 17.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Luka Garza|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Sam Hauser|F": {
      "ovr": 77,
      "salary": 13.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BOS|Sam Hauser|F",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "NYK": {
    "Jalen Brunson|G": {
      "ovr": 89,
      "salary": 40.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Jalen Brunson|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Karl-Anthony Towns|C": {
      "ovr": 91,
      "salary": 44.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Karl-Anthony Towns|C",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Mikal Bridges|F": {
      "ovr": 84,
      "salary": 29.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Mikal Bridges|F",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "OG Anunoby|F": {
      "ovr": 85,
      "salary": 32,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|OG Anunoby|F",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Josh Hart|G": {
      "ovr": 87,
      "salary": 36.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Josh Hart|G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Miles McBride|G": {
      "ovr": 79,
      "salary": 19.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Miles McBride|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Mitchell Robinson|C": {
      "ovr": 76,
      "salary": 12.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Mitchell Robinson|C",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Landry Shamet|G": {
      "ovr": 73,
      "salary": 6.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Landry Shamet|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Pacome Dadiet|F": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Pacome Dadiet|F",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jose Alvarado|G": {
      "ovr": 79,
      "salary": 19.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NYK|Jose Alvarado|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "LAL": {
    "Luka Doncic|F-G": {
      "ovr": 94,
      "salary": 50.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Luka Doncic|F-G",
        "openingOvr": 94,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Marcus Smart|G": {
      "ovr": 76,
      "salary": 12.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Marcus Smart|G",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Austin Reaves|G": {
      "ovr": 91,
      "salary": 44.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Austin Reaves|G",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Deandre Ayton|C": {
      "ovr": 82,
      "salary": 25.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Deandre Ayton|C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jake LaRavia|F": {
      "ovr": 74,
      "salary": 8.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Jake LaRavia|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Luke Kennard|G": {
      "ovr": 80,
      "salary": 21.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Luke Kennard|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jarred Vanderbilt|F": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Jarred Vanderbilt|F",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaxson Hayes|C": {
      "ovr": 79,
      "salary": 19.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Jaxson Hayes|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dalton Knecht|G-F": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Dalton Knecht|G-F",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Maxi Kleber|F-C": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAL|Maxi Kleber|F-C",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "MIL": {
    "Giannis Antetokounmpo|F": {
      "ovr": 91,
      "salary": 57.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Giannis Antetokounmpo|F",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Myles Turner|C-F": {
      "ovr": 81,
      "salary": 30,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Myles Turner|C-F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jericho Sims|F": {
      "ovr": 72,
      "salary": 5.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Jericho Sims|F",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kevin Porter Jr.|G": {
      "ovr": 86,
      "salary": 43.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Kevin Porter Jr.|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "AJ Green|G": {
      "ovr": 75,
      "salary": 13.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|AJ Green|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Gary Trent Jr.|G": {
      "ovr": 71,
      "salary": 2.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Gary Trent Jr.|G",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bobby Portis|F": {
      "ovr": 72,
      "salary": 5.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Bobby Portis|F",
        "openingOvr": 72,
        "basis": "unmeasured-prior",
        "partial": true
      }
    },
    "Andre Jackson Jr.|G-F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Andre Jackson Jr.|G-F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kyle Kuzma|F": {
      "ovr": 79,
      "salary": 24.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Kyle Kuzma|F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ousmane Dieng|F": {
      "ovr": 72,
      "salary": 5.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIL|Ousmane Dieng|F",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "MIN": {
    "Anthony Edwards|G": {
      "ovr": 93,
      "salary": 42,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Anthony Edwards|G",
        "openingOvr": 93,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Julius Randle|F": {
      "ovr": 89,
      "salary": 34.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Julius Randle|F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Donte DiVincenzo|G": {
      "ovr": 84,
      "salary": 25.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Donte DiVincenzo|G",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Rudy Gobert|C": {
      "ovr": 82,
      "salary": 22.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Rudy Gobert|C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaden McDaniels|F": {
      "ovr": 81,
      "salary": 20.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Jaden McDaniels|F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Naz Reid|C-F": {
      "ovr": 83,
      "salary": 23.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Naz Reid|C-F",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ayo Dosunmu|G": {
      "ovr": 85,
      "salary": 27.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Ayo Dosunmu|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Joan Beringer|C": {
      "ovr": 75,
      "salary": 9.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Joan Beringer|C",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Terrence Shannon Jr.|G": {
      "ovr": 72,
      "salary": 4.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Terrence Shannon Jr.|G",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Julian Phillips|F": {
      "ovr": 68,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIN|Julian Phillips|F",
        "openingOvr": 68,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "HOU": {
    "Kevin Durant|F": {
      "ovr": 92,
      "salary": 52.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Kevin Durant|F",
        "openingOvr": 92,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Alperen Sengun|F-C": {
      "ovr": 89,
      "salary": 45.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Alperen Sengun|F-C",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Clint Capela|C": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Clint Capela|C",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Amen Thompson|G-F": {
      "ovr": 87,
      "salary": 40.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Amen Thompson|G-F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Fred VanVleet|G": {
      "ovr": 78,
      "salary": 19,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Fred VanVleet|G",
        "openingOvr": 78,
        "basis": "prior-only",
        "partial": true
      }
    },
    "Josh Okogie|G-F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Josh Okogie|G-F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tari Eason|F": {
      "ovr": 75,
      "salary": 11.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Tari Eason|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Steven Adams|C": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Steven Adams|C",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Reed Sheppard|G": {
      "ovr": 82,
      "salary": 28.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Reed Sheppard|G",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jabari Smith Jr.|F": {
      "ovr": 77,
      "salary": 16.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "HOU|Jabari Smith Jr.|F",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "CLE": {
    "Donovan Mitchell|G": {
      "ovr": 92,
      "salary": 37.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Donovan Mitchell|G",
        "openingOvr": 92,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dennis Schroder|G": {
      "ovr": 80,
      "salary": 17.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Dennis Schroder|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Evan Mobley|F-C": {
      "ovr": 90,
      "salary": 34.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Evan Mobley|F-C",
        "openingOvr": 90,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "James Harden|G": {
      "ovr": 92,
      "salary": 37.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|James Harden|G",
        "openingOvr": 92,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jarrett Allen|C": {
      "ovr": 87,
      "salary": 29.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Jarrett Allen|C",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Max Strus|G-F": {
      "ovr": 79,
      "salary": 15.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Max Strus|G-F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dean Wade|F": {
      "ovr": 73,
      "salary": 5.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Dean Wade|F",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Keon Ellis|G": {
      "ovr": 72,
      "salary": 3.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Keon Ellis|G",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Sam Merrill|G": {
      "ovr": 80,
      "salary": 17.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Sam Merrill|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Craig Porter Jr.|G": {
      "ovr": 75,
      "salary": 9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CLE|Craig Porter Jr.|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "IND": {
    "Tyrese Haliburton|G": {
      "ovr": 83,
      "salary": 24,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Tyrese Haliburton|G",
        "openingOvr": 83,
        "basis": "prior-only",
        "partial": true
      }
    },
    "Andrew Nembhard|G-F": {
      "ovr": 84,
      "salary": 25.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Andrew Nembhard|G-F",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Obi Toppin|F": {
      "ovr": 83,
      "salary": 24,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Obi Toppin|F",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Pascal Siakam|F": {
      "ovr": 89,
      "salary": 34.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Pascal Siakam|F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ivica Zubac|C": {
      "ovr": 85,
      "salary": 27.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Ivica Zubac|C",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jay Huff|C": {
      "ovr": 81,
      "salary": 20.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Jay Huff|C",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Aaron Nesmith|F": {
      "ovr": 77,
      "salary": 13.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Aaron Nesmith|F",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "T.J. McConnell|G": {
      "ovr": 82,
      "salary": 22.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|T.J. McConnell|G",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jarace Walker|F": {
      "ovr": 77,
      "salary": 13.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Jarace Walker|F",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ben Sheppard|G-F": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "IND|Ben Sheppard|G-F",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "GSW": {
    "Stephen Curry|G": {
      "ovr": 89,
      "salary": 38.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Stephen Curry|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jimmy Butler|G-F": {
      "ovr": 72,
      "salary": 4.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Jimmy Butler|G-F",
        "openingOvr": 72,
        "basis": "unmeasured-prior",
        "partial": true
      }
    },
    "Draymond Green|F": {
      "ovr": 78,
      "salary": 16.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Draymond Green|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kristaps Porzingis|F-C": {
      "ovr": 87,
      "salary": 34.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Kristaps Porzingis|F-C",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Al Horford|C": {
      "ovr": 78,
      "salary": 16.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Al Horford|C",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "De'Anthony Melton|G": {
      "ovr": 79,
      "salary": 18.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|De'Anthony Melton|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Gary Payton II|G": {
      "ovr": 81,
      "salary": 22.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Gary Payton II|G",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Moses Moody|G-F": {
      "ovr": 78,
      "salary": 16.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Moses Moody|G-F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Brandin Podziemski|G": {
      "ovr": 85,
      "salary": 30.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Brandin Podziemski|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Quinten Post|C": {
      "ovr": 77,
      "salary": 14.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "GSW|Quinten Post|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "DAL": {
    "Kyrie Irving|G": {
      "ovr": 82,
      "salary": 27.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Kyrie Irving|G",
        "openingOvr": 82,
        "basis": "prior-only",
        "partial": true
      }
    },
    "Klay Thompson|G": {
      "ovr": 76,
      "salary": 13.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Klay Thompson|G",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Khris Middleton|F": {
      "ovr": 78,
      "salary": 18.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Khris Middleton|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Daniel Gafford|C": {
      "ovr": 82,
      "salary": 27.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Daniel Gafford|C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ryan Nembhard|G": {
      "ovr": 73,
      "salary": 6.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Ryan Nembhard|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Cooper Flagg|F": {
      "ovr": 86,
      "salary": 36.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Cooper Flagg|F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dereck Lively II|C": {
      "ovr": 77,
      "salary": 16.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Dereck Lively II|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "PJ Washington|F": {
      "ovr": 78,
      "salary": 18.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|PJ Washington|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Naji Marshall|F": {
      "ovr": 83,
      "salary": 29.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Naji Marshall|F",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Caleb Martin|F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DAL|Caleb Martin|F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "MEM": {
    "Ja Morant|G": {
      "ovr": 85,
      "salary": 24.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Ja Morant|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kentavious Caldwell-Pope|G": {
      "ovr": 74,
      "salary": 7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Kentavious Caldwell-Pope|G",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Zach Edey|C": {
      "ovr": 79,
      "salary": 15,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Zach Edey|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ty Jerome|G": {
      "ovr": 84,
      "salary": 23.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Ty Jerome|G",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Cedric Coward|G-F": {
      "ovr": 82,
      "salary": 19.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Cedric Coward|G-F",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Walter Clayton Jr.|G": {
      "ovr": 75,
      "salary": 8.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Walter Clayton Jr.|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaylen Wells|G-F": {
      "ovr": 73,
      "salary": 5.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Jaylen Wells|G-F",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Santi Aldama|F": {
      "ovr": 84,
      "salary": 23.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Santi Aldama|F",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kyle Anderson|F": {
      "ovr": 75,
      "salary": 8.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Kyle Anderson|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Scotty Pippen Jr.|G": {
      "ovr": 82,
      "salary": 19.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MEM|Scotty Pippen Jr.|G",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "PHI": {
    "Joel Embiid|F-C": {
      "ovr": 88,
      "salary": 33.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Joel Embiid|F-C",
        "openingOvr": 88,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tyrese Maxey|G": {
      "ovr": 92,
      "salary": 40.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Tyrese Maxey|G",
        "openingOvr": 92,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Quentin Grimes|G": {
      "ovr": 83,
      "salary": 24.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Quentin Grimes|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaylen Brown|G-F": {
      "ovr": 89,
      "salary": 35.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Jaylen Brown|G-F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Andre Drummond|C": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Andre Drummond|C",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kelly Oubre Jr.|F": {
      "ovr": 77,
      "salary": 13.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Kelly Oubre Jr.|F",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "VJ Edgecombe|G": {
      "ovr": 83,
      "salary": 24.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|VJ Edgecombe|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Trendon Watford|F": {
      "ovr": 76,
      "salary": 11.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Trendon Watford|F",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Justin Edwards|F": {
      "ovr": 74,
      "salary": 7.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Justin Edwards|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Adem Bona|C": {
      "ovr": 75,
      "salary": 9.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHI|Adem Bona|C",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "MIA": {
    "Bam Adebayo|C-F": {
      "ovr": 86,
      "salary": 22.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Bam Adebayo|C-F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tyler Herro|G": {
      "ovr": 89,
      "salary": 26.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Tyler Herro|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Andrew Wiggins|F": {
      "ovr": 85,
      "salary": 21.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Andrew Wiggins|F",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kasparas Jakucionis|G": {
      "ovr": 77,
      "salary": 10.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Kasparas Jakucionis|G",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Simone Fontecchio|F": {
      "ovr": 75,
      "salary": 7.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Simone Fontecchio|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaime Jaquez Jr.|F": {
      "ovr": 82,
      "salary": 17.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Jaime Jaquez Jr.|F",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kel'el Ware|C": {
      "ovr": 80,
      "salary": 14.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Kel'el Ware|C",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Davion Mitchell|G": {
      "ovr": 79,
      "salary": 13.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Davion Mitchell|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Nikola Jovic|F": {
      "ovr": 76,
      "salary": 9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Nikola Jovic|F",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Pelle Larsson|G": {
      "ovr": 77,
      "salary": 10.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "MIA|Pelle Larsson|G",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "LAC": {
    "John Collins|F": {
      "ovr": 83,
      "salary": 27.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|John Collins|F",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Darius Garland|G": {
      "ovr": 87,
      "salary": 35.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Darius Garland|G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bogdan Bogdanovic|G": {
      "ovr": 75,
      "salary": 10.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Bogdan Bogdanovic|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Brook Lopez|C": {
      "ovr": 77,
      "salary": 14.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Brook Lopez|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bradley Beal|G": {
      "ovr": 78,
      "salary": 16.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Bradley Beal|G",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bennedict Mathurin|G-F": {
      "ovr": 80,
      "salary": 21,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Bennedict Mathurin|G-F",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kawhi Leonard|F": {
      "ovr": 92,
      "salary": 45.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Kawhi Leonard|F",
        "openingOvr": 92,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Isaiah Jackson|C": {
      "ovr": 77,
      "salary": 14.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Isaiah Jackson|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Derrick Jones Jr.|F": {
      "ovr": 75,
      "salary": 10.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Derrick Jones Jr.|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Rui Hachimura|F": {
      "ovr": 76,
      "salary": 12.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "LAC|Rui Hachimura|F",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "PHX": {
    "Devin Booker|G": {
      "ovr": 90,
      "salary": 31.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Devin Booker|G",
        "openingOvr": 90,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jalen Green|G": {
      "ovr": 83,
      "salary": 20.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Jalen Green|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dillon Brooks|F": {
      "ovr": 78,
      "salary": 13,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Dillon Brooks|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Mark Williams|C": {
      "ovr": 84,
      "salary": 22.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Mark Williams|C",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ryan Dunn|F": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Ryan Dunn|F",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Royce O'Neale|F": {
      "ovr": 81,
      "salary": 17.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Royce O'Neale|F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Grayson Allen|G": {
      "ovr": 85,
      "salary": 23.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Grayson Allen|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Oso Ighodaro|C": {
      "ovr": 78,
      "salary": 13,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Oso Ighodaro|C",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Collin Gillespie|G": {
      "ovr": 85,
      "salary": 23.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Collin Gillespie|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Khaman Maluach|C": {
      "ovr": 71,
      "salary": 2.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "PHX|Khaman Maluach|C",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "SAC": {
    "Domantas Sabonis|F": {
      "ovr": 86,
      "salary": 30.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Domantas Sabonis|F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Zach LaVine|G": {
      "ovr": 85,
      "salary": 28.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Zach LaVine|G",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "De'Andre Hunter|F": {
      "ovr": 79,
      "salary": 17.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|De'Andre Hunter|F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Keegan Murray|F": {
      "ovr": 74,
      "salary": 8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Keegan Murray|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Precious Achiuwa|F": {
      "ovr": 73,
      "salary": 6.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Precious Achiuwa|F",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Nique Clifford|G-F": {
      "ovr": 71,
      "salary": 2.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Nique Clifford|G-F",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "DeMar DeRozan|F-G": {
      "ovr": 86,
      "salary": 30.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|DeMar DeRozan|F-G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Malik Monk|G": {
      "ovr": 84,
      "salary": 26.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Malik Monk|G",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Devin Carter|G": {
      "ovr": 75,
      "salary": 9.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Devin Carter|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Maxime Raynaud|C": {
      "ovr": 79,
      "salary": 17.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAC|Maxime Raynaud|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "ATL": {
    "Jonathan Kuminga|F": {
      "ovr": 79,
      "salary": 14.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Jonathan Kuminga|F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Buddy Hield|G": {
      "ovr": 77,
      "salary": 11.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Buddy Hield|G",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Nickeil Alexander-Walker|G": {
      "ovr": 86,
      "salary": 24.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Nickeil Alexander-Walker|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Zaccharie Risacher|F": {
      "ovr": 74,
      "salary": 6.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Zaccharie Risacher|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dyson Daniels|G": {
      "ovr": 83,
      "salary": 20.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Dyson Daniels|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jalen Johnson|F": {
      "ovr": 91,
      "salary": 32.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Jalen Johnson|F",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Onyeka Okongwu|C": {
      "ovr": 88,
      "salary": 27.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Onyeka Okongwu|C",
        "openingOvr": 88,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "CJ McCollum|G": {
      "ovr": 87,
      "salary": 26.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|CJ McCollum|G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Gabe Vincent|G": {
      "ovr": 68,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Gabe Vincent|G",
        "openingOvr": 68,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Aaron Wiggins|G": {
      "ovr": 76,
      "salary": 9.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ATL|Aaron Wiggins|G",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "NOP": {
    "Zion Williamson|F": {
      "ovr": 89,
      "salary": 31.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Zion Williamson|F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jordan Poole|G": {
      "ovr": 83,
      "salary": 21.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Jordan Poole|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jeremiah Fears|G": {
      "ovr": 81,
      "salary": 18.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Jeremiah Fears|G",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Trey Murphy III|F": {
      "ovr": 91,
      "salary": 34.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Trey Murphy III|F",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Herbert Jones|F": {
      "ovr": 73,
      "salary": 5.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Herbert Jones|F",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Yves Missi|C": {
      "ovr": 72,
      "salary": 3.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Yves Missi|C",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Saddiq Bey|F": {
      "ovr": 85,
      "salary": 25,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Saddiq Bey|F",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jordan Hawkins|G": {
      "ovr": 68,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Jordan Hawkins|G",
        "openingOvr": 68,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Derik Queen|C": {
      "ovr": 80,
      "salary": 16.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Derik Queen|C",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Antonio Reeves|G": {
      "ovr": 72,
      "salary": 3.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "NOP|Antonio Reeves|G",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "TOR": {
    "Scottie Barnes|G-F": {
      "ovr": 91,
      "salary": 26.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Scottie Barnes|G-F",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Brandon Ingram|F": {
      "ovr": 87,
      "salary": 21.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Brandon Ingram|F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jakob Poeltl|C": {
      "ovr": 85,
      "salary": 19.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Jakob Poeltl|C",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Immanuel Quickley|G": {
      "ovr": 89,
      "salary": 24.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Immanuel Quickley|G",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "RJ Barrett|F-G": {
      "ovr": 87,
      "salary": 21.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|RJ Barrett|F-G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Gradey Dick|G-F": {
      "ovr": 70,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Gradey Dick|G-F",
        "openingOvr": 70,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Trayce Jackson-Davis|C": {
      "ovr": 76,
      "salary": 8.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Trayce Jackson-Davis|C",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jamal Shead|G": {
      "ovr": 75,
      "salary": 7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Jamal Shead|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Collin Murray-Boyles|F": {
      "ovr": 78,
      "salary": 10.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Collin Murray-Boyles|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jonathan Mogbo|F": {
      "ovr": 72,
      "salary": 3.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "TOR|Jonathan Mogbo|F",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "SAS": {
    "Victor Wembanyama|F-C": {
      "ovr": 93,
      "salary": 35.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Victor Wembanyama|F-C",
        "openingOvr": 93,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "De'Aaron Fox|G": {
      "ovr": 90,
      "salary": 31.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|De'Aaron Fox|G",
        "openingOvr": 90,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Stephon Castle|G": {
      "ovr": 87,
      "salary": 26.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Stephon Castle|G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Devin Vassell|G-F": {
      "ovr": 82,
      "salary": 19,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Devin Vassell|G-F",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dylan Harper|G": {
      "ovr": 83,
      "salary": 20.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Dylan Harper|G",
        "openingOvr": 83,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Harrison Barnes|F": {
      "ovr": 78,
      "salary": 12.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Harrison Barnes|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Julian Champagnie|F": {
      "ovr": 79,
      "salary": 14.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Julian Champagnie|F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Luke Kornet|C": {
      "ovr": 81,
      "salary": 17.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Luke Kornet|C",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Keldon Johnson|F": {
      "ovr": 81,
      "salary": 17.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Keldon Johnson|F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kelly Olynyk|F-C": {
      "ovr": 76,
      "salary": 9.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "SAS|Kelly Olynyk|F-C",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "ORL": {
    "Paolo Banchero|F": {
      "ovr": 88,
      "salary": 32.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Paolo Banchero|F",
        "openingOvr": 88,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Franz Wagner|F": {
      "ovr": 87,
      "salary": 30.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Franz Wagner|F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jalen Suggs|G": {
      "ovr": 86,
      "salary": 29,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Jalen Suggs|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Desmond Bane|G": {
      "ovr": 91,
      "salary": 37.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Desmond Bane|G",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Moritz Wagner|C": {
      "ovr": 77,
      "salary": 12.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Moritz Wagner|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Wendell Carter Jr.|C": {
      "ovr": 79,
      "salary": 16.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Wendell Carter Jr.|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jonathan Isaac|F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Jonathan Isaac|F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Anthony Black|G": {
      "ovr": 81,
      "salary": 20.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Anthony Black|G",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tristan da Silva|F": {
      "ovr": 73,
      "salary": 5.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Tristan da Silva|F",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jase Richardson|G": {
      "ovr": 73,
      "salary": 5.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "ORL|Jase Richardson|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "UTA": {
    "Lauri Markkanen|F": {
      "ovr": 85,
      "salary": 20.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Lauri Markkanen|F",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jusuf Nurkic|C": {
      "ovr": 79,
      "salary": 12.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Jusuf Nurkic|C",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ace Bailey|F": {
      "ovr": 76,
      "salary": 8.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Ace Bailey|F",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaren Jackson Jr.|F-C": {
      "ovr": 86,
      "salary": 22.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Jaren Jackson Jr.|F-C",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Keyonte George|G": {
      "ovr": 88,
      "salary": 24.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Keyonte George|G",
        "openingOvr": 88,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Walker Kessler|C": {
      "ovr": 81,
      "salary": 15.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Walker Kessler|C",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Isaiah Collier|G": {
      "ovr": 80,
      "salary": 14.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Isaiah Collier|G",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Lonzo Ball|G": {
      "ovr": 76,
      "salary": 8.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Lonzo Ball|G",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kyle Filipowski|F-C": {
      "ovr": 82,
      "salary": 16.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Kyle Filipowski|F-C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Svi Mykhailiuk|G-F": {
      "ovr": 76,
      "salary": 8.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "UTA|Svi Mykhailiuk|G-F",
        "openingOvr": 76,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "CHA": {
    "Coby White|G": {
      "ovr": 87,
      "salary": 24.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Coby White|G",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "LaMelo Ball|G": {
      "ovr": 91,
      "salary": 30.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|LaMelo Ball|G",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Brandon Miller|F": {
      "ovr": 87,
      "salary": 24.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Brandon Miller|F",
        "openingOvr": 87,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Miles Bridges|F": {
      "ovr": 86,
      "salary": 23.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Miles Bridges|F",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kon Knueppel|G-F": {
      "ovr": 89,
      "salary": 27.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Kon Knueppel|G-F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Grant Williams|F": {
      "ovr": 75,
      "salary": 7.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Grant Williams|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Josh Green|G": {
      "ovr": 68,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Josh Green|G",
        "openingOvr": 68,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tidjane Salaun|F": {
      "ovr": 71,
      "salary": 2.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Tidjane Salaun|F",
        "openingOvr": 71,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ryan Kalkbrenner|C": {
      "ovr": 77,
      "salary": 10.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Ryan Kalkbrenner|C",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Dorian Finney-Smith|F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHA|Dorian Finney-Smith|F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "DET": {
    "Cade Cunningham|G-F": {
      "ovr": 93,
      "salary": 31.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Cade Cunningham|G-F",
        "openingOvr": 93,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jalen Duren|C": {
      "ovr": 89,
      "salary": 26.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Jalen Duren|C",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Duncan Robinson|G-F": {
      "ovr": 80,
      "salary": 14.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Duncan Robinson|G-F",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ausar Thompson|F": {
      "ovr": 78,
      "salary": 11.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Ausar Thompson|F",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tobias Harris|F": {
      "ovr": 81,
      "salary": 15.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Tobias Harris|F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Caris LeVert|G": {
      "ovr": 78,
      "salary": 11.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Caris LeVert|G",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Isaiah Stewart|C-F": {
      "ovr": 79,
      "salary": 13,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Isaiah Stewart|C-F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ron Holland II|F": {
      "ovr": 72,
      "salary": 3.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Ron Holland II|F",
        "openingOvr": 72,
        "basis": "unmeasured-prior",
        "partial": true
      }
    },
    "Marcus Sasser|G": {
      "ovr": 77,
      "salary": 10.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Marcus Sasser|G",
        "openingOvr": 77,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kevin Huerter|G": {
      "ovr": 79,
      "salary": 13,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "DET|Kevin Huerter|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "BKN": {
    "Nicolas Claxton|F-C": {
      "ovr": 72,
      "salary": 3.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Nicolas Claxton|F-C",
        "openingOvr": 72,
        "basis": "unmeasured-prior",
        "partial": true
      }
    },
    "Day'Ron Sharpe|C": {
      "ovr": 82,
      "salary": 17.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Day'Ron Sharpe|C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Egor Demin|G": {
      "ovr": 79,
      "salary": 13.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Egor Demin|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Michael Porter Jr.|F": {
      "ovr": 89,
      "salary": 27,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Michael Porter Jr.|F",
        "openingOvr": 89,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Terance Mann|G-F": {
      "ovr": 75,
      "salary": 7.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Terance Mann|G-F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ziaire Williams|F": {
      "ovr": 75,
      "salary": 7.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Ziaire Williams|F",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Noah Clowney|F": {
      "ovr": 74,
      "salary": 6.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Noah Clowney|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tyrese Martin|F-G": {
      "ovr": 72,
      "salary": 3.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Tyrese Martin|F-G",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Ochai Agbaji|G": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Ochai Agbaji|G",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Keon Johnson|G": {
      "ovr": 75,
      "salary": 7.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "BKN|Keon Johnson|G",
        "openingOvr": 75,
        "basis": "prior-only",
        "partial": true
      }
    }
  },
  "WAS": {
    "Trae Young|G": {
      "ovr": 86,
      "salary": 27.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Trae Young|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Anthony Davis|F-C": {
      "ovr": 84,
      "salary": 23.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Anthony Davis|F-C",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bilal Coulibaly|G": {
      "ovr": 78,
      "salary": 13.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Bilal Coulibaly|G",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Cam Whitmore|F": {
      "ovr": 74,
      "salary": 7.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Cam Whitmore|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Tre Johnson|G": {
      "ovr": 75,
      "salary": 8.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Tre Johnson|G",
        "openingOvr": 75,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Kyshawn George|F": {
      "ovr": 80,
      "salary": 17.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Kyshawn George|F",
        "openingOvr": 80,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Alex Sarr|F-C": {
      "ovr": 82,
      "salary": 20.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Alex Sarr|F-C",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Will Riley|F": {
      "ovr": 74,
      "salary": 7.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Will Riley|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Bub Carrington|G": {
      "ovr": 78,
      "salary": 13.9,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Bub Carrington|G",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jaden Hardy|G": {
      "ovr": 74,
      "salary": 7.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "WAS|Jaden Hardy|G",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "POR": {
    "Damian Lillard|G": {
      "ovr": 82,
      "salary": 21.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Damian Lillard|G",
        "openingOvr": 82,
        "basis": "prior-only",
        "partial": true
      }
    },
    "Jrue Holiday|G": {
      "ovr": 86,
      "salary": 28.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Jrue Holiday|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Jerami Grant|F": {
      "ovr": 81,
      "salary": 19.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Jerami Grant|F",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Shaedon Sharpe|G": {
      "ovr": 82,
      "salary": 21.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Shaedon Sharpe|G",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Donovan Clingan|C": {
      "ovr": 81,
      "salary": 19.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Donovan Clingan|C",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Deni Avdija|F": {
      "ovr": 91,
      "salary": 37,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Deni Avdija|F",
        "openingOvr": 91,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Matisse Thybulle|G-F": {
      "ovr": 72,
      "salary": 4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Matisse Thybulle|G-F",
        "openingOvr": 72,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Yang Hansen|C": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Yang Hansen|C",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Toumani Camara|F": {
      "ovr": 79,
      "salary": 16.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Toumani Camara|F",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Scoot Henderson|G": {
      "ovr": 81,
      "salary": 19.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "POR|Scoot Henderson|G",
        "openingOvr": 81,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  },
  "CHI": {
    "Jaden Ivey|G": {
      "ovr": 79,
      "salary": 12.5,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Jaden Ivey|G",
        "openingOvr": 79,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Guerschon Yabusele|F": {
      "ovr": 74,
      "salary": 6.1,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Guerschon Yabusele|F",
        "openingOvr": 74,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Josh Giddey|G-F": {
      "ovr": 90,
      "salary": 26.7,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Josh Giddey|G-F",
        "openingOvr": 90,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Norman Powell|G-F": {
      "ovr": 85,
      "salary": 20.3,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Norman Powell|G-F",
        "openingOvr": 85,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Anfernee Simons|G": {
      "ovr": 84,
      "salary": 19,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Anfernee Simons|G",
        "openingOvr": 84,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Patrick Williams|F": {
      "ovr": 69,
      "salary": 2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Patrick Williams|F",
        "openingOvr": 69,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Collin Sexton|G": {
      "ovr": 86,
      "salary": 21.6,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Collin Sexton|G",
        "openingOvr": 86,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Matas Buzelis|F": {
      "ovr": 82,
      "salary": 16.4,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Matas Buzelis|F",
        "openingOvr": 82,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Zach Collins|F-C": {
      "ovr": 78,
      "salary": 11.2,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Zach Collins|F-C",
        "openingOvr": 78,
        "basis": "box-score-proxy",
        "partial": true
      }
    },
    "Rob Dillingham|G": {
      "ovr": 73,
      "salary": 4.8,
      "evidence": {
        "modelVersion": "nba894-review-v0.4",
        "originKey": "CHI|Rob Dillingham|G",
        "openingOvr": 73,
        "basis": "box-score-proxy",
        "partial": true
      }
    }
  }
};
