/**
 * The 2026 FIFA World Cup as it was actually played. Round 395.
 *
 * The bracket game (/world-cup-bracket) asked players to predict a tournament
 * that ended on July 19, 2026, and never learned the result. This file is
 * what happened, so a bracket can be scored against it.
 *
 * Two sources for every row, compared programmatically on 2026-09-01:
 *   ESPN's open scoreboard header feed (the site's own scores source since
 *   Round 311), one request per tournament day, 104 matches with scores and
 *   winners; and Wikipedia's tournament articles through the API (the
 *   knockout bracket, the qualified-teams table, the awards table). Group
 *   membership comes from who played whom in ESPN's 72 group matches;
 *   positions one and two, and the qualified thirds, from the qualified-teams
 *   table, which agreed with the tables computed from ESPN's results in all
 *   twelve groups; the remaining third and fourth places from those computed
 *   tables (points, goal difference, goals for), none of them tied. All 32
 *   knockout scores and winners agreed between the two sources. Awards:
 *   Wikipedia's awards table, with The Athletic (Golden Ball, Golden Glove,
 *   Young Player) and FOX Sports (Golden Boot) as the second source.
 *
 * Team spellings are the bracket game's own (USA, Turkey, Czech Republic,
 * DR Congo, Bosnia & Herzegovina). Generated by a one-off script; the fence
 * is scripts/simWc2026Results.mjs.
 */

export type Wc2026Round = 'r32' | 'r16' | 'qf' | 'sf' | 'tp' | 'f';

export interface Wc2026Group {
  letter: string;
  /** Final standings, first to fourth. */
  teams: [string, string, string, string];
  /** Whether the third-placed team was one of the eight best thirds. */
  thirdQualified: boolean;
}

export interface Wc2026Match {
  round: Wc2026Round;
  date: string;
  team1: string;
  team2: string;
  score1: number;
  score2: number;
  /** Extra time was played (a shootout implies it). */
  extraTime: boolean;
  /** Shootout score as 'a-b' when the match went to penalties. */
  penalties: string | null;
  winner: string;
}

export const WC2026_GROUPS: Wc2026Group[] = [
  { letter: 'A', teams: ['Mexico', 'South Africa', 'South Korea', 'Czech Republic'], thirdQualified: false },
  { letter: 'B', teams: ['Switzerland', 'Canada', 'Bosnia & Herzegovina', 'Qatar'], thirdQualified: true },
  { letter: 'C', teams: ['Brazil', 'Morocco', 'Scotland', 'Haiti'], thirdQualified: false },
  { letter: 'D', teams: ['USA', 'Australia', 'Paraguay', 'Turkey'], thirdQualified: true },
  { letter: 'E', teams: ['Germany', 'Ivory Coast', 'Ecuador', 'Curaçao'], thirdQualified: true },
  { letter: 'F', teams: ['Netherlands', 'Japan', 'Sweden', 'Tunisia'], thirdQualified: true },
  { letter: 'G', teams: ['Belgium', 'Egypt', 'Iran', 'New Zealand'], thirdQualified: false },
  { letter: 'H', teams: ['Spain', 'Cape Verde', 'Uruguay', 'Saudi Arabia'], thirdQualified: false },
  { letter: 'I', teams: ['France', 'Norway', 'Senegal', 'Iraq'], thirdQualified: true },
  { letter: 'J', teams: ['Argentina', 'Austria', 'Algeria', 'Jordan'], thirdQualified: true },
  { letter: 'K', teams: ['Colombia', 'Portugal', 'DR Congo', 'Uzbekistan'], thirdQualified: true },
  { letter: 'L', teams: ['England', 'Croatia', 'Ghana', 'Panama'], thirdQualified: true },
];

export const WC2026_KNOCKOUT: Wc2026Match[] = [
  { round: 'r32', date: '2026-06-29', team1: 'Germany', team2: 'Paraguay', score1: 1, score2: 1, extraTime: true, penalties: '3-4', winner: 'Paraguay' },
  { round: 'r32', date: '2026-06-30', team1: 'France', team2: 'Sweden', score1: 3, score2: 0, extraTime: false, penalties: null, winner: 'France' },
  { round: 'r32', date: '2026-06-28', team1: 'South Africa', team2: 'Canada', score1: 0, score2: 1, extraTime: false, penalties: null, winner: 'Canada' },
  { round: 'r32', date: '2026-06-30', team1: 'Netherlands', team2: 'Morocco', score1: 1, score2: 1, extraTime: true, penalties: '2-3', winner: 'Morocco' },
  { round: 'r32', date: '2026-07-02', team1: 'Portugal', team2: 'Croatia', score1: 2, score2: 1, extraTime: false, penalties: null, winner: 'Portugal' },
  { round: 'r32', date: '2026-07-02', team1: 'Spain', team2: 'Austria', score1: 3, score2: 0, extraTime: false, penalties: null, winner: 'Spain' },
  { round: 'r32', date: '2026-07-02', team1: 'USA', team2: 'Bosnia & Herzegovina', score1: 2, score2: 0, extraTime: false, penalties: null, winner: 'USA' },
  { round: 'r32', date: '2026-07-01', team1: 'Belgium', team2: 'Senegal', score1: 3, score2: 2, extraTime: true, penalties: null, winner: 'Belgium' },
  { round: 'r32', date: '2026-06-29', team1: 'Brazil', team2: 'Japan', score1: 2, score2: 1, extraTime: false, penalties: null, winner: 'Brazil' },
  { round: 'r32', date: '2026-06-30', team1: 'Ivory Coast', team2: 'Norway', score1: 1, score2: 2, extraTime: false, penalties: null, winner: 'Norway' },
  { round: 'r32', date: '2026-07-01', team1: 'Mexico', team2: 'Ecuador', score1: 2, score2: 0, extraTime: false, penalties: null, winner: 'Mexico' },
  { round: 'r32', date: '2026-07-01', team1: 'England', team2: 'DR Congo', score1: 2, score2: 1, extraTime: false, penalties: null, winner: 'England' },
  { round: 'r32', date: '2026-07-03', team1: 'Argentina', team2: 'Cape Verde', score1: 3, score2: 2, extraTime: true, penalties: null, winner: 'Argentina' },
  { round: 'r32', date: '2026-07-03', team1: 'Australia', team2: 'Egypt', score1: 1, score2: 1, extraTime: true, penalties: '2-4', winner: 'Egypt' },
  { round: 'r32', date: '2026-07-03', team1: 'Switzerland', team2: 'Algeria', score1: 2, score2: 0, extraTime: false, penalties: null, winner: 'Switzerland' },
  { round: 'r32', date: '2026-07-04', team1: 'Colombia', team2: 'Ghana', score1: 1, score2: 0, extraTime: false, penalties: null, winner: 'Colombia' },
  { round: 'r16', date: '2026-07-04', team1: 'Paraguay', team2: 'France', score1: 0, score2: 1, extraTime: false, penalties: null, winner: 'France' },
  { round: 'r16', date: '2026-07-04', team1: 'Canada', team2: 'Morocco', score1: 0, score2: 3, extraTime: false, penalties: null, winner: 'Morocco' },
  { round: 'r16', date: '2026-07-06', team1: 'Portugal', team2: 'Spain', score1: 0, score2: 1, extraTime: false, penalties: null, winner: 'Spain' },
  { round: 'r16', date: '2026-07-07', team1: 'USA', team2: 'Belgium', score1: 1, score2: 4, extraTime: false, penalties: null, winner: 'Belgium' },
  { round: 'r16', date: '2026-07-05', team1: 'Brazil', team2: 'Norway', score1: 1, score2: 2, extraTime: false, penalties: null, winner: 'Norway' },
  { round: 'r16', date: '2026-07-06', team1: 'Mexico', team2: 'England', score1: 2, score2: 3, extraTime: false, penalties: null, winner: 'England' },
  { round: 'r16', date: '2026-07-07', team1: 'Argentina', team2: 'Egypt', score1: 3, score2: 2, extraTime: false, penalties: null, winner: 'Argentina' },
  { round: 'r16', date: '2026-07-07', team1: 'Switzerland', team2: 'Colombia', score1: 0, score2: 0, extraTime: true, penalties: '4-3', winner: 'Switzerland' },
  { round: 'qf', date: '2026-07-09', team1: 'France', team2: 'Morocco', score1: 2, score2: 0, extraTime: false, penalties: null, winner: 'France' },
  { round: 'qf', date: '2026-07-10', team1: 'Spain', team2: 'Belgium', score1: 2, score2: 1, extraTime: false, penalties: null, winner: 'Spain' },
  { round: 'qf', date: '2026-07-11', team1: 'Norway', team2: 'England', score1: 1, score2: 2, extraTime: true, penalties: null, winner: 'England' },
  { round: 'qf', date: '2026-07-12', team1: 'Argentina', team2: 'Switzerland', score1: 3, score2: 1, extraTime: true, penalties: null, winner: 'Argentina' },
  { round: 'sf', date: '2026-07-14', team1: 'France', team2: 'Spain', score1: 0, score2: 2, extraTime: false, penalties: null, winner: 'Spain' },
  { round: 'sf', date: '2026-07-15', team1: 'England', team2: 'Argentina', score1: 1, score2: 2, extraTime: false, penalties: null, winner: 'Argentina' },
  { round: 'f', date: '2026-07-19', team1: 'Spain', team2: 'Argentina', score1: 1, score2: 0, extraTime: true, penalties: null, winner: 'Spain' },
  { round: 'tp', date: '2026-07-18', team1: 'France', team2: 'England', score1: 4, score2: 6, extraTime: false, penalties: null, winner: 'England' },
];

export const WC2026_CHAMPION = 'Spain';
export const WC2026_RUNNER_UP = 'Argentina';
export const WC2026_THIRD = 'England';

/** Individual awards, as presented on July 19, 2026. */
export const WC2026_AWARDS = {
  goldenBall: { player: 'Rodri', nation: 'Spain' },
  goldenBoot: { player: 'Kylian Mbappé', nation: 'France', goals: 10 },
  goldenGlove: { player: 'Unai Simón', nation: 'Spain' },
  youngPlayer: { player: 'Pau Cubarsí', nation: 'Spain' },
} as const;

/** Teams that reached each round, derived from the matches above. */
export function wc2026TeamsInRound(round: Wc2026Round): string[] {
  const out = new Set<string>();
  for (const m of WC2026_KNOCKOUT) if (m.round === round) { out.add(m.team1); out.add(m.team2); }
  return [...out];
}
